// New categories 68-80
export default [
  {
    id: "apologies",
    name: "Apologies",
    scale: "How hard this is to say sorry for",
    cards: [
      { id: "apo_001", text: "Forgetting someone's birthday" },
      { id: "apo_002", text: "Being late" },
      { id: "apo_003", text: "Losing someone's stuff" },
      { id: "apo_004", text: "Canceling last minute" },
      { id: "apo_005", text: "Something you said when angry" },
      { id: "apo_006", text: "Not showing up" },
      { id: "apo_007", text: "Giving bad advice" },
      { id: "apo_008", text: "Accidentally spoiling something" },
      { id: "apo_009", text: "Forgetting someone's name" },
      { id: "apo_010", text: "Spilling on someone's clothes" },
      { id: "apo_011", text: "Being on your phone during a conversation" },
      { id: "apo_012", text: "Not texting back for days" },
      { id: "apo_013", text: "Eating someone's leftovers" },
      { id: "apo_014", text: "Talking over someone" },
      { id: "apo_015", text: "Making someone wait" },
      { id: "apo_016", text: "Breaking a promise" },
      { id: "apo_017", text: "Being too honest" },
      { id: "apo_018", text: "Accidentally sharing a secret" },
      { id: "apo_019", text: "Not being there when it mattered" },
      { id: "apo_020", text: "Leaving someone on read" },
      { id: "apo_021", text: "Being a sore loser" },
      { id: "apo_022", text: "Falling asleep during a movie night" },
      { id: "apo_023", text: "Judging someone too quickly" },
      { id: "apo_024", text: "Borrowing something and forgetting" },
      { id: "apo_025", text: "Making it about yourself" },
    ]
  },
  {
    id: "celebrity_dinner",
    name: "Celebrity Dinner Guests",
    scale: "How badly you want them at your table",
    cards: [
      { id: "celeb_001", text: "Beyoncé" },
      { id: "celeb_002", text: "Dwayne Johnson" },
      { id: "celeb_003", text: "Oprah" },
      { id: "celeb_004", text: "Keanu Reeves" },
      { id: "celeb_005", text: "Gordon Ramsay" },
      { id: "celeb_006", text: "Taylor Swift" },
      { id: "celeb_007", text: "David Attenborough" },
      { id: "celeb_008", text: "Snoop Dogg" },
      { id: "celeb_009", text: "Michelle Obama" },
      { id: "celeb_010", text: "Dolly Parton" },
      { id: "celeb_011", text: "Ryan Reynolds" },
      { id: "celeb_012", text: "Rihanna" },
      { id: "celeb_013", text: "Steve Irwin" },
      { id: "celeb_014", text: "Zendaya" },
      { id: "celeb_015", text: "Trevor Noah" },
      { id: "celeb_016", text: "Post Malone" },
      { id: "celeb_017", text: "Adele" },
      { id: "celeb_018", text: "Tom Hanks" },
      { id: "celeb_019", text: "Lizzo" },
      { id: "celeb_020", text: "Jeff Goldblum" },
      { id: "celeb_021", text: "Harry Styles" },
      { id: "celeb_022", text: "Billie Eilish" },
      { id: "celeb_023", text: "Matthew McConaughey" },
      { id: "celeb_024", text: "Jennifer Aniston" },
      { id: "celeb_025", text: "Guy Fieri" },
    ]
  },
  {
    id: "childhood_rules",
    name: "Childhood Rules",
    scale: "How much this one mattered to you",
    cards: [
      { id: "crule_001", text: "No elbows on the table" },
      { id: "crule_002", text: "Finish your plate before dessert" },
      { id: "crule_003", text: "Be home before dark" },
      { id: "crule_004", text: "No TV until homework was done" },
      { id: "crule_005", text: "Say please and thank you" },
      { id: "crule_006", text: "No running in the house" },
      { id: "crule_007", text: "Ask before leaving the table" },
      { id: "crule_008", text: "No phone at dinner" },
      { id: "crule_009", text: "Shoes off inside" },
      { id: "crule_010", text: "Brush your teeth before bed" },
      { id: "crule_011", text: "Don't sit too close to the TV" },
      { id: "crule_012", text: "Share with your siblings" },
      { id: "crule_013", text: "No snacks before dinner" },
      { id: "crule_014", text: "Bedtime was non-negotiable" },
      { id: "crule_015", text: "Always wear a jacket" },
      { id: "crule_016", text: "No talking to strangers" },
      { id: "crule_017", text: "Write thank-you cards" },
      { id: "crule_018", text: "You break it, you buy it" },
      { id: "crule_019", text: "Finish what you started" },
      { id: "crule_020", text: "No jumping on the bed" },
      { id: "crule_021", text: "Wait 30 minutes after eating to swim" },
      { id: "crule_022", text: "Clean your room on Saturday" },
      { id: "crule_023", text: "One hour of screen time max" },
      { id: "crule_024", text: "Look both ways before crossing" },
      { id: "crule_025", text: "Respect your elders" },
    ]
  },
  {
    id: "seasons_of_life",
    name: "Seasons of Life",
    scale: "How much you look forward to this",
    cards: [
      { id: "sol_001", text: "Your first apartment alone" },
      { id: "sol_002", text: "Finding a career you love" },
      { id: "sol_003", text: "Getting a dog" },
      { id: "sol_004", text: "Living in another country" },
      { id: "sol_005", text: "Getting married" },
      { id: "sol_006", text: "Having kids" },
      { id: "sol_007", text: "Buying your first home" },
      { id: "sol_008", text: "Retirement" },
      { id: "sol_009", text: "The empty nest years" },
      { id: "sol_010", text: "Being a grandparent" },
      { id: "sol_011", text: "A gap year" },
      { id: "sol_012", text: "Starting your own business" },
      { id: "sol_013", text: "Your wild single years" },
      { id: "sol_014", text: "Living near your best friends" },
      { id: "sol_015", text: "The toddler years" },
      { id: "sol_016", text: "Becoming financially comfortable" },
      { id: "sol_017", text: "A sabbatical" },
      { id: "sol_018", text: "Being a mentor" },
      { id: "sol_019", text: "Your quarter-life crisis" },
      { id: "sol_020", text: "Learning to let go" },
      { id: "sol_021", text: "Your comeback era" },
      { id: "sol_022", text: "Downsizing to a simple life" },
      { id: "sol_023", text: "Finding your people" },
      { id: "sol_024", text: "Becoming the fun aunt or uncle" },
      { id: "sol_025", text: "A chapter nobody saw coming" },
    ]
  },
  {
    id: "things_to_binge",
    name: "Things to Binge",
    scale: "How hard it is to stop once you start",
    cards: [
      { id: "binge_001", text: "A crime documentary series" },
      { id: "binge_002", text: "A bag of chips" },
      { id: "binge_003", text: "TikTok or Reels" },
      { id: "binge_004", text: "A new reality show" },
      { id: "binge_005", text: "Wikipedia rabbit holes" },
      { id: "binge_006", text: "A podcast everyone's talking about" },
      { id: "binge_007", text: "A page-turner novel" },
      { id: "binge_008", text: "A new video game" },
      { id: "binge_009", text: "Gummy candy" },
      { id: "binge_010", text: "Online shopping at 2 AM" },
      { id: "binge_011", text: "A comfort show rewatch" },
      { id: "binge_012", text: "A friend's Instagram from 2014" },
      { id: "binge_013", text: "Trail mix" },
      { id: "binge_014", text: "Reddit threads" },
      { id: "binge_015", text: "A K-drama" },
      { id: "binge_016", text: "Cheese and crackers" },
      { id: "binge_017", text: "A thriller series" },
      { id: "binge_018", text: "YouTube tutorials at midnight" },
      { id: "binge_019", text: "Pistachios" },
      { id: "binge_020", text: "A drama-filled season finale" },
      { id: "binge_021", text: "Sour candy" },
      { id: "binge_022", text: "A Twitter or X drama thread" },
      { id: "binge_023", text: "A fantasy book series" },
      { id: "binge_024", text: "Dark chocolate" },
      { id: "binge_025", text: "A cooking competition show" },
    ]
  },
  {
    id: "city_vs_country",
    name: "City vs. Country",
    scale: "How much this matters for where you live",
    cards: [
      { id: "cvc_001", text: "Walking everywhere" },
      { id: "cvc_002", text: "Knowing your neighbors" },
      { id: "cvc_003", text: "Good restaurants nearby" },
      { id: "cvc_004", text: "Seeing stars at night" },
      { id: "cvc_005", text: "Silence" },
      { id: "cvc_006", text: "Public transportation" },
      { id: "cvc_007", text: "A big backyard" },
      { id: "cvc_008", text: "Nightlife" },
      { id: "cvc_009", text: "Fresh air" },
      { id: "cvc_010", text: "Delivery at midnight" },
      { id: "cvc_011", text: "Space between houses" },
      { id: "cvc_012", text: "Cultural events and museums" },
      { id: "cvc_013", text: "Bonfires" },
      { id: "cvc_014", text: "Coffee shops on every block" },
      { id: "cvc_015", text: "A porch with a view" },
      { id: "cvc_016", text: "Farmers markets" },
      { id: "cvc_017", text: "A short commute" },
      { id: "cvc_018", text: "Hearing crickets instead of sirens" },
      { id: "cvc_019", text: "Diversity" },
      { id: "cvc_020", text: "A dirt road" },
      { id: "cvc_021", text: "Live music" },
      { id: "cvc_022", text: "Keeping chickens" },
      { id: "cvc_023", text: "People-watching" },
      { id: "cvc_024", text: "Room for a garden" },
      { id: "cvc_025", text: "Always something to do" },
    ]
  },
  {
    id: "things_teachers_say",
    name: "Things Teachers Say",
    scale: "How much you heard this one",
    cards: [
      { id: "teach_001", text: "I'll wait" },
      { id: "teach_002", text: "This will be on the test" },
      { id: "teach_003", text: "I don't know, can you?" },
      { id: "teach_004", text: "You should have gone at lunch" },
      { id: "teach_005", text: "Quiet down, please" },
      { id: "teach_006", text: "Eyes on your own paper" },
      { id: "teach_007", text: "You're only hurting yourself" },
      { id: "teach_008", text: "The bell doesn't dismiss you, I do" },
      { id: "teach_009", text: "I'm not your friend, I'm your teacher" },
      { id: "teach_010", text: "Use it in a sentence" },
      { id: "teach_011", text: "Who can tell me the answer" },
      { id: "teach_012", text: "No hats in class" },
      { id: "teach_013", text: "Show your work" },
      { id: "teach_014", text: "If you have time to lean, you have time to clean" },
      { id: "teach_015", text: "I'm very disappointed" },
      { id: "teach_016", text: "Hands to yourself" },
      { id: "teach_017", text: "Put your phone away" },
      { id: "teach_018", text: "Does anyone have questions" },
      { id: "teach_019", text: "You won't always have a calculator" },
      { id: "teach_020", text: "That's for me to know and you to find out" },
      { id: "teach_021", text: "Is there something you'd like to share" },
      { id: "teach_022", text: "Read the instructions carefully" },
      { id: "teach_023", text: "This is going on your record" },
      { id: "teach_024", text: "I'm not going to say it again" },
      { id: "teach_025", text: "See me after class" },
    ]
  },
  {
    id: "green_flags",
    name: "Green Flags",
    scale: "How much this matters to you",
    cards: [
      { id: "gf_001", text: "They remember small details about you" },
      { id: "gf_002", text: "They apologize without being asked" },
      { id: "gf_003", text: "They're kind to service workers" },
      { id: "gf_004", text: "They celebrate your wins" },
      { id: "gf_005", text: "They don't keep score" },
      { id: "gf_006", text: "They text back at a normal pace" },
      { id: "gf_007", text: "They get along with your friends" },
      { id: "gf_008", text: "They can laugh at themselves" },
      { id: "gf_009", text: "They respect your alone time" },
      { id: "gf_010", text: "They ask follow-up questions" },
      { id: "gf_011", text: "They show up on time" },
      { id: "gf_012", text: "They bring you food without asking" },
      { id: "gf_013", text: "They don't talk badly about their ex" },
      { id: "gf_014", text: "They make plans and follow through" },
      { id: "gf_015", text: "They're honest about their feelings" },
      { id: "gf_016", text: "They put their phone down around you" },
      { id: "gf_017", text: "They listen more than they talk" },
      { id: "gf_018", text: "They handle disagreements calmly" },
      { id: "gf_019", text: "They say thank you often" },
      { id: "gf_020", text: "They have their own hobbies" },
      { id: "gf_021", text: "They include you in future plans" },
      { id: "gf_022", text: "They're close with their family" },
      { id: "gf_023", text: "They admit when they're wrong" },
      { id: "gf_024", text: "They remember your coffee order" },
      { id: "gf_025", text: "They make you feel safe to be yourself" },
    ]
  },
  {
    id: "airport_behaviors",
    name: "Airport Behaviors",
    scale: "How much this is you",
    cards: [
      { id: "air_001", text: "Arriving three hours early" },
      { id: "air_002", text: "Straight to the gate, no browsing" },
      { id: "air_003", text: "Buying overpriced food" },
      { id: "air_004", text: "Having a drink before noon" },
      { id: "air_005", text: "Browsing every shop in the terminal" },
      { id: "air_006", text: "Charging your phone at the gate" },
      { id: "air_007", text: "Watching other planes take off" },
      { id: "air_008", text: "Standing up the second the plane lands" },
      { id: "air_009", text: "Wearing pajamas to fly" },
      { id: "air_010", text: "Clapping when the plane lands" },
      { id: "air_011", text: "Falling asleep before takeoff" },
      { id: "air_012", text: "Boarding group anxiety" },
      { id: "air_013", text: "Packing snacks from home" },
      { id: "air_014", text: "Downloading shows the night before" },
      { id: "air_015", text: "Taking a photo of the wing" },
      { id: "air_016", text: "Checking the departures board 10 times" },
      { id: "air_017", text: "Buying something at duty free" },
      { id: "air_018", text: "Making friends with your seatmate" },
      { id: "air_019", text: "Walking laps around the terminal" },
      { id: "air_020", text: "Pretending to read while eavesdropping" },
      { id: "air_021", text: "Getting a neck pillow" },
      { id: "air_022", text: "Stressing about overhead bin space" },
      { id: "air_023", text: "Rating every airport you visit" },
      { id: "air_024", text: "Sprinting to a connecting flight" },
      { id: "air_025", text: "Already planning your next trip" },
    ]
  },
  {
    id: "roommate_habits",
    name: "Roommate Habits",
    scale: "How much this would bother you",
    cards: [
      { id: "rm_001", text: "Leaving dishes in the sink" },
      { id: "rm_002", text: "Playing music without headphones" },
      { id: "rm_003", text: "Having people over late on a weeknight" },
      { id: "rm_004", text: "Never taking out the trash" },
      { id: "rm_005", text: "Eating your labeled food" },
      { id: "rm_006", text: "Long showers in the morning" },
      { id: "rm_007", text: "Leaving lights on in every room" },
      { id: "rm_008", text: "Not replacing the toilet paper roll" },
      { id: "rm_009", text: "FaceTiming in the common area" },
      { id: "rm_010", text: "Passive-aggressive Post-it notes" },
      { id: "rm_011", text: "Their partner basically living there" },
      { id: "rm_012", text: "Slamming doors at 7 AM" },
      { id: "rm_013", text: "Using your stuff without asking" },
      { id: "rm_014", text: "Never cleaning the bathroom" },
      { id: "rm_015", text: "Cooking smelly food often" },
      { id: "rm_016", text: "Leaving hair in the drain" },
      { id: "rm_017", text: "Setting five alarms in a row" },
      { id: "rm_018", text: "Always controlling the thermostat" },
      { id: "rm_019", text: "Locking you out by accident" },
      { id: "rm_020", text: "Leaving shoes everywhere" },
      { id: "rm_021", text: "Being overly loud on phone calls" },
      { id: "rm_022", text: "Keeping expired food in the fridge" },
      { id: "rm_023", text: "Never buying household supplies" },
      { id: "rm_024", text: "Having the TV on all day" },
      { id: "rm_025", text: "Throwing parties without warning" },
    ]
  },
  {
    id: "first_world_problems",
    name: "First World Problems",
    scale: "How much this ruins your day",
    cards: [
      { id: "fwp_001", text: "WiFi buffering during a show" },
      { id: "fwp_002", text: "Your phone at 5% with no charger" },
      { id: "fwp_003", text: "The store is out of your favorite flavor" },
      { id: "fwp_004", text: "Cold food delivery" },
      { id: "fwp_005", text: "A slow coffee shop line" },
      { id: "fwp_006", text: "Your food arriving wrong at a restaurant" },
      { id: "fwp_007", text: "No parking spots up front" },
      { id: "fwp_008", text: "A cracked phone screen" },
      { id: "fwp_009", text: "Too many streaming services" },
      { id: "fwp_010", text: "Forgetting your reusable bags" },
      { id: "fwp_011", text: "The ice cream is too hard to scoop" },
      { id: "fwp_012", text: "Your headphones dying mid-workout" },
      { id: "fwp_013", text: "When your bed is too comfortable to leave" },
      { id: "fwp_014", text: "Getting an ad right before the good part" },
      { id: "fwp_015", text: "Your avocado going bad overnight" },
      { id: "fwp_016", text: "The fitted sheet popping off" },
      { id: "fwp_017", text: "Having nothing to watch with 500 options" },
      { id: "fwp_018", text: "A wet sock" },
      { id: "fwp_019", text: "When autocorrect changes the right word" },
      { id: "fwp_020", text: "An uneven tan line" },
      { id: "fwp_021", text: "Your lip balm going through the wash" },
      { id: "fwp_022", text: "A wobbly restaurant table" },
      { id: "fwp_023", text: "Running out of hot water mid-shower" },
      { id: "fwp_024", text: "Getting the wrong order at a drive-through" },
      { id: "fwp_025", text: "A seat that won't recline on a plane" },
    ]
  },
  {
    id: "things_to_teach_kids",
    name: "Things to Teach Kids",
    scale: "How important this lesson is",
    cards: [
      { id: "kid_001", text: "How to cook a basic meal" },
      { id: "kid_002", text: "Managing money" },
      { id: "kid_003", text: "Being kind to strangers" },
      { id: "kid_004", text: "How to lose gracefully" },
      { id: "kid_005", text: "Doing laundry" },
      { id: "kid_006", text: "Saying sorry and meaning it" },
      { id: "kid_007", text: "Reading for fun" },
      { id: "kid_008", text: "Standing up for others" },
      { id: "kid_009", text: "How to swim" },
      { id: "kid_010", text: "Cleaning up after yourself" },
      { id: "kid_011", text: "That failure is normal" },
      { id: "kid_012", text: "Trying new foods" },
      { id: "kid_013", text: "Being bored is okay" },
      { id: "kid_014", text: "Writing a handwritten note" },
      { id: "kid_015", text: "Changing a tire" },
      { id: "kid_016", text: "Asking for help" },
      { id: "kid_017", text: "Tipping at restaurants" },
      { id: "kid_018", text: "Respecting other cultures" },
      { id: "kid_019", text: "How to ride a bike" },
      { id: "kid_020", text: "Thinking before you speak" },
      { id: "kid_021", text: "That not everything is fair" },
      { id: "kid_022", text: "Doing chores without being asked" },
      { id: "kid_023", text: "Being a good listener" },
      { id: "kid_024", text: "How to shake hands properly" },
      { id: "kid_025", text: "That your word matters" },
    ]
  },
  {
    id: "conversation_starters",
    name: "Conversation Starters",
    scale: "How likely this leads to a great talk",
    cards: [
      { id: "convo_001", text: "What are you watching right now" },
      { id: "convo_002", text: "Where did you grow up" },
      { id: "convo_003", text: "What's your dream vacation" },
      { id: "convo_004", text: "Do you have any pets" },
      { id: "convo_005", text: "What's the best meal you've ever had" },
      { id: "convo_006", text: "What did you want to be as a kid" },
      { id: "convo_007", text: "Are you a morning or night person" },
      { id: "convo_008", text: "What's your go-to karaoke song" },
      { id: "convo_009", text: "What's the last thing that made you laugh" },
      { id: "convo_010", text: "What's your hot take on something" },
      { id: "convo_011", text: "What skill do you wish you had" },
      { id: "convo_012", text: "Who would play you in a movie" },
      { id: "convo_013", text: "What's your comfort show" },
      { id: "convo_014", text: "Are you a planner or spontaneous" },
      { id: "convo_015", text: "What's your favorite holiday" },
      { id: "convo_016", text: "What's the best advice you've gotten" },
      { id: "convo_017", text: "What are you weirdly competitive about" },
      { id: "convo_018", text: "What would your autobiography be called" },
      { id: "convo_019", text: "What's your love language" },
      { id: "convo_020", text: "What's the best concert you've been to" },
      { id: "convo_021", text: "What do you order at a coffee shop" },
      { id: "convo_022", text: "What's your unpopular opinion" },
      { id: "convo_023", text: "What decade would you live in" },
      { id: "convo_024", text: "What do you do to unwind" },
      { id: "convo_025", text: "What's one thing on your bucket list" },
    ]
  },
];
