// New categories 56-67
export default [
  {
    id: "excuses",
    name: "Excuses",
    scale: "How likely you are to use this",
    cards: [
      { id: "exc_001", text: "I didn't see your text" },
      { id: "exc_002", text: "My phone died" },
      { id: "exc_003", text: "I'm stuck in traffic" },
      { id: "exc_004", text: "I have an early morning" },
      { id: "exc_005", text: "I'm not feeling great" },
      { id: "exc_006", text: "Something came up" },
      { id: "exc_007", text: "I forgot" },
      { id: "exc_008", text: "I thought that was next week" },
      { id: "exc_009", text: "My alarm didn't go off" },
      { id: "exc_010", text: "I'm on my way" },
      { id: "exc_011", text: "I already have plans" },
      { id: "exc_012", text: "I have to work late" },
      { id: "exc_013", text: "My car won't start" },
      { id: "exc_014", text: "I just saw this" },
      { id: "exc_015", text: "I was in the shower" },
      { id: "exc_016", text: "I thought you said something else" },
      { id: "exc_017", text: "I didn't get the invite" },
      { id: "exc_018", text: "I fell asleep" },
      { id: "exc_019", text: "My WiFi was down" },
      { id: "exc_020", text: "I was about to text you" },
      { id: "exc_021", text: "I sent it but it didn't go through" },
      { id: "exc_022", text: "I have a family thing" },
      { id: "exc_023", text: "I'm waiting on a delivery" },
      { id: "exc_024", text: "I double-booked myself" },
      { id: "exc_025", text: "Let me check and get back to you" },
    ]
  },
  {
    id: "random_talents",
    name: "Random Talents",
    scale: "How much you wish you could do this",
    cards: [
      { id: "rtal_001", text: "Doing a backflip" },
      { id: "rtal_002", text: "Whistling with your fingers" },
      { id: "rtal_003", text: "Shuffling cards like a dealer" },
      { id: "rtal_004", text: "Solving a Rubik's cube fast" },
      { id: "rtal_005", text: "Doing a perfect cartwheel" },
      { id: "rtal_006", text: "Juggling" },
      { id: "rtal_007", text: "Rolling your R's" },
      { id: "rtal_008", text: "Catching food in your mouth" },
      { id: "rtal_009", text: "Beatboxing" },
      { id: "rtal_010", text: "Speed reading" },
      { id: "rtal_011", text: "Doing a handstand" },
      { id: "rtal_012", text: "Drawing a perfect circle" },
      { id: "rtal_013", text: "Picking locks" },
      { id: "rtal_014", text: "Pen spinning" },
      { id: "rtal_015", text: "Skipping stones perfectly" },
      { id: "rtal_016", text: "Parallel parking in one shot" },
      { id: "rtal_017", text: "Tying a cherry stem with your tongue" },
      { id: "rtal_018", text: "Remembering everyone's birthday" },
      { id: "rtal_019", text: "Doing any accent perfectly" },
      { id: "rtal_020", text: "Cooking without a recipe" },
      { id: "rtal_021", text: "A loud two-finger whistle" },
      { id: "rtal_022", text: "Guessing songs in one note" },
      { id: "rtal_023", text: "Doing the worm" },
      { id: "rtal_024", text: "Winking without looking weird" },
      { id: "rtal_025", text: "Folding a fitted sheet" },
    ]
  },
  {
    id: "types_of_rest",
    name: "Types of Rest",
    scale: "How much you need this right now",
    cards: [
      { id: "rest_001", text: "A nap" },
      { id: "rest_002", text: "A day with zero plans" },
      { id: "rest_003", text: "Turning your phone off" },
      { id: "rest_004", text: "A long bath" },
      { id: "rest_005", text: "Canceling everything" },
      { id: "rest_006", text: "Going to bed early" },
      { id: "rest_007", text: "A quiet walk alone" },
      { id: "rest_008", text: "Not talking to anyone for 24 hours" },
      { id: "rest_009", text: "A massage" },
      { id: "rest_010", text: "Sitting in the sun doing nothing" },
      { id: "rest_011", text: "A weekend with no screens" },
      { id: "rest_012", text: "Reading for hours" },
      { id: "rest_013", text: "A slow morning with coffee" },
      { id: "rest_014", text: "Sleeping with no alarm set" },
      { id: "rest_015", text: "A change of scenery" },
      { id: "rest_016", text: "Journaling your thoughts" },
      { id: "rest_017", text: "Saying no to everything for a week" },
      { id: "rest_018", text: "A long drive with no destination" },
      { id: "rest_019", text: "Cooking something slowly" },
      { id: "rest_020", text: "Time with one person you trust" },
      { id: "rest_021", text: "Watching clouds" },
      { id: "rest_022", text: "Stretching for 20 minutes" },
      { id: "rest_023", text: "Crying it out" },
      { id: "rest_024", text: "A hammock" },
      { id: "rest_025", text: "Doing absolutely nothing" },
    ]
  },
  {
    id: "things_outgrew",
    name: "Things You Outgrew",
    scale: "How much you miss this",
    cards: [
      { id: "outg_001", text: "Staying up past midnight easily" },
      { id: "outg_002", text: "Eating whatever with no consequences" },
      { id: "outg_003", text: "Drama with friends" },
      { id: "outg_004", text: "Caring what everyone thinks" },
      { id: "outg_005", text: "Partying every weekend" },
      { id: "outg_006", text: "Social media obsession" },
      { id: "outg_007", text: "Your first favorite band" },
      { id: "outg_008", text: "Needing to be right" },
      { id: "outg_009", text: "Pulling all-nighters" },
      { id: "outg_010", text: "Being scared of the dark" },
      { id: "outg_011", text: "Wanting to be popular" },
      { id: "outg_012", text: "Your college wardrobe" },
      { id: "outg_013", text: "Bouncing back from no sleep" },
      { id: "outg_014", text: "That one toxic friendship" },
      { id: "outg_015", text: "Fast fashion" },
      { id: "outg_016", text: "Needing plans every weekend" },
      { id: "outg_017", text: "Your first job" },
      { id: "outg_018", text: "Energy drinks" },
      { id: "outg_019", text: "Saying yes to everything" },
      { id: "outg_020", text: "Thinking adults had it figured out" },
      { id: "outg_021", text: "Living for Friday nights" },
      { id: "outg_022", text: "Your high school taste in music" },
      { id: "outg_023", text: "Matching with your best friend" },
      { id: "outg_024", text: "Believing you'd use your degree daily" },
      { id: "outg_025", text: "FOMO" },
    ]
  },
  {
    id: "group_chat",
    name: "Group Chat Behaviors",
    scale: "How much this annoys you",
    cards: [
      { id: "gc_001", text: "Someone who never responds" },
      { id: "gc_002", text: "Muting the chat permanently" },
      { id: "gc_003", text: "Plans changing 47 times" },
      { id: "gc_004", text: "Inside jokes you missed" },
      { id: "gc_005", text: "200 unread messages overnight" },
      { id: "gc_006", text: "Someone adding a random person" },
      { id: "gc_007", text: "The person who sends one word at a time" },
      { id: "gc_008", text: "Passive-aggressive energy" },
      { id: "gc_009", text: "Someone leaving without explanation" },
      { id: "gc_010", text: "A question nobody answers" },
      { id: "gc_011", text: "Photo dumps at midnight" },
      { id: "gc_012", text: "The off-topic spiral" },
      { id: "gc_013", text: "Someone screenshotting your messages" },
      { id: "gc_014", text: "A poll that gets three votes" },
      { id: "gc_015", text: "The person who always starts drama" },
      { id: "gc_016", text: "Reacting to every single message" },
      { id: "gc_017", text: "Scheduling plans over text for days" },
      { id: "gc_018", text: "Someone changing the group name" },
      { id: "gc_019", text: "The three dots that never become a message" },
      { id: "gc_020", text: "Someone only texting to ask for favors" },
      { id: "gc_021", text: "A wall of text from one person" },
      { id: "gc_022", text: "The one who always says 'I'm down' then bails" },
      { id: "gc_023", text: "Voice notes in a text-based chat" },
      { id: "gc_024", text: "Political debates nobody asked for" },
      { id: "gc_025", text: "Starting a new group for the same people" },
    ]
  },
  {
    id: "life_advice",
    name: "Life Advice",
    scale: "How much you wish you heard this sooner",
    cards: [
      { id: "advice_001", text: "It's okay to outgrow people" },
      { id: "advice_002", text: "Done is better than perfect" },
      { id: "advice_003", text: "Most people aren't thinking about you" },
      { id: "advice_004", text: "Comparison is the thief of joy" },
      { id: "advice_005", text: "Sleep is not optional" },
      { id: "advice_006", text: "Your gut is usually right" },
      { id: "advice_007", text: "Not every thought needs to be shared" },
      { id: "advice_008", text: "Show up even when you don't feel like it" },
      { id: "advice_009", text: "Save money before you need to" },
      { id: "advice_010", text: "Learn to cook a few meals well" },
      { id: "advice_011", text: "You don't owe everyone an explanation" },
      { id: "advice_012", text: "Take more photos of the people you love" },
      { id: "advice_013", text: "Don't keep score in friendships" },
      { id: "advice_014", text: "Say less" },
      { id: "advice_015", text: "Invest in good shoes" },
      { id: "advice_016", text: "Nobody has it all figured out" },
      { id: "advice_017", text: "Ask for help before you need it" },
      { id: "advice_018", text: "The days are long but the years are short" },
      { id: "advice_019", text: "You teach people how to treat you" },
      { id: "advice_020", text: "Drink more water" },
      { id: "advice_021", text: "Protect your energy" },
      { id: "advice_022", text: "It's okay to change your mind" },
      { id: "advice_023", text: "Be the friend you want to have" },
      { id: "advice_024", text: "Start before you're ready" },
      { id: "advice_025", text: "Your 20s are for figuring it out" },
    ]
  },
  {
    id: "wedding_details",
    name: "Wedding Details",
    scale: "How much you'd care about this",
    cards: [
      { id: "wed_001", text: "The venue" },
      { id: "wed_002", text: "The food" },
      { id: "wed_003", text: "The music and dancing" },
      { id: "wed_004", text: "The photographer" },
      { id: "wed_005", text: "The guest list" },
      { id: "wed_006", text: "The dress or suit" },
      { id: "wed_007", text: "The cake" },
      { id: "wed_008", text: "The vows" },
      { id: "wed_009", text: "Open bar" },
      { id: "wed_010", text: "The first dance song" },
      { id: "wed_011", text: "The flowers" },
      { id: "wed_012", text: "The seating chart" },
      { id: "wed_013", text: "The weather" },
      { id: "wed_014", text: "The speeches" },
      { id: "wed_015", text: "A live band vs. DJ" },
      { id: "wed_016", text: "The invitations" },
      { id: "wed_017", text: "Late-night snacks" },
      { id: "wed_018", text: "A photo booth" },
      { id: "wed_019", text: "The getaway car" },
      { id: "wed_020", text: "Matching bridesmaids or groomsmen" },
      { id: "wed_021", text: "A signature cocktail" },
      { id: "wed_022", text: "A sparkler send-off" },
      { id: "wed_023", text: "The honeymoon" },
      { id: "wed_024", text: "Table centerpieces" },
      { id: "wed_025", text: "A surprise for your partner" },
    ]
  },
  {
    id: "types_of_intelligence",
    name: "Types of Intelligence",
    scale: "How much you value this",
    cards: [
      { id: "intel_001", text: "Street smarts" },
      { id: "intel_002", text: "Emotional intelligence" },
      { id: "intel_003", text: "Book smarts" },
      { id: "intel_004", text: "Common sense" },
      { id: "intel_005", text: "Creativity" },
      { id: "intel_006", text: "Reading a room" },
      { id: "intel_007", text: "Problem-solving under pressure" },
      { id: "intel_008", text: "Musical ability" },
      { id: "intel_009", text: "Knowing when to be quiet" },
      { id: "intel_010", text: "Body awareness and coordination" },
      { id: "intel_011", text: "Quick wit" },
      { id: "intel_012", text: "Self-awareness" },
      { id: "intel_013", text: "Knowing how to fix things" },
      { id: "intel_014", text: "Being good with money" },
      { id: "intel_015", text: "Navigating without a GPS" },
      { id: "intel_016", text: "Reading people's intentions" },
      { id: "intel_017", text: "Spatial reasoning" },
      { id: "intel_018", text: "Memory for names and faces" },
      { id: "intel_019", text: "Persuasion" },
      { id: "intel_020", text: "Learning from mistakes" },
      { id: "intel_021", text: "Knowing a little about everything" },
      { id: "intel_022", text: "Adapting to new situations" },
      { id: "intel_023", text: "Knowing when to walk away" },
      { id: "intel_024", text: "Teaching others clearly" },
      { id: "intel_025", text: "Pattern recognition" },
    ]
  },
  {
    id: "things_to_collect",
    name: "Things to Collect",
    scale: "How much you'd enjoy collecting this",
    cards: [
      { id: "coll_001", text: "Vinyl records" },
      { id: "coll_002", text: "Books" },
      { id: "coll_003", text: "Sneakers" },
      { id: "coll_004", text: "Shot glasses from every city" },
      { id: "coll_005", text: "Vintage posters" },
      { id: "coll_006", text: "Plants" },
      { id: "coll_007", text: "Magnets from places you've been" },
      { id: "coll_008", text: "Concert ticket stubs" },
      { id: "coll_009", text: "Mugs" },
      { id: "coll_010", text: "Hot sauces" },
      { id: "coll_011", text: "Polaroid photos" },
      { id: "coll_012", text: "Old maps" },
      { id: "coll_013", text: "Board games" },
      { id: "coll_014", text: "Watches" },
      { id: "coll_015", text: "Postcards" },
      { id: "coll_016", text: "Hats" },
      { id: "coll_017", text: "Recipes you've tried" },
      { id: "coll_018", text: "Stickers" },
      { id: "coll_019", text: "Vintage cameras" },
      { id: "coll_020", text: "Spices from different countries" },
      { id: "coll_021", text: "Art prints" },
      { id: "coll_022", text: "Coins" },
      { id: "coll_023", text: "Keychains" },
      { id: "coll_024", text: "Seashells" },
      { id: "coll_025", text: "Cookbooks" },
    ]
  },
  {
    id: "lies_people_tell",
    name: "Things People Lie About",
    scale: "How often you stretch the truth here",
    cards: [
      { id: "lie_001", text: "How many drinks you had" },
      { id: "lie_002", text: "Whether you've seen that movie" },
      { id: "lie_003", text: "How long it took to get ready" },
      { id: "lie_004", text: "Your actual budget" },
      { id: "lie_005", text: "Whether you read the article" },
      { id: "lie_006", text: "How much sleep you got" },
      { id: "lie_007", text: "Being 'five minutes away'" },
      { id: "lie_008", text: "Liking someone's cooking" },
      { id: "lie_009", text: "Your body count" },
      { id: "lie_010", text: "Having read the terms and conditions" },
      { id: "lie_011", text: "Being fine" },
      { id: "lie_012", text: "How often you work out" },
      { id: "lie_013", text: "Whether you floss" },
      { id: "lie_014", text: "Your screen time" },
      { id: "lie_015", text: "Liking a gift you hate" },
      { id: "lie_016", text: "How much something cost" },
      { id: "lie_017", text: "Why you were late" },
      { id: "lie_018", text: "Whether you've been listening" },
      { id: "lie_019", text: "Having plans to avoid an invite" },
      { id: "lie_020", text: "Your age on a website" },
      { id: "lie_021", text: "How much you tipped" },
      { id: "lie_022", text: "Being busy when you're not" },
      { id: "lie_023", text: "Your weight" },
      { id: "lie_024", text: "Having watched that show everyone talks about" },
      { id: "lie_025", text: "Whether you cried during that movie" },
    ]
  },
  {
    id: "productivity_hacks",
    name: "Productivity Hacks",
    scale: "How much this actually helps you",
    cards: [
      { id: "prod_001", text: "A to-do list" },
      { id: "prod_002", text: "Putting your phone in another room" },
      { id: "prod_003", text: "The Pomodoro technique" },
      { id: "prod_004", text: "Working at a coffee shop" },
      { id: "prod_005", text: "A clean desk" },
      { id: "prod_006", text: "Noise-canceling headphones" },
      { id: "prod_007", text: "Waking up early" },
      { id: "prod_008", text: "Time-blocking your calendar" },
      { id: "prod_009", text: "Doing the hardest thing first" },
      { id: "prod_010", text: "A second monitor" },
      { id: "prod_011", text: "Body doubling" },
      { id: "prod_012", text: "Setting deadlines for yourself" },
      { id: "prod_013", text: "Working in silence" },
      { id: "prod_014", text: "Lo-fi beats" },
      { id: "prod_015", text: "Closing all your tabs" },
      { id: "prod_016", text: "A standing desk" },
      { id: "prod_017", text: "Batching similar tasks" },
      { id: "prod_018", text: "Saying no to meetings" },
      { id: "prod_019", text: "A physical planner" },
      { id: "prod_020", text: "Working in 90-minute sprints" },
      { id: "prod_021", text: "Airplane mode" },
      { id: "prod_022", text: "A reward after finishing something" },
      { id: "prod_023", text: "Cold water to wake up" },
      { id: "prod_024", text: "Writing things down by hand" },
      { id: "prod_025", text: "A countdown timer" },
    ]
  },
  {
    id: "ways_to_say_no",
    name: "Ways to Say No",
    scale: "How hard this is for you",
    cards: [
      { id: "sayno_001", text: "Turning down a party invite" },
      { id: "sayno_002", text: "Saying no to a friend asking for money" },
      { id: "sayno_003", text: "Declining a second date" },
      { id: "sayno_004", text: "Sending food back at a restaurant" },
      { id: "sayno_005", text: "Refusing overtime at work" },
      { id: "sayno_006", text: "Not answering the phone" },
      { id: "sayno_007", text: "Setting a boundary with family" },
      { id: "sayno_008", text: "Turning down a toast at a dinner" },
      { id: "sayno_009", text: "Saying no to a volunteer request" },
      { id: "sayno_010", text: "Declining a wedding invitation" },
      { id: "sayno_011", text: "Telling someone their idea isn't good" },
      { id: "sayno_012", text: "Not lending your car" },
      { id: "sayno_013", text: "Skipping a family event" },
      { id: "sayno_014", text: "Saying you don't like a gift" },
      { id: "sayno_015", text: "Refusing to help someone move" },
      { id: "sayno_016", text: "Not going to a coworker's birthday" },
      { id: "sayno_017", text: "Leaving a party early" },
      { id: "sayno_018", text: "Canceling plans you already made" },
      { id: "sayno_019", text: "Saying no to your boss" },
      { id: "sayno_020", text: "Not splitting the bill evenly" },
      { id: "sayno_021", text: "Turning down a road trip" },
      { id: "sayno_022", text: "Telling someone to lower their voice" },
      { id: "sayno_023", text: "Declining a group project role" },
      { id: "sayno_024", text: "Passing on a round of shots" },
      { id: "sayno_025", text: "Saying 'I just don't want to'" },
    ]
  },
];
