// Categories 1-16: Existing categories, cleaned & deduplicated
export default [
  {
    id: "foods",
    name: "Foods & Drinks",
    scale: "How much you're craving this right now",
    cards: [
      { id: "food_001", text: "Tacos" },
      { id: "food_002", text: "A perfectly ripe mango" },
      { id: "food_003", text: "Fresh-baked sourdough" },
      { id: "food_004", text: "A greasy breakfast sandwich" },
      { id: "food_005", text: "Sushi" },
      { id: "food_006", text: "Mac and cheese" },
      { id: "food_007", text: "A cold beer on a hot day" },
      { id: "food_008", text: "Cookies fresh from the oven" },
      { id: "food_009", text: "Spicy ramen" },
      { id: "food_010", text: "Ice cream" },
      { id: "food_011", text: "Crispy French fries" },
      { id: "food_012", text: "Pad Thai" },
      { id: "food_013", text: "A warm bowl of pho" },
      { id: "food_014", text: "A cheeseburger" },
      { id: "food_015", text: "Guacamole with warm chips" },
      { id: "food_016", text: "A slice of New York pizza" },
      { id: "food_017", text: "Chicken tikka masala" },
      { id: "food_018", text: "A good smoothie" },
      { id: "food_019", text: "Waffles with butter and syrup" },
      { id: "food_020", text: "A bagel with cream cheese" },
      { id: "food_021", text: "Grandma's cooking" },
      { id: "food_022", text: "A charcuterie board" },
      { id: "food_023", text: "Fresh-squeezed orange juice" },
      { id: "food_024", text: "Crispy fried chicken" },
      { id: "food_025", text: "A warm cinnamon roll" },
    ]
  },
  {
    id: "comfort",
    name: "Comfort & Coziness",
    scale: "How much you'd miss this if it were gone",
    cards: [
      { id: "comfort_001", text: "Your own bed" },
      { id: "comfort_002", text: "A hot shower" },
      { id: "comfort_003", text: "Your favorite hoodie" },
      { id: "comfort_004", text: "Your morning coffee or tea" },
      { id: "comfort_005", text: "A cozy blanket" },
      { id: "comfort_006", text: "Fast, reliable WiFi" },
      { id: "comfort_007", text: "A full night of sleep" },
      { id: "comfort_008", text: "Silence when you need it" },
      { id: "comfort_009", text: "A pet to come home to" },
      { id: "comfort_010", text: "Wearing whatever you want at home" },
      { id: "comfort_011", text: "Freshly washed sheets" },
      { id: "comfort_012", text: "Air conditioning on a hot day" },
      { id: "comfort_013", text: "Your favorite sweatpants" },
      { id: "comfort_014", text: "A warm bath" },
      { id: "comfort_015", text: "Having the house to yourself" },
      { id: "comfort_016", text: "A broken-in pair of shoes" },
      { id: "comfort_017", text: "Noise-canceling headphones" },
      { id: "comfort_018", text: "A fridge full of food you want" },
      { id: "comfort_019", text: "Getting home after a long trip" },
      { id: "comfort_020", text: "A good pillow" },
      { id: "comfort_021", text: "A shoulder massage" },
      { id: "comfort_022", text: "A clean house you didn't clean" },
      { id: "comfort_023", text: "Your favorite recliner or spot" },
      { id: "comfort_024", text: "Two-day shipping" },
      { id: "comfort_025", text: "The right room temperature" },
    ]
  },
  {
    id: "social_dread",
    name: "Social Situations",
    scale: "How much you dread this",
    cards: [
      { id: "social_001", text: "Running into your ex" },
      { id: "social_002", text: "Small talk at a party where you know nobody" },
      { id: "social_003", text: "Everyone singing happy birthday at you" },
      { id: "social_004", text: "A phone call when a text would do" },
      { id: "social_005", text: "Accidentally replying all" },
      { id: "social_006", text: "An awkward silence that won't end" },
      { id: "social_007", text: "Hearing your own voice recorded" },
      { id: "social_008", text: "A 'we need to talk' text" },
      { id: "social_009", text: "Waving at someone who wasn't waving at you" },
      { id: "social_010", text: "Forgetting someone's name immediately" },
      { id: "social_011", text: "Your card declining at the register" },
      { id: "social_012", text: "Being called on when you weren't listening" },
      { id: "social_013", text: "Telling a joke and nobody laughing" },
      { id: "social_014", text: "Walking into a glass door in public" },
      { id: "social_015", text: "Liking a three-year-old Instagram post" },
      { id: "social_016", text: "Food in your teeth all day" },
      { id: "social_017", text: "Someone swiping too far on your photos" },
      { id: "social_018", text: "Being way overdressed or underdressed" },
      { id: "social_019", text: "Calling a teacher 'Mom'" },
      { id: "social_020", text: "Mispronouncing a word for years" },
      { id: "social_021", text: "Being on speakerphone unknowingly" },
      { id: "social_022", text: "The silence when no one volunteers" },
      { id: "social_023", text: "Accidentally texting someone about them" },
      { id: "social_024", text: "Being asked 'so what do you do?'" },
      { id: "social_025", text: "Sending a voice note to the wrong person" },
    ]
  },
  {
    id: "activities",
    name: "Activities",
    scale: "How much you enjoy this",
    cards: [
      { id: "act_001", text: "A long hike with a great view" },
      { id: "act_002", text: "Cooking a meal from scratch" },
      { id: "act_003", text: "A lazy Sunday with no plans" },
      { id: "act_004", text: "Reading a book you can't put down" },
      { id: "act_005", text: "Playing a board game with friends" },
      { id: "act_006", text: "Exploring a new city on foot" },
      { id: "act_007", text: "Getting absorbed in a video game" },
      { id: "act_008", text: "A spontaneous road trip" },
      { id: "act_009", text: "A bonfire with friends" },
      { id: "act_010", text: "A long drive with good music" },
      { id: "act_011", text: "Swimming in a lake on a hot day" },
      { id: "act_012", text: "Dancing when your song comes on" },
      { id: "act_013", text: "An accidental three-hour nap" },
      { id: "act_014", text: "Trying a restaurant you've walked past forever" },
      { id: "act_015", text: "Going to a museum" },
      { id: "act_016", text: "Flying a kite on a windy day" },
      { id: "act_017", text: "Staying up late talking with a friend" },
      { id: "act_018", text: "Finding treasure at a flea market" },
      { id: "act_019", text: "People-watching at a coffee shop" },
      { id: "act_020", text: "Running through sprinklers" },
      { id: "act_021", text: "Ice skating" },
      { id: "act_022", text: "A walk with no destination" },
      { id: "act_023", text: "Painting or drawing" },
      { id: "act_024", text: "Karaoke night" },
      { id: "act_025", text: "Watching a sunset" },
    ]
  },
  {
    id: "upgrades",
    name: "Life Upgrades",
    scale: "How much you'd want this",
    cards: [
      { id: "upg_001", text: "A personal chef" },
      { id: "upg_002", text: "Never doing laundry again" },
      { id: "upg_003", text: "Perfect sleep every night" },
      { id: "upg_004", text: "Never sitting in traffic again" },
      { id: "upg_005", text: "Never worrying about money" },
      { id: "upg_006", text: "Fast internet everywhere" },
      { id: "upg_007", text: "Never getting sick" },
      { id: "upg_008", text: "An extra hour every day" },
      { id: "upg_009", text: "Always knowing what to say" },
      { id: "upg_010", text: "Waking up refreshed every morning" },
      { id: "upg_011", text: "A weekly cleaning service" },
      { id: "upg_012", text: "Teeth that never need work" },
      { id: "upg_013", text: "Clothes that always fit perfectly" },
      { id: "upg_014", text: "Speaking every language fluently" },
      { id: "upg_015", text: "Never losing your keys or phone" },
      { id: "upg_016", text: "A metabolism that handles anything" },
      { id: "upg_017", text: "Always having exact change" },
      { id: "upg_018", text: "A front-row parking spot every time" },
      { id: "upg_019", text: "Perfect vision forever" },
      { id: "upg_020", text: "Effortlessly great hair" },
      { id: "upg_021", text: "A body that heals twice as fast" },
      { id: "upg_022", text: "Free first-class flights for life" },
      { id: "upg_023", text: "A photographic memory" },
      { id: "upg_024", text: "Never feeling jet-lagged" },
      { id: "upg_025", text: "Knowing which decisions to make" },
    ]
  },
  {
    id: "annoyances",
    name: "Annoyances",
    scale: "How much this ruins your day",
    cards: [
      { id: "ann_001", text: "Stepping on a wet floor in socks" },
      { id: "ann_002", text: "Your phone dying with no charger" },
      { id: "ann_003", text: "Slow WiFi when you need it" },
      { id: "ann_004", text: "A mosquito in your room at night" },
      { id: "ann_005", text: "Being on hold for 45 minutes" },
      { id: "ann_006", text: "Someone spoiling a show" },
      { id: "ann_007", text: "Running out of hot water mid-shower" },
      { id: "ann_008", text: "A charger that only works at one angle" },
      { id: "ann_009", text: "Buffering during the best part" },
      { id: "ann_010", text: "Sending a message to the wrong person" },
      { id: "ann_011", text: "A paper cut" },
      { id: "ann_012", text: "Headphones yanked out by a doorknob" },
      { id: "ann_013", text: "Forgetting why you walked into a room" },
      { id: "ann_014", text: "A song you hate stuck in your head" },
      { id: "ann_015", text: "Someone eating your labeled food" },
      { id: "ann_016", text: "Accidentally closing a tab you needed" },
      { id: "ann_017", text: "Autocorrect changing your words" },
      { id: "ann_018", text: "Sitting on your sunglasses" },
      { id: "ann_019", text: "Rain the second you step outside" },
      { id: "ann_020", text: "A rock in your shoe" },
      { id: "ann_021", text: "Hitting every red light" },
      { id: "ann_022", text: "Pen running out of ink mid-sentence" },
      { id: "ann_023", text: "Someone parking too close to your door" },
      { id: "ann_024", text: "A hangnail that catches on everything" },
      { id: "ann_025", text: "A wobbly table at a restaurant" },
    ]
  },
  {
    id: "movies_tv",
    name: "Movies & TV",
    scale: "How likely you are to rewatch this",
    cards: [
      { id: "mtv_001", text: "A rom-com you've seen ten times" },
      { id: "mtv_002", text: "A thriller that kept you up all night" },
      { id: "mtv_003", text: "A documentary that changed your view" },
      { id: "mtv_004", text: "A show you binged in one weekend" },
      { id: "mtv_005", text: "A movie that made you ugly cry" },
      { id: "mtv_006", text: "A comedy special that wrecked you" },
      { id: "mtv_007", text: "A childhood cartoon you still love" },
      { id: "mtv_008", text: "A slow-burn drama with a perfect finale" },
      { id: "mtv_009", text: "A trashy reality show" },
      { id: "mtv_010", text: "A movie with a twist you never saw coming" },
      { id: "mtv_011", text: "An animated movie that hits harder as an adult" },
      { id: "mtv_012", text: "A horror movie that genuinely scared you" },
      { id: "mtv_013", text: "A show with the perfect series finale" },
      { id: "mtv_014", text: "A movie you can quote word for word" },
      { id: "mtv_015", text: "A miniseries you watched in one sitting" },
      { id: "mtv_016", text: "A show you recommend to everyone" },
      { id: "mtv_017", text: "A movie with an incredible soundtrack" },
      { id: "mtv_018", text: "A foreign film that blew your mind" },
      { id: "mtv_019", text: "A comfort show you watch when sick" },
      { id: "mtv_020", text: "A villain you secretly rooted for" },
      { id: "mtv_021", text: "A pilot that hooked you immediately" },
      { id: "mtv_022", text: "A movie that made you think for days" },
      { id: "mtv_023", text: "A show you watched for one character" },
      { id: "mtv_024", text: "A sequel better than the original" },
      { id: "mtv_025", text: "A movie so bad it's good" },
    ]
  },
  {
    id: "music",
    name: "Music Moments",
    scale: "How powerful this moment is",
    cards: [
      { id: "mus_001", text: "Your song coming on shuffle perfectly" },
      { id: "mus_002", text: "Discovering an artist before they blow up" },
      { id: "mus_003", text: "Feeling the bass at a live concert" },
      { id: "mus_004", text: "A song that makes you drive faster" },
      { id: "mus_005", text: "A song that takes you back instantly" },
      { id: "mus_006", text: "Singing alone in the car at full volume" },
      { id: "mus_007", text: "The drop in a song you've been waiting for" },
      { id: "mus_008", text: "Learning all the lyrics to a new song" },
      { id: "mus_009", text: "A playlist that matches your mood exactly" },
      { id: "mus_010", text: "Hearing a song you forgot existed" },
      { id: "mus_011", text: "The opening notes of your favorite song" },
      { id: "mus_012", text: "A road trip playlist" },
      { id: "mus_013", text: "Music that gives you chills" },
      { id: "mus_014", text: "A song that makes you cry every time" },
      { id: "mus_015", text: "Dancing alone in your room" },
      { id: "mus_016", text: "A whole crowd singing along together" },
      { id: "mus_017", text: "The silence after an incredible song" },
      { id: "mus_018", text: "A bassline that lives in your head" },
      { id: "mus_019", text: "Putting someone onto new music" },
      { id: "mus_020", text: "A song at a wedding or funeral" },
      { id: "mus_021", text: "An album you've listened to front to back" },
      { id: "mus_022", text: "Music that makes a workout fly by" },
      { id: "mus_023", text: "Sharing headphones with someone" },
      { id: "mus_024", text: "A late-night drive with the right song" },
      { id: "mus_025", text: "Hearing a street musician nail it" },
    ]
  },
  {
    id: "travel",
    name: "Travel Destinations",
    scale: "How badly you want to go here",
    cards: [
      { id: "trv_001", text: "Tokyo" },
      { id: "trv_002", text: "A cabin in the mountains" },
      { id: "trv_003", text: "A beach with nothing to do" },
      { id: "trv_004", text: "A European city you can't pronounce" },
      { id: "trv_005", text: "New York City" },
      { id: "trv_006", text: "The Northern Lights" },
      { id: "trv_007", text: "A safari in Africa" },
      { id: "trv_008", text: "A cozy Airbnb in a small town" },
      { id: "trv_009", text: "Bali" },
      { id: "trv_010", text: "A cross-country road trip" },
      { id: "trv_011", text: "Iceland" },
      { id: "trv_012", text: "A street market in Southeast Asia" },
      { id: "trv_013", text: "Paris" },
      { id: "trv_014", text: "The Grand Canyon" },
      { id: "trv_015", text: "A Greek island" },
      { id: "trv_016", text: "A backpacking trip through South America" },
      { id: "trv_017", text: "A train ride through the countryside" },
      { id: "trv_018", text: "An overwater bungalow" },
      { id: "trv_019", text: "A food tour in Italy" },
      { id: "trv_020", text: "Machu Picchu" },
      { id: "trv_021", text: "A cruise to nowhere" },
      { id: "trv_022", text: "A music festival abroad" },
      { id: "trv_023", text: "The Amalfi Coast" },
      { id: "trv_024", text: "A treehouse hotel in the jungle" },
      { id: "trv_025", text: "Antarctica" },
    ]
  },
  {
    id: "nostalgia",
    name: "Childhood Nostalgia",
    scale: "How much you miss this",
    cards: [
      { id: "nos_001", text: "Summer break" },
      { id: "nos_002", text: "Saturday morning cartoons" },
      { id: "nos_003", text: "Sleepovers with friends" },
      { id: "nos_004", text: "Your first best friend" },
      { id: "nos_005", text: "Trick-or-treating" },
      { id: "nos_006", text: "Recess" },
      { id: "nos_007", text: "Snow days" },
      { id: "nos_008", text: "Building a blanket fort" },
      { id: "nos_009", text: "Your favorite toy" },
      { id: "nos_010", text: "Not knowing what time it was" },
      { id: "nos_011", text: "Riding bikes around the neighborhood" },
      { id: "nos_012", text: "The last day of school" },
      { id: "nos_013", text: "Birthday parties with all your friends" },
      { id: "nos_014", text: "Catching fireflies" },
      { id: "nos_015", text: "Getting picked first in gym class" },
      { id: "nos_016", text: "A home-cooked meal after school" },
      { id: "nos_017", text: "The ice cream truck jingle" },
      { id: "nos_018", text: "Climbing trees" },
      { id: "nos_019", text: "Your childhood bedroom" },
      { id: "nos_020", text: "Family road trips" },
      { id: "nos_021", text: "The excitement of a new school year" },
      { id: "nos_022", text: "Playing in the rain" },
      { id: "nos_023", text: "Your favorite Halloween costume" },
      { id: "nos_024", text: "Friday afternoon before the weekend" },
      { id: "nos_025", text: "Believing in magic" },
    ]
  },
  {
    id: "superpowers",
    name: "Superpowers",
    scale: "How much you'd want this power",
    cards: [
      { id: "pow_001", text: "Flying" },
      { id: "pow_002", text: "Reading minds" },
      { id: "pow_003", text: "Invisibility" },
      { id: "pow_004", text: "Time travel" },
      { id: "pow_005", text: "Super strength" },
      { id: "pow_006", text: "Teleportation" },
      { id: "pow_007", text: "Perfect memory" },
      { id: "pow_008", text: "Healing any injury or illness" },
      { id: "pow_009", text: "Controlling the weather" },
      { id: "pow_010", text: "Talking to animals" },
      { id: "pow_011", text: "Shapeshifting" },
      { id: "pow_012", text: "Super speed" },
      { id: "pow_013", text: "Breathing underwater" },
      { id: "pow_014", text: "Seeing the future" },
      { id: "pow_015", text: "Mind control" },
      { id: "pow_016", text: "X-ray vision" },
      { id: "pow_017", text: "Stopping time" },
      { id: "pow_018", text: "Talking to the dead" },
      { id: "pow_019", text: "Creating force fields" },
      { id: "pow_020", text: "Duplicating yourself" },
      { id: "pow_021", text: "Telekinesis" },
      { id: "pow_022", text: "Shrinking or growing at will" },
      { id: "pow_023", text: "Learning any skill instantly" },
      { id: "pow_024", text: "Making yourself weightless" },
      { id: "pow_025", text: "Controlling fire" },
    ]
  },
  {
    id: "fears",
    name: "Fears & Phobias",
    scale: "How much this terrifies you",
    cards: [
      { id: "fear_001", text: "Being stuck in a small space" },
      { id: "fear_002", text: "Public speaking" },
      { id: "fear_003", text: "Heights" },
      { id: "fear_004", text: "Open water you can't see through" },
      { id: "fear_005", text: "Spiders" },
      { id: "fear_006", text: "Flying in a plane" },
      { id: "fear_007", text: "Losing your memory" },
      { id: "fear_008", text: "The dark" },
      { id: "fear_009", text: "Snakes" },
      { id: "fear_010", text: "Being alone forever" },
      { id: "fear_011", text: "A knock on the door at 3 AM" },
      { id: "fear_012", text: "Sharks" },
      { id: "fear_013", text: "Needles" },
      { id: "fear_014", text: "Being watched and not knowing it" },
      { id: "fear_015", text: "Walking alone at night" },
      { id: "fear_016", text: "Your phone screen during a presentation" },
      { id: "fear_017", text: "Clowns" },
      { id: "fear_018", text: "Outliving everyone you love" },
      { id: "fear_019", text: "Being trapped in an elevator" },
      { id: "fear_020", text: "A car with no brakes" },
      { id: "fear_021", text: "The deep ocean at night" },
      { id: "fear_022", text: "Waking up during surgery" },
      { id: "fear_023", text: "Identity theft" },
      { id: "fear_024", text: "Sleep paralysis" },
      { id: "fear_025", text: "A bridge swaying in the wind" },
    ]
  },
  {
    id: "date_night",
    name: "Date Night Ideas",
    scale: "How great of a date this would be",
    cards: [
      { id: "date_001", text: "Cooking dinner together" },
      { id: "date_002", text: "A rooftop restaurant" },
      { id: "date_003", text: "A sunset hike" },
      { id: "date_004", text: "A comedy show" },
      { id: "date_005", text: "A wine or cocktail tasting" },
      { id: "date_006", text: "A bookstore then coffee" },
      { id: "date_007", text: "A picnic in the park" },
      { id: "date_008", text: "A movie marathon at home" },
      { id: "date_009", text: "An escape room" },
      { id: "date_010", text: "A farmers market morning" },
      { id: "date_011", text: "A ferry ride at sunset" },
      { id: "date_012", text: "A museum with no rush" },
      { id: "date_013", text: "A vinyl record shopping trip" },
      { id: "date_014", text: "A food truck crawl" },
      { id: "date_015", text: "Stargazing somewhere dark" },
      { id: "date_016", text: "A pottery or painting class" },
      { id: "date_017", text: "A spontaneous road trip" },
      { id: "date_018", text: "An arcade or bowling alley" },
      { id: "date_019", text: "Dancing — any kind" },
      { id: "date_020", text: "A concert" },
      { id: "date_021", text: "A neighborhood walk at night" },
      { id: "date_022", text: "A themed dinner at home" },
      { id: "date_023", text: "A boat ride" },
      { id: "date_024", text: "Ice cream and a long walk" },
      { id: "date_025", text: "Breakfast for dinner" },
    ]
  },
  {
    id: "workouts",
    name: "Workout Types",
    scale: "How likely you'd do this regularly",
    cards: [
      { id: "wrk_001", text: "Running" },
      { id: "wrk_002", text: "Yoga" },
      { id: "wrk_003", text: "Weight lifting" },
      { id: "wrk_004", text: "Swimming laps" },
      { id: "wrk_005", text: "A dance class" },
      { id: "wrk_006", text: "Rock climbing" },
      { id: "wrk_007", text: "Cycling" },
      { id: "wrk_008", text: "A pickup basketball game" },
      { id: "wrk_009", text: "A long walk" },
      { id: "wrk_010", text: "A quick home workout" },
      { id: "wrk_011", text: "Boxing" },
      { id: "wrk_012", text: "Tennis" },
      { id: "wrk_013", text: "CrossFit" },
      { id: "wrk_014", text: "Martial arts" },
      { id: "wrk_015", text: "Hiking" },
      { id: "wrk_016", text: "Pilates" },
      { id: "wrk_017", text: "Rowing" },
      { id: "wrk_018", text: "A spin class" },
      { id: "wrk_019", text: "Jump rope" },
      { id: "wrk_020", text: "Surfing" },
      { id: "wrk_021", text: "Stretching for 20 minutes" },
      { id: "wrk_022", text: "Hot yoga" },
      { id: "wrk_023", text: "Playing soccer" },
      { id: "wrk_024", text: "Rollerblading" },
      { id: "wrk_025", text: "A stairmaster session" },
    ]
  },
  {
    id: "apps",
    name: "Apps & Websites",
    scale: "How lost you'd be without this",
    cards: [
      { id: "app_001", text: "Google Maps" },
      { id: "app_002", text: "Spotify or Apple Music" },
      { id: "app_003", text: "A group chat app" },
      { id: "app_004", text: "Online banking" },
      { id: "app_005", text: "YouTube" },
      { id: "app_006", text: "A food delivery app" },
      { id: "app_007", text: "Instagram" },
      { id: "app_008", text: "Wikipedia" },
      { id: "app_009", text: "A weather app" },
      { id: "app_010", text: "Netflix or streaming" },
      { id: "app_011", text: "A podcast app" },
      { id: "app_012", text: "Your photo gallery" },
      { id: "app_013", text: "A calendar app" },
      { id: "app_014", text: "A language-learning app" },
      { id: "app_015", text: "TikTok" },
      { id: "app_016", text: "Amazon" },
      { id: "app_017", text: "A notes app" },
      { id: "app_018", text: "Google Search" },
      { id: "app_019", text: "A fitness tracker" },
      { id: "app_020", text: "An alarm app" },
      { id: "app_021", text: "A recipe app" },
      { id: "app_022", text: "Venmo or payment apps" },
      { id: "app_023", text: "Reddit" },
      { id: "app_024", text: "Your email" },
      { id: "app_025", text: "A ride-sharing app" },
    ]
  },
  {
    id: "dream_jobs",
    name: "Dream Jobs",
    scale: "How much you'd love this career",
    cards: [
      { id: "job_001", text: "Travel show host" },
      { id: "job_002", text: "Video game designer" },
      { id: "job_003", text: "Professional food taster" },
      { id: "job_004", text: "National park ranger" },
      { id: "job_005", text: "Astronaut" },
      { id: "job_006", text: "Bestselling novelist" },
      { id: "job_007", text: "Music producer" },
      { id: "job_008", text: "Professional athlete" },
      { id: "job_009", text: "Film director" },
      { id: "job_010", text: "Owning a bookstore" },
      { id: "job_011", text: "Surfing instructor in Hawaii" },
      { id: "job_012", text: "Wildlife photographer" },
      { id: "job_013", text: "Running a bed and breakfast" },
      { id: "job_014", text: "Voice actor" },
      { id: "job_015", text: "Museum curator" },
      { id: "job_016", text: "Travel writer" },
      { id: "job_017", text: "Stand-up comedian" },
      { id: "job_018", text: "Ice cream flavor inventor" },
      { id: "job_019", text: "Architect" },
      { id: "job_020", text: "Professional video game streamer" },
      { id: "job_021", text: "Race car driver" },
      { id: "job_022", text: "Owning a vineyard" },
      { id: "job_023", text: "Marine biologist" },
      { id: "job_024", text: "Owning a food truck" },
      { id: "job_025", text: "Treasure hunter" },
    ]
  },
];
