// New categories 31-43
export default [
  {
    id: "compliments",
    name: "Compliments",
    scale: "How good this would make you feel",
    cards: [
      { id: "comp_001", text: "You're the funniest person I know" },
      { id: "comp_002", text: "You look great today" },
      { id: "comp_003", text: "You give the best advice" },
      { id: "comp_004", text: "I always feel safe around you" },
      { id: "comp_005", text: "You're a great listener" },
      { id: "comp_006", text: "Your smile lights up a room" },
      { id: "comp_007", text: "You're so easy to talk to" },
      { id: "comp_008", text: "I wish I had your confidence" },
      { id: "comp_009", text: "You have amazing taste" },
      { id: "comp_010", text: "You make everyone around you better" },
      { id: "comp_011", text: "Your outfit is incredible" },
      { id: "comp_012", text: "You're the hardest worker I know" },
      { id: "comp_013", text: "You're the kind of person I want to be" },
      { id: "comp_014", text: "You have a great voice" },
      { id: "comp_015", text: "You're genuinely one of a kind" },
      { id: "comp_016", text: "People feel better after talking to you" },
      { id: "comp_017", text: "You have great energy" },
      { id: "comp_018", text: "Your cooking is incredible" },
      { id: "comp_019", text: "You always know what to say" },
      { id: "comp_020", text: "You have a contagious laugh" },
      { id: "comp_021", text: "You make hard things look easy" },
      { id: "comp_022", text: "I admire your patience" },
      { id: "comp_023", text: "You smell amazing" },
      { id: "comp_024", text: "You're the glue of this friend group" },
      { id: "comp_025", text: "I trust your judgment completely" },
    ]
  },
  {
    id: "first_dates",
    name: "First Date Nerves",
    scale: "How nervous this would make you",
    cards: [
      { id: "fdate_001", text: "Awkward silence at the table" },
      { id: "fdate_002", text: "Deciding who pays" },
      { id: "fdate_003", text: "Spilling a drink on yourself" },
      { id: "fdate_004", text: "Running out of things to say" },
      { id: "fdate_005", text: "The goodbye moment" },
      { id: "fdate_006", text: "Forgetting their name" },
      { id: "fdate_007", text: "Showing up underdressed" },
      { id: "fdate_008", text: "Ordering something messy" },
      { id: "fdate_009", text: "Your phone going off mid-sentence" },
      { id: "fdate_010", text: "Getting food in your teeth" },
      { id: "fdate_011", text: "Laughing too hard at something not funny" },
      { id: "fdate_012", text: "A long pause after a joke" },
      { id: "fdate_013", text: "Accidentally mentioning your ex" },
      { id: "fdate_014", text: "Arriving first and sitting alone" },
      { id: "fdate_015", text: "Sweaty handshake or hug" },
      { id: "fdate_016", text: "Mispronouncing something on the menu" },
      { id: "fdate_017", text: "Checking if there's something in your teeth" },
      { id: "fdate_018", text: "Overthinking what to wear" },
      { id: "fdate_019", text: "The walk to the car after" },
      { id: "fdate_020", text: "Realizing your breath might be bad" },
      { id: "fdate_021", text: "A text from your friend asking how it's going" },
      { id: "fdate_022", text: "Eye contact that goes on too long" },
      { id: "fdate_023", text: "Accidentally talking too much about yourself" },
      { id: "fdate_024", text: "Waiting for the first text after" },
      { id: "fdate_025", text: "They look different from their photos" },
    ]
  },
  {
    id: "conversation_topics",
    name: "Conversation Topics",
    scale: "How long you could talk about this",
    cards: [
      { id: "conv_001", text: "Conspiracy theories" },
      { id: "conv_002", text: "Travel stories" },
      { id: "conv_003", text: "Your childhood" },
      { id: "conv_004", text: "Celebrity drama" },
      { id: "conv_005", text: "Food and restaurants" },
      { id: "conv_006", text: "Your pet" },
      { id: "conv_007", text: "Sports" },
      { id: "conv_008", text: "True crime" },
      { id: "conv_009", text: "Music recommendations" },
      { id: "conv_010", text: "Dreams you've had" },
      { id: "conv_011", text: "Your love life" },
      { id: "conv_012", text: "Movies and TV" },
      { id: "conv_013", text: "The meaning of life" },
      { id: "conv_014", text: "Work drama" },
      { id: "conv_015", text: "Aliens and space" },
      { id: "conv_016", text: "Your hot takes" },
      { id: "conv_017", text: "Hypothetical scenarios" },
      { id: "conv_018", text: "Money and investing" },
      { id: "conv_019", text: "Embarrassing stories" },
      { id: "conv_020", text: "Your family" },
      { id: "conv_021", text: "Health and fitness" },
      { id: "conv_022", text: "Politics" },
      { id: "conv_023", text: "Fashion and style" },
      { id: "conv_024", text: "Video games" },
      { id: "conv_025", text: "What happens when we die" },
    ]
  },
  {
    id: "childhood_games",
    name: "Childhood Games",
    scale: "How much you want to play this again",
    cards: [
      { id: "cgame_001", text: "Tag" },
      { id: "cgame_002", text: "Hide and seek" },
      { id: "cgame_003", text: "Capture the flag" },
      { id: "cgame_004", text: "Kickball" },
      { id: "cgame_005", text: "Dodgeball" },
      { id: "cgame_006", text: "Four square" },
      { id: "cgame_007", text: "Marco Polo" },
      { id: "cgame_008", text: "Red Rover" },
      { id: "cgame_009", text: "Musical chairs" },
      { id: "cgame_010", text: "Freeze tag" },
      { id: "cgame_011", text: "Sardines" },
      { id: "cgame_012", text: "Manhunt" },
      { id: "cgame_013", text: "Kick the can" },
      { id: "cgame_014", text: "Flashlight tag at night" },
      { id: "cgame_015", text: "Simon Says" },
      { id: "cgame_016", text: "Red Light, Green Light" },
      { id: "cgame_017", text: "Cops and Robbers" },
      { id: "cgame_018", text: "Playground basketball" },
      { id: "cgame_019", text: "Double Dutch" },
      { id: "cgame_020", text: "Wall ball" },
      { id: "cgame_021", text: "Tug of war" },
      { id: "cgame_022", text: "Monkey in the Middle" },
      { id: "cgame_023", text: "Hopscotch" },
      { id: "cgame_024", text: "Ghost in the Graveyard" },
      { id: "cgame_025", text: "Sharks and Minnows" },
    ]
  },
  {
    id: "rabbit_holes",
    name: "Internet Rabbit Holes",
    scale: "How deep you'd go",
    cards: [
      { id: "rabbit_001", text: "Unsolved mysteries" },
      { id: "rabbit_002", text: "Celebrity net worths" },
      { id: "rabbit_003", text: "Wikipedia at 3 AM" },
      { id: "rabbit_004", text: "House tours of mansions" },
      { id: "rabbit_005", text: "True crime deep dives" },
      { id: "rabbit_006", text: "Conspiracy theory threads" },
      { id: "rabbit_007", text: "Your own name on Google" },
      { id: "rabbit_008", text: "Plane ticket prices to random places" },
      { id: "rabbit_009", text: "'What happened to' child actors" },
      { id: "rabbit_010", text: "Restaurant reviews before choosing" },
      { id: "rabbit_011", text: "Dog breeds you'll never own" },
      { id: "rabbit_012", text: "Reddit AMAs" },
      { id: "rabbit_013", text: "Old yearbook photos of celebrities" },
      { id: "rabbit_014", text: "How things are made" },
      { id: "rabbit_015", text: "Historical events you never learned" },
      { id: "rabbit_016", text: "Tiny house tours" },
      { id: "rabbit_017", text: "Salary comparisons" },
      { id: "rabbit_018", text: "Before and after home renovations" },
      { id: "rabbit_019", text: "Your ex's social media" },
      { id: "rabbit_020", text: "A stranger's entire Instagram" },
      { id: "rabbit_021", text: "Wedding planning boards" },
      { id: "rabbit_022", text: "Cooking videos at midnight" },
      { id: "rabbit_023", text: "Your symptoms on WebMD" },
      { id: "rabbit_024", text: "Amazon reviews for weird products" },
      { id: "rabbit_025", text: "What your name means" },
    ]
  },
  {
    id: "things_to_learn",
    name: "Things to Learn",
    scale: "How badly you want to master this",
    cards: [
      { id: "learn_001", text: "A new language" },
      { id: "learn_002", text: "Playing guitar" },
      { id: "learn_003", text: "Cooking Italian food" },
      { id: "learn_004", text: "Photography" },
      { id: "learn_005", text: "Coding" },
      { id: "learn_006", text: "Surfing" },
      { id: "learn_007", text: "Dancing salsa" },
      { id: "learn_008", text: "Woodworking" },
      { id: "learn_009", text: "Playing piano" },
      { id: "learn_010", text: "Pottery" },
      { id: "learn_011", text: "Investing" },
      { id: "learn_012", text: "Sewing your own clothes" },
      { id: "learn_013", text: "Mixology" },
      { id: "learn_014", text: "Sign language" },
      { id: "learn_015", text: "Martial arts" },
      { id: "learn_016", text: "Drawing or painting" },
      { id: "learn_017", text: "Rock climbing" },
      { id: "learn_018", text: "Chess at a competitive level" },
      { id: "learn_019", text: "Car mechanics" },
      { id: "learn_020", text: "Gardening" },
      { id: "learn_021", text: "Scuba diving" },
      { id: "learn_022", text: "Calligraphy" },
      { id: "learn_023", text: "Public speaking" },
      { id: "learn_024", text: "Baking bread" },
      { id: "learn_025", text: "Skateboarding" },
    ]
  },
  {
    id: "bad_habits",
    name: "Bad Habits",
    scale: "How hard this would be to quit",
    cards: [
      { id: "bhab_001", text: "Doomscrolling before bed" },
      { id: "bhab_002", text: "Hitting snooze too many times" },
      { id: "bhab_003", text: "Stress eating" },
      { id: "bhab_004", text: "Procrastinating" },
      { id: "bhab_005", text: "Biting your nails" },
      { id: "bhab_006", text: "Staying up way too late" },
      { id: "bhab_007", text: "Skipping breakfast" },
      { id: "bhab_008", text: "Online shopping when bored" },
      { id: "bhab_009", text: "Checking your phone in bed" },
      { id: "bhab_010", text: "Saying yes when you mean no" },
      { id: "bhab_011", text: "Comparing yourself to others online" },
      { id: "bhab_012", text: "Not drinking enough water" },
      { id: "bhab_013", text: "Leaving dishes in the sink" },
      { id: "bhab_014", text: "Skipping the gym" },
      { id: "bhab_015", text: "Ordering delivery instead of cooking" },
      { id: "bhab_016", text: "Interrupting people" },
      { id: "bhab_017", text: "Overthinking everything" },
      { id: "bhab_018", text: "Forgetting to reply to texts" },
      { id: "bhab_019", text: "Cracking your knuckles" },
      { id: "bhab_020", text: "Gossiping" },
      { id: "bhab_021", text: "Eating in bed" },
      { id: "bhab_022", text: "Not flossing" },
      { id: "bhab_023", text: "Picking at your skin" },
      { id: "bhab_024", text: "Watching one more episode" },
      { id: "bhab_025", text: "Spending money you don't have" },
    ]
  },
  {
    id: "small_wins",
    name: "Small Wins",
    scale: "How much this brightens your day",
    cards: [
      { id: "swin_001", text: "Finding money in your pocket" },
      { id: "swin_002", text: "All green lights on your drive" },
      { id: "swin_003", text: "A compliment from a stranger" },
      { id: "swin_004", text: "Your package arriving early" },
      { id: "swin_005", text: "A perfect parking spot" },
      { id: "swin_006", text: "Waking up before your alarm" },
      { id: "swin_007", text: "Inbox zero" },
      { id: "swin_008", text: "A canceled meeting" },
      { id: "swin_009", text: "Finishing a book" },
      { id: "swin_010", text: "Exact change in your pocket" },
      { id: "swin_011", text: "Getting carded" },
      { id: "swin_012", text: "Your team winning a close game" },
      { id: "swin_013", text: "An unexpected free upgrade" },
      { id: "swin_014", text: "Nailing a parallel park" },
      { id: "swin_015", text: "A sale on something you were going to buy" },
      { id: "swin_016", text: "Finding a show you immediately love" },
      { id: "swin_017", text: "Someone holding the door" },
      { id: "swin_018", text: "Guessing the twist in a movie" },
      { id: "swin_019", text: "Getting the last one in stock" },
      { id: "swin_020", text: "A text from someone you miss" },
      { id: "swin_021", text: "The vending machine giving you two" },
      { id: "swin_022", text: "Your food coming out fast" },
      { id: "swin_023", text: "A sunny day you didn't expect" },
      { id: "swin_024", text: "Finishing a workout" },
      { id: "swin_025", text: "Your favorite song on the radio" },
    ]
  },
  {
    id: "texting_habits",
    name: "Texting Habits",
    scale: "How much this annoys you",
    cards: [
      { id: "text_001", text: "One-word replies" },
      { id: "text_002", text: "Leaving you on read" },
      { id: "text_003", text: "Voice messages instead of texts" },
      { id: "text_004", text: "Texting 'K'" },
      { id: "text_005", text: "Typing for five minutes then sending 'lol'" },
      { id: "text_006", text: "A paragraph when a sentence would do" },
      { id: "text_007", text: "Using too many emojis" },
      { id: "text_008", text: "No emojis at all" },
      { id: "text_009", text: "Replying three days later" },
      { id: "text_010", text: "The thumbs-up reaction" },
      { id: "text_011", text: "Sending ten texts in a row" },
      { id: "text_012", text: "ALL CAPS for no reason" },
      { id: "text_013", text: "Using periods in casual texts" },
      { id: "text_014", text: "Calling instead of texting" },
      { id: "text_015", text: "'Per my last text'" },
      { id: "text_016", text: "Starting a text with 'We need to talk'" },
      { id: "text_017", text: "Group chat that never stops" },
      { id: "text_018", text: "Abbreviations you can't decode" },
      { id: "text_019", text: "Texting during a face-to-face conversation" },
      { id: "text_020", text: "Autocorrect that changes your meaning" },
      { id: "text_021", text: "A 'haha' that feels passive-aggressive" },
      { id: "text_022", text: "Double-texting when you haven't replied" },
      { id: "text_023", text: "Sending a meme with no context" },
      { id: "text_024", text: "The typing bubble disappearing" },
      { id: "text_025", text: "Screenshots of your conversation posted" },
    ]
  },
  {
    id: "fictional_worlds",
    name: "Fictional Worlds",
    scale: "How badly you'd want to live here",
    cards: [
      { id: "fict_001", text: "Hogwarts" },
      { id: "fict_002", text: "Middle-earth" },
      { id: "fict_003", text: "The Star Wars galaxy" },
      { id: "fict_004", text: "Narnia" },
      { id: "fict_005", text: "The Marvel universe" },
      { id: "fict_006", text: "Westeros" },
      { id: "fict_007", text: "Wakanda" },
      { id: "fict_008", text: "The world of Pokémon" },
      { id: "fict_009", text: "The Shire" },
      { id: "fict_010", text: "Jurassic Park" },
      { id: "fict_011", text: "Avatar's Pandora" },
      { id: "fict_012", text: "Willy Wonka's factory" },
      { id: "fict_013", text: "The Matrix" },
      { id: "fict_014", text: "Animal Crossing island" },
      { id: "fict_015", text: "Springfield" },
      { id: "fict_016", text: "Gotham City" },
      { id: "fict_017", text: "Naruto's Hidden Leaf Village" },
      { id: "fict_018", text: "The world of Studio Ghibli" },
      { id: "fict_019", text: "Bikini Bottom" },
      { id: "fict_020", text: "The Upside Down" },
      { id: "fict_021", text: "Minecraft" },
      { id: "fict_022", text: "Neverland" },
      { id: "fict_023", text: "The world of Avatar: The Last Airbender" },
      { id: "fict_024", text: "Skyrim" },
      { id: "fict_025", text: "Wonderland" },
    ]
  },
  {
    id: "humor_types",
    name: "Types of Humor",
    scale: "How hard this makes you laugh",
    cards: [
      { id: "humor_001", text: "Dry sarcasm" },
      { id: "humor_002", text: "Physical comedy and slapstick" },
      { id: "humor_003", text: "Self-deprecating jokes" },
      { id: "humor_004", text: "Puns" },
      { id: "humor_005", text: "Dark humor" },
      { id: "humor_006", text: "Impressions of people you know" },
      { id: "humor_007", text: "Absurd randomness" },
      { id: "humor_008", text: "Inside jokes" },
      { id: "humor_009", text: "Deadpan delivery" },
      { id: "humor_010", text: "Memes" },
      { id: "humor_011", text: "Situational irony" },
      { id: "humor_012", text: "Dad jokes" },
      { id: "humor_013", text: "Roasting friends" },
      { id: "humor_014", text: "Observational comedy" },
      { id: "humor_015", text: "Accidental comedy" },
      { id: "humor_016", text: "Toilet humor" },
      { id: "humor_017", text: "Witty comebacks" },
      { id: "humor_018", text: "Running gags" },
      { id: "humor_019", text: "Awkward cringe humor" },
      { id: "humor_020", text: "Wordplay" },
      { id: "humor_021", text: "Pranks" },
      { id: "humor_022", text: "Storytelling with a punchline" },
      { id: "humor_023", text: "Animal videos" },
      { id: "humor_024", text: "Satire" },
      { id: "humor_025", text: "A well-timed 'that's what she said'" },
    ]
  },
  {
    id: "red_flags",
    name: "Red Flags",
    scale: "How fast you'd walk away",
    cards: [
      { id: "rflag_001", text: "Rude to waiters" },
      { id: "rflag_002", text: "Never apologizes" },
      { id: "rflag_003", text: "Checks your phone without asking" },
      { id: "rflag_004", text: "Love-bombs you immediately" },
      { id: "rflag_005", text: "Talks badly about all their exes" },
      { id: "rflag_006", text: "Always the victim in every story" },
      { id: "rflag_007", text: "Doesn't tip" },
      { id: "rflag_008", text: "Gets angry at small things" },
      { id: "rflag_009", text: "Never asks you questions about yourself" },
      { id: "rflag_010", text: "Lies about small things" },
      { id: "rflag_011", text: "Controls who you hang out with" },
      { id: "rflag_012", text: "Still hung up on their ex" },
      { id: "rflag_013", text: "Ghosts and comes back" },
      { id: "rflag_014", text: "Can't take a joke" },
      { id: "rflag_015", text: "Only talks about themselves" },
      { id: "rflag_016", text: "Won't introduce you to friends" },
      { id: "rflag_017", text: "Mean when they're drunk" },
      { id: "rflag_018", text: "Keeps score in arguments" },
      { id: "rflag_019", text: "Bad relationship with everyone" },
      { id: "rflag_020", text: "Gaslights you" },
      { id: "rflag_021", text: "Always on their phone around you" },
      { id: "rflag_022", text: "Makes fun of your interests" },
      { id: "rflag_023", text: "Won't compromise" },
      { id: "rflag_024", text: "Talks over you" },
      { id: "rflag_025", text: "Different in public vs. private" },
    ]
  },
  {
    id: "friendship_qualities",
    name: "Friendship Qualities",
    scale: "How much you value this in a friend",
    cards: [
      { id: "fq_001", text: "Always shows up" },
      { id: "fq_002", text: "Keeps your secrets" },
      { id: "fq_003", text: "Makes you laugh" },
      { id: "fq_004", text: "Tells you the truth" },
      { id: "fq_005", text: "Remembers important dates" },
      { id: "fq_006", text: "Checks in without being asked" },
      { id: "fq_007", text: "Down for anything" },
      { id: "fq_008", text: "Good in a crisis" },
      { id: "fq_009", text: "Doesn't keep score" },
      { id: "fq_010", text: "Celebrates your wins" },
      { id: "fq_011", text: "Comfortable with silence" },
      { id: "fq_012", text: "Picks up where you left off" },
      { id: "fq_013", text: "Gives great advice" },
      { id: "fq_014", text: "Will drive you to the airport" },
      { id: "fq_015", text: "Defends you when you're not there" },
      { id: "fq_016", text: "Shares food without hesitation" },
      { id: "fq_017", text: "Never flaky" },
      { id: "fq_018", text: "Introduces you to cool people" },
      { id: "fq_019", text: "Doesn't judge you" },
      { id: "fq_020", text: "Good at planning group things" },
      { id: "fq_021", text: "Brings out your best side" },
      { id: "fq_022", text: "Responds fast when it matters" },
      { id: "fq_023", text: "Forgives easily" },
      { id: "fq_024", text: "Fun to travel with" },
      { id: "fq_025", text: "Sends you things that remind them of you" },
    ]
  },
];
