// Categories 17-30: Existing categories, cleaned & deduplicated
export default [
  {
    id: "guilty_pleasures",
    name: "Guilty Pleasures",
    scale: "How much you secretly enjoy this",
    cards: [
      { id: "gp_001", text: "Reality TV" },
      { id: "gp_002", text: "Eating cereal for dinner" },
      { id: "gp_003", text: "Online shopping at 2 AM" },
      { id: "gp_004", text: "Singing in the shower" },
      { id: "gp_005", text: "A terrible pop song you love" },
      { id: "gp_006", text: "Gossip" },
      { id: "gp_007", text: "Skipping plans to stay home" },
      { id: "gp_008", text: "Eating the whole bag of chips" },
      { id: "gp_009", text: "Rewatching a show for the fifth time" },
      { id: "gp_010", text: "Deep-stalking someone's social media" },
      { id: "gp_011", text: "Browsing houses you can't afford" },
      { id: "gp_012", text: "Napping in the middle of the day" },
      { id: "gp_013", text: "Watching makeup or cooking tutorials" },
      { id: "gp_014", text: "Fast food after a healthy week" },
      { id: "gp_015", text: "Reading your old texts" },
      { id: "gp_016", text: "A rom-com you'd never admit to liking" },
      { id: "gp_017", text: "Taking BuzzFeed quizzes" },
      { id: "gp_018", text: "A pint of ice cream from the container" },
      { id: "gp_019", text: "An energy drink" },
      { id: "gp_020", text: "True crime binges before bed" },
      { id: "gp_021", text: "Scrolling TikTok for an hour" },
      { id: "gp_022", text: "Karaoke alone in the car" },
      { id: "gp_023", text: "Canceling plans last minute" },
      { id: "gp_024", text: "Wearing the same outfit two days in a row" },
      { id: "gp_025", text: "Checking your ex's profile" },
    ]
  },
  {
    id: "morning_routines",
    name: "Morning Routines",
    scale: "How essential this is to your morning",
    cards: [
      { id: "morn_001", text: "Coffee or tea" },
      { id: "morn_002", text: "Checking your phone first thing" },
      { id: "morn_003", text: "A shower to wake up" },
      { id: "morn_004", text: "A solid breakfast" },
      { id: "morn_005", text: "Hitting snooze at least once" },
      { id: "morn_006", text: "Brushing your teeth immediately" },
      { id: "morn_007", text: "Making your bed" },
      { id: "morn_008", text: "Stretching or light exercise" },
      { id: "morn_009", text: "Silence before talking to anyone" },
      { id: "morn_010", text: "Picking your outfit the night before" },
      { id: "morn_011", text: "A skincare routine" },
      { id: "morn_012", text: "Listening to music or a podcast" },
      { id: "morn_013", text: "Journaling or meditating" },
      { id: "morn_014", text: "Packing lunch the night before" },
      { id: "morn_015", text: "Sunlight first thing" },
      { id: "morn_016", text: "A glass of water right away" },
      { id: "morn_017", text: "Scrolling the news" },
      { id: "morn_018", text: "Feeding your pet" },
      { id: "morn_019", text: "A specific playlist to get going" },
      { id: "morn_020", text: "Not speaking for the first 30 minutes" },
      { id: "morn_021", text: "Reviewing your to-do list" },
      { id: "morn_022", text: "A slow morning with no rush" },
      { id: "morn_023", text: "Fresh air on your face" },
      { id: "morn_024", text: "A smoothie" },
      { id: "morn_025", text: "Leaving early to avoid stress" },
    ]
  },
  {
    id: "pet_peeves",
    name: "Pet Peeves",
    scale: "How irrationally angry this makes you",
    cards: [
      { id: "peev_001", text: "Chewing with mouth open" },
      { id: "peev_002", text: "People who don't use turn signals" },
      { id: "peev_003", text: "Being interrupted mid-sentence" },
      { id: "peev_004", text: "A pen that stops working" },
      { id: "peev_005", text: "People who stand too close" },
      { id: "peev_006", text: "Loud speakerphone in public" },
      { id: "peev_007", text: "Leaving the lights on" },
      { id: "peev_008", text: "'Seen' with no reply" },
      { id: "peev_009", text: "Wet countertops" },
      { id: "peev_010", text: "Someone always five minutes late" },
      { id: "peev_011", text: "Slow walkers blocking the sidewalk" },
      { id: "peev_012", text: "Not replacing the toilet paper roll" },
      { id: "peev_013", text: "Unsolicited advice" },
      { id: "peev_014", text: "People who don't clean up their dog's mess" },
      { id: "peev_015", text: "A limp handshake" },
      { id: "peev_016", text: "Talking during a movie" },
      { id: "peev_017", text: "Someone reading over your shoulder" },
      { id: "peev_018", text: "Leaving cabinet doors open" },
      { id: "peev_019", text: "Misusing 'your' and 'you're'" },
      { id: "peev_020", text: "Double-texting before you can reply" },
      { id: "peev_021", text: "People who litter" },
      { id: "peev_022", text: "Crumbs in the butter" },
      { id: "peev_023", text: "Loud chewing on a phone call" },
      { id: "peev_024", text: "Not covering your mouth when coughing" },
      { id: "peev_025", text: "Someone stopping at the top of stairs" },
    ]
  },
  {
    id: "weekend_plans",
    name: "Weekend Plans",
    scale: "How much you'd look forward to this",
    cards: [
      { id: "wknd_001", text: "Brunch with friends" },
      { id: "wknd_002", text: "A full day of nothing" },
      { id: "wknd_003", text: "A day trip somewhere new" },
      { id: "wknd_004", text: "A backyard barbecue" },
      { id: "wknd_005", text: "Sleeping in past noon" },
      { id: "wknd_006", text: "A movie marathon" },
      { id: "wknd_007", text: "Thrift store shopping" },
      { id: "wknd_008", text: "A long bike ride" },
      { id: "wknd_009", text: "Game night" },
      { id: "wknd_010", text: "A live music show" },
      { id: "wknd_011", text: "A beach day" },
      { id: "wknd_012", text: "Catching up on a series" },
      { id: "wknd_013", text: "Organizing your closet" },
      { id: "wknd_014", text: "A home-cooked feast" },
      { id: "wknd_015", text: "A hike with a friend" },
      { id: "wknd_016", text: "Trying a new recipe" },
      { id: "wknd_017", text: "A spa day at home" },
      { id: "wknd_018", text: "A picnic in the park" },
      { id: "wknd_019", text: "A local comedy show" },
      { id: "wknd_020", text: "Volunteering for a cause you like" },
      { id: "wknd_021", text: "A museum or gallery" },
      { id: "wknd_022", text: "A farmers market haul" },
      { id: "wknd_023", text: "Going for a drive with no plan" },
      { id: "wknd_024", text: "A puzzle or craft project" },
      { id: "wknd_025", text: "A sunset happy hour" },
    ]
  },
  {
    id: "milestones",
    name: "Life Milestones",
    scale: "How much this moment means to you",
    cards: [
      { id: "mile_001", text: "Graduating" },
      { id: "mile_002", text: "Moving into your own place" },
      { id: "mile_003", text: "Your first real paycheck" },
      { id: "mile_004", text: "Falling in love" },
      { id: "mile_005", text: "Getting your driver's license" },
      { id: "mile_006", text: "Your first trip alone" },
      { id: "mile_007", text: "Landing your dream job" },
      { id: "mile_008", text: "Paying off a major debt" },
      { id: "mile_009", text: "Buying your first car" },
      { id: "mile_010", text: "Making a lifelong friend" },
      { id: "mile_011", text: "Voting for the first time" },
      { id: "mile_012", text: "Your first apartment key" },
      { id: "mile_013", text: "Turning 21" },
      { id: "mile_014", text: "Running a race" },
      { id: "mile_015", text: "Overcoming something hard" },
      { id: "mile_016", text: "Learning to cook a signature dish" },
      { id: "mile_017", text: "Getting a pet" },
      { id: "mile_018", text: "Seeing your name in print" },
      { id: "mile_019", text: "Quitting something toxic" },
      { id: "mile_020", text: "Buying real furniture" },
      { id: "mile_021", text: "Hosting Thanksgiving solo" },
      { id: "mile_022", text: "Saying no without guilt" },
      { id: "mile_023", text: "Having a savings account" },
      { id: "mile_024", text: "Your first international trip" },
      { id: "mile_025", text: "Knowing who your real friends are" },
    ]
  },
  {
    id: "college",
    name: "College Experiences",
    scale: "How essential this is to college",
    cards: [
      { id: "col_001", text: "An all-nighter before an exam" },
      { id: "col_002", text: "A class that changed how you think" },
      { id: "col_003", text: "Free food at a campus event" },
      { id: "col_004", text: "Living with your best friends" },
      { id: "col_005", text: "A terrible dorm room" },
      { id: "col_006", text: "A professor you still think about" },
      { id: "col_007", text: "Tailgating or game day" },
      { id: "col_008", text: "A study abroad semester" },
      { id: "col_009", text: "Ramen as a food group" },
      { id: "col_010", text: "A random Wednesday night out" },
      { id: "col_011", text: "The dining hall at midnight" },
      { id: "col_012", text: "Changing your major" },
      { id: "col_013", text: "Making your dorm room cozy" },
      { id: "col_014", text: "A road trip with friends" },
      { id: "col_015", text: "Office hours saving your grade" },
      { id: "col_016", text: "A group project you survived" },
      { id: "col_017", text: "A class you took on a whim" },
      { id: "col_018", text: "Move-in day nerves" },
      { id: "col_019", text: "Dollar pizza at 2 AM" },
      { id: "col_020", text: "Your first time doing laundry" },
      { id: "col_021", text: "A campus tradition" },
      { id: "col_022", text: "Meeting your lifelong friends" },
      { id: "col_023", text: "Graduation day" },
      { id: "col_024", text: "A favorite study spot" },
      { id: "col_025", text: "Pulling off a surprise party in a dorm" },
    ]
  },
  {
    id: "wfh",
    name: "Work From Home Perks",
    scale: "How much you'd miss this at the office",
    cards: [
      { id: "wfh_001", text: "No commute" },
      { id: "wfh_002", text: "Working in sweatpants" },
      { id: "wfh_003", text: "Your own bathroom" },
      { id: "wfh_004", text: "Cooking lunch at home" },
      { id: "wfh_005", text: "Music without headphones" },
      { id: "wfh_006", text: "Taking breaks whenever" },
      { id: "wfh_007", text: "Your pet on your lap" },
      { id: "wfh_008", text: "Napping on lunch break" },
      { id: "wfh_009", text: "No one watching your screen" },
      { id: "wfh_010", text: "Controlling the thermostat" },
      { id: "wfh_011", text: "Sleeping ten extra minutes" },
      { id: "wfh_012", text: "Doing laundry between meetings" },
      { id: "wfh_013", text: "A fridge full of your own food" },
      { id: "wfh_014", text: "No small talk in the kitchen" },
      { id: "wfh_015", text: "Working from your couch" },
      { id: "wfh_016", text: "Going barefoot all day" },
      { id: "wfh_017", text: "Muting yourself to vent" },
      { id: "wfh_018", text: "Accepting packages in real time" },
      { id: "wfh_019", text: "Starting a workout right after work" },
      { id: "wfh_020", text: "Watching something during lunch" },
      { id: "wfh_021", text: "No fluorescent lighting" },
      { id: "wfh_022", text: "Making your own coffee" },
      { id: "wfh_023", text: "Blending work and errands" },
      { id: "wfh_024", text: "Your own desk setup" },
      { id: "wfh_025", text: "Camera off on bad hair days" },
    ]
  },
  {
    id: "snacks",
    name: "Snack Time",
    scale: "How fast you'd demolish this right now",
    cards: [
      { id: "snk_001", text: "Popcorn" },
      { id: "snk_002", text: "Trail mix" },
      { id: "snk_003", text: "Goldfish crackers" },
      { id: "snk_004", text: "An apple with peanut butter" },
      { id: "snk_005", text: "Chips and salsa" },
      { id: "snk_006", text: "Pretzels" },
      { id: "snk_007", text: "Gummy bears" },
      { id: "snk_008", text: "Cheese and crackers" },
      { id: "snk_009", text: "A granola bar" },
      { id: "snk_010", text: "String cheese" },
      { id: "snk_011", text: "Tortilla chips with guac" },
      { id: "snk_012", text: "Fruit snacks" },
      { id: "snk_013", text: "A banana" },
      { id: "snk_014", text: "A smoothie bowl" },
      { id: "snk_015", text: "Free samples at the grocery store" },
      { id: "snk_016", text: "A rice cake" },
      { id: "snk_017", text: "Mini muffins" },
      { id: "snk_018", text: "Mixed nuts" },
      { id: "snk_019", text: "Beef jerky" },
      { id: "snk_020", text: "Veggies and hummus" },
      { id: "snk_021", text: "Frozen grapes" },
      { id: "snk_022", text: "A handful of M&Ms" },
      { id: "snk_023", text: "Carrots with ranch" },
      { id: "snk_024", text: "Doritos" },
      { id: "snk_025", text: "Dark chocolate" },
    ]
  },
  {
    id: "weather",
    name: "Weather Types",
    scale: "How much you enjoy this weather",
    cards: [
      { id: "wea_001", text: "A crisp fall day" },
      { id: "wea_002", text: "A thunderstorm from inside" },
      { id: "wea_003", text: "A warm spring morning" },
      { id: "wea_004", text: "Fresh snowfall" },
      { id: "wea_005", text: "A beach-perfect sunny day" },
      { id: "wea_006", text: "A cool foggy morning" },
      { id: "wea_007", text: "Rain on a tin roof" },
      { id: "wea_008", text: "A breezy summer evening" },
      { id: "wea_009", text: "Overcast and cozy" },
      { id: "wea_010", text: "A blizzard when you have nowhere to be" },
      { id: "wea_011", text: "A quiet morning after snowfall" },
      { id: "wea_012", text: "The first warm day of spring" },
      { id: "wea_013", text: "A dry heat" },
      { id: "wea_014", text: "A rainbow after the rain" },
      { id: "wea_015", text: "A dramatic sunset" },
      { id: "wea_016", text: "The smell of rain on hot pavement" },
      { id: "wea_017", text: "Sunshine after a week of rain" },
      { id: "wea_018", text: "A misty mountain morning" },
      { id: "wea_019", text: "A light drizzle" },
      { id: "wea_020", text: "A hurricane watch from your couch" },
      { id: "wea_021", text: "Wind so strong you lean into it" },
      { id: "wea_022", text: "Frost on your windshield" },
      { id: "wea_023", text: "Hail the size of golf balls" },
      { id: "wea_024", text: "A warm day in the middle of winter" },
      { id: "wea_025", text: "A perfect 72-degree day" },
    ]
  },
  {
    id: "holidays",
    name: "Holiday Traditions",
    scale: "How much this makes the holiday",
    cards: [
      { id: "hol_001", text: "A big family dinner" },
      { id: "hol_002", text: "Decorating the house" },
      { id: "hol_003", text: "Gift wrapping" },
      { id: "hol_004", text: "A holiday movie marathon" },
      { id: "hol_005", text: "A secret Santa exchange" },
      { id: "hol_006", text: "Baking cookies from scratch" },
      { id: "hol_007", text: "Friendsgiving" },
      { id: "hol_008", text: "Midnight on New Year's Eve" },
      { id: "hol_009", text: "Wearing matching pajamas" },
      { id: "hol_010", text: "Holiday lights around the neighborhood" },
      { id: "hol_011", text: "A stocking stuffed with small things" },
      { id: "hol_012", text: "Cooking together as a family" },
      { id: "hol_013", text: "Ugly sweater parties" },
      { id: "hol_014", text: "Holiday music playing everywhere" },
      { id: "hol_015", text: "Black Friday shopping" },
      { id: "hol_016", text: "Thanksgiving leftovers" },
      { id: "hol_017", text: "Fireworks on the Fourth of July" },
      { id: "hol_018", text: "An Easter egg hunt" },
      { id: "hol_019", text: "Candy on clearance the day after" },
      { id: "hol_020", text: "A NYE house party" },
      { id: "hol_021", text: "Opening one gift on Christmas Eve" },
      { id: "hol_022", text: "A Thanksgiving nap" },
      { id: "hol_023", text: "Sparklers on a warm night" },
      { id: "hol_024", text: "A gratitude toast" },
      { id: "hol_025", text: "Hot cocoa by the fire" },
    ]
  },
  {
    id: "fashion",
    name: "Fashion & Style",
    scale: "How confident this makes you feel",
    cards: [
      { id: "fash_001", text: "A perfect-fitting pair of jeans" },
      { id: "fash_002", text: "Brand new sneakers" },
      { id: "fash_003", text: "A leather jacket" },
      { id: "fash_004", text: "Sunglasses that suit your face" },
      { id: "fash_005", text: "A well-tailored suit or blazer" },
      { id: "fash_006", text: "Your go-to outfit" },
      { id: "fash_007", text: "A meaningful piece of jewelry" },
      { id: "fash_008", text: "Getting a compliment on your outfit" },
      { id: "fash_009", text: "A fresh haircut" },
      { id: "fash_010", text: "A vintage find" },
      { id: "fash_011", text: "A cozy scarf in winter" },
      { id: "fash_012", text: "A crisp white t-shirt" },
      { id: "fash_013", text: "A statement piece nobody else has" },
      { id: "fash_014", text: "Matching your shoes to the outfit" },
      { id: "fash_015", text: "Wearing something new for the first time" },
      { id: "fash_016", text: "A great watch" },
      { id: "fash_017", text: "An outfit that turns heads" },
      { id: "fash_018", text: "A hat that works on you" },
      { id: "fash_019", text: "A broken-in denim jacket" },
      { id: "fash_020", text: "Nailing a new style" },
      { id: "fash_021", text: "Comfortable heels" },
      { id: "fash_022", text: "A signature scent" },
      { id: "fash_023", text: "Pajamas you'd answer the door in" },
      { id: "fash_024", text: "A bag that ties everything together" },
      { id: "fash_025", text: "Looking good without trying" },
    ]
  },
  {
    id: "relationships",
    name: "Relationship Traits",
    scale: "How important this is in a partner",
    cards: [
      { id: "rel_001", text: "Makes you laugh daily" },
      { id: "rel_002", text: "Good with your family" },
      { id: "rel_003", text: "Gives you space without drama" },
      { id: "rel_004", text: "Remembers the small things" },
      { id: "rel_005", text: "Apologizes when wrong" },
      { id: "rel_006", text: "Hypes you up in public" },
      { id: "rel_007", text: "Comfortable silence together" },
      { id: "rel_008", text: "Same taste in music" },
      { id: "rel_009", text: "Good cook" },
      { id: "rel_010", text: "Adventurous in trying new things" },
      { id: "rel_011", text: "Handles money responsibly" },
      { id: "rel_012", text: "Texts back quickly" },
      { id: "rel_013", text: "Gets along with your friends" },
      { id: "rel_014", text: "Plans dates without being asked" },
      { id: "rel_015", text: "Shares your sense of humor" },
      { id: "rel_016", text: "Emotionally available" },
      { id: "rel_017", text: "Same cleanliness standards" },
      { id: "rel_018", text: "Loves animals" },
      { id: "rel_019", text: "Morning person vs. night owl match" },
      { id: "rel_020", text: "Can fix things around the house" },
      { id: "rel_021", text: "Same political views" },
      { id: "rel_022", text: "Ambitious and driven" },
      { id: "rel_023", text: "Physical affection" },
      { id: "rel_024", text: "Willing to compromise" },
      { id: "rel_025", text: "Good taste in movies and shows" },
    ]
  },
  {
    id: "smells",
    name: "Smells",
    scale: "How much you love this smell",
    cards: [
      { id: "smell_001", text: "Fresh-baked cookies" },
      { id: "smell_002", text: "Campfire smoke" },
      { id: "smell_003", text: "Rain on hot pavement" },
      { id: "smell_004", text: "Coffee brewing" },
      { id: "smell_005", text: "Sunscreen" },
      { id: "smell_006", text: "Clean laundry" },
      { id: "smell_007", text: "Ocean air" },
      { id: "smell_008", text: "A new book" },
      { id: "smell_009", text: "Pine trees" },
      { id: "smell_010", text: "Fresh-cut grass" },
      { id: "smell_011", text: "Vanilla" },
      { id: "smell_012", text: "Gasoline" },
      { id: "smell_013", text: "A candle you can't stop sniffing" },
      { id: "smell_014", text: "Cinnamon" },
      { id: "smell_015", text: "Your favorite person's scent" },
      { id: "smell_016", text: "Bacon cooking" },
      { id: "smell_017", text: "Old books in a used bookstore" },
      { id: "smell_018", text: "A fireplace in winter" },
      { id: "smell_019", text: "Fresh basil" },
      { id: "smell_020", text: "A barbecue grill" },
      { id: "smell_021", text: "Lavender" },
      { id: "smell_022", text: "A baby's head" },
      { id: "smell_023", text: "Thanksgiving dinner cooking" },
      { id: "smell_024", text: "A cedar closet" },
      { id: "smell_025", text: "Bread baking in the oven" },
    ]
  },
  {
    id: "party_games",
    name: "Party Games",
    scale: "How down you'd be to play right now",
    cards: [
      { id: "party_001", text: "Cards Against Humanity" },
      { id: "party_002", text: "Beer pong" },
      { id: "party_003", text: "Charades" },
      { id: "party_004", text: "Never Have I Ever" },
      { id: "party_005", text: "Trivia night" },
      { id: "party_006", text: "Mafia or Werewolf" },
      { id: "party_007", text: "A dance-off" },
      { id: "party_008", text: "Karaoke" },
      { id: "party_009", text: "Flip cup" },
      { id: "party_010", text: "Two Truths and a Lie" },
      { id: "party_011", text: "Monopoly" },
      { id: "party_012", text: "Pictionary" },
      { id: "party_013", text: "Jenga" },
      { id: "party_014", text: "Mario Kart tournament" },
      { id: "party_015", text: "Would You Rather" },
      { id: "party_016", text: "Musical chairs" },
      { id: "party_017", text: "Spoons" },
      { id: "party_018", text: "A lip sync battle" },
      { id: "party_019", text: "Codenames" },
      { id: "party_020", text: "Sardines" },
      { id: "party_021", text: "A relay race" },
      { id: "party_022", text: "Truth or Dare" },
      { id: "party_023", text: "King's Cup" },
      { id: "party_024", text: "A talent show" },
      { id: "party_025", text: "A blindfolded taste test" },
    ]
  },
];
