// New categories 44-55
export default [
  {
    id: "things_worth_waiting",
    name: "Things Worth Waiting For",
    scale: "How patient you'd be for this",
    cards: [
      { id: "wait_001", text: "A table at the best restaurant" },
      { id: "wait_002", text: "The right person" },
      { id: "wait_003", text: "A house you actually love" },
      { id: "wait_004", text: "Concert tickets going on sale" },
      { id: "wait_005", text: "A package from overseas" },
      { id: "wait_006", text: "Bread rising" },
      { id: "wait_007", text: "A promotion" },
      { id: "wait_008", text: "Your turn at the barber" },
      { id: "wait_009", text: "The next season of your show" },
      { id: "wait_010", text: "A friend running late" },
      { id: "wait_011", text: "Fresh cookies to cool down" },
      { id: "wait_012", text: "A flight delay" },
      { id: "wait_013", text: "A custom order" },
      { id: "wait_014", text: "The right time to make a move" },
      { id: "wait_015", text: "Results from a job interview" },
      { id: "wait_016", text: "Someone to text you back" },
      { id: "wait_017", text: "A sunset" },
      { id: "wait_018", text: "Your tax refund" },
      { id: "wait_019", text: "The sequel to your favorite book" },
      { id: "wait_020", text: "A sold-out item to restock" },
      { id: "wait_021", text: "A long download to finish" },
      { id: "wait_022", text: "A reservation in two months" },
      { id: "wait_023", text: "Aged cheese or wine" },
      { id: "wait_024", text: "A friend to get ready" },
      { id: "wait_025", text: "The perfect wave" },
    ]
  },
  {
    id: "things_that_age_well",
    name: "Things That Age Well",
    scale: "How much better this gets with time",
    cards: [
      { id: "age_001", text: "A good leather jacket" },
      { id: "age_002", text: "Friendships" },
      { id: "age_003", text: "Wine" },
      { id: "age_004", text: "Cast iron skillets" },
      { id: "age_005", text: "Your taste in music" },
      { id: "age_006", text: "Denim" },
      { id: "age_007", text: "Your sense of humor" },
      { id: "age_008", text: "A good pair of boots" },
      { id: "age_009", text: "Knowing yourself" },
      { id: "age_010", text: "A well-made wooden table" },
      { id: "age_011", text: "Cheese" },
      { id: "age_012", text: "Old photographs" },
      { id: "age_013", text: "Confidence" },
      { id: "age_014", text: "A classic car" },
      { id: "age_015", text: "Your cooking skills" },
      { id: "age_016", text: "A well-tended garden" },
      { id: "age_017", text: "Vinyl records" },
      { id: "age_018", text: "Patience" },
      { id: "age_019", text: "A good mattress" },
      { id: "age_020", text: "Saying no" },
      { id: "age_021", text: "Whiskey" },
      { id: "age_022", text: "Your handwriting" },
      { id: "age_023", text: "Empathy" },
      { id: "age_024", text: "A sourdough starter" },
      { id: "age_025", text: "Stories you'll tell forever" },
    ]
  },
  {
    id: "sounds",
    name: "Sounds",
    scale: "How much this sound affects you",
    cards: [
      { id: "snd_001", text: "Rain on a window" },
      { id: "snd_002", text: "A crackling fire" },
      { id: "snd_003", text: "Ocean waves" },
      { id: "snd_004", text: "Birds in the morning" },
      { id: "snd_005", text: "Thunder in the distance" },
      { id: "snd_006", text: "A baby laughing" },
      { id: "snd_007", text: "Your alarm clock" },
      { id: "snd_008", text: "A crowd cheering" },
      { id: "snd_009", text: "Someone chewing loudly" },
      { id: "snd_010", text: "A cat purring" },
      { id: "snd_011", text: "Wind through trees" },
      { id: "snd_012", text: "A notification ding" },
      { id: "snd_013", text: "Leaves crunching underfoot" },
      { id: "snd_014", text: "A train in the distance" },
      { id: "snd_015", text: "Popcorn popping" },
      { id: "snd_016", text: "Someone whispering" },
      { id: "snd_017", text: "A dog barking at nothing" },
      { id: "snd_018", text: "A vinyl record crackling" },
      { id: "snd_019", text: "Church bells" },
      { id: "snd_020", text: "Construction outside your window" },
      { id: "snd_021", text: "A loon on a lake" },
      { id: "snd_022", text: "Your name being called" },
      { id: "snd_023", text: "Crickets at night" },
      { id: "snd_024", text: "A champagne cork popping" },
      { id: "snd_025", text: "Complete silence" },
    ]
  },
  {
    id: "things_feel_illegal",
    name: "Things That Feel Illegal",
    scale: "How guilty this makes you feel",
    cards: [
      { id: "illegal_001", text: "Leaving work early on a Friday" },
      { id: "illegal_002", text: "Walking out of a store without buying anything" },
      { id: "illegal_003", text: "Taking the hotel toiletries" },
      { id: "illegal_004", text: "Eating before paying at a buffet" },
      { id: "illegal_005", text: "Using a sick day when you're not sick" },
      { id: "illegal_006", text: "Passing a cop while driving" },
      { id: "illegal_007", text: "Wearing pajamas to the grocery store" },
      { id: "illegal_008", text: "Getting a refund on something you used" },
      { id: "illegal_009", text: "Streaming on someone else's account" },
      { id: "illegal_010", text: "Eating grapes at the store before buying" },
      { id: "illegal_011", text: "Taking extra napkins at a restaurant" },
      { id: "illegal_012", text: "Googling yourself" },
      { id: "illegal_013", text: "Using your phone during a meeting" },
      { id: "illegal_014", text: "Skipping the gym two weeks in a row" },
      { id: "illegal_015", text: "Returning something you wore once" },
      { id: "illegal_016", text: "Taking the last slice without asking" },
      { id: "illegal_017", text: "Sitting in first class before anyone checks" },
      { id: "illegal_018", text: "Bringing outside food into a movie theater" },
      { id: "illegal_019", text: "Free refills when it's not free refills" },
      { id: "illegal_020", text: "Walking through a store's entrance as an exit" },
      { id: "illegal_021", text: "Eating lunch at 11 AM" },
      { id: "illegal_022", text: "Napping at 3 PM on a workday" },
      { id: "illegal_023", text: "Keeping incorrect change in your favor" },
      { id: "illegal_024", text: "Going to bed at 8 PM" },
      { id: "illegal_025", text: "Saying you're 'on the way' from bed" },
    ]
  },
  {
    id: "things_automate",
    name: "Things You'd Automate",
    scale: "How much time this wastes",
    cards: [
      { id: "auto_001", text: "Folding laundry" },
      { id: "auto_002", text: "Cooking on weeknights" },
      { id: "auto_003", text: "Cleaning the bathroom" },
      { id: "auto_004", text: "Responding to emails" },
      { id: "auto_005", text: "Grocery shopping" },
      { id: "auto_006", text: "Doing the dishes" },
      { id: "auto_007", text: "Your commute" },
      { id: "auto_008", text: "Scheduling appointments" },
      { id: "auto_009", text: "Meal planning" },
      { id: "auto_010", text: "Vacuuming" },
      { id: "auto_011", text: "Filing taxes" },
      { id: "auto_012", text: "Watering plants" },
      { id: "auto_013", text: "Parallel parking" },
      { id: "auto_014", text: "Wrapping gifts" },
      { id: "auto_015", text: "Getting ready in the morning" },
      { id: "auto_016", text: "Matching socks" },
      { id: "auto_017", text: "Mowing the lawn" },
      { id: "auto_018", text: "Returning packages" },
      { id: "auto_019", text: "Scrolling for something to watch" },
      { id: "auto_020", text: "Choosing an outfit" },
      { id: "auto_021", text: "Shoveling snow" },
      { id: "auto_022", text: "Making the bed" },
      { id: "auto_023", text: "Packing a suitcase" },
      { id: "auto_024", text: "Renewing subscriptions" },
      { id: "auto_025", text: "Backing up your phone" },
    ]
  },
  {
    id: "old_person_hobbies",
    name: "Old Person Hobbies",
    scale: "How much you'd enjoy this at 70",
    cards: [
      { id: "old_001", text: "Gardening" },
      { id: "old_002", text: "Birdwatching" },
      { id: "old_003", text: "Crossword puzzles" },
      { id: "old_004", text: "Knitting or crocheting" },
      { id: "old_005", text: "A morning walk routine" },
      { id: "old_006", text: "Playing bridge or cards" },
      { id: "old_007", text: "Woodworking" },
      { id: "old_008", text: "Painting watercolors" },
      { id: "old_009", text: "Antiquing" },
      { id: "old_010", text: "Fishing" },
      { id: "old_011", text: "Collecting stamps or coins" },
      { id: "old_012", text: "Reading on the porch all day" },
      { id: "old_013", text: "Golfing" },
      { id: "old_014", text: "Cooking elaborate meals" },
      { id: "old_015", text: "Writing letters by hand" },
      { id: "old_016", text: "Volunteering at a library" },
      { id: "old_017", text: "Doing jigsaw puzzles" },
      { id: "old_018", text: "Learning to play the harmonica" },
      { id: "old_019", text: "Making jam from your garden" },
      { id: "old_020", text: "Feeding ducks at the pond" },
      { id: "old_021", text: "Photography walks" },
      { id: "old_022", text: "A weekly poker night" },
      { id: "old_023", text: "Building model trains" },
      { id: "old_024", text: "Telling stories to grandkids" },
      { id: "old_025", text: "Sitting on the porch doing nothing" },
    ]
  },
  {
    id: "splurge_worthy",
    name: "Worth Splurging On",
    scale: "How much you'd spend on this",
    cards: [
      { id: "splurge_001", text: "A really good mattress" },
      { id: "splurge_002", text: "Quality shoes" },
      { id: "splurge_003", text: "A nice dinner out" },
      { id: "splurge_004", text: "A great haircut" },
      { id: "splurge_005", text: "Concert tickets" },
      { id: "splurge_006", text: "Skincare" },
      { id: "splurge_007", text: "A good winter coat" },
      { id: "splurge_008", text: "Kitchen knives" },
      { id: "splurge_009", text: "Sunglasses" },
      { id: "splurge_010", text: "A vacation" },
      { id: "splurge_011", text: "Noise-canceling headphones" },
      { id: "splurge_012", text: "A good backpack" },
      { id: "splurge_013", text: "Coffee or espresso equipment" },
      { id: "splurge_014", text: "A tailored suit" },
      { id: "splurge_015", text: "Bedsheets" },
      { id: "splurge_016", text: "A gym membership" },
      { id: "splurge_017", text: "A good pillow" },
      { id: "splurge_018", text: "A phone case that works" },
      { id: "splurge_019", text: "Luggage" },
      { id: "splurge_020", text: "A watch" },
      { id: "splurge_021", text: "Running shoes" },
      { id: "splurge_022", text: "Cookware" },
      { id: "splurge_023", text: "A comfortable desk chair" },
      { id: "splurge_024", text: "Socks that actually last" },
      { id: "splurge_025", text: "A birthday gift for someone you love" },
    ]
  },
  {
    id: "social_rules",
    name: "Unwritten Social Rules",
    scale: "How strongly you follow this",
    cards: [
      { id: "srule_001", text: "Let people off the elevator first" },
      { id: "srule_002", text: "Don't recline on a short flight" },
      { id: "srule_003", text: "Replace what you finish" },
      { id: "srule_004", text: "Wave when someone lets you merge" },
      { id: "srule_005", text: "Don't FaceTime in public on speaker" },
      { id: "srule_006", text: "Offer to help clean up at a party" },
      { id: "srule_007", text: "Don't take the last slice without asking" },
      { id: "srule_008", text: "Return your grocery cart" },
      { id: "srule_009", text: "Say thank you to the bus driver" },
      { id: "srule_010", text: "Don't double-dip" },
      { id: "srule_011", text: "Hold the door for people behind you" },
      { id: "srule_012", text: "Don't talk in a quiet train car" },
      { id: "srule_013", text: "Tip at least 20 percent" },
      { id: "srule_014", text: "Don't show up empty-handed" },
      { id: "srule_015", text: "Keep right on escalators" },
      { id: "srule_016", text: "Don't spoil a movie" },
      { id: "srule_017", text: "Reply to RSVPs" },
      { id: "srule_018", text: "Don't wear white to a wedding" },
      { id: "srule_019", text: "Pick up after your dog" },
      { id: "srule_020", text: "Don't clip your nails in public" },
      { id: "srule_021", text: "Ask before petting someone's dog" },
      { id: "srule_022", text: "Keep your backpack off the seat" },
      { id: "srule_023", text: "Mute yourself on group calls" },
      { id: "srule_024", text: "Don't play music from your phone speaker" },
      { id: "srule_025", text: "Text before calling" },
    ]
  },
  {
    id: "after_midnight",
    name: "After Midnight",
    scale: "How different this feels past midnight",
    cards: [
      { id: "mid_001", text: "A drive through empty streets" },
      { id: "mid_002", text: "Deep conversations" },
      { id: "mid_003", text: "Ordering pizza" },
      { id: "mid_004", text: "Looking at old photos" },
      { id: "mid_005", text: "Online shopping" },
      { id: "mid_006", text: "Texting your ex" },
      { id: "mid_007", text: "A walk outside" },
      { id: "mid_008", text: "Cooking a meal" },
      { id: "mid_009", text: "Watching a documentary" },
      { id: "mid_010", text: "Writing in a journal" },
      { id: "mid_011", text: "A shower" },
      { id: "mid_012", text: "Cleaning your room" },
      { id: "mid_013", text: "Listening to sad music" },
      { id: "mid_014", text: "Making life decisions" },
      { id: "mid_015", text: "A bowl of cereal" },
      { id: "mid_016", text: "Scrolling through social media" },
      { id: "mid_017", text: "Sending a long text" },
      { id: "mid_018", text: "Staring at the ceiling" },
      { id: "mid_019", text: "Watching the sunrise happen" },
      { id: "mid_020", text: "A gas station run" },
      { id: "mid_021", text: "Reading Wikipedia" },
      { id: "mid_022", text: "Working out" },
      { id: "mid_023", text: "A confession" },
      { id: "mid_024", text: "Overthinking" },
      { id: "mid_025", text: "A phone call with someone you miss" },
    ]
  },
  {
    id: "hotel_musts",
    name: "Hotel Must-Haves",
    scale: "How much this matters for your stay",
    cards: [
      { id: "hotel_001", text: "A comfortable bed" },
      { id: "hotel_002", text: "Good water pressure" },
      { id: "hotel_003", text: "Free WiFi" },
      { id: "hotel_004", text: "A balcony or view" },
      { id: "hotel_005", text: "A mini fridge" },
      { id: "hotel_006", text: "A coffee maker in the room" },
      { id: "hotel_007", text: "Late checkout" },
      { id: "hotel_008", text: "Room service" },
      { id: "hotel_009", text: "A pool" },
      { id: "hotel_010", text: "Soundproof walls" },
      { id: "hotel_011", text: "Blackout curtains" },
      { id: "hotel_012", text: "Free breakfast" },
      { id: "hotel_013", text: "Close to restaurants" },
      { id: "hotel_014", text: "A bathtub" },
      { id: "hotel_015", text: "Extra pillows" },
      { id: "hotel_016", text: "Good lighting in the bathroom" },
      { id: "hotel_017", text: "A safe for your stuff" },
      { id: "hotel_018", text: "An iron or steamer" },
      { id: "hotel_019", text: "A desk to work at" },
      { id: "hotel_020", text: "Robes and slippers" },
      { id: "hotel_021", text: "No carpet" },
      { id: "hotel_022", text: "A gym" },
      { id: "hotel_023", text: "Contactless check-in" },
      { id: "hotel_024", text: "A king-size bed" },
      { id: "hotel_025", text: "Thick towels" },
    ]
  },
  {
    id: "underrated_pleasures",
    name: "Underrated Pleasures",
    scale: "How underappreciated this is",
    cards: [
      { id: "under_001", text: "Drinking cold water when dehydrated" },
      { id: "under_002", text: "Taking off your shoes after a long day" },
      { id: "under_003", text: "A good stretch" },
      { id: "under_004", text: "Clean teeth after the dentist" },
      { id: "under_005", text: "The cool side of the pillow" },
      { id: "under_006", text: "Peeling the plastic off something new" },
      { id: "under_007", text: "Fresh socks" },
      { id: "under_008", text: "An empty laundry basket" },
      { id: "under_009", text: "Your ears popping on a plane" },
      { id: "under_010", text: "A sneeze that finally comes" },
      { id: "under_011", text: "A perfectly ripe avocado" },
      { id: "under_012", text: "The first sip of a cold drink" },
      { id: "under_013", text: "Waking up thinking it's Monday but it's Saturday" },
      { id: "under_014", text: "A dog being happy to see you" },
      { id: "under_015", text: "Getting into a made bed" },
      { id: "under_016", text: "The click of a good pen" },
      { id: "under_017", text: "Cracking your back" },
      { id: "under_018", text: "A warm towel out of the dryer" },
      { id: "under_019", text: "No line at the coffee shop" },
      { id: "under_020", text: "Catching something you dropped mid-air" },
      { id: "under_021", text: "The weight of a blanket in bed" },
      { id: "under_022", text: "Getting the USB in first try" },
      { id: "under_023", text: "A long exhale after holding your breath" },
      { id: "under_024", text: "Stepping outside after a movie" },
      { id: "under_025", text: "That post-shower clean feeling" },
    ]
  },
  {
    id: "childhood_snacks",
    name: "Childhood Snacks",
    scale: "How much you'd eat this right now",
    cards: [
      { id: "csnk_001", text: "Fruit Roll-Ups" },
      { id: "csnk_002", text: "Lunchables" },
      { id: "csnk_003", text: "Gushers" },
      { id: "csnk_004", text: "Dunkaroos" },
      { id: "csnk_005", text: "Capri Sun" },
      { id: "csnk_006", text: "Pop-Tarts" },
      { id: "csnk_007", text: "Pizza Bagel Bites" },
      { id: "csnk_008", text: "Cosmic Brownies" },
      { id: "csnk_009", text: "Fruit by the Foot" },
      { id: "csnk_010", text: "Teddy Grahams" },
      { id: "csnk_011", text: "Ring Pops" },
      { id: "csnk_012", text: "Scooby-Doo gummies" },
      { id: "csnk_013", text: "Animal crackers" },
      { id: "csnk_014", text: "Oreos and milk" },
      { id: "csnk_015", text: "String cheese" },
      { id: "csnk_016", text: "Hot Pockets" },
      { id: "csnk_017", text: "Warheads" },
      { id: "csnk_018", text: "Push Pops" },
      { id: "csnk_019", text: "Dino nuggets" },
      { id: "csnk_020", text: "Cheese-Its" },
      { id: "csnk_021", text: "Go-Gurt" },
      { id: "csnk_022", text: "Toaster Strudels" },
      { id: "csnk_023", text: "Fun Dip" },
      { id: "csnk_024", text: "Goldfish crackers" },
      { id: "csnk_025", text: "Ants on a log" },
    ]
  },
];
