export default {
    things_to_learn: [
        { id: 'things_to_learn_01', text: 'A second language' },
        { id: 'things_to_learn_02', text: 'Piano' },
        { id: 'things_to_learn_03', text: 'Guitar' },
        { id: 'things_to_learn_04', text: 'Cooking' },
        { id: 'things_to_learn_05', text: 'Drawing' },
        { id: 'things_to_learn_06', text: 'Woodworking' },
        { id: 'things_to_learn_07', text: 'Latte art' },
        { id: 'things_to_learn_08', text: 'Coding' },
        { id: 'things_to_learn_09', text: 'Knife skills' },
        { id: 'things_to_learn_10', text: 'Photography' },
        { id: 'things_to_learn_11', text: 'Dancing' },
        { id: 'things_to_learn_12', text: 'Singing' },
        { id: 'things_to_learn_13', text: 'Juggling' },
        { id: 'things_to_learn_14', text: 'Swimming' },
        { id: 'things_to_learn_15', text: 'Sewing' },
        { id: 'things_to_learn_16', text: 'Flying a plane' },
        { id: 'things_to_learn_17', text: 'Sailing' },
        { id: 'things_to_learn_18', text: 'Skiing' },
        { id: 'things_to_learn_19', text: 'Riding a motorcycle' },
        { id: 'things_to_learn_20', text: 'Speed reading' },
        { id: 'things_to_learn_21', text: 'Astronomy' },
        { id: 'things_to_learn_22', text: 'Magic tricks' },
        { id: 'things_to_learn_23', text: 'Bartending' },
        { id: 'things_to_learn_24', text: 'Fiction writing' },
        { id: 'things_to_learn_25', text: 'Calligraphy' },
    ],
    talents: [
        { id: 'talents_01', text: 'Sing beautifully' },
        { id: 'talents_02', text: 'Wiggle your ears' },
        { id: 'talents_03', text: 'Do a backflip' },
        { id: 'talents_04', text: "Solve a Rubik's Cube fast" },
        { id: 'talents_05', text: 'Whistle loudly' },
        { id: 'talents_06', text: 'Do spot-on impressions' },
        { id: 'talents_07', text: 'Juggle five balls' },
        { id: 'talents_08', text: 'Walk on your hands' },
        { id: 'talents_09', text: 'Roll your tongue' },
        { id: 'talents_10', text: 'Play piano by ear' },
        { id: 'talents_11', text: 'Draw a perfect circle' },
        { id: 'talents_12', text: 'Do card tricks' },
        { id: 'talents_13', text: 'Beatbox' },
        { id: 'talents_14', text: 'Do the splits' },
        { id: 'talents_15', text: 'Yodel' },
        { id: 'talents_16', text: 'Read lips' },
        { id: 'talents_17', text: 'Freestyle rap' },
        { id: 'talents_18', text: 'Moonwalk' },
        { id: 'talents_19', text: 'Recite pi to 100 digits' },
        { id: 'talents_20', text: 'Name any wine blind' },
        { id: 'talents_21', text: 'Cry on cue' },
        { id: 'talents_22', text: 'Tap dance' },
        { id: 'talents_23', text: 'Whistle with fingers' },
        { id: 'talents_24', text: 'Nail any accent' },
        { id: 'talents_25', text: 'Twirl a pen' },
    ],
    hobbies_at_70: [
        { id: 'hobbies_at_70_01', text: 'Tending bonsai' },
        { id: 'hobbies_at_70_02', text: 'Golf' },
        { id: 'hobbies_at_70_03', text: 'Whittling' },
        { id: 'hobbies_at_70_04', text: 'Bird watching' },
        { id: 'hobbies_at_70_05', text: 'Painting' },
        { id: 'hobbies_at_70_06', text: 'Chess' },
        { id: 'hobbies_at_70_07', text: 'Reading novels' },
        { id: 'hobbies_at_70_08', text: 'Sailing' },
        { id: 'hobbies_at_70_09', text: 'Cooking classes' },
        { id: 'hobbies_at_70_10', text: 'Baking bread' },
        { id: 'hobbies_at_70_11', text: 'Volunteering' },
        { id: 'hobbies_at_70_12', text: 'Traveling' },
        { id: 'hobbies_at_70_13', text: 'Ballroom dancing' },
        { id: 'hobbies_at_70_14', text: 'Bridge' },
        { id: 'hobbies_at_70_15', text: 'Fishing' },
        { id: 'hobbies_at_70_16', text: 'Nature photography' },
        { id: 'hobbies_at_70_17', text: 'Writing memoirs' },
        { id: 'hobbies_at_70_18', text: 'Playing organ' },
        { id: 'hobbies_at_70_19', text: 'Beekeeping' },
        { id: 'hobbies_at_70_20', text: 'Pottery' },
        { id: 'hobbies_at_70_21', text: 'Yoga' },
        { id: 'hobbies_at_70_22', text: 'Crossword puzzles' },
        { id: 'hobbies_at_70_23', text: 'Model trains' },
        { id: 'hobbies_at_70_24', text: 'Ham radio' },
        { id: 'hobbies_at_70_25', text: 'Genealogy' },
    ],
    collecting: [
        { id: 'collecting_01', text: 'Stamps' },
        { id: 'collecting_02', text: 'Vinyl records' },
        { id: 'collecting_03', text: 'Rare books' },
        { id: 'collecting_04', text: 'Coins' },
        { id: 'collecting_05', text: 'Comic books' },
        { id: 'collecting_06', text: 'Sneakers' },
        { id: 'collecting_07', text: 'Watches' },
        { id: 'collecting_08', text: 'Art prints' },
        { id: 'collecting_09', text: 'Trading cards' },
        { id: 'collecting_10', text: 'Antique maps' },
        { id: 'collecting_11', text: 'Fountain pens' },
        { id: 'collecting_12', text: 'Souvenir magnets' },
        { id: 'collecting_13', text: 'Vintage cameras' },
        { id: 'collecting_14', text: 'Rare whiskeys' },
        { id: 'collecting_15', text: 'Board games' },
        { id: 'collecting_16', text: 'LEGO sets' },
        { id: 'collecting_17', text: 'Rocks and minerals' },
        { id: 'collecting_18', text: 'Sea shells' },
        { id: 'collecting_19', text: 'Postcards' },
        { id: 'collecting_20', text: 'Autographs' },
        { id: 'collecting_21', text: 'Movie posters' },
        { id: 'collecting_22', text: 'Perfume bottles' },
        { id: 'collecting_23', text: 'Snow globes' },
        { id: 'collecting_24', text: 'Action figures' },
        { id: 'collecting_25', text: 'Teapots' },
    ],
    conversation: [
        { id: 'conversation_01', text: 'Movies' },
        { id: 'conversation_02', text: 'Sports' },
        { id: 'conversation_03', text: 'Vacation plans' },
        { id: 'conversation_04', text: 'Food' },
        { id: 'conversation_05', text: 'Concerts' },
        { id: 'conversation_06', text: 'Novels' },
        { id: 'conversation_07', text: 'TV shows' },
        { id: 'conversation_08', text: 'True crime' },
        { id: 'conversation_09', text: 'Family gossip' },
        { id: 'conversation_10', text: 'Work drama' },
        { id: 'conversation_11', text: 'History' },
        { id: 'conversation_12', text: 'Science' },
        { id: 'conversation_13', text: 'Fashion' },
        { id: 'conversation_14', text: 'Cars' },
        { id: 'conversation_15', text: 'Home renovation' },
        { id: 'conversation_16', text: 'Parenting' },
        { id: 'conversation_17', text: 'Pets' },
        { id: 'conversation_18', text: 'Dating' },
        { id: 'conversation_19', text: 'Personal finance' },
        { id: 'conversation_20', text: 'Celebrities' },
        { id: 'conversation_21', text: 'Local news' },
        { id: 'conversation_22', text: 'Fitness' },
        { id: 'conversation_23', text: 'Technology' },
        { id: 'conversation_24', text: 'The weather' },
        { id: 'conversation_25', text: 'Weekend plans' },
    ],
    icebreakers: [
        { id: 'icebreakers_01', text: 'What is your dream job?' },
        { id: 'icebreakers_02', text: 'Where would you love to live?' },
        { id: 'icebreakers_03', text: 'What is your comfort food?' },
        { id: 'icebreakers_04', text: 'Any hidden talents?' },
        { id: 'icebreakers_05', text: 'Best trip you have taken?' },
        { id: 'icebreakers_06', text: 'Favorite movie ever?' },
        { id: 'icebreakers_07', text: 'Weirdest fear?' },
        { id: 'icebreakers_08', text: 'Childhood hero?' },
        { id: 'icebreakers_09', text: 'Worst haircut ever?' },
        { id: 'icebreakers_10', text: 'Go-to karaoke song?' },
        { id: 'icebreakers_11', text: 'First job you had?' },
        { id: 'icebreakers_12', text: 'Best gift ever received?' },
        { id: 'icebreakers_13', text: 'Guilty pleasure show?' },
        { id: 'icebreakers_14', text: 'Coffee or tea?' },
        { id: 'icebreakers_15', text: 'Morning person or night owl?' },
        { id: 'icebreakers_16', text: 'What if you won the lottery?' },
        { id: 'icebreakers_17', text: 'Any big regrets?' },
        { id: 'icebreakers_18', text: 'A weird food you love?' },
        { id: 'icebreakers_19', text: 'Last thing that made you cry?' },
        { id: 'icebreakers_20', text: 'Dream dinner guest?' },
        { id: 'icebreakers_21', text: 'What would you never do?' },
        { id: 'icebreakers_22', text: 'Favorite smell?' },
        { id: 'icebreakers_23', text: 'Last book you loved?' },
        { id: 'icebreakers_24', text: 'Biggest pet peeve?' },
        { id: 'icebreakers_25', text: 'What are you proud of?' },
    ],
    humor: [
        { id: 'humor_01', text: 'Slapstick' },
        { id: 'humor_02', text: 'Dad jokes' },
        { id: 'humor_03', text: 'Puns' },
        { id: 'humor_04', text: 'Dry wit' },
        { id: 'humor_05', text: 'Dark humor' },
        { id: 'humor_06', text: 'Sarcasm' },
        { id: 'humor_07', text: 'Self-deprecation' },
        { id: 'humor_08', text: 'Absurdism' },
        { id: 'humor_09', text: 'Observational humor' },
        { id: 'humor_10', text: 'Physical comedy' },
        { id: 'humor_11', text: 'Toilet humor' },
        { id: 'humor_12', text: 'Deadpan' },
        { id: 'humor_13', text: 'Impressions' },
        { id: 'humor_14', text: 'Roasts' },
        { id: 'humor_15', text: 'Improv' },
        { id: 'humor_16', text: 'Prank humor' },
        { id: 'humor_17', text: 'Pop culture riffs' },
        { id: 'humor_18', text: 'Cringe comedy' },
        { id: 'humor_19', text: 'Wordplay' },
        { id: 'humor_20', text: 'Political satire' },
        { id: 'humor_21', text: 'Musical parody' },
        { id: 'humor_22', text: 'One-liners' },
        { id: 'humor_23', text: 'Storytelling' },
        { id: 'humor_24', text: 'Meme humor' },
        { id: 'humor_25', text: 'Anti-humor' },
    ],
    excuses: [
        { id: 'excuses_01', text: 'Not feeling well' },
        { id: 'excuses_02', text: 'Phone died' },
        { id: 'excuses_03', text: 'Traffic was awful' },
        { id: 'excuses_04', text: 'I forgot' },
        { id: 'excuses_05', text: 'Family emergency' },
        { id: 'excuses_06', text: 'Work is crazy' },
        { id: 'excuses_07', text: 'Too tired' },
        { id: 'excuses_08', text: 'Bad headache' },
        { id: 'excuses_09', text: 'The dog needs me' },
        { id: 'excuses_10', text: 'Already have plans' },
        { id: 'excuses_11', text: 'Totally swamped' },
        { id: 'excuses_12', text: 'Lost track of time' },
        { id: 'excuses_13', text: 'Alarm never went off' },
        { id: 'excuses_14', text: 'Got the dates mixed up' },
        { id: 'excuses_15', text: 'Something came up' },
        { id: 'excuses_16', text: 'Broke this week' },
        { id: 'excuses_17', text: 'Kids are sick' },
        { id: 'excuses_18', text: 'Need a quiet night' },
        { id: 'excuses_19', text: 'Back is acting up' },
        { id: 'excuses_20', text: 'Waiting on a package' },
        { id: 'excuses_21', text: 'Bad signal' },
        { id: 'excuses_22', text: 'Missed your text' },
        { id: 'excuses_23', text: 'Car trouble' },
        { id: 'excuses_24', text: 'On a deadline' },
        { id: 'excuses_25', text: 'It slipped my mind' },
    ],
    white_lies: [
        { id: 'white_lies_01', text: 'Your age' },
        { id: 'white_lies_02', text: 'Your weight' },
        { id: 'white_lies_03', text: 'Being on your way' },
        { id: 'white_lies_04', text: 'Reading the terms' },
        { id: 'white_lies_05', text: 'Loving a gift' },
        { id: 'white_lies_06', text: 'Enjoying the party' },
        { id: 'white_lies_07', text: 'Finishing the book' },
        { id: 'white_lies_08', text: 'Watching the show' },
        { id: 'white_lies_09', text: 'Being fine' },
        { id: 'white_lies_10', text: 'Doing the homework' },
        { id: 'white_lies_11', text: 'Loving the meal' },
        { id: 'white_lies_12', text: 'Your salary' },
        { id: 'white_lies_13', text: 'How much you slept' },
        { id: 'white_lies_14', text: 'How much you drank' },
        { id: 'white_lies_15', text: 'Being too busy' },
        { id: 'white_lies_16', text: 'Missing the text' },
        { id: 'white_lies_17', text: 'Running late' },
        { id: 'white_lies_18', text: 'Knowing the person' },
        { id: 'white_lies_19', text: 'Remembering the name' },
        { id: 'white_lies_20', text: 'Being almost done' },
        { id: 'white_lies_21', text: 'Your workout routine' },
        { id: 'white_lies_22', text: 'Your screen time' },
        { id: 'white_lies_23', text: 'Getting the joke' },
        { id: 'white_lies_24', text: 'Being interested' },
        { id: 'white_lies_25', text: 'Following the diet' },
    ],
    unwritten_rules: [
        { id: 'unwritten_rules_01', text: 'Return the shopping cart' },
        { id: 'unwritten_rules_02', text: 'Tip well' },
        { id: 'unwritten_rules_03', text: 'Hold the door' },
        { id: 'unwritten_rules_04', text: 'Say please and thank you' },
        { id: 'unwritten_rules_05', text: 'RSVP on time' },
        { id: 'unwritten_rules_06', text: 'Reply within a day' },
        { id: 'unwritten_rules_07', text: 'Never text after 10pm' },
        { id: 'unwritten_rules_08', text: 'Bring a gift to a party' },
        { id: 'unwritten_rules_09', text: 'Take shoes off inside' },
        { id: 'unwritten_rules_10', text: 'No phone at the table' },
        { id: 'unwritten_rules_11', text: 'Mute yourself on calls' },
        { id: 'unwritten_rules_12', text: 'Left lane is for passing' },
        { id: 'unwritten_rules_13', text: 'Wait your turn in line' },
        { id: 'unwritten_rules_14', text: 'Stay quiet in elevators' },
        { id: 'unwritten_rules_15', text: 'Refill the coffee pot' },
        { id: 'unwritten_rules_16', text: 'Wave when let through' },
        { id: 'unwritten_rules_17', text: 'Match the dress code' },
        { id: 'unwritten_rules_18', text: 'Bring beer to a BBQ' },
        { id: 'unwritten_rules_19', text: 'Compliment the chef' },
        { id: 'unwritten_rules_20', text: 'Split the bill evenly' },
        { id: 'unwritten_rules_21', text: 'Reply-all only if needed' },
        { id: 'unwritten_rules_22', text: 'Never skip small talk' },
        { id: 'unwritten_rules_23', text: 'Never ghost people' },
        { id: 'unwritten_rules_24', text: 'Cover your yawn' },
        { id: 'unwritten_rules_25', text: 'Rinse your dishes' },
    ],
    phone_habits: [
        { id: 'phone_habits_01', text: 'Check it first thing' },
        { id: 'phone_habits_02', text: 'Scroll before bed' },
        { id: 'phone_habits_03', text: 'Silence all notifications' },
        { id: 'phone_habits_04', text: 'Ignore unknown calls' },
        { id: 'phone_habits_05', text: 'Reply immediately' },
        { id: 'phone_habits_06', text: 'Leave texts unread' },
        { id: 'phone_habits_07', text: 'Keep it face down' },
        { id: 'phone_habits_08', text: 'Doomscroll the news' },
        { id: 'phone_habits_09', text: 'Take too many selfies' },
        { id: 'phone_habits_10', text: 'Never delete photos' },
        { id: 'phone_habits_11', text: 'Airdrop memes to friends' },
        { id: 'phone_habits_12', text: 'Screen record everything' },
        { id: 'phone_habits_13', text: 'Use it as a flashlight' },
        { id: 'phone_habits_14', text: 'Charge it overnight' },
        { id: 'phone_habits_15', text: 'Let battery hit 1%' },
        { id: 'phone_habits_16', text: 'Snooze every alarm' },
        { id: 'phone_habits_17', text: 'Send voice memos' },
        { id: 'phone_habits_18', text: 'Skip every phone call' },
        { id: 'phone_habits_19', text: 'Send long paragraphs' },
        { id: 'phone_habits_20', text: 'Type with one finger' },
        { id: 'phone_habits_21', text: 'Rely on voice-to-text' },
        { id: 'phone_habits_22', text: 'Turn it off at dinner' },
        { id: 'phone_habits_23', text: 'Bring it to the bathroom' },
        { id: 'phone_habits_24', text: 'Track your screen time' },
        { id: 'phone_habits_25', text: 'Read but never reply' },
    ],
    rabbit_holes: [
        { id: 'rabbit_holes_01', text: 'True crime cases' },
        { id: 'rabbit_holes_02', text: 'Celebrity gossip' },
        { id: 'rabbit_holes_03', text: 'Conspiracy theories' },
        { id: 'rabbit_holes_04', text: 'Historical mysteries' },
        { id: 'rabbit_holes_05', text: 'Space and physics' },
        { id: 'rabbit_holes_06', text: 'Ancient civilizations' },
        { id: 'rabbit_holes_07', text: 'Deep sea creatures' },
        { id: 'rabbit_holes_08', text: 'Cult documentaries' },
        { id: 'rabbit_holes_09', text: 'Cold cases' },
        { id: 'rabbit_holes_10', text: 'Royal family drama' },
        { id: 'rabbit_holes_11', text: 'Wikipedia deep dives' },
        { id: 'rabbit_holes_12', text: 'Reddit threads' },
        { id: 'rabbit_holes_13', text: 'Old family photos' },
        { id: 'rabbit_holes_14', text: 'Genealogy trees' },
        { id: 'rabbit_holes_15', text: 'Zillow listings' },
        { id: 'rabbit_holes_16', text: 'Product reviews' },
        { id: 'rabbit_holes_17', text: 'Fan theories' },
        { id: 'rabbit_holes_18', text: 'Reality TV drama' },
        { id: 'rabbit_holes_19', text: 'Sports stats' },
        { id: 'rabbit_holes_20', text: 'Recipe blogs' },
        { id: 'rabbit_holes_21', text: 'Vintage ads' },
        { id: 'rabbit_holes_22', text: 'Abandoned places' },
        { id: 'rabbit_holes_23', text: 'Unsolved disappearances' },
        { id: 'rabbit_holes_24', text: 'Nature documentaries' },
        { id: 'rabbit_holes_25', text: 'Retro tech' },
    ],
    binging: [
        { id: 'binging_01', text: 'TV shows' },
        { id: 'binging_02', text: 'Chips' },
        { id: 'binging_03', text: 'Chocolate' },
        { id: 'binging_04', text: 'Ice cream' },
        { id: 'binging_05', text: 'YouTube' },
        { id: 'binging_06', text: 'TikTok' },
        { id: 'binging_07', text: 'Reddit' },
        { id: 'binging_08', text: 'Cookie dough' },
        { id: 'binging_09', text: 'Popcorn' },
        { id: 'binging_10', text: 'Cheese' },
        { id: 'binging_11', text: 'Mobile games' },
        { id: 'binging_12', text: 'Podcasts' },
        { id: 'binging_13', text: 'True crime shows' },
        { id: 'binging_14', text: 'Trashy reality TV' },
        { id: 'binging_15', text: 'News refreshes' },
        { id: 'binging_16', text: 'Book series' },
        { id: 'binging_17', text: 'Pistachios' },
        { id: 'binging_18', text: 'Wine' },
        { id: 'binging_19', text: 'Iced coffee' },
        { id: 'binging_20', text: 'Instagram reels' },
        { id: 'binging_21', text: 'Naps' },
        { id: 'binging_22', text: 'Pastries' },
        { id: 'binging_23', text: 'Sudoku' },
        { id: 'binging_24', text: 'Sports highlights' },
        { id: 'binging_25', text: 'Movie marathons' },
    ],
    apps: [
        { id: 'apps_01', text: 'Google Maps' },
        { id: 'apps_02', text: 'WhatsApp' },
        { id: 'apps_03', text: 'Instagram' },
        { id: 'apps_04', text: 'TikTok' },
        { id: 'apps_05', text: 'YouTube' },
        { id: 'apps_06', text: 'Spotify' },
        { id: 'apps_07', text: 'Gmail' },
        { id: 'apps_08', text: 'Uber' },
        { id: 'apps_09', text: 'Amazon' },
        { id: 'apps_10', text: 'Netflix' },
        { id: 'apps_11', text: 'Weather app' },
        { id: 'apps_12', text: 'Calendar' },
        { id: 'apps_13', text: 'Notes app' },
        { id: 'apps_14', text: 'Camera' },
        { id: 'apps_15', text: 'Slack' },
        { id: 'apps_16', text: 'Zoom' },
        { id: 'apps_17', text: 'Chrome' },
        { id: 'apps_18', text: 'Photos' },
        { id: 'apps_19', text: 'Venmo' },
        { id: 'apps_20', text: 'Podcasts' },
        { id: 'apps_21', text: 'Reddit' },
        { id: 'apps_22', text: 'LinkedIn' },
        { id: 'apps_23', text: 'Duolingo' },
        { id: 'apps_24', text: 'Alarm clock' },
        { id: 'apps_25', text: 'Banking app' },
    ],
    automation: [
        { id: 'automation_01', text: 'Laundry' },
        { id: 'automation_02', text: 'Dishes' },
        { id: 'automation_03', text: 'Cooking dinner' },
        { id: 'automation_04', text: 'Grocery shopping' },
        { id: 'automation_05', text: 'Cleaning bathrooms' },
        { id: 'automation_06', text: 'Vacuuming' },
        { id: 'automation_07', text: 'Mowing the lawn' },
        { id: 'automation_08', text: 'Ironing' },
        { id: 'automation_09', text: 'Folding laundry' },
        { id: 'automation_10', text: 'Taking out trash' },
        { id: 'automation_11', text: 'Doing taxes' },
        { id: 'automation_12', text: 'Paying bills' },
        { id: 'automation_13', text: 'Meal planning' },
        { id: 'automation_14', text: 'Answering emails' },
        { id: 'automation_15', text: 'Scheduling meetings' },
        { id: 'automation_16', text: 'Driving to work' },
        { id: 'automation_17', text: 'Making the bed' },
        { id: 'automation_18', text: 'Packing lunches' },
        { id: 'automation_19', text: 'Booking travel' },
        { id: 'automation_20', text: 'Filing paperwork' },
        { id: 'automation_21', text: 'Watering plants' },
        { id: 'automation_22', text: 'Walking the dog' },
        { id: 'automation_23', text: 'Cleaning the car' },
        { id: 'automation_24', text: 'Sending birthday cards' },
        { id: 'automation_25', text: 'Wrapping gifts' },
    ],
};
