export default {
  in_a_partner: [
    { id: "in_a_partner_01", text: "Kindness" },
    { id: "in_a_partner_02", text: "A sense of humor" },
    { id: "in_a_partner_03", text: "Ambition" },
    { id: "in_a_partner_04", text: "Emotional honesty" },
    { id: "in_a_partner_05", text: "Physical attraction" },
    { id: "in_a_partner_06", text: "Shared values" },
    { id: "in_a_partner_07", text: "Financial stability" },
    { id: "in_a_partner_08", text: "Intelligence" },
    { id: "in_a_partner_09", text: "Loyalty" },
    { id: "in_a_partner_10", text: "Independence" },
    { id: "in_a_partner_11", text: "Wanting kids" },
    { id: "in_a_partner_12", text: "Similar interests" },
    { id: "in_a_partner_13", text: "Emotional maturity" },
    { id: "in_a_partner_14", text: "Adventurousness" },
    { id: "in_a_partner_15", text: "Good communication" },
    { id: "in_a_partner_16", text: "Closeness to family" },
    { id: "in_a_partner_17", text: "Physical affection" },
    { id: "in_a_partner_18", text: "Similar politics" },
    { id: "in_a_partner_19", text: "Curiosity" },
    { id: "in_a_partner_20", text: "Patience" },
    { id: "in_a_partner_21", text: "A calm temperament" },
    { id: "in_a_partner_22", text: "Career drive" },
    { id: "in_a_partner_23", text: "Being easy to talk to" },
    { id: "in_a_partner_24", text: "Wanting a quiet life" },
    { id: "in_a_partner_25", text: "Being a good listener" },
  ],

  dealbreakers: [
    { id: "dealbreakers_01", text: "Lying to you" },
    { id: "dealbreakers_02", text: "Cheating" },
    { id: "dealbreakers_03", text: "Being rude to servers" },
    { id: "dealbreakers_04", text: "Never apologizing" },
    { id: "dealbreakers_05", text: "Bad hygiene" },
    { id: "dealbreakers_06", text: "Being cheap with money" },
    { id: "dealbreakers_07", text: "Constant jealousy" },
    { id: "dealbreakers_08", text: "No ambition" },
    { id: "dealbreakers_09", text: "Being closed off" },
    { id: "dealbreakers_10", text: "Different life goals" },
    { id: "dealbreakers_11", text: "Rudeness to your family" },
    { id: "dealbreakers_12", text: "Talking down to you" },
    { id: "dealbreakers_13", text: "Not pulling their weight" },
    { id: "dealbreakers_14", text: "Different politics" },
    { id: "dealbreakers_15", text: "Wanting different things" },
    { id: "dealbreakers_16", text: "Being unreliable" },
    { id: "dealbreakers_17", text: "A bad temper" },
    { id: "dealbreakers_18", text: "Being controlling" },
    { id: "dealbreakers_19", text: "Passive aggression" },
    { id: "dealbreakers_20", text: "Refusing to grow" },
    { id: "dealbreakers_21", text: "Never really listening" },
    { id: "dealbreakers_22", text: "Being secretive" },
    { id: "dealbreakers_23", text: "Flirting with others" },
    { id: "dealbreakers_24", text: "Trashing their exes" },
    { id: "dealbreakers_25", text: "Being messy" },
  ],

  green_flags: [
    { id: "green_flags_01", text: "Being kind to strangers" },
    { id: "green_flags_02", text: "Owning their mistakes" },
    { id: "green_flags_03", text: "Keeping their promises" },
    { id: "green_flags_04", text: "Being on time" },
    { id: "green_flags_05", text: "Remembering small details" },
    { id: "green_flags_06", text: "Long-term friendships" },
    { id: "green_flags_07", text: "Being kind to their parents" },
    { id: "green_flags_08", text: "Tipping well" },
    { id: "green_flags_09", text: "Being calm under stress" },
    { id: "green_flags_10", text: "Asking good questions" },
    { id: "green_flags_11", text: "Being good with kids" },
    { id: "green_flags_12", text: "Staying patient in traffic" },
    { id: "green_flags_13", text: "Genuine curiosity" },
    { id: "green_flags_14", text: "Following through" },
    { id: "green_flags_15", text: "Being open about feelings" },
    { id: "green_flags_16", text: "Taking care of pets" },
    { id: "green_flags_17", text: "Reading real books" },
    { id: "green_flags_18", text: "Showing up early" },
    { id: "green_flags_19", text: "Making people feel seen" },
    { id: "green_flags_20", text: "Being self-aware" },
    { id: "green_flags_21", text: "Handling money well" },
    { id: "green_flags_22", text: "Being generous" },
    { id: "green_flags_23", text: "Laughing at themselves" },
    { id: "green_flags_24", text: "Direct communication" },
    { id: "green_flags_25", text: "Being close with siblings" },
  ],

  compliments: [
    { id: "compliments_01", text: "You're so kind" },
    { id: "compliments_02", text: "You're hilarious" },
    { id: "compliments_03", text: "You're brilliant" },
    { id: "compliments_04", text: "You have great taste" },
    { id: "compliments_05", text: "You're beautiful" },
    { id: "compliments_06", text: "You're a great friend" },
    { id: "compliments_07", text: "You always show up" },
    { id: "compliments_08", text: "You're wise" },
    { id: "compliments_09", text: "You're so talented" },
    { id: "compliments_10", text: "You make me feel safe" },
    { id: "compliments_11", text: "You're a great listener" },
    { id: "compliments_12", text: "You inspire me" },
    { id: "compliments_13", text: "You're so thoughtful" },
    { id: "compliments_14", text: "You're great at your job" },
    { id: "compliments_15", text: "You make people feel seen" },
    { id: "compliments_16", text: "You're strong" },
    { id: "compliments_17", text: "You're a good soul" },
    { id: "compliments_18", text: "You're so creative" },
    { id: "compliments_19", text: "You have a great laugh" },
    { id: "compliments_20", text: "You always know what to say" },
    { id: "compliments_21", text: "You're really cool" },
    { id: "compliments_22", text: "You made my day" },
    { id: "compliments_23", text: "You're my favorite person" },
    { id: "compliments_24", text: "You seem sure of yourself" },
    { id: "compliments_25", text: "You're doing great" },
  ],

  insecurities: [
    { id: "insecurities_01", text: "Your appearance" },
    { id: "insecurities_02", text: "Your weight" },
    { id: "insecurities_03", text: "How you sound on video" },
    { id: "insecurities_04", text: "Your career path" },
    { id: "insecurities_05", text: "Your income" },
    { id: "insecurities_06", text: "Your intelligence" },
    { id: "insecurities_07", text: "Being liked" },
    { id: "insecurities_08", text: "Being boring" },
    { id: "insecurities_09", text: "Being too much" },
    { id: "insecurities_10", text: "Not being enough" },
    { id: "insecurities_11", text: "Your body" },
    { id: "insecurities_12", text: "Getting older" },
    { id: "insecurities_13", text: "Your teeth" },
    { id: "insecurities_14", text: "Your hair" },
    { id: "insecurities_15", text: "Ending up alone" },
    { id: "insecurities_16", text: "Not being funny" },
    { id: "insecurities_17", text: "Being single" },
    { id: "insecurities_18", text: "Coming off fake" },
    { id: "insecurities_19", text: "Your handwriting" },
    { id: "insecurities_20", text: "Sounding dumb" },
    { id: "insecurities_21", text: "Being left behind" },
    { id: "insecurities_22", text: "Falling behind friends" },
    { id: "insecurities_23", text: "Your voice" },
    { id: "insecurities_24", text: "Being forgettable" },
    { id: "insecurities_25", text: "Not being taken seriously" },
  ],

  success: [
    { id: "success_01", text: "Owning a home" },
    { id: "success_02", text: "Making six figures" },
    { id: "success_03", text: "A happy family" },
    { id: "success_04", text: "Being your own boss" },
    { id: "success_05", text: "Getting promoted" },
    { id: "success_06", text: "Being known in your field" },
    { id: "success_07", text: "Being debt-free" },
    { id: "success_08", text: "Traveling the world" },
    { id: "success_09", text: "Close, lasting friendships" },
    { id: "success_10", text: "A job you love" },
    { id: "success_11", text: "Retiring early" },
    { id: "success_12", text: "Raising great kids" },
    { id: "success_13", text: "Financial independence" },
    { id: "success_14", text: "A strong marriage" },
    { id: "success_15", text: "Being widely respected" },
    { id: "success_16", text: "Making things you're proud of" },
    { id: "success_17", text: "Being fit and healthy" },
    { id: "success_18", text: "Winning a major award" },
    { id: "success_19", text: "Being asked to speak" },
    { id: "success_20", text: "Mastering a craft" },
    { id: "success_21", text: "Being asked for advice" },
    { id: "success_22", text: "Living where you want" },
    { id: "success_23", text: "Feeling at peace" },
    { id: "success_24", text: "Being remembered well" },
    { id: "success_25", text: "Out-earning your parents" },
  ],

  admiration: [
    { id: "admiration_01", text: "Kindness" },
    { id: "admiration_02", text: "Courage" },
    { id: "admiration_03", text: "Wit" },
    { id: "admiration_04", text: "Confidence" },
    { id: "admiration_05", text: "Discipline" },
    { id: "admiration_06", text: "Honesty" },
    { id: "admiration_07", text: "Generosity" },
    { id: "admiration_08", text: "Curiosity" },
    { id: "admiration_09", text: "Ambition" },
    { id: "admiration_10", text: "Humility" },
    { id: "admiration_11", text: "Patience" },
    { id: "admiration_12", text: "Loyalty" },
    { id: "admiration_13", text: "Creativity" },
    { id: "admiration_14", text: "Self-awareness" },
    { id: "admiration_15", text: "Wisdom" },
    { id: "admiration_16", text: "Empathy" },
    { id: "admiration_17", text: "Charisma" },
    { id: "admiration_18", text: "Reliability" },
    { id: "admiration_19", text: "Toughness" },
    { id: "admiration_20", text: "Warmth" },
    { id: "admiration_21", text: "Optimism" },
    { id: "admiration_22", text: "Independence" },
    { id: "admiration_23", text: "A strong work ethic" },
    { id: "admiration_24", text: "Playfulness" },
    { id: "admiration_25", text: "Fairness" },
  ],

  family: [
    { id: "family_01", text: "Sunday dinners" },
    { id: "family_02", text: "Staying in touch" },
    { id: "family_03", text: "Big holiday gatherings" },
    { id: "family_04", text: "Family traditions" },
    { id: "family_05", text: "Living close by" },
    { id: "family_06", text: "The family group chat" },
    { id: "family_07", text: "Knowing your cousins" },
    { id: "family_08", text: "Family photos on the wall" },
    { id: "family_09", text: "Passing down recipes" },
    { id: "family_10", text: "Keeping family stories alive" },
    { id: "family_11", text: "Showing up for birthdays" },
    { id: "family_12", text: "Being able to be yourself" },
    { id: "family_13", text: "Getting along with in-laws" },
    { id: "family_14", text: "Regular phone calls" },
    { id: "family_15", text: "Being there in a crisis" },
    { id: "family_16", text: "Family vacations" },
    { id: "family_17", text: "A shared sense of humor" },
    { id: "family_18", text: "Respecting your elders" },
    { id: "family_19", text: "Knowing your family history" },
    { id: "family_20", text: "Forgiving old grudges" },
    { id: "family_21", text: "Being a role model" },
    { id: "family_22", text: "Passing down values" },
    { id: "family_23", text: "Weddings and funerals" },
    { id: "family_24", text: "Being proud of each other" },
    { id: "family_25", text: "Not keeping score" },
  ],

  loneliness: [
    { id: "loneliness_01", text: "Eating alone in public" },
    { id: "loneliness_02", text: "A quiet weekend at home" },
    { id: "loneliness_03", text: "Scrolling at 2am" },
    { id: "loneliness_04", text: "Being the only single friend" },
    { id: "loneliness_05", text: "No plans on a Friday" },
    { id: "loneliness_06", text: "A birthday with no calls" },
    { id: "loneliness_07", text: "Moving to a new city" },
    { id: "loneliness_08", text: "Working from home all week" },
    { id: "loneliness_09", text: "Being in a big crowd" },
    { id: "loneliness_10", text: "Seeing couples on a walk" },
    { id: "loneliness_11", text: "An empty apartment" },
    { id: "loneliness_12", text: "A silent group chat" },
    { id: "loneliness_13", text: "Photos you weren't in" },
    { id: "loneliness_14", text: "Nobody texting first" },
    { id: "loneliness_15", text: "A long drive alone" },
    { id: "loneliness_16", text: "Going to a wedding alone" },
    { id: "loneliness_17", text: "Eating in front of the TV" },
    { id: "loneliness_18", text: "Missing an inside joke" },
    { id: "loneliness_19", text: "Being sick alone" },
    { id: "loneliness_20", text: "A quiet holiday" },
    { id: "loneliness_21", text: "Feeling unseen in a room" },
    { id: "loneliness_22", text: "Losing touch with old friends" },
    { id: "loneliness_23", text: "Being new at work" },
    { id: "loneliness_24", text: "Nobody to call at night" },
    { id: "loneliness_25", text: "Ordering takeout for one" },
  ],

  feeling_safe: [
    { id: "feeling_safe_01", text: "Money in savings" },
    { id: "feeling_safe_02", text: "A stable job" },
    { id: "feeling_safe_03", text: "A locked door" },
    { id: "feeling_safe_04", text: "Your partner beside you" },
    { id: "feeling_safe_05", text: "Being home" },
    { id: "feeling_safe_06", text: "A tidy house" },
    { id: "feeling_safe_07", text: "Being in good health" },
    { id: "feeling_safe_08", text: "Close friends nearby" },
    { id: "feeling_safe_09", text: "Your childhood bedroom" },
    { id: "feeling_safe_10", text: "A full fridge" },
    { id: "feeling_safe_11", text: "Owning your home" },
    { id: "feeling_safe_12", text: "A quiet routine" },
    { id: "feeling_safe_13", text: "Knowing your neighbors" },
    { id: "feeling_safe_14", text: "Being with family" },
    { id: "feeling_safe_15", text: "A hot shower" },
    { id: "feeling_safe_16", text: "A warm bed" },
    { id: "feeling_safe_17", text: "Health insurance" },
    { id: "feeling_safe_18", text: "A clear calendar" },
    { id: "feeling_safe_19", text: "Being alone in your space" },
    { id: "feeling_safe_20", text: "A charged phone" },
    { id: "feeling_safe_21", text: "A full tank of gas" },
    { id: "feeling_safe_22", text: "Sunday mornings" },
    { id: "feeling_safe_23", text: "A doctor you trust" },
    { id: "feeling_safe_24", text: "No debt" },
    { id: "feeling_safe_25", text: "A weekly routine" },
  ],

  hard_to_admit: [
    { id: "hard_to_admit_01", text: "\"I was wrong\"" },
    { id: "hard_to_admit_02", text: "\"I'm jealous\"" },
    { id: "hard_to_admit_03", text: "\"I need help\"" },
    { id: "hard_to_admit_04", text: "\"I don't know\"" },
    { id: "hard_to_admit_05", text: "\"I miss you\"" },
    { id: "hard_to_admit_06", text: "\"I'm scared\"" },
    { id: "hard_to_admit_07", text: "\"I'm lonely\"" },
    { id: "hard_to_admit_08", text: "\"I care what they think\"" },
    { id: "hard_to_admit_09", text: "\"I hate my job\"" },
    { id: "hard_to_admit_10", text: "\"I'm not okay\"" },
    { id: "hard_to_admit_11", text: "\"That hurt me\"" },
    { id: "hard_to_admit_12", text: "\"I still think about it\"" },
    { id: "hard_to_admit_13", text: "\"I copied someone\"" },
    { id: "hard_to_admit_14", text: "\"I don't feel loved\"" },
    { id: "hard_to_admit_15", text: "\"I want more\"" },
    { id: "hard_to_admit_16", text: "\"I'm proud of myself\"" },
    { id: "hard_to_admit_17", text: "\"I love you\"" },
    { id: "hard_to_admit_18", text: "\"I regret it\"" },
    { id: "hard_to_admit_19", text: "\"I have no real friends\"" },
    { id: "hard_to_admit_20", text: "\"I overreacted\"" },
    { id: "hard_to_admit_21", text: "\"I lied\"" },
    { id: "hard_to_admit_22", text: "\"I'm not over it\"" },
    { id: "hard_to_admit_23", text: "\"I don't know what I want\"" },
    { id: "hard_to_admit_24", text: "\"I'm struggling\"" },
    { id: "hard_to_admit_25", text: "\"I need attention\"" },
  ],

  recharging: [
    { id: "recharging_01", text: "A long nap" },
    { id: "recharging_02", text: "A walk outside" },
    { id: "recharging_03", text: "A slow morning" },
    { id: "recharging_04", text: "Time alone" },
    { id: "recharging_05", text: "Time with close friends" },
    { id: "recharging_06", text: "Reading a book" },
    { id: "recharging_07", text: "A hard workout" },
    { id: "recharging_08", text: "Cooking a meal" },
    { id: "recharging_09", text: "Cleaning your space" },
    { id: "recharging_10", text: "Scrolling your phone" },
    { id: "recharging_11", text: "A weekend away" },
    { id: "recharging_12", text: "Sleeping in" },
    { id: "recharging_13", text: "Playing with a pet" },
    { id: "recharging_14", text: "A good cry" },
    { id: "recharging_15", text: "Comfort TV" },
    { id: "recharging_16", text: "Making something by hand" },
    { id: "recharging_17", text: "Being outdoors" },
    { id: "recharging_18", text: "A quiet coffee" },
    { id: "recharging_19", text: "Journaling" },
    { id: "recharging_20", text: "Sitting in the sun" },
    { id: "recharging_21", text: "A road trip" },
    { id: "recharging_22", text: "Baking something" },
    { id: "recharging_23", text: "Gardening" },
    { id: "recharging_24", text: "A day off work" },
    { id: "recharging_25", text: "Deep conversation" },
  ],

  what_drives_you: [
    { id: "what_drives_you_01", text: "Money" },
    { id: "what_drives_you_02", text: "Proving people wrong" },
    { id: "what_drives_you_03", text: "Making your parents proud" },
    { id: "what_drives_you_04", text: "Building something lasting" },
    { id: "what_drives_you_05", text: "Fear of failure" },
    { id: "what_drives_you_06", text: "Recognition" },
    { id: "what_drives_you_07", text: "Learning new things" },
    { id: "what_drives_you_08", text: "Helping others" },
    { id: "what_drives_you_09", text: "A deadline" },
    { id: "what_drives_you_10", text: "Competition" },
    { id: "what_drives_you_11", text: "Financial security" },
    { id: "what_drives_you_12", text: "Love" },
    { id: "what_drives_you_13", text: "Getting better every day" },
    { id: "what_drives_you_14", text: "Being independent" },
    { id: "what_drives_you_15", text: "A big vision" },
    { id: "what_drives_you_16", text: "Not falling behind" },
    { id: "what_drives_you_17", text: "Being respected" },
    { id: "what_drives_you_18", text: "Doing meaningful work" },
    { id: "what_drives_you_19", text: "Making people laugh" },
    { id: "what_drives_you_20", text: "Legacy" },
    { id: "what_drives_you_21", text: "Freedom" },
    { id: "what_drives_you_22", text: "Winning" },
    { id: "what_drives_you_23", text: "A challenge" },
    { id: "what_drives_you_24", text: "Praise" },
    { id: "what_drives_you_25", text: "Boredom" },
  ],

  change_yourself: [
    { id: "change_yourself_01", text: "Your temper" },
    { id: "change_yourself_02", text: "Your patience" },
    { id: "change_yourself_03", text: "Your body" },
    { id: "change_yourself_04", text: "Your discipline" },
    { id: "change_yourself_05", text: "Your confidence" },
    { id: "change_yourself_06", text: "Your bank account" },
    { id: "change_yourself_07", text: "Your job" },
    { id: "change_yourself_08", text: "Your hair" },
    { id: "change_yourself_09", text: "Your height" },
    { id: "change_yourself_10", text: "Your sleep" },
    { id: "change_yourself_11", text: "Your phone habits" },
    { id: "change_yourself_12", text: "How you handle stress" },
    { id: "change_yourself_13", text: "Your social skills" },
    { id: "change_yourself_14", text: "Your energy level" },
    { id: "change_yourself_15", text: "How much you overthink" },
    { id: "change_yourself_16", text: "Your voice" },
    { id: "change_yourself_17", text: "Your fitness" },
    { id: "change_yourself_18", text: "How you handle conflict" },
    { id: "change_yourself_19", text: "Your mornings" },
    { id: "change_yourself_20", text: "How much you procrastinate" },
    { id: "change_yourself_21", text: "Your diet" },
    { id: "change_yourself_22", text: "Your handwriting" },
    { id: "change_yourself_23", text: "Your ability to say no" },
    { id: "change_yourself_24", text: "Your need for approval" },
    { id: "change_yourself_25", text: "Your posture" },
  ],

  advice: [
    { id: "advice_01", text: "\"Slow down\"" },
    { id: "advice_02", text: "\"Ask for help\"" },
    { id: "advice_03", text: "\"Say no more often\"" },
    { id: "advice_04", text: "\"Trust your gut\"" },
    { id: "advice_05", text: "\"Save more money\"" },
    { id: "advice_06", text: "\"Call your mom\"" },
    { id: "advice_07", text: "\"Get more sleep\"" },
    { id: "advice_08", text: "\"You're doing enough\"" },
    { id: "advice_09", text: "\"Move your body\"" },
    { id: "advice_10", text: "\"Stop overthinking\"" },
    { id: "advice_11", text: "\"Be kinder to yourself\"" },
    { id: "advice_12", text: "\"Speak up\"" },
    { id: "advice_13", text: "\"Let it go\"" },
    { id: "advice_14", text: "\"Take the risk\"" },
    { id: "advice_15", text: "\"Get off your phone\"" },
    { id: "advice_16", text: "\"You're not behind\"" },
    { id: "advice_17", text: "\"Set boundaries\"" },
    { id: "advice_18", text: "\"Start now\"" },
    { id: "advice_19", text: "\"Drink more water\"" },
    { id: "advice_20", text: "\"Forgive them\"" },
    { id: "advice_21", text: "\"Try therapy\"" },
    { id: "advice_22", text: "\"Say what you mean\"" },
    { id: "advice_23", text: "\"Take the compliment\"" },
    { id: "advice_24", text: "\"Rest is productive\"" },
    { id: "advice_25", text: "\"It's not about you\"" },
  ],
};
