// Master deck specification: 150 decks.
// Each entry defines the label + prompt + tier. Cards live in decks-*.mjs modules,
// keyed by deck id.
//
// PROMPT STYLE GUIDE — every prompt must be:
//   1. Self-contained (readable without the label)
//   2. Explicit about what "Most" means (the ranking axis is hardcoded to Most/Least)
//   3. One interpretation only — no hidden time qualifiers, no compound questions
//   4. Second person ("you"/"your"), never "people" or "most people"
//   5. One sentence, <= 90 characters

export const DECK_SPECS = [
  // ---------------------------------------------------------------- DEEP (50)
  { id: 'love_languages', label: 'Love Languages', tier: 'deep', prompt: 'Rank these ways of showing love by how loved they make you feel.' },
  { id: 'apologies', label: 'Apologies', tier: 'deep', prompt: 'Rank these apologies by how forgiving they would make you feel.' },
  { id: 'support', label: 'Support', tier: 'deep', prompt: 'Rank these by how much they help you when you are going through something hard.' },
  { id: 'when_upset', label: 'When You Are Upset', tier: 'deep', prompt: 'Rank these by how much you want them from people when you are upset.' },
  { id: 'values', label: 'Values', tier: 'deep', prompt: 'Rank these values by how much you try to live by them.' },
  { id: 'pride', label: 'Pride', tier: 'deep', prompt: 'Rank these by how proud you would be to have done them.' },
  { id: 'fears', label: 'Fears', tier: 'deep', prompt: 'Rank these fears by how much they actually scare you.' },
  { id: 'regrets', label: 'Regrets', tier: 'deep', prompt: 'Rank these by how much you would regret never doing them.' },
  { id: 'what_gets_you', label: 'What Gets You', tier: 'deep', prompt: 'Rank these by how likely they are to make you tear up.' },
  { id: 'trust', label: 'Trust', tier: 'deep', prompt: 'Rank these by how badly they would break your trust in someone.' },
  { id: 'forgiveness', label: 'Forgiveness', tier: 'deep', prompt: 'Rank these by how hard they would be for you to forgive.' },
  { id: 'self_worth', label: 'Self-Worth', tier: 'deep', prompt: 'Rank these by how good about yourself they make you feel.' },
  { id: 'legacy', label: 'Legacy', tier: 'deep', prompt: 'Rank these by how much you would want to be remembered that way.' },
  { id: 'hard_talks', label: 'Hard Conversations', tier: 'deep', prompt: 'Rank these conversations by how much you would avoid having them.' },
  { id: 'in_a_friend', label: 'In a Friend', tier: 'deep', prompt: 'Rank these by how much you need them from a close friend.' },
  { id: 'in_a_partner', label: 'In a Partner', tier: 'deep', prompt: 'Rank these by how much they matter to you in a long-term partner.' },
  { id: 'dealbreakers', label: 'Dealbreakers', tier: 'deep', prompt: 'Rank these by how quickly they would end a relationship for you.' },
  { id: 'green_flags', label: 'Green Flags', tier: 'deep', prompt: 'Rank these by how much they would make you trust someone.' },
  { id: 'compliments', label: 'Compliments', tier: 'deep', prompt: 'Rank these compliments by how much they would mean to you.' },
  { id: 'insecurities', label: 'Insecurities', tier: 'deep', prompt: 'Rank these by how much you worry about them.' },
  { id: 'success', label: 'Success', tier: 'deep', prompt: 'Rank these by how successful they would make you feel.' },
  { id: 'admiration', label: 'Admiration', tier: 'deep', prompt: 'Rank these traits by how much you admire them in other people.' },
  { id: 'family', label: 'Family', tier: 'deep', prompt: 'Rank these family things by how much they matter to you.' },
  { id: 'loneliness', label: 'Loneliness', tier: 'deep', prompt: 'Rank these by how lonely they would make you feel.' },
  { id: 'feeling_safe', label: 'Feeling Safe', tier: 'deep', prompt: 'Rank these by how safe and settled they make you feel.' },
  { id: 'hard_to_admit', label: 'Hard to Admit', tier: 'deep', prompt: 'Rank these by how hard they would be for you to admit out loud.' },
  { id: 'recharging', label: 'Recharging', tier: 'deep', prompt: 'Rank these by how much they actually restore your energy.' },
  { id: 'what_drives_you', label: 'What Drives You', tier: 'deep', prompt: 'Rank these by how much they actually motivate you.' },
  { id: 'change_yourself', label: 'Change', tier: 'deep', prompt: 'Rank these by how much you would want to change them about yourself.' },
  { id: 'advice', label: 'Advice', tier: 'deep', prompt: 'Rank this advice by how much you needed to hear it.' },
  { id: 'growing_up', label: 'Growing Up', tier: 'deep', prompt: 'Rank these by how much they shaped who you are today.' },
  { id: 'saying_no', label: 'Saying No', tier: 'deep', prompt: 'Rank these by how hard they are for you to say no to.' },
  { id: 'being_known', label: 'Being Known', tier: 'deep', prompt: 'Rank these by how much you want someone close to really know them.' },
  { id: 'gratitude', label: 'Gratitude', tier: 'deep', prompt: 'Rank these by how grateful you are to have them in your life.' },
  { id: 'asking_for_help', label: 'Asking for Help', tier: 'deep', prompt: 'Rank these by how hard it is for you to ask for help with them.' },
  { id: 'conflict', label: 'Conflict', tier: 'deep', prompt: 'Rank these by how much they sound like you during an argument.' },
  { id: 'worries', label: 'Worries', tier: 'deep', prompt: 'Rank these worries by how often they are on your mind.' },
  { id: 'gifts', label: 'Gifts', tier: 'deep', prompt: 'Rank these gifts by how much getting one would mean to you.' },
  { id: 'time_together', label: 'Time Together', tier: 'deep', prompt: 'Rank these by how close to someone they would make you feel.' },
  { id: 'being_wrong', label: 'Being Wrong', tier: 'deep', prompt: 'Rank these by how hard it is for you to admit you were wrong.' },
  { id: 'what_you_hide', label: 'What You Hide', tier: 'deep', prompt: 'Rank these by how much you keep them to yourself.' },
  { id: 'a_good_life', label: 'A Good Life', tier: 'deep', prompt: 'Rank these by how much they would make your life feel well lived.' },
  { id: 'courage', label: 'Courage', tier: 'deep', prompt: 'Rank these by how brave you would have to be to do them.' },
  { id: 'home', label: 'Home', tier: 'deep', prompt: 'Rank these by how much they make a place feel like home to you.' },
  { id: 'meaning', label: 'Meaning', tier: 'deep', prompt: 'Rank these by how much meaning you find in them.' },
  { id: 'getting_older', label: 'Getting Older', tier: 'deep', prompt: 'Rank these by how much you look forward to them as you age.' },
  { id: 'raising_kids', label: 'Raising Kids', tier: 'deep', prompt: 'Rank these by how important they would be for you to teach a kid.' },
  { id: 'work_meaning', label: 'Meaningful Work', tier: 'deep', prompt: 'Rank these by how much they would make a job worth doing for you.' },
  { id: 'second_chances', label: 'Second Chances', tier: 'deep', prompt: 'Rank these by how willing you would be to give someone another shot.' },
  { id: 'peace', label: 'Peace', tier: 'deep', prompt: 'Rank these by how much peace they bring you.' },

  // ----------------------------------------------------------------- MID (50)
  { id: 'pet_peeves', label: 'Pet Peeves', tier: 'mid', prompt: 'Rank these by how much they irritate you.' },
  { id: 'awkward_moments', label: 'Awkward Moments', tier: 'mid', prompt: 'Rank these by how much you would dread them happening to you.' },
  { id: 'texting', label: 'Texting', tier: 'mid', prompt: 'Rank these texting habits by how much they annoy you.' },
  { id: 'group_chats', label: 'Group Chats', tier: 'mid', prompt: 'Rank these group chat habits by how much they annoy you.' },
  { id: 'roommates', label: 'Roommates', tier: 'mid', prompt: 'Rank these roommate habits by how much they would bother you.' },
  { id: 'bad_habits', label: 'Bad Habits', tier: 'mid', prompt: 'Rank these by how hard they would be for you to quit.' },
  { id: 'procrastination', label: 'Procrastination', tier: 'mid', prompt: 'Rank these by how often you use them to avoid real work.' },
  { id: 'mornings', label: 'Mornings', tier: 'mid', prompt: 'Rank these by how essential they are to your morning.' },
  { id: 'nights', label: 'Winding Down', tier: 'mid', prompt: 'Rank these by how much they help you wind down at night.' },
  { id: 'guilty_pleasures', label: 'Guilty Pleasures', tier: 'mid', prompt: 'Rank these by how much you secretly enjoy them.' },
  { id: 'small_wins', label: 'Small Wins', tier: 'mid', prompt: 'Rank these by how much they would brighten your day.' },
  { id: 'first_dates', label: 'First Dates', tier: 'mid', prompt: 'Rank these by how nervous they would make you.' },
  { id: 'date_ideas', label: 'Date Ideas', tier: 'mid', prompt: 'Rank these by how good a date they would be for you.' },
  { id: 'at_a_party', label: 'At a Party', tier: 'mid', prompt: 'Rank these by how much they sound like you at a party.' },
  { id: 'travel_style', label: 'Travel Style', tier: 'mid', prompt: 'Rank these by how well they describe the way you travel.' },
  { id: 'airports', label: 'Airports', tier: 'mid', prompt: 'Rank these airport habits by how much they sound like you.' },
  { id: 'money', label: 'Money', tier: 'mid', prompt: 'Rank these by how happily you would spend your money on them.' },
  { id: 'splurging', label: 'Splurging', tier: 'mid', prompt: 'Rank these by how worth the extra money they are to you.' },
  { id: 'weekends', label: 'Weekends', tier: 'mid', prompt: 'Rank these by how much you would look forward to them.' },
  { id: 'free_hour', label: 'A Free Hour', tier: 'mid', prompt: 'Rank these by how much you would want to spend a free hour that way.' },
  { id: 'stress', label: 'Stress Relief', tier: 'mid', prompt: 'Rank these by how much they would calm you down.' },
  { id: 'rest', label: 'Rest', tier: 'mid', prompt: 'Rank these kinds of rest by how badly you have needed them lately.' },
  { id: 'how_you_work', label: 'How You Work', tier: 'mid', prompt: 'Rank these by how well they describe the way you work best.' },
  { id: 'working_from_home', label: 'Working From Home', tier: 'mid', prompt: 'Rank these by how much you would miss them at an office.' },
  { id: 'dream_jobs', label: 'Dream Jobs', tier: 'mid', prompt: 'Rank these jobs by how much you would love doing them.' },
  { id: 'things_to_learn', label: 'Things to Learn', tier: 'mid', prompt: 'Rank these skills by how badly you want to learn them.' },
  { id: 'talents', label: 'Talents', tier: 'mid', prompt: 'Rank these by how much you wish you could do them.' },
  { id: 'hobbies_at_70', label: 'Hobbies at 70', tier: 'mid', prompt: 'Rank these hobbies by how much you would enjoy them at seventy.' },
  { id: 'collecting', label: 'Collecting', tier: 'mid', prompt: 'Rank these by how much you would enjoy collecting them.' },
  { id: 'conversation', label: 'Conversation', tier: 'mid', prompt: 'Rank these topics by how long you could happily talk about them.' },
  { id: 'icebreakers', label: 'Icebreakers', tier: 'mid', prompt: 'Rank these questions by how much you would enjoy being asked them.' },
  { id: 'humor', label: 'Humor', tier: 'mid', prompt: 'Rank these kinds of humor by how hard they make you laugh.' },
  { id: 'excuses', label: 'Excuses', tier: 'mid', prompt: 'Rank these excuses by how likely you are to use one.' },
  { id: 'white_lies', label: 'White Lies', tier: 'mid', prompt: 'Rank these by how often you stretch the truth about them.' },
  { id: 'unwritten_rules', label: 'Unwritten Rules', tier: 'mid', prompt: 'Rank these unwritten rules by how strictly you follow them.' },
  { id: 'phone_habits', label: 'Phone Habits', tier: 'mid', prompt: 'Rank these phone habits by how much they sound like you.' },
  { id: 'rabbit_holes', label: 'Rabbit Holes', tier: 'mid', prompt: 'Rank these by how deep down the internet you would go on them.' },
  { id: 'binging', label: 'Binging', tier: 'mid', prompt: 'Rank these by how hard it is for you to stop once you start.' },
  { id: 'apps', label: 'Apps', tier: 'mid', prompt: 'Rank these apps by how lost you would be without them.' },
  { id: 'automation', label: 'Automation', tier: 'mid', prompt: 'Rank these by how gladly you would never do them yourself again.' },
  { id: 'chores', label: 'Chores', tier: 'mid', prompt: 'Rank these chores by how much you hate doing them.' },
  { id: 'minor_inconveniences', label: 'Minor Inconveniences', tier: 'mid', prompt: 'Rank these by how much they would ruin your day.' },
  { id: 'driving', label: 'Driving', tier: 'mid', prompt: 'Rank these driving habits by how much they sound like you.' },
  { id: 'eating_out', label: 'Eating Out', tier: 'mid', prompt: 'Rank these by how much they matter to you at a restaurant.' },
  { id: 'giving_gifts', label: 'Giving Gifts', tier: 'mid', prompt: 'Rank these gift-giving styles by how much they sound like you.' },
  { id: 'decisions', label: 'Decisions', tier: 'mid', prompt: 'Rank these by how well they describe the way you make decisions.' },
  { id: 'taking_compliments', label: 'Taking Compliments', tier: 'mid', prompt: 'Rank these by how awkward they would make you feel.' },
  { id: 'hotels', label: 'Hotels', tier: 'mid', prompt: 'Rank these hotel features by how much they matter to you.' },
  { id: 'road_trips', label: 'Road Trips', tier: 'mid', prompt: 'Rank these by how much they matter to you on a road trip.' },
  { id: 'planning', label: 'Planning a Trip', tier: 'mid', prompt: 'Rank these by how well they describe the way you plan a trip.' },

  // --------------------------------------------------------------- LIGHT (50)
  { id: 'foods', label: 'Foods', tier: 'light', prompt: 'Rank these foods from your all-time favorite to your least favorite.' },
  { id: 'cuisines', label: 'Cuisines', tier: 'light', prompt: 'Rank these cuisines from your favorite to your least favorite.' },
  { id: 'snacks', label: 'Snacks', tier: 'light', prompt: 'Rank these snacks from your favorite to your least favorite.' },
  { id: 'childhood_snacks', label: 'Childhood Snacks', tier: 'light', prompt: 'Rank these by how much you loved them as a kid.' },
  { id: 'desserts', label: 'Desserts', tier: 'light', prompt: 'Rank these desserts from your favorite to your least favorite.' },
  { id: 'breakfast', label: 'Breakfast', tier: 'light', prompt: 'Rank these breakfasts from your favorite to your least favorite.' },
  { id: 'pizza', label: 'Pizza Toppings', tier: 'light', prompt: 'Rank these pizza toppings from your favorite to your least favorite.' },
  { id: 'drinks', label: 'Drinks', tier: 'light', prompt: 'Rank these drinks from your favorite to your least favorite.' },
  { id: 'condiments', label: 'Condiments', tier: 'light', prompt: 'Rank these condiments from your favorite to your least favorite.' },
  { id: 'fast_food', label: 'Fast Food', tier: 'light', prompt: 'Rank these fast food orders from your favorite to your least favorite.' },
  { id: 'coffee', label: 'Coffee', tier: 'light', prompt: 'Rank these coffee orders from your favorite to your least favorite.' },
  { id: 'candy', label: 'Candy', tier: 'light', prompt: 'Rank these candies from your favorite to your least favorite.' },
  { id: 'comforts', label: 'Comforts', tier: 'light', prompt: 'Rank these by how much you would hate to lose them.' },
  { id: 'smells', label: 'Smells', tier: 'light', prompt: 'Rank these smells from the one you love most to the one you love least.' },
  { id: 'sounds', label: 'Sounds', tier: 'light', prompt: 'Rank these sounds from the one you find most satisfying to the most unpleasant.' },
  { id: 'weather', label: 'Weather', tier: 'light', prompt: 'Rank these kinds of weather from your favorite to your least favorite.' },
  { id: 'seasons', label: 'Seasons', tier: 'light', prompt: 'Rank these seasonal things by how much you look forward to them.' },
  { id: 'destinations', label: 'Destinations', tier: 'light', prompt: 'Rank these places by how badly you want to visit them.' },
  { id: 'vacations', label: 'Vacations', tier: 'light', prompt: 'Rank these kinds of trips from your favorite to your least favorite.' },
  { id: 'cities', label: 'Cities', tier: 'light', prompt: 'Rank these cities by how much you would want to live there.' },
  { id: 'animals', label: 'Animals', tier: 'light', prompt: 'Rank these animals by how much you would want to meet one.' },
  { id: 'pets', label: 'Pets', tier: 'light', prompt: 'Rank these pets by how much you would want to own one.' },
  { id: 'superpowers', label: 'Superpowers', tier: 'light', prompt: 'Rank these superpowers by how badly you would want them.' },
  { id: 'fictional_worlds', label: 'Fictional Worlds', tier: 'light', prompt: 'Rank these worlds by how much you would want to live in them.' },
  { id: 'movie_genres', label: 'Movie Genres', tier: 'light', prompt: 'Rank these movie genres from your favorite to your least favorite.' },
  { id: 'movie_night', label: 'Movie Night', tier: 'light', prompt: 'Rank these picks by how much you would want to watch one tonight.' },
  { id: 'music_genres', label: 'Music Genres', tier: 'light', prompt: 'Rank these music genres from your favorite to your least favorite.' },
  { id: 'live_music', label: 'Live Music', tier: 'light', prompt: 'Rank these concert moments by how much you love them.' },
  { id: 'karaoke', label: 'Karaoke', tier: 'light', prompt: 'Rank these by how likely you would be to sing one at karaoke.' },
  { id: 'game_night', label: 'Game Night', tier: 'light', prompt: 'Rank these games by how much you would want to play one tonight.' },
  { id: 'childhood_games', label: 'Childhood Games', tier: 'light', prompt: 'Rank these games by how much you would want to play them again.' },
  { id: 'nostalgia', label: 'Nostalgia', tier: 'light', prompt: 'Rank these childhood things by how much you miss them.' },
  { id: 'school_subjects', label: 'School Subjects', tier: 'light', prompt: 'Rank these subjects by how much you would enjoy taking them now.' },
  { id: 'holidays', label: 'Holidays', tier: 'light', prompt: 'Rank these holidays from your favorite to your least favorite.' },
  { id: 'holiday_traditions', label: 'Holiday Traditions', tier: 'light', prompt: 'Rank these traditions by how much you love them.' },
  { id: 'birthdays', label: 'Birthdays', tier: 'light', prompt: 'Rank these birthday plans by how much you would enjoy one.' },
  { id: 'style', label: 'Style', tier: 'light', prompt: 'Rank these looks by how confident they would make you feel.' },
  { id: 'shoes', label: 'Shoes', tier: 'light', prompt: 'Rank these shoes by how often you would actually wear them.' },
  { id: 'workouts', label: 'Workouts', tier: 'light', prompt: 'Rank these workouts by how much you would enjoy doing them.' },
  { id: 'sports', label: 'Sports', tier: 'light', prompt: 'Rank these sports by how much you enjoy watching them.' },
  { id: 'theme_parks', label: 'Theme Parks', tier: 'light', prompt: 'Rank these rides by how much you would want to go on one.' },
  { id: 'outdoors', label: 'Outdoors', tier: 'light', prompt: 'Rank these outdoor activities by how much you would enjoy them.' },
  { id: 'cooking', label: 'Cooking', tier: 'light', prompt: 'Rank these kitchen tasks by how much you enjoy doing them.' },
  { id: 'dinner_guests', label: 'Dinner Guests', tier: 'light', prompt: 'Rank these guests by how badly you would want one at your table.' },
  { id: 'time_travel', label: 'Time Travel', tier: 'light', prompt: 'Rank these eras by how badly you would want to visit them.' },
  { id: 'windfall', label: 'Ten Thousand Dollars', tier: 'light', prompt: 'Rank these by how much you would want to spend a surprise windfall on them.' },
  { id: 'talent_show', label: 'Talent Show', tier: 'light', prompt: 'Rank these acts by how willing you would be to perform one on stage.' },
  { id: 'last_meal', label: 'Last Meal', tier: 'light', prompt: 'Rank these dishes by how badly you would want one as your last meal.' },
  { id: 'dream_home', label: 'Dream Home', tier: 'light', prompt: 'Rank these home features by how much you would want one.' },
  { id: 'long_flight', label: 'Long Flight', tier: 'light', prompt: 'Rank these by how much they would help you survive a twelve-hour flight.' },
];

export default DECK_SPECS;
