export default {
    love_languages: [
        { id: "love_languages_01", text: "A long hug" },
        { id: "love_languages_02", text: "A love letter" },
        { id: "love_languages_03", text: "Cooking your favorite meal" },
        { id: "love_languages_04", text: "Saying I love you often" },
        { id: "love_languages_05", text: "Undivided attention" },
        { id: "love_languages_06", text: "A thoughtful gift" },
        { id: "love_languages_07", text: "Remembering small details" },
        { id: "love_languages_08", text: "Sitting quietly together" },
        { id: "love_languages_09", text: "Public praise" },
        { id: "love_languages_10", text: "A back rub" },
        { id: "love_languages_11", text: "Doing your chores" },
        { id: "love_languages_12", text: "Planning a surprise" },
        { id: "love_languages_13", text: "Checking in daily" },
        { id: "love_languages_14", text: "Sharing an inside joke" },
        { id: "love_languages_15", text: "Fixing something for you" },
        { id: "love_languages_16", text: "Deep eye contact" },
        { id: "love_languages_17", text: "A goodnight text" },
        { id: "love_languages_18", text: "Making you laugh" },
        { id: "love_languages_19", text: "Defending you to others" },
        { id: "love_languages_20", text: "Making time no matter what" },
        { id: "love_languages_21", text: "Learning what you love" },
        { id: "love_languages_22", text: "A slow dance" },
        { id: "love_languages_23", text: "Sharing food off their plate" },
        { id: "love_languages_24", text: "Saying you were right" },
        { id: "love_languages_25", text: "Showing up unannounced" },
    ],
    apologies: [
        { id: "apologies_01", text: "A written apology note" },
        { id: "apologies_02", text: "Saying I was wrong" },
        { id: "apologies_03", text: "Owning the specific hurt" },
        { id: "apologies_04", text: "Making things right" },
        { id: "apologies_05", text: "Flowers with a note" },
        { id: "apologies_06", text: "A tearful apology" },
        { id: "apologies_07", text: "Apologizing over dinner" },
        { id: "apologies_08", text: "Promising it won't happen again" },
        { id: "apologies_09", text: "Explaining their reasons" },
        { id: "apologies_10", text: "A long honest talk" },
        { id: "apologies_11", text: "A hug and honest words" },
        { id: "apologies_12", text: "Naming what will change" },
        { id: "apologies_13", text: "A make-up gift" },
        { id: "apologies_14", text: "Asking to earn trust back" },
        { id: "apologies_15", text: "Sitting with your anger" },
        { id: "apologies_16", text: "A quick my bad" },
        { id: "apologies_17", text: "Taking full blame" },
        { id: "apologies_18", text: "A voice memo apology" },
        { id: "apologies_19", text: "Apologizing again days later" },
        { id: "apologies_20", text: "Letting you vent first" },
        { id: "apologies_21", text: "Following through on a promise" },
        { id: "apologies_22", text: "A public apology" },
        { id: "apologies_23", text: "Saying sorry the next day" },
        { id: "apologies_24", text: "Bringing your favorite food" },
        { id: "apologies_25", text: "Asking what you need" },
    ],
    support: [
        { id: "support_01", text: "Just listening" },
        { id: "support_02", text: "Practical advice" },
        { id: "support_03", text: "A comforting hug" },
        { id: "support_04", text: "Making you laugh" },
        { id: "support_05", text: "Cooking you dinner" },
        { id: "support_06", text: "Sitting in silence together" },
        { id: "support_07", text: "Distracting you with a movie" },
        { id: "support_08", text: "A daily check-in text" },
        { id: "support_09", text: "Saying that sounds awful" },
        { id: "support_10", text: "Bringing over snacks" },
        { id: "support_11", text: "Helping with your to-do list" },
        { id: "support_12", text: "Sharing a similar story" },
        { id: "support_13", text: "Letting you cry it out" },
        { id: "support_14", text: "Reminding you of your strengths" },
        { id: "support_15", text: "Coming over unannounced" },
        { id: "support_16", text: "Taking you for a walk" },
        { id: "support_17", text: "Handling logistics for you" },
        { id: "support_18", text: "A thoughtful care package" },
        { id: "support_19", text: "Advocating for you elsewhere" },
        { id: "support_20", text: "Offering their spare room" },
        { id: "support_21", text: "Driving you somewhere quiet" },
        { id: "support_22", text: "Reading up on what you face" },
        { id: "support_23", text: "Checking on you weeks later" },
        { id: "support_24", text: "Sending a long voice memo" },
        { id: "support_25", text: "Telling you it will be okay" },
    ],
    when_upset: [
        { id: "when_upset_01", text: "Space and quiet" },
        { id: "when_upset_02", text: "A long hug" },
        { id: "when_upset_03", text: "Being asked what you need" },
        { id: "when_upset_04", text: "Someone just listening" },
        { id: "when_upset_05", text: "Practical solutions" },
        { id: "when_upset_06", text: "A good distraction" },
        { id: "when_upset_07", text: "Tough love" },
        { id: "when_upset_08", text: "Validation of your feelings" },
        { id: "when_upset_09", text: "Silly jokes" },
        { id: "when_upset_10", text: "A shoulder to cry on" },
        { id: "when_upset_11", text: "Being left alone" },
        { id: "when_upset_12", text: "A calm presence" },
        { id: "when_upset_13", text: "Someone taking your side" },
        { id: "when_upset_14", text: "Honest pushback" },
        { id: "when_upset_15", text: "A warm meal" },
        { id: "when_upset_16", text: "A cup of tea" },
        { id: "when_upset_17", text: "A pep talk" },
        { id: "when_upset_18", text: "A hand on your back" },
        { id: "when_upset_19", text: "Being told it will pass" },
        { id: "when_upset_20", text: "Company without talking" },
        { id: "when_upset_21", text: "A funny video" },
        { id: "when_upset_22", text: "Being checked on later" },
        { id: "when_upset_23", text: "Reassurance you're right" },
        { id: "when_upset_24", text: "An honest opinion" },
        { id: "when_upset_25", text: "A change of scenery" },
    ],
    values: [
        { id: "values_01", text: "Devotion" },
        { id: "values_02", text: "Truthfulness" },
        { id: "values_03", text: "Drive" },
        { id: "values_04", text: "Compassion" },
        { id: "values_05", text: "Autonomy" },
        { id: "values_06", text: "Family" },
        { id: "values_07", text: "Self-control" },
        { id: "values_08", text: "Originality" },
        { id: "values_09", text: "Adventure" },
        { id: "values_10", text: "Optimism" },
        { id: "values_11", text: "Open-mindedness" },
        { id: "values_12", text: "Wealth" },
        { id: "values_13", text: "Fairness" },
        { id: "values_14", text: "Generosity" },
        { id: "values_15", text: "Freedom" },
        { id: "values_16", text: "Tradition" },
        { id: "values_17", text: "Excellence" },
        { id: "values_18", text: "Serenity" },
        { id: "values_19", text: "Fun" },
        { id: "values_20", text: "Humility" },
        { id: "values_21", text: "Bravery" },
        { id: "values_22", text: "Insight" },
        { id: "values_23", text: "Dependability" },
        { id: "values_24", text: "Growth" },
        { id: "values_25", text: "Self-respect" },
    ],
    pride: [
        { id: "pride_01", text: "Raised a happy kid" },
        { id: "pride_02", text: "Started a business" },
        { id: "pride_03", text: "Written a book" },
        { id: "pride_04", text: "Run a marathon" },
        { id: "pride_05", text: "Bought a house" },
        { id: "pride_06", text: "Learned a new language" },
        { id: "pride_07", text: "Given a great speech" },
        { id: "pride_08", text: "Made a stranger's day" },
        { id: "pride_09", text: "Traveled solo abroad" },
        { id: "pride_10", text: "Been on live TV" },
        { id: "pride_11", text: "Won an award at work" },
        { id: "pride_12", text: "Made a lot of money" },
        { id: "pride_13", text: "Built something with your hands" },
        { id: "pride_14", text: "Forgiven someone hard to forgive" },
        { id: "pride_15", text: "Left a job with grace" },
        { id: "pride_16", text: "Stood up to a bully" },
        { id: "pride_17", text: "Kept a lifelong friend" },
        { id: "pride_18", text: "Mastered an instrument" },
        { id: "pride_19", text: "Quit a bad habit" },
        { id: "pride_20", text: "Learned to cook well" },
        { id: "pride_21", text: "Held a difficult secret" },
        { id: "pride_22", text: "Adopted a pet" },
        { id: "pride_23", text: "Repaired a family rift" },
        { id: "pride_24", text: "Started over from scratch" },
        { id: "pride_25", text: "Told a hard truth" },
    ],
    fears: [
        { id: "fears_01", text: "Speaking to a crowd" },
        { id: "fears_02", text: "Heights" },
        { id: "fears_03", text: "Spiders" },
        { id: "fears_04", text: "Deep water" },
        { id: "fears_05", text: "Flying" },
        { id: "fears_06", text: "Being forgotten" },
        { id: "fears_07", text: "Failure" },
        { id: "fears_08", text: "Loneliness" },
        { id: "fears_09", text: "The dark" },
        { id: "fears_10", text: "Needles" },
        { id: "fears_11", text: "Not mattering" },
        { id: "fears_12", text: "Getting old" },
        { id: "fears_13", text: "Losing your mind" },
        { id: "fears_14", text: "Being broke" },
        { id: "fears_15", text: "Change" },
        { id: "fears_16", text: "Confrontation" },
        { id: "fears_17", text: "Small spaces" },
        { id: "fears_18", text: "Judgment from others" },
        { id: "fears_19", text: "Wasting your life" },
        { id: "fears_20", text: "Not being loved" },
        { id: "fears_21", text: "Losing your looks" },
        { id: "fears_22", text: "Being wrong in public" },
        { id: "fears_23", text: "Boredom" },
        { id: "fears_24", text: "Regret" },
        { id: "fears_25", text: "Losing control" },
    ],
    regrets: [
        { id: "regrets_01", text: "Traveling the world" },
        { id: "regrets_02", text: "Learning a language" },
        { id: "regrets_03", text: "Writing a book" },
        { id: "regrets_04", text: "Starting your own business" },
        { id: "regrets_05", text: "Living abroad" },
        { id: "regrets_06", text: "Falling deeply in love" },
        { id: "regrets_07", text: "Having kids" },
        { id: "regrets_08", text: "Reconnecting with an old friend" },
        { id: "regrets_09", text: "Learning an instrument" },
        { id: "regrets_10", text: "Making a lot of money" },
        { id: "regrets_11", text: "Standing up to your boss" },
        { id: "regrets_12", text: "Telling someone how you felt" },
        { id: "regrets_13", text: "Trying stand-up comedy" },
        { id: "regrets_14", text: "Running a marathon" },
        { id: "regrets_15", text: "Getting in great shape" },
        { id: "regrets_16", text: "Buying your dream home" },
        { id: "regrets_17", text: "Making peace with family" },
        { id: "regrets_18", text: "Going to therapy" },
        { id: "regrets_19", text: "Chasing a wild dream" },
        { id: "regrets_20", text: "Taking a big risk" },
        { id: "regrets_21", text: "Saying no more often" },
        { id: "regrets_22", text: "Slowing down sooner" },
        { id: "regrets_23", text: "Being more present" },
        { id: "regrets_24", text: "Making close friends later" },
        { id: "regrets_25", text: "Forgiving yourself" },
    ],
    what_gets_you: [
        { id: "what_gets_you_01", text: "A dog reunion video" },
        { id: "what_gets_you_02", text: "The national anthem" },
        { id: "what_gets_you_03", text: "Wedding vows" },
        { id: "what_gets_you_04", text: "A father-daughter dance" },
        { id: "what_gets_you_05", text: "A soldier coming home" },
        { id: "what_gets_you_06", text: "A pet dying in a movie" },
        { id: "what_gets_you_07", text: "Sad music" },
        { id: "what_gets_you_08", text: "A kid's speech" },
        { id: "what_gets_you_09", text: "Old home videos" },
        { id: "what_gets_you_10", text: "A friend's big win" },
        { id: "what_gets_you_11", text: "Movie endings" },
        { id: "what_gets_you_12", text: "A stranger's kindness" },
        { id: "what_gets_you_13", text: "Watching someone propose" },
        { id: "what_gets_you_14", text: "A heartfelt eulogy" },
        { id: "what_gets_you_15", text: "A choir singing together" },
        { id: "what_gets_you_16", text: "A grandparent's advice" },
        { id: "what_gets_you_17", text: "A perfect sunset" },
        { id: "what_gets_you_18", text: "Reading old letters" },
        { id: "what_gets_you_19", text: "Seeing a parent cry" },
        { id: "what_gets_you_20", text: "A team's underdog win" },
        { id: "what_gets_you_21", text: "Someone singing at open mic" },
        { id: "what_gets_you_22", text: "A first steps video" },
        { id: "what_gets_you_23", text: "Long-lost friends reuniting" },
        { id: "what_gets_you_24", text: "A really honest apology" },
        { id: "what_gets_you_25", text: "A song from your childhood" },
    ],
    trust: [
        { id: "trust_01", text: "Reading your texts" },
        { id: "trust_02", text: "Lying about small things" },
        { id: "trust_03", text: "Sharing a secret you told them" },
        { id: "trust_04", text: "Talking behind your back" },
        { id: "trust_05", text: "Flirting with your partner" },
        { id: "trust_06", text: "Forgetting an important day" },
        { id: "trust_07", text: "Breaking a promise" },
        { id: "trust_08", text: "Making a big decision without you" },
        { id: "trust_09", text: "Borrowing money and not repaying" },
        { id: "trust_10", text: "Canceling last minute a lot" },
        { id: "trust_11", text: "Snooping through your things" },
        { id: "trust_12", text: "Trashing you to your family" },
        { id: "trust_13", text: "Taking credit for your work" },
        { id: "trust_14", text: "Ghosting after a fight" },
        { id: "trust_15", text: "Faking an excuse" },
        { id: "trust_16", text: "Being late every time" },
        { id: "trust_17", text: "Not defending you in public" },
        { id: "trust_18", text: "Airing your business online" },
        { id: "trust_19", text: "Bringing up your past in a fight" },
        { id: "trust_20", text: "Half-listening when you vent" },
        { id: "trust_21", text: "Making plans and forgetting" },
        { id: "trust_22", text: "Bailing on a big moment" },
        { id: "trust_23", text: "Rolling their eyes at you" },
        { id: "trust_24", text: "Copying your style constantly" },
        { id: "trust_25", text: "Hiding a small purchase" },
    ],
    forgiveness: [
        { id: "forgiveness_01", text: "A one-time lie" },
        { id: "forgiveness_02", text: "A drunken insult" },
        { id: "forgiveness_03", text: "An emotional betrayal" },
        { id: "forgiveness_04", text: "Missing your big day" },
        { id: "forgiveness_05", text: "Ghosting for months" },
        { id: "forgiveness_06", text: "Trashing you to a friend" },
        { id: "forgiveness_07", text: "Forgetting your birthday" },
        { id: "forgiveness_08", text: "Losing something you loaned" },
        { id: "forgiveness_09", text: "Choosing someone else's side" },
        { id: "forgiveness_10", text: "A public embarrassment" },
        { id: "forgiveness_11", text: "Breaking your favorite thing" },
        { id: "forgiveness_12", text: "Repeating a mistake" },
        { id: "forgiveness_13", text: "A cruel joke at your expense" },
        { id: "forgiveness_14", text: "Blowing up over nothing" },
        { id: "forgiveness_15", text: "Not showing up when needed" },
        { id: "forgiveness_16", text: "A comment about your body" },
        { id: "forgiveness_17", text: "Selling out a mutual friend" },
        { id: "forgiveness_18", text: "Denying something you saw" },
        { id: "forgiveness_19", text: "Copying your big idea" },
        { id: "forgiveness_20", text: "Backing out of a promise" },
        { id: "forgiveness_21", text: "A dangerous prank" },
        { id: "forgiveness_22", text: "Judging your parenting" },
        { id: "forgiveness_23", text: "Making fun of your dream" },
        { id: "forgiveness_24", text: "Never saying sorry" },
        { id: "forgiveness_25", text: "Spilling your secret to family" },
    ],
    self_worth: [
        { id: "self_worth_01", text: "Praise from your boss" },
        { id: "self_worth_02", text: "A great outfit day" },
        { id: "self_worth_03", text: "Finishing a hard workout" },
        { id: "self_worth_04", text: "Being told you're kind" },
        { id: "self_worth_05", text: "A friend confiding in you" },
        { id: "self_worth_06", text: "Making someone laugh" },
        { id: "self_worth_07", text: "A compliment on your looks" },
        { id: "self_worth_08", text: "Nailing something at work" },
        { id: "self_worth_09", text: "Cooking a great meal" },
        { id: "self_worth_10", text: "Helping a stranger" },
        { id: "self_worth_11", text: "Learning something new" },
        { id: "self_worth_12", text: "A parent's approval" },
        { id: "self_worth_13", text: "Being asked for advice" },
        { id: "self_worth_14", text: "Standing up for yourself" },
        { id: "self_worth_15", text: "Winning an argument" },
        { id: "self_worth_16", text: "A text out of the blue" },
        { id: "self_worth_17", text: "Being told you're missed" },
        { id: "self_worth_18", text: "Keeping a promise to yourself" },
        { id: "self_worth_19", text: "A good hair day" },
        { id: "self_worth_20", text: "Being invited to something" },
        { id: "self_worth_21", text: "Someone remembering a detail" },
        { id: "self_worth_22", text: "Finishing a big project" },
        { id: "self_worth_23", text: "Being chosen first" },
        { id: "self_worth_24", text: "A stranger flirting with you" },
        { id: "self_worth_25", text: "Reading a great book" },
    ],
    legacy: [
        { id: "legacy_01", text: "As kind" },
        { id: "legacy_02", text: "As brilliant" },
        { id: "legacy_03", text: "As funny" },
        { id: "legacy_04", text: "As loyal" },
        { id: "legacy_05", text: "As honest" },
        { id: "legacy_06", text: "As successful" },
        { id: "legacy_07", text: "As a great parent" },
        { id: "legacy_08", text: "As wise" },
        { id: "legacy_09", text: "As brave" },
        { id: "legacy_10", text: "As creative" },
        { id: "legacy_11", text: "As hardworking" },
        { id: "legacy_12", text: "As generous" },
        { id: "legacy_13", text: "As fun to be around" },
        { id: "legacy_14", text: "As a great friend" },
        { id: "legacy_15", text: "As a great partner" },
        { id: "legacy_16", text: "As a fighter" },
        { id: "legacy_17", text: "As humble" },
        { id: "legacy_18", text: "As stylish" },
        { id: "legacy_19", text: "As a mentor" },
        { id: "legacy_20", text: "As tough" },
        { id: "legacy_21", text: "As adventurous" },
        { id: "legacy_22", text: "As calm under pressure" },
        { id: "legacy_23", text: "As deeply loved" },
        { id: "legacy_24", text: "As one of a kind" },
        { id: "legacy_25", text: "As a good listener" },
    ],
    hard_talks: [
        { id: "hard_talks_01", text: "Asking for a raise" },
        { id: "hard_talks_02", text: "Telling a friend they hurt you" },
        { id: "hard_talks_03", text: "Ending a friendship" },
        { id: "hard_talks_04", text: "Breaking up with someone" },
        { id: "hard_talks_05", text: "Telling parents bad news" },
        { id: "hard_talks_06", text: "Confronting a family member" },
        { id: "hard_talks_07", text: "Giving tough feedback at work" },
        { id: "hard_talks_08", text: "Saying no to a favor" },
        { id: "hard_talks_09", text: "Asking for help" },
        { id: "hard_talks_10", text: "Telling someone they smell" },
        { id: "hard_talks_11", text: "Sharing something personal" },
        { id: "hard_talks_12", text: "Talking money with a partner" },
        { id: "hard_talks_13", text: "Setting a boundary" },
        { id: "hard_talks_14", text: "Admitting you were wrong" },
        { id: "hard_talks_15", text: "Telling a friend to get help" },
        { id: "hard_talks_16", text: "Asking a partner to change" },
        { id: "hard_talks_17", text: "Discussing your will" },
        { id: "hard_talks_18", text: "Explaining a mistake at work" },
        { id: "hard_talks_19", text: "Asking someone out" },
        { id: "hard_talks_20", text: "Talking past relationships" },
        { id: "hard_talks_21", text: "Telling family you're moving" },
        { id: "hard_talks_22", text: "Naming an awkward vibe" },
        { id: "hard_talks_23", text: "Bringing up a taboo topic" },
        { id: "hard_talks_24", text: "Renegotiating a promise" },
        { id: "hard_talks_25", text: "Telling someone you love them" },
    ],
    in_a_friend: [
        { id: "in_a_friend_01", text: "Ride-or-die energy" },
        { id: "in_a_friend_02", text: "A shared sense of humor" },
        { id: "in_a_friend_03", text: "Deep honesty" },
        { id: "in_a_friend_04", text: "Being dependable" },
        { id: "in_a_friend_05", text: "Drive to grow" },
        { id: "in_a_friend_06", text: "Shared interests" },
        { id: "in_a_friend_07", text: "Emotional depth" },
        { id: "in_a_friend_08", text: "Easy silence" },
        { id: "in_a_friend_09", text: "Adventurous spirit" },
        { id: "in_a_friend_10", text: "Similar values" },
        { id: "in_a_friend_11", text: "Great advice" },
        { id: "in_a_friend_12", text: "Being fun" },
        { id: "in_a_friend_13", text: "Remembering little things" },
        { id: "in_a_friend_14", text: "Making time for you" },
        { id: "in_a_friend_15", text: "Being drama-free" },
        { id: "in_a_friend_16", text: "Being a good listener" },
        { id: "in_a_friend_17", text: "A sharp mind" },
        { id: "in_a_friend_18", text: "Kindness to others" },
        { id: "in_a_friend_19", text: "A cheerful energy" },
        { id: "in_a_friend_20", text: "Similar life stage" },
        { id: "in_a_friend_21", text: "Championing your wins" },
        { id: "in_a_friend_22", text: "Showing up in a crisis" },
        { id: "in_a_friend_23", text: "Long history together" },
        { id: "in_a_friend_24", text: "Never judging you" },
        { id: "in_a_friend_25", text: "Total discretion" },
    ],
};
