export default {
  animals: [
    { id: 'animals_01', text: 'Elephant' },
    { id: 'animals_02', text: 'Dolphin' },
    { id: 'animals_03', text: 'Tiger' },
    { id: 'animals_04', text: 'Panda' },
    { id: 'animals_05', text: 'Sloth' },
    { id: 'animals_06', text: 'Koala' },
    { id: 'animals_07', text: 'Octopus' },
    { id: 'animals_08', text: 'Kangaroo' },
    { id: 'animals_09', text: 'Penguin' },
    { id: 'animals_10', text: 'Otter' },
    { id: 'animals_11', text: 'Wolf' },
    { id: 'animals_12', text: 'Grizzly bear' },
    { id: 'animals_13', text: 'Giraffe' },
    { id: 'animals_14', text: 'Great white shark' },
    { id: 'animals_15', text: 'Owl' },
    { id: 'animals_16', text: 'Blue whale' },
    { id: 'animals_17', text: 'Gorilla' },
    { id: 'animals_18', text: 'Cheetah' },
    { id: 'animals_19', text: 'Fox' },
    { id: 'animals_20', text: 'Bald eagle' },
    { id: 'animals_21', text: 'Hippo' },
    { id: 'animals_22', text: 'Chimpanzee' },
    { id: 'animals_23', text: 'Lemur' },
    { id: 'animals_24', text: 'Red panda' },
    { id: 'animals_25', text: 'Moose' },
  ],
  pets: [
    { id: 'pets_01', text: 'Dog' },
    { id: 'pets_02', text: 'Cat' },
    { id: 'pets_03', text: 'Rabbit' },
    { id: 'pets_04', text: 'Hamster' },
    { id: 'pets_05', text: 'Goldfish' },
    { id: 'pets_06', text: 'Parrot' },
    { id: 'pets_07', text: 'Snake' },
    { id: 'pets_08', text: 'Turtle' },
    { id: 'pets_09', text: 'Guinea pig' },
    { id: 'pets_10', text: 'Ferret' },
    { id: 'pets_11', text: 'Chinchilla' },
    { id: 'pets_12', text: 'Tarantula' },
    { id: 'pets_13', text: 'Bearded dragon' },
    { id: 'pets_14', text: 'Hedgehog' },
    { id: 'pets_15', text: 'Iguana' },
    { id: 'pets_16', text: 'Chicken' },
    { id: 'pets_17', text: 'Mini pig' },
    { id: 'pets_18', text: 'Cockatiel' },
    { id: 'pets_19', text: 'Axolotl' },
    { id: 'pets_20', text: 'Pet rat' },
    { id: 'pets_21', text: 'Gecko' },
    { id: 'pets_22', text: 'Pony' },
    { id: 'pets_23', text: 'Tree frog' },
    { id: 'pets_24', text: 'Betta fish' },
    { id: 'pets_25', text: 'Sugar glider' },
  ],
  superpowers: [
    { id: 'superpowers_01', text: 'Flight' },
    { id: 'superpowers_02', text: 'Invisibility' },
    { id: 'superpowers_03', text: 'Time travel' },
    { id: 'superpowers_04', text: 'Mind reading' },
    { id: 'superpowers_05', text: 'Teleportation' },
    { id: 'superpowers_06', text: 'Super strength' },
    { id: 'superpowers_07', text: 'Super speed' },
    { id: 'superpowers_08', text: 'Shapeshifting' },
    { id: 'superpowers_09', text: 'Talking to animals' },
    { id: 'superpowers_10', text: 'Immortality' },
    { id: 'superpowers_11', text: 'Healing others' },
    { id: 'superpowers_12', text: 'Controlling weather' },
    { id: 'superpowers_13', text: 'Telekinesis' },
    { id: 'superpowers_14', text: 'X-ray vision' },
    { id: 'superpowers_15', text: 'Freezing time' },
    { id: 'superpowers_16', text: 'Breathing underwater' },
    { id: 'superpowers_17', text: 'Force fields' },
    { id: 'superpowers_18', text: 'Perfect memory' },
    { id: 'superpowers_19', text: 'Speaking every language' },
    { id: 'superpowers_20', text: 'Seeing the future' },
    { id: 'superpowers_21', text: 'Duplicating yourself' },
    { id: 'superpowers_22', text: 'Never needing sleep' },
    { id: 'superpowers_23', text: 'Summoning any object' },
    { id: 'superpowers_24', text: 'Controlling fire' },
    { id: 'superpowers_25', text: 'Walking through walls' },
  ],
  fictional_worlds: [
    { id: 'fictional_worlds_01', text: 'Hogwarts' },
    { id: 'fictional_worlds_02', text: 'Middle-earth' },
    { id: 'fictional_worlds_03', text: 'Narnia' },
    { id: 'fictional_worlds_04', text: 'The Star Wars galaxy' },
    { id: 'fictional_worlds_05', text: 'The Star Trek Federation' },
    { id: 'fictional_worlds_06', text: 'The Marvel universe' },
    { id: 'fictional_worlds_07', text: 'Westeros' },
    { id: 'fictional_worlds_08', text: 'The Shire' },
    { id: 'fictional_worlds_09', text: 'Pandora (Avatar)' },
    { id: 'fictional_worlds_10', text: 'Wakanda' },
    { id: 'fictional_worlds_11', text: 'Hyrule' },
    { id: 'fictional_worlds_12', text: 'The Mushroom Kingdom' },
    { id: 'fictional_worlds_13', text: 'The Pokemon world' },
    { id: 'fictional_worlds_14', text: 'Hundred Acre Wood' },
    { id: 'fictional_worlds_15', text: 'Neverland' },
    { id: 'fictional_worlds_16', text: 'Wonderland' },
    { id: 'fictional_worlds_17', text: 'The Land of Oz' },
    { id: 'fictional_worlds_18', text: 'The Matrix' },
    { id: 'fictional_worlds_19', text: 'Gotham City' },
    { id: 'fictional_worlds_20', text: 'Bikini Bottom' },
    { id: 'fictional_worlds_21', text: 'Stardew Valley' },
    { id: 'fictional_worlds_22', text: 'Rivendell' },
    { id: 'fictional_worlds_23', text: 'Panem' },
    { id: 'fictional_worlds_24', text: 'Tatooine' },
    { id: 'fictional_worlds_25', text: 'Springfield' },
  ],
  movie_genres: [
    { id: 'movie_genres_01', text: 'Action' },
    { id: 'movie_genres_02', text: 'Comedy' },
    { id: 'movie_genres_03', text: 'Romantic comedy' },
    { id: 'movie_genres_04', text: 'Horror' },
    { id: 'movie_genres_05', text: 'Sci-fi' },
    { id: 'movie_genres_06', text: 'Fantasy' },
    { id: 'movie_genres_07', text: 'Thriller' },
    { id: 'movie_genres_08', text: 'Drama' },
    { id: 'movie_genres_09', text: 'Documentary' },
    { id: 'movie_genres_10', text: 'Animation' },
    { id: 'movie_genres_11', text: 'Musical' },
    { id: 'movie_genres_12', text: 'Mystery' },
    { id: 'movie_genres_13', text: 'Western' },
    { id: 'movie_genres_14', text: 'Superhero' },
    { id: 'movie_genres_15', text: 'Historical epic' },
    { id: 'movie_genres_16', text: 'Crime' },
    { id: 'movie_genres_17', text: 'Indie' },
    { id: 'movie_genres_18', text: 'Coming-of-age' },
    { id: 'movie_genres_19', text: 'Slasher' },
    { id: 'movie_genres_20', text: 'Mockumentary' },
    { id: 'movie_genres_21', text: 'Heist' },
    { id: 'movie_genres_22', text: 'War' },
    { id: 'movie_genres_23', text: 'Foreign film' },
    { id: 'movie_genres_24', text: 'Family film' },
    { id: 'movie_genres_25', text: 'Biopic' },
  ],
  movie_night: [
    { id: 'movie_night_01', text: 'A comfort rewatch' },
    { id: 'movie_night_02', text: 'A three-hour epic' },
    { id: 'movie_night_03', text: 'A goofy comedy' },
    { id: 'movie_night_04', text: 'A big tearjerker' },
    { id: 'movie_night_05', text: 'A tense thriller' },
    { id: 'movie_night_06', text: 'A cheesy rom-com' },
    { id: 'movie_night_07', text: 'A scary horror movie' },
    { id: 'movie_night_08', text: 'A brainy sci-fi' },
    { id: 'movie_night_09', text: 'A stylish action flick' },
    { id: 'movie_night_10', text: 'A slow indie film' },
    { id: 'movie_night_11', text: 'A wholesome family movie' },
    { id: 'movie_night_12', text: 'A gritty crime drama' },
    { id: 'movie_night_13', text: 'A cult classic' },
    { id: 'movie_night_14', text: 'A splashy musical' },
    { id: 'movie_night_15', text: 'A mind-bending mystery' },
    { id: 'movie_night_16', text: 'A nature documentary' },
    { id: 'movie_night_17', text: 'A superhero blockbuster' },
    { id: 'movie_night_18', text: 'A foreign film with subtitles' },
    { id: 'movie_night_19', text: 'A dark true-crime doc' },
    { id: 'movie_night_20', text: 'An animated adventure' },
    { id: 'movie_night_21', text: 'A charming coming-of-age' },
    { id: 'movie_night_22', text: 'A campy B-movie' },
    { id: 'movie_night_23', text: 'A holiday classic' },
    { id: 'movie_night_24', text: 'A slick heist flick' },
    { id: 'movie_night_25', text: 'A quiet drama' },
  ],
  music_genres: [
    { id: 'music_genres_01', text: 'Pop' },
    { id: 'music_genres_02', text: 'Rock' },
    { id: 'music_genres_03', text: 'Hip-hop' },
    { id: 'music_genres_04', text: 'R&B' },
    { id: 'music_genres_05', text: 'Country' },
    { id: 'music_genres_06', text: 'Jazz' },
    { id: 'music_genres_07', text: 'Classical' },
    { id: 'music_genres_08', text: 'Electronic' },
    { id: 'music_genres_09', text: 'Indie rock' },
    { id: 'music_genres_10', text: 'Metal' },
    { id: 'music_genres_11', text: 'Folk' },
    { id: 'music_genres_12', text: 'Punk' },
    { id: 'music_genres_13', text: 'Reggae' },
    { id: 'music_genres_14', text: 'Blues' },
    { id: 'music_genres_15', text: 'Soul' },
    { id: 'music_genres_16', text: 'Funk' },
    { id: 'music_genres_17', text: 'K-pop' },
    { id: 'music_genres_18', text: 'Latin' },
    { id: 'music_genres_19', text: 'Disco' },
    { id: 'music_genres_20', text: 'House' },
    { id: 'music_genres_21', text: 'Techno' },
    { id: 'music_genres_22', text: 'Musical theater' },
    { id: 'music_genres_23', text: 'Bluegrass' },
    { id: 'music_genres_24', text: 'Gospel' },
    { id: 'music_genres_25', text: 'Ambient' },
  ],
  live_music: [
    { id: 'live_music_01', text: 'The opening song' },
    { id: 'live_music_02', text: 'A killer guitar solo' },
    { id: 'live_music_03', text: 'Singing along to a chorus' },
    { id: 'live_music_04', text: 'A slow ballad, lighters up' },
    { id: 'live_music_05', text: 'The encore' },
    { id: 'live_music_06', text: 'A surprise cover' },
    { id: 'live_music_07', text: 'Meeting the band' },
    { id: 'live_music_08', text: 'The bass drop' },
    { id: 'live_music_09', text: 'Crowd surfing' },
    { id: 'live_music_10', text: 'A mosh pit' },
    { id: 'live_music_11', text: 'The pre-show wait' },
    { id: 'live_music_12', text: 'Getting front row' },
    { id: 'live_music_13', text: 'Buying a tour shirt' },
    { id: 'live_music_14', text: 'A big pyro moment' },
    { id: 'live_music_15', text: 'The final bow' },
    { id: 'live_music_16', text: 'A quiet acoustic set' },
    { id: 'live_music_17', text: 'Dancing with strangers' },
    { id: 'live_music_18', text: 'The lights going down' },
    { id: 'live_music_19', text: 'A surprise guest artist' },
    { id: 'live_music_20', text: 'A drum solo' },
    { id: 'live_music_21', text: 'Confetti raining down' },
    { id: 'live_music_22', text: 'Chanting for an encore' },
    { id: 'live_music_23', text: 'Hearing your favorite song' },
    { id: 'live_music_24', text: 'Filming a clip on your phone' },
    { id: 'live_music_25', text: 'Meeting fans in line' },
  ],
  karaoke: [
    { id: 'karaoke_01', text: 'Bohemian Rhapsody' },
    { id: 'karaoke_02', text: "Don't Stop Believin'" },
    { id: 'karaoke_03', text: 'Sweet Caroline' },
    { id: 'karaoke_04', text: "Livin' on a Prayer" },
    { id: 'karaoke_05', text: 'Wonderwall' },
    { id: 'karaoke_06', text: 'Mr. Brightside' },
    { id: 'karaoke_07', text: 'I Will Survive' },
    { id: 'karaoke_08', text: 'Piano Man' },
    { id: 'karaoke_09', text: 'Total Eclipse of the Heart' },
    { id: 'karaoke_10', text: 'Africa' },
    { id: 'karaoke_11', text: 'Ice Ice Baby' },
    { id: 'karaoke_12', text: 'Baby Got Back' },
    { id: 'karaoke_13', text: 'Shallow' },
    { id: 'karaoke_14', text: 'Someone Like You' },
    { id: 'karaoke_15', text: 'Let It Go' },
    { id: 'karaoke_16', text: "Sweet Child O' Mine" },
    { id: 'karaoke_17', text: 'Take On Me' },
    { id: 'karaoke_18', text: 'Dancing Queen' },
    { id: 'karaoke_19', text: 'Uptown Funk' },
    { id: 'karaoke_20', text: 'Barbie Girl' },
    { id: 'karaoke_21', text: 'My Heart Will Go On' },
    { id: 'karaoke_22', text: 'Since U Been Gone' },
    { id: 'karaoke_23', text: 'Rolling in the Deep' },
    { id: 'karaoke_24', text: 'Tiny Dancer' },
    { id: 'karaoke_25', text: 'Livin La Vida Loca' },
  ],
  game_night: [
    { id: 'game_night_01', text: 'Poker' },
    { id: 'game_night_02', text: 'Charades' },
    { id: 'game_night_03', text: 'Monopoly' },
    { id: 'game_night_04', text: 'Scrabble' },
    { id: 'game_night_05', text: 'Chess' },
    { id: 'game_night_06', text: 'Risk' },
    { id: 'game_night_07', text: 'Catan' },
    { id: 'game_night_08', text: 'Codenames' },
    { id: 'game_night_09', text: 'Pictionary' },
    { id: 'game_night_10', text: 'Uno' },
    { id: 'game_night_11', text: 'Cards Against Humanity' },
    { id: 'game_night_12', text: 'Trivial Pursuit' },
    { id: 'game_night_13', text: 'Clue' },
    { id: 'game_night_14', text: 'Ticket to Ride' },
    { id: 'game_night_15', text: 'Bananagrams' },
    { id: 'game_night_16', text: 'Jenga' },
    { id: 'game_night_17', text: 'Twister' },
    { id: 'game_night_18', text: 'Werewolf' },
    { id: 'game_night_19', text: 'Backgammon' },
    { id: 'game_night_20', text: 'Mahjong' },
    { id: 'game_night_21', text: 'Yahtzee' },
    { id: 'game_night_22', text: 'Battleship' },
    { id: 'game_night_23', text: 'Boggle' },
    { id: 'game_night_24', text: 'Dominoes' },
    { id: 'game_night_25', text: 'Rummikub' },
  ],
  childhood_games: [
    { id: 'childhood_games_01', text: 'Tag' },
    { id: 'childhood_games_02', text: 'Hide and seek' },
    { id: 'childhood_games_03', text: 'Freeze tag' },
    { id: 'childhood_games_04', text: 'Red rover' },
    { id: 'childhood_games_05', text: 'Duck, duck, goose' },
    { id: 'childhood_games_06', text: 'Simon says' },
    { id: 'childhood_games_07', text: 'Musical chairs' },
    { id: 'childhood_games_08', text: 'Four square' },
    { id: 'childhood_games_09', text: 'Kickball' },
    { id: 'childhood_games_10', text: 'Dodgeball' },
    { id: 'childhood_games_11', text: 'Marco Polo' },
    { id: 'childhood_games_12', text: 'Sharks and minnows' },
    { id: 'childhood_games_13', text: 'Capture the flag' },
    { id: 'childhood_games_14', text: 'Red light, green light' },
    { id: 'childhood_games_15', text: 'Hopscotch' },
    { id: 'childhood_games_16', text: 'Jump rope' },
    { id: 'childhood_games_17', text: 'Tetherball' },
    { id: 'childhood_games_18', text: 'Manhunt' },
    { id: 'childhood_games_19', text: 'Sardines' },
    { id: 'childhood_games_20', text: 'Kick the can' },
    { id: 'childhood_games_21', text: 'Ghost in the graveyard' },
    { id: 'childhood_games_22', text: 'Truth or dare' },
    { id: 'childhood_games_23', text: 'MASH' },
    { id: 'childhood_games_24', text: 'Would You Rather' },
    { id: 'childhood_games_25', text: 'Telephone' },
  ],
  nostalgia: [
    { id: 'nostalgia_01', text: 'Saturday morning cartoons' },
    { id: 'nostalgia_02', text: 'Blockbuster Fridays' },
    { id: 'nostalgia_03', text: 'Trick-or-treating' },
    { id: 'nostalgia_04', text: 'Snow days' },
    { id: 'nostalgia_05', text: 'Summer break' },
    { id: 'nostalgia_06', text: 'Recess' },
    { id: 'nostalgia_07', text: 'Sleepovers' },
    { id: 'nostalgia_08', text: 'Field trips' },
    { id: 'nostalgia_09', text: 'Biking around all day' },
    { id: 'nostalgia_10', text: 'Blowing bubbles' },
    { id: 'nostalgia_11', text: 'Building blanket forts' },
    { id: 'nostalgia_12', text: 'Passing notes in class' },
    { id: 'nostalgia_13', text: 'Losing a baby tooth' },
    { id: 'nostalgia_14', text: 'AIM chats after school' },
    { id: 'nostalgia_15', text: 'Making mixtapes' },
    { id: 'nostalgia_16', text: 'Yearbook signing day' },
    { id: 'nostalgia_17', text: 'Arcade birthday parties' },
    { id: 'nostalgia_18', text: 'Blowing on a cartridge' },
    { id: 'nostalgia_19', text: 'Trading Pokemon cards' },
    { id: 'nostalgia_20', text: 'Ice cream truck music' },
    { id: 'nostalgia_21', text: 'School book fairs' },
    { id: 'nostalgia_22', text: 'Snacks after school' },
    { id: 'nostalgia_23', text: 'Report card day' },
    { id: 'nostalgia_24', text: 'Playing outside till dark' },
    { id: 'nostalgia_25', text: 'Family road trips' },
  ],
  school_subjects: [
    { id: 'school_subjects_01', text: 'Math' },
    { id: 'school_subjects_02', text: 'English' },
    { id: 'school_subjects_03', text: 'History' },
    { id: 'school_subjects_04', text: 'Biology' },
    { id: 'school_subjects_05', text: 'Chemistry' },
    { id: 'school_subjects_06', text: 'Physics' },
    { id: 'school_subjects_07', text: 'Art' },
    { id: 'school_subjects_08', text: 'Music class' },
    { id: 'school_subjects_09', text: 'Gym class' },
    { id: 'school_subjects_10', text: 'Drama' },
    { id: 'school_subjects_11', text: 'Computer science' },
    { id: 'school_subjects_12', text: 'Spanish' },
    { id: 'school_subjects_13', text: 'French' },
    { id: 'school_subjects_14', text: 'Geography' },
    { id: 'school_subjects_15', text: 'Economics' },
    { id: 'school_subjects_16', text: 'Psychology' },
    { id: 'school_subjects_17', text: 'Philosophy' },
    { id: 'school_subjects_18', text: 'Home economics' },
    { id: 'school_subjects_19', text: 'Shop class' },
    { id: 'school_subjects_20', text: 'Creative writing' },
    { id: 'school_subjects_21', text: 'Statistics' },
    { id: 'school_subjects_22', text: 'Debate' },
    { id: 'school_subjects_23', text: 'Photography' },
    { id: 'school_subjects_24', text: 'Astronomy' },
    { id: 'school_subjects_25', text: 'Latin' },
  ],
  holidays: [
    { id: 'holidays_01', text: 'Christmas' },
    { id: 'holidays_02', text: 'Thanksgiving' },
    { id: 'holidays_03', text: 'Halloween' },
    { id: 'holidays_04', text: "New Year's Eve" },
    { id: 'holidays_05', text: "Valentine's Day" },
    { id: 'holidays_06', text: 'Easter' },
    { id: 'holidays_07', text: 'Fourth of July' },
    { id: 'holidays_08', text: "St. Patrick's Day" },
    { id: 'holidays_09', text: "Mother's Day" },
    { id: 'holidays_10', text: "Father's Day" },
    { id: 'holidays_11', text: 'Labor Day' },
    { id: 'holidays_12', text: 'Memorial Day' },
    { id: 'holidays_13', text: 'Your birthday' },
    { id: 'holidays_14', text: "April Fool's Day" },
    { id: 'holidays_15', text: 'Cinco de Mayo' },
    { id: 'holidays_16', text: 'Groundhog Day' },
    { id: 'holidays_17', text: 'Mardi Gras' },
    { id: 'holidays_18', text: 'Diwali' },
    { id: 'holidays_19', text: 'Hanukkah' },
    { id: 'holidays_20', text: 'Lunar New Year' },
    { id: 'holidays_21', text: 'Christmas Eve' },
    { id: 'holidays_22', text: "New Year's Day" },
    { id: 'holidays_23', text: 'Boxing Day' },
    { id: 'holidays_24', text: 'Oktoberfest' },
    { id: 'holidays_25', text: 'Earth Day' },
  ],
  holiday_traditions: [
    { id: 'holiday_traditions_01', text: 'Decorating the tree' },
    { id: 'holiday_traditions_02', text: 'Baking holiday cookies' },
    { id: 'holiday_traditions_03', text: 'Wrapping presents' },
    { id: 'holiday_traditions_04', text: 'Hanging stockings' },
    { id: 'holiday_traditions_05', text: 'Watching holiday movies' },
    { id: 'holiday_traditions_06', text: 'Christmas caroling' },
    { id: 'holiday_traditions_07', text: 'Ugly sweater parties' },
    { id: 'holiday_traditions_08', text: 'Making gingerbread houses' },
    { id: 'holiday_traditions_09', text: 'Sending holiday cards' },
    { id: 'holiday_traditions_10', text: 'Matching family pajamas' },
    { id: 'holiday_traditions_11', text: 'A big family dinner' },
    { id: 'holiday_traditions_12', text: 'Secret Santa' },
    { id: 'holiday_traditions_13', text: 'Watching the parade' },
    { id: 'holiday_traditions_14', text: 'Lighting a menorah' },
    { id: 'holiday_traditions_15', text: 'Watching the ball drop' },
    { id: 'holiday_traditions_16', text: 'Making resolutions' },
    { id: 'holiday_traditions_17', text: 'Going trick-or-treating' },
    { id: 'holiday_traditions_18', text: 'Carving a pumpkin' },
    { id: 'holiday_traditions_19', text: 'Hunting for Easter eggs' },
    { id: 'holiday_traditions_20', text: 'Roasting a turkey' },
    { id: 'holiday_traditions_21', text: 'Kissing at midnight' },
    { id: 'holiday_traditions_22', text: 'A fireworks display' },
    { id: 'holiday_traditions_23', text: 'Opening a Christmas Eve gift' },
    { id: 'holiday_traditions_24', text: 'Elf on the Shelf' },
    { id: 'holiday_traditions_25', text: 'Opening an advent calendar' },
  ],
};
