export default {
  growing_up: [
    { id: 'growing_up_01', text: 'My parents' },
    { id: 'growing_up_02', text: 'Where I grew up' },
    { id: 'growing_up_03', text: 'My siblings' },
    { id: 'growing_up_04', text: 'My best friend then' },
    { id: 'growing_up_05', text: 'Money at home' },
    { id: 'growing_up_06', text: 'School' },
    { id: 'growing_up_07', text: 'My teachers' },
    { id: 'growing_up_08', text: 'Family traditions' },
    { id: 'growing_up_09', text: 'Sports I played' },
    { id: 'growing_up_10', text: 'Books I read' },
    { id: 'growing_up_11', text: 'Family dinners' },
    { id: 'growing_up_12', text: 'Family vacations' },
    { id: 'growing_up_13', text: 'Being teased' },
    { id: 'growing_up_14', text: 'My first job' },
    { id: 'growing_up_15', text: 'Moving a lot' },
    { id: 'growing_up_16', text: 'My grandparents' },
    { id: 'growing_up_17', text: 'My hometown' },
    { id: 'growing_up_18', text: 'Music I loved' },
    { id: 'growing_up_19', text: 'Chores I had' },
    { id: 'growing_up_20', text: 'Feeling different' },
    { id: 'growing_up_21', text: 'A favorite teacher' },
    { id: 'growing_up_22', text: 'Being praised' },
    { id: 'growing_up_23', text: 'Losing at things' },
    { id: 'growing_up_24', text: 'Long car rides' },
    { id: 'growing_up_25', text: 'TV I watched' },
  ],

  saying_no: [
    { id: 'saying_no_01', text: 'Dessert' },
    { id: 'saying_no_02', text: 'Free food' },
    { id: 'saying_no_03', text: 'A great deal' },
    { id: 'saying_no_04', text: 'Late-night snacks' },
    { id: 'saying_no_05', text: 'Plans with friends' },
    { id: 'saying_no_06', text: 'A drink after work' },
    { id: 'saying_no_07', text: 'One more episode' },
    { id: 'saying_no_08', text: 'My phone' },
    { id: 'saying_no_09', text: 'Adding to my cart' },
    { id: 'saying_no_10', text: 'A weekend trip' },
    { id: 'saying_no_11', text: 'Extra work hours' },
    { id: 'saying_no_12', text: 'Trying a new hobby' },
    { id: 'saying_no_13', text: 'Buying books' },
    { id: 'saying_no_14', text: 'A guilt trip' },
    { id: 'saying_no_15', text: 'A last-minute invite' },
    { id: 'saying_no_16', text: 'Peer pressure' },
    { id: 'saying_no_17', text: 'Volunteering' },
    { id: 'saying_no_18', text: 'Hitting snooze' },
    { id: 'saying_no_19', text: 'A second helping' },
    { id: 'saying_no_20', text: 'Splurging on gifts' },
    { id: 'saying_no_21', text: 'A cute animal' },
    { id: 'saying_no_22', text: 'A pastry' },
    { id: 'saying_no_23', text: 'A group chat plan' },
    { id: 'saying_no_24', text: 'Someone in tears' },
    { id: 'saying_no_25', text: 'A big favor' },
  ],

  being_known: [
    { id: 'being_known_01', text: 'My fears' },
    { id: 'being_known_02', text: 'My childhood' },
    { id: 'being_known_03', text: 'My dreams' },
    { id: 'being_known_04', text: 'My regrets' },
    { id: 'being_known_05', text: 'My favorite memories' },
    { id: 'being_known_06', text: 'My guilty pleasures' },
    { id: 'being_known_07', text: 'My hopes for us' },
    { id: 'being_known_08', text: 'My money worries' },
    { id: 'being_known_09', text: 'My weird habits' },
    { id: 'being_known_10', text: 'My worst mistake' },
    { id: 'being_known_11', text: 'My proudest moment' },
    { id: 'being_known_12', text: 'My family dynamics' },
    { id: 'being_known_13', text: 'My health stuff' },
    { id: 'being_known_14', text: 'My insecurities' },
    { id: 'being_known_15', text: 'What makes me cry' },
    { id: 'being_known_16', text: 'What makes me laugh' },
    { id: 'being_known_17', text: 'My favorite music' },
    { id: 'being_known_18', text: 'My work life' },
    { id: 'being_known_19', text: 'My first love' },
    { id: 'being_known_20', text: 'My friendships' },
    { id: 'being_known_21', text: 'My beliefs' },
    { id: 'being_known_22', text: 'My comfort foods' },
    { id: 'being_known_23', text: 'My daily routine' },
    { id: 'being_known_24', text: 'My daydreams' },
    { id: 'being_known_25', text: 'What I want in life' },
  ],

  gratitude: [
    { id: 'gratitude_01', text: 'My family' },
    { id: 'gratitude_02', text: 'My best friend' },
    { id: 'gratitude_03', text: 'My health' },
    { id: 'gratitude_04', text: 'My home' },
    { id: 'gratitude_05', text: 'My job' },
    { id: 'gratitude_06', text: 'Enough money' },
    { id: 'gratitude_07', text: 'Good food' },
    { id: 'gratitude_08', text: 'My pet' },
    { id: 'gratitude_09', text: 'Time to myself' },
    { id: 'gratitude_10', text: 'My hobbies' },
    { id: 'gratitude_11', text: 'Old friendships' },
    { id: 'gratitude_12', text: 'New friendships' },
    { id: 'gratitude_13', text: 'My neighborhood' },
    { id: 'gratitude_14', text: 'Weekends off' },
    { id: 'gratitude_15', text: 'Long walks' },
    { id: 'gratitude_16', text: 'A good book' },
    { id: 'gratitude_17', text: 'Quiet evenings' },
    { id: 'gratitude_18', text: 'Music I love' },
    { id: 'gratitude_19', text: 'Sunshine' },
    { id: 'gratitude_20', text: 'A warm bed' },
    { id: 'gratitude_21', text: 'Someone to text' },
    { id: 'gratitude_22', text: 'My education' },
    { id: 'gratitude_23', text: 'My routines' },
    { id: 'gratitude_24', text: 'Laughter' },
    { id: 'gratitude_25', text: 'Coffee mornings' },
  ],

  asking_for_help: [
    { id: 'asking_for_help_01', text: 'Moving apartments' },
    { id: 'asking_for_help_02', text: 'Money problems' },
    { id: 'asking_for_help_03', text: 'Feeling lonely' },
    { id: 'asking_for_help_04', text: 'A hard decision' },
    { id: 'asking_for_help_05', text: 'Cooking a meal' },
    { id: 'asking_for_help_06', text: 'Home repairs' },
    { id: 'asking_for_help_07', text: 'Directions' },
    { id: 'asking_for_help_08', text: 'Reading something over' },
    { id: 'asking_for_help_09', text: 'Learning new tech' },
    { id: 'asking_for_help_10', text: 'Feeling anxious' },
    { id: 'asking_for_help_11', text: 'Finding a job' },
    { id: 'asking_for_help_12', text: 'A ride somewhere' },
    { id: 'asking_for_help_13', text: 'Fixing my car' },
    { id: 'asking_for_help_14', text: 'Health worries' },
    { id: 'asking_for_help_15', text: 'Assembling furniture' },
    { id: 'asking_for_help_16', text: 'A big favor' },
    { id: 'asking_for_help_17', text: 'Reaching a top shelf' },
    { id: 'asking_for_help_18', text: 'Understanding a bill' },
    { id: 'asking_for_help_19', text: 'Cleaning up' },
    { id: 'asking_for_help_20', text: 'Making a call' },
    { id: 'asking_for_help_21', text: 'A late-night ride' },
    { id: 'asking_for_help_22', text: 'Studying' },
    { id: 'asking_for_help_23', text: 'Editing my writing' },
    { id: 'asking_for_help_24', text: 'Choosing an outfit' },
    { id: 'asking_for_help_25', text: 'Difficult feelings' },
  ],

  conflict: [
    { id: 'conflict_01', text: 'Going quiet' },
    { id: 'conflict_02', text: 'Getting loud' },
    { id: 'conflict_03', text: 'Making jokes' },
    { id: 'conflict_04', text: 'Walking away' },
    { id: 'conflict_05', text: 'Crying' },
    { id: 'conflict_06', text: 'Apologizing fast' },
    { id: 'conflict_07', text: 'Digging in' },
    { id: 'conflict_08', text: 'Getting sarcastic' },
    { id: 'conflict_09', text: 'Overexplaining' },
    { id: 'conflict_10', text: 'Interrupting' },
    { id: 'conflict_11', text: 'Bringing up the past' },
    { id: 'conflict_12', text: 'Shutting down' },
    { id: 'conflict_13', text: 'Nitpicking words' },
    { id: 'conflict_14', text: 'Taking a break' },
    { id: 'conflict_15', text: 'Wanting to win' },
    { id: 'conflict_16', text: 'Overthinking later' },
    { id: 'conflict_17', text: 'Naming feelings' },
    { id: 'conflict_18', text: 'Getting cold' },
    { id: 'conflict_19', text: 'Asking questions' },
    { id: 'conflict_20', text: 'Going to bed angry' },
    { id: 'conflict_21', text: 'Texting instead' },
    { id: 'conflict_22', text: 'Rehearsing my point' },
    { id: 'conflict_23', text: 'Waiting them out' },
    { id: 'conflict_24', text: 'Fixing it fast' },
    { id: 'conflict_25', text: 'Softening my voice' },
  ],

  worries: [
    { id: 'worries_01', text: 'Money' },
    { id: 'worries_02', text: 'My health' },
    { id: 'worries_03', text: 'My job' },
    { id: 'worries_04', text: 'Getting older' },
    { id: 'worries_05', text: 'What people think' },
    { id: 'worries_06', text: 'The future' },
    { id: 'worries_07', text: 'My relationships' },
    { id: 'worries_08', text: 'Ending up alone' },
    { id: 'worries_09', text: 'Missing out' },
    { id: 'worries_10', text: 'Falling behind' },
    { id: 'worries_11', text: 'My weight' },
    { id: 'worries_12', text: 'Something at home' },
    { id: 'worries_13', text: 'A friend I miss' },
    { id: 'worries_14', text: 'My looks' },
    { id: 'worries_15', text: 'Time slipping by' },
    { id: 'worries_16', text: 'Making a wrong choice' },
    { id: 'worries_17', text: 'Being liked' },
    { id: 'worries_18', text: 'My purpose' },
    { id: 'worries_19', text: 'A big deadline' },
    { id: 'worries_20', text: 'Sleeping enough' },
    { id: 'worries_21', text: 'A bill coming due' },
    { id: 'worries_22', text: 'Aging parents' },
    { id: 'worries_23', text: 'World news' },
    { id: 'worries_24', text: 'Being forgotten' },
    { id: 'worries_25', text: 'Not doing enough' },
  ],

  gifts: [
    { id: 'gifts_01', text: 'A scrapbook' },
    { id: 'gifts_02', text: 'Flowers' },
    { id: 'gifts_03', text: 'Cash' },
    { id: 'gifts_04', text: 'A homemade meal' },
    { id: 'gifts_05', text: 'A concert ticket' },
    { id: 'gifts_06', text: 'A book they picked' },
    { id: 'gifts_07', text: 'Chocolate' },
    { id: 'gifts_08', text: 'Jewelry' },
    { id: 'gifts_09', text: 'A photo album' },
    { id: 'gifts_10', text: 'A weekend away' },
    { id: 'gifts_11', text: 'A cozy sweater' },
    { id: 'gifts_12', text: 'A framed photo' },
    { id: 'gifts_13', text: 'A gift card' },
    { id: 'gifts_14', text: 'A plant' },
    { id: 'gifts_15', text: 'A playlist' },
    { id: 'gifts_16', text: 'A massage' },
    { id: 'gifts_17', text: 'A new gadget' },
    { id: 'gifts_18', text: 'A donation in my name' },
    { id: 'gifts_19', text: 'Their time' },
    { id: 'gifts_20', text: 'A surprise party' },
    { id: 'gifts_21', text: 'Art they made' },
    { id: 'gifts_22', text: 'Cozy socks' },
    { id: 'gifts_23', text: 'A fancy dinner' },
    { id: 'gifts_24', text: 'A spa day' },
    { id: 'gifts_25', text: 'A funny mug' },
  ],

  time_together: [
    { id: 'time_together_01', text: 'A long walk' },
    { id: 'time_together_02', text: 'Cooking together' },
    { id: 'time_together_03', text: 'An inside joke' },
    { id: 'time_together_04', text: 'Deep conversation' },
    { id: 'time_together_05', text: 'Watching a movie' },
    { id: 'time_together_06', text: 'Sharing a meal' },
    { id: 'time_together_07', text: 'Playing a game' },
    { id: 'time_together_08', text: 'A shared silence' },
    { id: 'time_together_09', text: 'A workout' },
    { id: 'time_together_10', text: 'Running errands' },
    { id: 'time_together_11', text: 'Reading side by side' },
    { id: 'time_together_12', text: 'Dancing' },
    { id: 'time_together_13', text: 'A phone call' },
    { id: 'time_together_14', text: 'Making something' },
    { id: 'time_together_15', text: 'A shared secret' },
    { id: 'time_together_16', text: 'Volunteering together' },
    { id: 'time_together_17', text: 'Watching a sunset' },
    { id: 'time_together_18', text: 'A late-night chat' },
    { id: 'time_together_19', text: 'Traveling together' },
    { id: 'time_together_20', text: 'Laughing hard' },
    { id: 'time_together_21', text: 'A hug' },
    { id: 'time_together_22', text: 'Sharing music' },
    { id: 'time_together_23', text: 'Sending memes' },
    { id: 'time_together_24', text: 'A shared cry' },
    { id: 'time_together_25', text: 'Sharing coffee' },
  ],

  being_wrong: [
    { id: 'being_wrong_01', text: 'In a fight with a partner' },
    { id: 'being_wrong_02', text: 'To a parent' },
    { id: 'being_wrong_03', text: 'To a boss' },
    { id: 'being_wrong_04', text: 'To a kid' },
    { id: 'being_wrong_05', text: 'About directions' },
    { id: 'being_wrong_06', text: 'About a fact' },
    { id: 'being_wrong_07', text: 'To a friend' },
    { id: 'being_wrong_08', text: 'In front of a group' },
    { id: 'being_wrong_09', text: 'About my feelings' },
    { id: 'being_wrong_10', text: 'About someone I judged' },
    { id: 'being_wrong_11', text: 'In writing' },
    { id: 'being_wrong_12', text: 'About taste' },
    { id: 'being_wrong_13', text: 'About a plan I picked' },
    { id: 'being_wrong_14', text: 'To a stranger' },
    { id: 'being_wrong_15', text: 'About how I acted' },
    { id: 'being_wrong_16', text: 'On something small' },
    { id: 'being_wrong_17', text: 'About a memory' },
    { id: 'being_wrong_18', text: 'To a sibling' },
    { id: 'being_wrong_19', text: 'Online' },
    { id: 'being_wrong_20', text: 'About a first impression' },
    { id: 'being_wrong_21', text: 'To a younger person' },
    { id: 'being_wrong_22', text: 'About a rule I made' },
    { id: 'being_wrong_23', text: 'About money' },
    { id: 'being_wrong_24', text: 'In a group chat' },
    { id: 'being_wrong_25', text: 'About being late' },
  ],

  what_you_hide: [
    { id: 'what_you_hide_01', text: 'My salary' },
    { id: 'what_you_hide_02', text: 'My weight' },
    { id: 'what_you_hide_03', text: 'My private opinions' },
    { id: 'what_you_hide_04', text: 'My true feelings' },
    { id: 'what_you_hide_05', text: 'My family drama' },
    { id: 'what_you_hide_06', text: 'My daydreams' },
    { id: 'what_you_hide_07', text: 'My guilty pleasures' },
    { id: 'what_you_hide_08', text: 'My insecurities' },
    { id: 'what_you_hide_09', text: 'My past mistakes' },
    { id: 'what_you_hide_10', text: 'My real hobbies' },
    { id: 'what_you_hide_11', text: 'My health issues' },
    { id: 'what_you_hide_12', text: 'My money worries' },
    { id: 'what_you_hide_13', text: 'My crushes' },
    { id: 'what_you_hide_14', text: 'What I really think' },
    { id: 'what_you_hide_15', text: 'What I want' },
    { id: 'what_you_hide_16', text: 'My weird habits' },
    { id: 'what_you_hide_17', text: 'My browser history' },
    { id: 'what_you_hide_18', text: 'My journal' },
    { id: 'what_you_hide_19', text: 'How lonely I feel' },
    { id: 'what_you_hide_20', text: 'What hurt me' },
    { id: 'what_you_hide_21', text: 'My big dreams' },
    { id: 'what_you_hide_22', text: 'My real age' },
    { id: 'what_you_hide_23', text: 'My fears' },
    { id: 'what_you_hide_24', text: 'My envy' },
    { id: 'what_you_hide_25', text: 'My anger' },
  ],

  a_good_life: [
    { id: 'a_good_life_01', text: 'Raising a family' },
    { id: 'a_good_life_02', text: 'Meaningful work' },
    { id: 'a_good_life_03', text: 'Seeing the world' },
    { id: 'a_good_life_04', text: 'Retiring early' },
    { id: 'a_good_life_05', text: 'Deep friendships' },
    { id: 'a_good_life_06', text: 'Creative work' },
    { id: 'a_good_life_07', text: 'Constant learning' },
    { id: 'a_good_life_08', text: 'Great health' },
    { id: 'a_good_life_09', text: 'Making people laugh' },
    { id: 'a_good_life_10', text: 'Finding love' },
    { id: 'a_good_life_11', text: 'A simple life' },
    { id: 'a_good_life_12', text: 'Helping others' },
    { id: 'a_good_life_13', text: 'Being remembered' },
    { id: 'a_good_life_14', text: 'Financial security' },
    { id: 'a_good_life_15', text: 'Adventures' },
    { id: 'a_good_life_16', text: 'A quiet life' },
    { id: 'a_good_life_17', text: 'Working for myself' },
    { id: 'a_good_life_18', text: 'Mastering a craft' },
    { id: 'a_good_life_19', text: 'A close-knit community' },
    { id: 'a_good_life_20', text: 'Time in nature' },
    { id: 'a_good_life_21', text: 'Kids who love you' },
    { id: 'a_good_life_22', text: 'Being a good friend' },
    { id: 'a_good_life_23', text: 'Waking up excited' },
    { id: 'a_good_life_24', text: 'Finding your calling' },
    { id: 'a_good_life_25', text: 'Peace at home' },
  ],

  courage: [
    { id: 'courage_01', text: 'Giving a toast' },
    { id: 'courage_02', text: 'Ending a friendship' },
    { id: 'courage_03', text: 'Quitting your job' },
    { id: 'courage_04', text: 'Saying I love you first' },
    { id: 'courage_05', text: 'Confronting a bully' },
    { id: 'courage_06', text: 'Moving abroad' },
    { id: 'courage_07', text: 'Asking for a raise' },
    { id: 'courage_08', text: 'Starting a business' },
    { id: 'courage_09', text: 'Skydiving' },
    { id: 'courage_10', text: 'Singing solo' },
    { id: 'courage_11', text: 'Telling a hard truth' },
    { id: 'courage_12', text: 'Setting a boundary' },
    { id: 'courage_13', text: 'Dancing sober' },
    { id: 'courage_14', text: 'Sharing your art' },
    { id: 'courage_15', text: 'Asking someone out' },
    { id: 'courage_16', text: 'Traveling alone' },
    { id: 'courage_17', text: 'Trying stand-up' },
    { id: 'courage_18', text: 'Speaking up at work' },
    { id: 'courage_19', text: 'Wearing something bold' },
    { id: 'courage_20', text: 'Eating alone in public' },
    { id: 'courage_21', text: 'Applying for a dream job' },
    { id: 'courage_22', text: 'Going back to school' },
    { id: 'courage_23', text: 'Living somewhere new' },
    { id: 'courage_24', text: 'Telling your crush' },
    { id: 'courage_25', text: 'Being fully honest' },
  ],

  home: [
    { id: 'home_01', text: 'My own bed' },
    { id: 'home_02', text: 'A stocked fridge' },
    { id: 'home_03', text: 'Family photos up' },
    { id: 'home_04', text: 'My favorite mug' },
    { id: 'home_05', text: 'Plants' },
    { id: 'home_06', text: 'A cozy blanket' },
    { id: 'home_07', text: 'Familiar smells' },
    { id: 'home_08', text: 'My kitchen' },
    { id: 'home_09', text: 'A pet greeting me' },
    { id: 'home_10', text: 'My books on a shelf' },
    { id: 'home_11', text: 'Good lighting' },
    { id: 'home_12', text: 'Music playing' },
    { id: 'home_13', text: 'A quiet room' },
    { id: 'home_14', text: 'A neighborhood I know' },
    { id: 'home_15', text: 'My routines' },
    { id: 'home_16', text: 'Warm colors' },
    { id: 'home_17', text: 'Art on the walls' },
    { id: 'home_18', text: 'A window I love' },
    { id: 'home_19', text: 'My favorite chair' },
    { id: 'home_20', text: 'Familiar noises' },
    { id: 'home_21', text: 'A place to cook' },
    { id: 'home_22', text: 'A worn-in couch' },
    { id: 'home_23', text: 'A view I know' },
    { id: 'home_24', text: 'Space to be messy' },
    { id: 'home_25', text: 'Someone waiting' },
  ],

  meaning: [
    { id: 'meaning_01', text: 'My work' },
    { id: 'meaning_02', text: 'My family' },
    { id: 'meaning_03', text: 'My friendships' },
    { id: 'meaning_04', text: 'Making art' },
    { id: 'meaning_05', text: 'Helping strangers' },
    { id: 'meaning_06', text: 'Being in nature' },
    { id: 'meaning_07', text: 'Learning new things' },
    { id: 'meaning_08', text: 'My hobbies' },
    { id: 'meaning_09', text: 'Cooking for others' },
    { id: 'meaning_10', text: 'Building something' },
    { id: 'meaning_11', text: 'A cause I care about' },
    { id: 'meaning_12', text: 'Traditions' },
    { id: 'meaning_13', text: 'Raising kids' },
    { id: 'meaning_14', text: 'My community' },
    { id: 'meaning_15', text: 'Quiet moments' },
    { id: 'meaning_16', text: 'Solving problems' },
    { id: 'meaning_17', text: 'Teaching someone' },
    { id: 'meaning_18', text: 'A long friendship' },
    { id: 'meaning_19', text: 'Storytelling' },
    { id: 'meaning_20', text: 'Making music' },
    { id: 'meaning_21', text: 'Being a mentor' },
    { id: 'meaning_22', text: 'Small daily rituals' },
    { id: 'meaning_23', text: 'A shared meal' },
    { id: 'meaning_24', text: 'Long conversations' },
    { id: 'meaning_25', text: 'Being needed' },
  ],
};
