export default {
  chores: [
    { id: "chores_01", text: "Doing the dishes" },
    { id: "chores_02", text: "Folding laundry" },
    { id: "chores_03", text: "Taking out the trash" },
    { id: "chores_04", text: "Vacuuming" },
    { id: "chores_05", text: "Mopping floors" },
    { id: "chores_06", text: "Cleaning the bathroom" },
    { id: "chores_07", text: "Scrubbing the toilet" },
    { id: "chores_08", text: "Organizing the closet" },
    { id: "chores_09", text: "Cleaning the microwave" },
    { id: "chores_10", text: "Doing a big grocery run" },
    { id: "chores_11", text: "Washing windows" },
    { id: "chores_12", text: "Dusting shelves" },
    { id: "chores_13", text: "Ironing clothes" },
    { id: "chores_14", text: "Doing taxes" },
    { id: "chores_15", text: "Cleaning the fridge" },
    { id: "chores_16", text: "Sweeping floors" },
    { id: "chores_17", text: "Changing the sheets" },
    { id: "chores_18", text: "Emptying the dishwasher" },
    { id: "chores_19", text: "Wiping down counters" },
    { id: "chores_20", text: "Cleaning the oven" },
    { id: "chores_21", text: "Watering the plants" },
    { id: "chores_22", text: "Sorting the mail" },
    { id: "chores_23", text: "Raking leaves" },
    { id: "chores_24", text: "Shoveling snow" },
    { id: "chores_25", text: "Mowing the lawn" },
  ],
  minor_inconveniences: [
    { id: "minor_inconveniences_01", text: "Stubbing your toe" },
    { id: "minor_inconveniences_02", text: "Spilling coffee on yourself" },
    { id: "minor_inconveniences_03", text: "Missing the bus" },
    { id: "minor_inconveniences_04", text: "Getting stuck in traffic" },
    { id: "minor_inconveniences_05", text: "A slow internet connection" },
    { id: "minor_inconveniences_06", text: "Losing your keys" },
    { id: "minor_inconveniences_07", text: "A broken phone charger" },
    { id: "minor_inconveniences_08", text: "Waking up late" },
    { id: "minor_inconveniences_09", text: "Running out of hot water" },
    { id: "minor_inconveniences_10", text: "Rain with no umbrella" },
    { id: "minor_inconveniences_11", text: "A dead phone battery" },
    { id: "minor_inconveniences_12", text: "Forgetting your wallet" },
    { id: "minor_inconveniences_13", text: "Getting a paper cut" },
    { id: "minor_inconveniences_14", text: "A slow checkout line" },
    { id: "minor_inconveniences_15", text: "Biting your cheek" },
    { id: "minor_inconveniences_16", text: "Getting a parking ticket" },
    { id: "minor_inconveniences_17", text: "Loud neighbors" },
    { id: "minor_inconveniences_18", text: "A bad hair day" },
    { id: "minor_inconveniences_19", text: "No clean socks" },
    { id: "minor_inconveniences_20", text: "Burning your toast" },
    { id: "minor_inconveniences_21", text: "Dropping your phone" },
    { id: "minor_inconveniences_22", text: "Stepping in a puddle" },
    { id: "minor_inconveniences_23", text: "A middle seat on a flight" },
    { id: "minor_inconveniences_24", text: "Getting spam calls" },
    { id: "minor_inconveniences_25", text: "Forgetting a password" },
  ],
  driving: [
    { id: "driving_01", text: "Speeding on the highway" },
    { id: "driving_02", text: "Blasting the music" },
    { id: "driving_03", text: "Singing along loudly" },
    { id: "driving_04", text: "Following the GPS everywhere" },
    { id: "driving_05", text: "Tailgating slow drivers" },
    { id: "driving_06", text: "Honking at everything" },
    { id: "driving_07", text: "Talking on the phone" },
    { id: "driving_08", text: "Snacking behind the wheel" },
    { id: "driving_09", text: "Getting road rage easily" },
    { id: "driving_10", text: "Cutting people off" },
    { id: "driving_11", text: "Driving in total silence" },
    { id: "driving_12", text: "Always taking shortcuts" },
    { id: "driving_13", text: "Going exactly the speed limit" },
    { id: "driving_14", text: "Rolling through stop signs" },
    { id: "driving_15", text: "Waving other drivers in" },
    { id: "driving_16", text: "Yelling at bad drivers" },
    { id: "driving_17", text: "Zoning out on long drives" },
    { id: "driving_18", text: "Rushing every yellow light" },
    { id: "driving_19", text: "Driving barefoot" },
    { id: "driving_20", text: "Backing into every spot" },
    { id: "driving_21", text: "Checking mirrors constantly" },
    { id: "driving_22", text: "Braking way too early" },
    { id: "driving_23", text: "Coasting to save gas" },
    { id: "driving_24", text: "Listening to podcasts" },
    { id: "driving_25", text: "Chatting with passengers" },
  ],
  eating_out: [
    { id: "eating_out_01", text: "Fast service" },
    { id: "eating_out_02", text: "Friendly staff" },
    { id: "eating_out_03", text: "A great view" },
    { id: "eating_out_04", text: "A quiet atmosphere" },
    { id: "eating_out_05", text: "Fair prices" },
    { id: "eating_out_06", text: "Big portions" },
    { id: "eating_out_07", text: "A good wine list" },
    { id: "eating_out_08", text: "Fresh ingredients" },
    { id: "eating_out_09", text: "Beautiful plating" },
    { id: "eating_out_10", text: "Clean bathrooms" },
    { id: "eating_out_11", text: "Comfortable seating" },
    { id: "eating_out_12", text: "Vegetarian options" },
    { id: "eating_out_13", text: "Good background music" },
    { id: "eating_out_14", text: "A lively atmosphere" },
    { id: "eating_out_15", text: "Quick refills" },
    { id: "eating_out_16", text: "A short wait for a table" },
    { id: "eating_out_17", text: "Free bread or chips" },
    { id: "eating_out_18", text: "Local sourcing" },
    { id: "eating_out_19", text: "Dim lighting" },
    { id: "eating_out_20", text: "A creative menu" },
    { id: "eating_out_21", text: "Familiar comfort food" },
    { id: "eating_out_22", text: "A full bar" },
    { id: "eating_out_23", text: "Kid-friendly options" },
    { id: "eating_out_24", text: "Easy parking" },
    { id: "eating_out_25", text: "Late hours" },
  ],
  giving_gifts: [
    { id: "giving_gifts_01", text: "Buying something practical" },
    { id: "giving_gifts_02", text: "Making something by hand" },
    { id: "giving_gifts_03", text: "Giving cash every time" },
    { id: "giving_gifts_04", text: "Grabbing a gift card" },
    { id: "giving_gifts_05", text: "Planning weeks ahead" },
    { id: "giving_gifts_06", text: "Shopping last minute" },
    { id: "giving_gifts_07", text: "Regifting when it fits" },
    { id: "giving_gifts_08", text: "Splurging on one big thing" },
    { id: "giving_gifts_09", text: "Wrapping it perfectly" },
    { id: "giving_gifts_10", text: "Sticking to a strict budget" },
    { id: "giving_gifts_11", text: "Going way over budget" },
    { id: "giving_gifts_12", text: "Giving an experience" },
    { id: "giving_gifts_13", text: "Picking something sentimental" },
    { id: "giving_gifts_14", text: "Copying their wishlist" },
    { id: "giving_gifts_15", text: "Guessing what they want" },
    { id: "giving_gifts_16", text: "Asking them what they want" },
    { id: "giving_gifts_17", text: "Buying in bulk on sale" },
    { id: "giving_gifts_18", text: "Giving the same gift yearly" },
    { id: "giving_gifts_19", text: "Adding a heartfelt card" },
    { id: "giving_gifts_20", text: "Skipping the card" },
    { id: "giving_gifts_21", text: "Tossing it in a gift bag" },
    { id: "giving_gifts_22", text: "Picking an inside joke" },
    { id: "giving_gifts_23", text: "Sending flowers" },
    { id: "giving_gifts_24", text: "Ordering online at 11 PM" },
    { id: "giving_gifts_25", text: "Shopping in one quick trip" },
  ],
  decisions: [
    { id: "decisions_01", text: "Overthinking every option" },
    { id: "decisions_02", text: "Going with your gut" },
    { id: "decisions_03", text: "Making a pros and cons list" },
    { id: "decisions_04", text: "Asking everyone for advice" },
    { id: "decisions_05", text: "Second-guessing yourself" },
    { id: "decisions_06", text: "Picking the safe option" },
    { id: "decisions_07", text: "Taking the risky choice" },
    { id: "decisions_08", text: "Sleeping on it first" },
    { id: "decisions_09", text: "Deciding on impulse" },
    { id: "decisions_10", text: "Following the crowd" },
    { id: "decisions_11", text: "Doing tons of research" },
    { id: "decisions_12", text: "Flipping a coin" },
    { id: "decisions_13", text: "Waiting for a sign" },
    { id: "decisions_14", text: "Reading every review" },
    { id: "decisions_15", text: "Trusting one close friend" },
    { id: "decisions_16", text: "Choosing what is cheapest" },
    { id: "decisions_17", text: "Choosing what is fastest" },
    { id: "decisions_18", text: "Weighing every detail" },
    { id: "decisions_19", text: "Just picking anything" },
    { id: "decisions_20", text: "Going with the default" },
    { id: "decisions_21", text: "Avoiding the choice entirely" },
    { id: "decisions_22", text: "Choosing what sounds most fun" },
    { id: "decisions_23", text: "Rushing to just be done" },
    { id: "decisions_24", text: "Changing your mind twice" },
    { id: "decisions_25", text: "Copying your last choice" },
  ],
  taking_compliments: [
    { id: "taking_compliments_01", text: "Being called smart" },
    { id: "taking_compliments_02", text: "Being called funny" },
    { id: "taking_compliments_03", text: "Being called cute" },
    { id: "taking_compliments_04", text: "Being called hot" },
    { id: "taking_compliments_05", text: "Being called generous" },
    { id: "taking_compliments_06", text: "Being called mature" },
    { id: "taking_compliments_07", text: "Being called wise" },
    { id: "taking_compliments_08", text: "Being called stylish" },
    { id: "taking_compliments_09", text: "Being called inspiring" },
    { id: "taking_compliments_10", text: "Being called a good friend" },
    { id: "taking_compliments_11", text: "Being called the fun one" },
    { id: "taking_compliments_12", text: "Being called responsible" },
    { id: "taking_compliments_13", text: "Being called a great parent" },
    { id: "taking_compliments_14", text: "Being called a great cook" },
    { id: "taking_compliments_15", text: "Being called well-dressed" },
    { id: "taking_compliments_16", text: "Being praised for your work" },
    { id: "taking_compliments_17", text: "Being praised in a group" },
    { id: "taking_compliments_18", text: "Being praised by your boss" },
    { id: "taking_compliments_19", text: "Being praised by a stranger" },
    { id: "taking_compliments_20", text: "Being praised by an ex" },
    { id: "taking_compliments_21", text: "Being called talented" },
    { id: "taking_compliments_22", text: "Being praised for something small" },
    { id: "taking_compliments_23", text: "Getting a backhanded compliment" },
    { id: "taking_compliments_24", text: "Being told you seem happy" },
    { id: "taking_compliments_25", text: "Being told you have a nice voice" },
  ],
  hotels: [
    { id: "hotels_01", text: "A great location" },
    { id: "hotels_02", text: "A comfortable bed" },
    { id: "hotels_03", text: "A quiet room" },
    { id: "hotels_04", text: "Fast Wi-Fi" },
    { id: "hotels_05", text: "A nice pool" },
    { id: "hotels_06", text: "A good gym" },
    { id: "hotels_07", text: "Free breakfast" },
    { id: "hotels_08", text: "Room service" },
    { id: "hotels_09", text: "A great view" },
    { id: "hotels_10", text: "A big bathroom" },
    { id: "hotels_11", text: "A rain shower" },
    { id: "hotels_12", text: "Blackout curtains" },
    { id: "hotels_13", text: "A minibar" },
    { id: "hotels_14", text: "A cheap rate" },
    { id: "hotels_15", text: "Friendly staff" },
    { id: "hotels_16", text: "A hot tub" },
    { id: "hotels_17", text: "Modern decor" },
    { id: "hotels_18", text: "A balcony" },
    { id: "hotels_19", text: "An in-room coffee maker" },
    { id: "hotels_20", text: "Late checkout" },
    { id: "hotels_21", text: "A high floor" },
    { id: "hotels_22", text: "On-site parking" },
    { id: "hotels_23", text: "A rooftop bar" },
    { id: "hotels_24", text: "Fluffy towels" },
    { id: "hotels_25", text: "Extra pillows" },
  ],
  road_trips: [
    { id: "road_trips_01", text: "A great playlist" },
    { id: "road_trips_02", text: "Snacks in the car" },
    { id: "road_trips_03", text: "A comfortable seat" },
    { id: "road_trips_04", text: "Interesting scenery" },
    { id: "road_trips_05", text: "Good conversation" },
    { id: "road_trips_06", text: "Frequent bathroom breaks" },
    { id: "road_trips_07", text: "Sticking to the plan" },
    { id: "road_trips_08", text: "Random detours" },
    { id: "road_trips_09", text: "A clean car" },
    { id: "road_trips_10", text: "Gas station coffee" },
    { id: "road_trips_11", text: "Sunglasses on hand" },
    { id: "road_trips_12", text: "A phone charger" },
    { id: "road_trips_13", text: "Roadside diners" },
    { id: "road_trips_14", text: "Cruise control" },
    { id: "road_trips_15", text: "Making good time" },
    { id: "road_trips_16", text: "Fun podcasts" },
    { id: "road_trips_17", text: "Audiobooks" },
    { id: "road_trips_18", text: "Great weather" },
    { id: "road_trips_19", text: "A driving buddy" },
    { id: "road_trips_20", text: "Silence for a while" },
    { id: "road_trips_21", text: "Souvenir stops" },
    { id: "road_trips_22", text: "Weird roadside attractions" },
    { id: "road_trips_23", text: "A packed cooler" },
    { id: "road_trips_24", text: "Sunrise on the road" },
    { id: "road_trips_25", text: "Sunset on the road" },
  ],
  planning: [
    { id: "planning_01", text: "Booking months in advance" },
    { id: "planning_02", text: "Booking the day before" },
    { id: "planning_03", text: "Building a detailed itinerary" },
    { id: "planning_04", text: "Winging the whole thing" },
    { id: "planning_05", text: "Reading endless reviews" },
    { id: "planning_06", text: "Asking friends for tips" },
    { id: "planning_07", text: "Making a packing list" },
    { id: "planning_08", text: "Packing the night before" },
    { id: "planning_09", text: "Overpacking every time" },
    { id: "planning_10", text: "Underpacking on purpose" },
    { id: "planning_11", text: "Booking the cheapest flight" },
    { id: "planning_12", text: "Splurging on a nice hotel" },
    { id: "planning_13", text: "Making a spreadsheet" },
    { id: "planning_14", text: "Just showing up" },
    { id: "planning_15", text: "Copying online itineraries" },
    { id: "planning_16", text: "Planning every meal" },
    { id: "planning_17", text: "Leaving meals to chance" },
    { id: "planning_18", text: "Pre-booking every activity" },
    { id: "planning_19", text: "Watching travel videos" },
    { id: "planning_20", text: "Learning a few phrases" },
    { id: "planning_21", text: "Checking the weather daily" },
    { id: "planning_22", text: "Making backup plans" },
    { id: "planning_23", text: "Overpaying to avoid stress" },
    { id: "planning_24", text: "Skipping the tourist spots" },
    { id: "planning_25", text: "Doing all the tourist spots" },
  ],
  foods: [
    { id: "foods_01", text: "Pizza" },
    { id: "foods_02", text: "Tacos" },
    { id: "foods_03", text: "Burgers" },
    { id: "foods_04", text: "Sushi" },
    { id: "foods_05", text: "Ramen" },
    { id: "foods_06", text: "Pad thai" },
    { id: "foods_07", text: "Fried chicken" },
    { id: "foods_08", text: "Steak" },
    { id: "foods_09", text: "Lasagna" },
    { id: "foods_10", text: "Burritos" },
    { id: "foods_11", text: "BBQ ribs" },
    { id: "foods_12", text: "Grilled cheese" },
    { id: "foods_13", text: "Mac and cheese" },
    { id: "foods_14", text: "Fish and chips" },
    { id: "foods_15", text: "Pho" },
    { id: "foods_16", text: "Dumplings" },
    { id: "foods_17", text: "Curry" },
    { id: "foods_18", text: "Pasta carbonara" },
    { id: "foods_19", text: "Meatloaf" },
    { id: "foods_20", text: "Chicken wings" },
    { id: "foods_21", text: "Chili" },
    { id: "foods_22", text: "Kebabs" },
    { id: "foods_23", text: "Salmon fillet" },
    { id: "foods_24", text: "Enchiladas" },
    { id: "foods_25", text: "Gnocchi" },
  ],
  cuisines: [
    { id: "cuisines_01", text: "Italian" },
    { id: "cuisines_02", text: "Mexican" },
    { id: "cuisines_03", text: "Chinese" },
    { id: "cuisines_04", text: "Japanese" },
    { id: "cuisines_05", text: "Thai" },
    { id: "cuisines_06", text: "Indian" },
    { id: "cuisines_07", text: "French" },
    { id: "cuisines_08", text: "Greek" },
    { id: "cuisines_09", text: "Korean" },
    { id: "cuisines_10", text: "Vietnamese" },
    { id: "cuisines_11", text: "Spanish" },
    { id: "cuisines_12", text: "Ethiopian" },
    { id: "cuisines_13", text: "Lebanese" },
    { id: "cuisines_14", text: "Turkish" },
    { id: "cuisines_15", text: "American" },
    { id: "cuisines_16", text: "Cuban" },
    { id: "cuisines_17", text: "Peruvian" },
    { id: "cuisines_18", text: "Brazilian" },
    { id: "cuisines_19", text: "Moroccan" },
    { id: "cuisines_20", text: "German" },
    { id: "cuisines_21", text: "British" },
    { id: "cuisines_22", text: "Filipino" },
    { id: "cuisines_23", text: "Southern" },
    { id: "cuisines_24", text: "Cajun" },
    { id: "cuisines_25", text: "Tex-Mex" },
  ],
  snacks: [
    { id: "snacks_01", text: "Potato chips" },
    { id: "snacks_02", text: "Wasabi peas" },
    { id: "snacks_03", text: "Trail mix" },
    { id: "snacks_04", text: "Pretzels" },
    { id: "snacks_05", text: "Sunflower seeds" },
    { id: "snacks_06", text: "Beef jerky" },
    { id: "snacks_07", text: "Hummus and pita" },
    { id: "snacks_08", text: "Mixed nuts" },
    { id: "snacks_09", text: "Crackers" },
    { id: "snacks_10", text: "Cheese and crackers" },
    { id: "snacks_11", text: "Apple slices" },
    { id: "snacks_12", text: "Baby carrots" },
    { id: "snacks_13", text: "Yogurt" },
    { id: "snacks_14", text: "Granola bars" },
    { id: "snacks_15", text: "Rice cakes" },
    { id: "snacks_16", text: "Chips and salsa" },
    { id: "snacks_17", text: "Guacamole" },
    { id: "snacks_18", text: "Olives" },
    { id: "snacks_19", text: "Pickles" },
    { id: "snacks_20", text: "Edamame" },
    { id: "snacks_21", text: "Hard-boiled eggs" },
    { id: "snacks_22", text: "A protein bar" },
    { id: "snacks_23", text: "Cheese cubes" },
    { id: "snacks_24", text: "Veggie chips" },
    { id: "snacks_25", text: "Roasted chickpeas" },
  ],
  childhood_snacks: [
    { id: "childhood_snacks_01", text: "Goldfish crackers" },
    { id: "childhood_snacks_02", text: "Fruit Roll-Ups" },
    { id: "childhood_snacks_03", text: "Gushers" },
    { id: "childhood_snacks_04", text: "Lunchables" },
    { id: "childhood_snacks_05", text: "Dunkaroos" },
    { id: "childhood_snacks_06", text: "Animal crackers" },
    { id: "childhood_snacks_07", text: "Juice boxes" },
    { id: "childhood_snacks_08", text: "Graham crackers" },
    { id: "childhood_snacks_09", text: "PB and J sandwiches" },
    { id: "childhood_snacks_10", text: "Ants on a log" },
    { id: "childhood_snacks_11", text: "Applesauce cups" },
    { id: "childhood_snacks_12", text: "Pudding cups" },
    { id: "childhood_snacks_13", text: "Fruit snacks" },
    { id: "childhood_snacks_14", text: "Cheese puffs" },
    { id: "childhood_snacks_15", text: "Teddy Grahams" },
    { id: "childhood_snacks_16", text: "Cheez-Its" },
    { id: "childhood_snacks_17", text: "Pop-Tarts" },
    { id: "childhood_snacks_18", text: "Dry cereal by the handful" },
    { id: "childhood_snacks_19", text: "Squeezable yogurt tubes" },
    { id: "childhood_snacks_20", text: "Chocolate milk" },
    { id: "childhood_snacks_21", text: "Bagel Bites" },
    { id: "childhood_snacks_22", text: "String cheese" },
    { id: "childhood_snacks_23", text: "Saltines with butter" },
    { id: "childhood_snacks_24", text: "Fun-size candy bars" },
    { id: "childhood_snacks_25", text: "Capri Sun" },
  ],
  desserts: [
    { id: "desserts_01", text: "Chocolate cake" },
    { id: "desserts_02", text: "Cheesecake" },
    { id: "desserts_03", text: "Ice cream" },
    { id: "desserts_04", text: "Brownies" },
    { id: "desserts_05", text: "Apple pie" },
    { id: "desserts_06", text: "Tiramisu" },
    { id: "desserts_07", text: "Creme brulee" },
    { id: "desserts_08", text: "Cookies" },
    { id: "desserts_09", text: "Donuts" },
    { id: "desserts_10", text: "Churros" },
    { id: "desserts_11", text: "Cupcakes" },
    { id: "desserts_12", text: "Cannoli" },
    { id: "desserts_13", text: "Key lime pie" },
    { id: "desserts_14", text: "Pecan pie" },
    { id: "desserts_15", text: "Bread pudding" },
    { id: "desserts_16", text: "Flan" },
    { id: "desserts_17", text: "Macarons" },
    { id: "desserts_18", text: "Mochi" },
    { id: "desserts_19", text: "Tres leches" },
    { id: "desserts_20", text: "Carrot cake" },
    { id: "desserts_21", text: "Banana pudding" },
    { id: "desserts_22", text: "Milkshakes" },
    { id: "desserts_23", text: "Sorbet" },
    { id: "desserts_24", text: "Panna cotta" },
    { id: "desserts_25", text: "Baklava" },
  ],
};
