export default {
    getting_older: [
        { id: 'getting_older_01', text: 'Grandkids' },
        { id: 'getting_older_02', text: 'Retirement' },
        { id: 'getting_older_03', text: 'Hard-earned wisdom' },
        { id: 'getting_older_04', text: 'Guilt-free naps' },
        { id: 'getting_older_05', text: 'Slower mornings' },
        { id: 'getting_older_06', text: 'Long friendships' },
        { id: 'getting_older_07', text: 'Financial stability' },
        { id: 'getting_older_08', text: 'More free time' },
        { id: 'getting_older_09', text: 'Travel' },
        { id: 'getting_older_10', text: 'Paying off the house' },
        { id: 'getting_older_11', text: 'Family dinners' },
        { id: 'getting_older_12', text: 'Not caring what others think' },
        { id: 'getting_older_13', text: 'Comfortable routines' },
        { id: 'getting_older_14', text: 'Gardening' },
        { id: 'getting_older_15', text: 'More reading time' },
        { id: 'getting_older_16', text: 'Perspective' },
        { id: 'getting_older_17', text: 'New hobbies' },
        { id: 'getting_older_18', text: 'Being a mentor' },
        { id: 'getting_older_19', text: 'Quiet weekends' },
        { id: 'getting_older_20', text: 'Early bedtimes' },
        { id: 'getting_older_21', text: 'Self-knowledge' },
        { id: 'getting_older_22', text: 'Grown kids' },
        { id: 'getting_older_23', text: 'Legacy' },
        { id: 'getting_older_24', text: 'Saying what you think' },
        { id: 'getting_older_25', text: 'Slowing down' },
    ],
    raising_kids: [
        { id: 'raising_kids_01', text: 'Being kind' },
        { id: 'raising_kids_02', text: 'Telling the truth' },
        { id: 'raising_kids_03', text: 'Staying curious' },
        { id: 'raising_kids_04', text: 'A work ethic' },
        { id: 'raising_kids_05', text: 'Bouncing back' },
        { id: 'raising_kids_06', text: 'Manners' },
        { id: 'raising_kids_07', text: 'Thinking for yourself' },
        { id: 'raising_kids_08', text: 'Empathy for others' },
        { id: 'raising_kids_09', text: 'Self-confidence' },
        { id: 'raising_kids_10', text: 'Money smarts' },
        { id: 'raising_kids_11', text: 'Cooking basics' },
        { id: 'raising_kids_12', text: 'A love of reading' },
        { id: 'raising_kids_13', text: 'Standing up for others' },
        { id: 'raising_kids_14', text: 'Handling failure' },
        { id: 'raising_kids_15', text: 'Self-discipline' },
        { id: 'raising_kids_16', text: 'Making things' },
        { id: 'raising_kids_17', text: 'Respect for elders' },
        { id: 'raising_kids_18', text: 'Time management' },
        { id: 'raising_kids_19', text: 'Speaking up in a group' },
        { id: 'raising_kids_20', text: 'Physical fitness' },
        { id: 'raising_kids_21', text: 'Sharing' },
        { id: 'raising_kids_22', text: 'Being patient' },
        { id: 'raising_kids_23', text: 'Chasing big goals' },
        { id: 'raising_kids_24', text: 'A sense of humor' },
        { id: 'raising_kids_25', text: 'Owning mistakes' },
    ],
    work_meaning: [
        { id: 'work_meaning_01', text: 'Great pay' },
        { id: 'work_meaning_02', text: 'Kind coworkers' },
        { id: 'work_meaning_03', text: 'Real impact' },
        { id: 'work_meaning_04', text: 'Flexible hours' },
        { id: 'work_meaning_05', text: 'Learning constantly' },
        { id: 'work_meaning_06', text: 'Recognition' },
        { id: 'work_meaning_07', text: 'Creative freedom' },
        { id: 'work_meaning_08', text: 'A strong mission' },
        { id: 'work_meaning_09', text: 'A boss you trust' },
        { id: 'work_meaning_10', text: 'Job security' },
        { id: 'work_meaning_11', text: 'Remote work' },
        { id: 'work_meaning_12', text: 'Room to grow' },
        { id: 'work_meaning_13', text: 'Prestige' },
        { id: 'work_meaning_14', text: 'Helping people directly' },
        { id: 'work_meaning_15', text: 'Solving hard problems' },
        { id: 'work_meaning_16', text: 'Autonomy' },
        { id: 'work_meaning_17', text: 'A short commute' },
        { id: 'work_meaning_18', text: 'Great benefits' },
        { id: 'work_meaning_19', text: 'A close-knit team' },
        { id: 'work_meaning_20', text: 'Building something real' },
        { id: 'work_meaning_21', text: 'A calm workplace' },
        { id: 'work_meaning_22', text: 'Travel opportunities' },
        { id: 'work_meaning_23', text: 'Working for yourself' },
        { id: 'work_meaning_24', text: 'Clear expectations' },
        { id: 'work_meaning_25', text: 'Pride in your work' },
    ],
    second_chances: [
        { id: 'second_chances_01', text: 'Forgetting your birthday' },
        { id: 'second_chances_02', text: 'Breaking a promise' },
        { id: 'second_chances_03', text: 'Embarrassing you publicly' },
        { id: 'second_chances_04', text: 'A harsh comment' },
        { id: 'second_chances_05', text: 'Lying by omission' },
        { id: 'second_chances_06', text: 'Ghosting you' },
        { id: 'second_chances_07', text: 'Gossiping about you' },
        { id: 'second_chances_08', text: 'Missing your wedding' },
        { id: 'second_chances_09', text: 'Never returning what they borrowed' },
        { id: 'second_chances_10', text: 'Not paying you back' },
        { id: 'second_chances_11', text: 'Cheating at a game' },
        { id: 'second_chances_12', text: 'Bailing when you needed them' },
        { id: 'second_chances_13', text: 'Canceling last minute' },
        { id: 'second_chances_14', text: 'Forgetting a huge favor' },
        { id: 'second_chances_15', text: 'Taking credit for your work' },
        { id: 'second_chances_16', text: 'Insulting you in front of others' },
        { id: 'second_chances_17', text: 'Judging your choices' },
        { id: 'second_chances_18', text: 'Spilling a secret' },
        { id: 'second_chances_19', text: 'Backing out of a trip' },
        { id: 'second_chances_20', text: 'Flaking on a reference' },
        { id: 'second_chances_21', text: 'A hollow apology' },
        { id: 'second_chances_22', text: 'Snapping at you in public' },
        { id: 'second_chances_23', text: 'Missing your big moment' },
        { id: 'second_chances_24', text: 'Years of silence' },
        { id: 'second_chances_25', text: 'A cheap-shot joke' },
    ],
    peace: [
        { id: 'peace_01', text: 'Sunday mornings' },
        { id: 'peace_02', text: 'A quiet walk' },
        { id: 'peace_03', text: 'Ocean waves' },
        { id: 'peace_04', text: 'A clean house' },
        { id: 'peace_05', text: 'Fresh sheets' },
        { id: 'peace_06', text: 'A good book' },
        { id: 'peace_07', text: 'Rain on the roof' },
        { id: 'peace_08', text: 'Cooking a slow meal' },
        { id: 'peace_09', text: 'Soaking in the tub' },
        { id: 'peace_10', text: 'Being alone' },
        { id: 'peace_11', text: 'Silence' },
        { id: 'peace_12', text: 'A warm drink' },
        { id: 'peace_13', text: 'Watching a fire' },
        { id: 'peace_14', text: 'Time with a pet' },
        { id: 'peace_15', text: 'Gardening in the sun' },
        { id: 'peace_16', text: 'Deep sleep' },
        { id: 'peace_17', text: 'An empty inbox' },
        { id: 'peace_18', text: 'A finished to-do list' },
        { id: 'peace_19', text: 'A long drive' },
        { id: 'peace_20', text: 'Watching the sunset' },
        { id: 'peace_21', text: 'Journaling' },
        { id: 'peace_22', text: 'Prayer or meditation' },
        { id: 'peace_23', text: 'Being in the woods' },
        { id: 'peace_24', text: 'Music you love' },
        { id: 'peace_25', text: 'A hug from someone you trust' },
    ],
    pet_peeves: [
        { id: 'pet_peeves_01', text: 'Loud chewing' },
        { id: 'pet_peeves_02', text: 'Slow walkers' },
        { id: 'pet_peeves_03', text: 'Wet socks' },
        { id: 'pet_peeves_04', text: 'Talking in movies' },
        { id: 'pet_peeves_05', text: 'Cold food' },
        { id: 'pet_peeves_06', text: 'Interrupters' },
        { id: 'pet_peeves_07', text: 'Bad drivers' },
        { id: 'pet_peeves_08', text: 'Line cutters' },
        { id: 'pet_peeves_09', text: 'Chairs left pushed out' },
        { id: 'pet_peeves_10', text: 'Doors left wide open' },
        { id: 'pet_peeves_11', text: 'Empty milk in the fridge' },
        { id: 'pet_peeves_12', text: 'Nose whistling' },
        { id: 'pet_peeves_13', text: 'Chewing ice' },
        { id: 'pet_peeves_14', text: 'Constant sniffling' },
        { id: 'pet_peeves_15', text: 'Toilet seat left up' },
        { id: 'pet_peeves_16', text: 'Music through phone speakers' },
        { id: 'pet_peeves_17', text: 'Autoplay videos' },
        { id: 'pet_peeves_18', text: 'Small talk' },
        { id: 'pet_peeves_19', text: 'Unread notification badges' },
        { id: 'pet_peeves_20', text: 'Bad grammar' },
        { id: 'pet_peeves_21', text: 'Loud typers' },
        { id: 'pet_peeves_22', text: 'Chronic lateness' },
        { id: 'pet_peeves_23', text: 'Slow internet' },
        { id: 'pet_peeves_24', text: 'Backseat drivers' },
        { id: 'pet_peeves_25', text: 'Bragging' },
    ],
    awkward_moments: [
        { id: 'awkward_moments_01', text: 'Waving at a stranger' },
        { id: 'awkward_moments_02', text: 'Tripping in public' },
        { id: 'awkward_moments_03', text: 'Calling a teacher "mom"' },
        { id: 'awkward_moments_04', text: 'Forgetting a name mid-intro' },
        { id: 'awkward_moments_05', text: 'A hug when they meant a shake' },
        { id: 'awkward_moments_06', text: 'Walking into a glass door' },
        { id: 'awkward_moments_07', text: 'Talking to yourself out loud' },
        { id: 'awkward_moments_08', text: 'Texting the wrong person' },
        { id: 'awkward_moments_09', text: 'Loud stomach in a meeting' },
        { id: 'awkward_moments_10', text: 'Zoom on with pants off' },
        { id: 'awkward_moments_11', text: 'A reply-all disaster' },
        { id: 'awkward_moments_12', text: 'Being caught singing' },
        { id: 'awkward_moments_13', text: 'Toilet paper on your shoe' },
        { id: 'awkward_moments_14', text: 'Food in your teeth all day' },
        { id: 'awkward_moments_15', text: 'Saying "you too" to a waiter' },
        { id: 'awkward_moments_16', text: 'Waving back at nobody' },
        { id: 'awkward_moments_17', text: 'Pushing a pull door' },
        { id: 'awkward_moments_18', text: 'Dozing off in a meeting' },
        { id: 'awkward_moments_19', text: 'Missing a high five' },
        { id: 'awkward_moments_20', text: 'A silent elevator ride' },
        { id: 'awkward_moments_21', text: 'A loud pants rip' },
        { id: 'awkward_moments_22', text: 'Mispronouncing a common word' },
        { id: 'awkward_moments_23', text: 'Being caught crying' },
        { id: 'awkward_moments_24', text: 'Butt-dialing your boss' },
        { id: 'awkward_moments_25', text: 'Small talk with an ex' },
    ],
    texting: [
        { id: 'texting_01', text: 'One-word replies' },
        { id: 'texting_02', text: 'Excessive emojis' },
        { id: 'texting_03', text: 'All lowercase' },
        { id: 'texting_04', text: 'Long voice memos' },
        { id: 'texting_05', text: '"K." as a full reply' },
        { id: 'texting_06', text: 'Days-late replies' },
        { id: 'texting_07', text: 'Double texting' },
        { id: 'texting_08', text: 'Read receipts on' },
        { id: 'texting_09', text: 'No punctuation ever' },
        { id: 'texting_10', text: 'Overusing "lol"' },
        { id: 'texting_11', text: 'Ten texts in a row' },
        { id: 'texting_12', text: 'Random ellipses...' },
        { id: 'texting_13', text: 'Grammar corrections' },
        { id: 'texting_14', text: 'Links with no context' },
        { id: 'texting_15', text: 'Too many exclamation marks' },
        { id: 'texting_16', text: '"Haha" with no real laugh' },
        { id: 'texting_17', text: 'Ending with a period' },
        { id: 'texting_18', text: 'Extremely vague replies' },
        { id: 'texting_19', text: '"We should hang out"' },
        { id: 'texting_20', text: 'Screenshots of texts' },
        { id: 'texting_21', text: 'Meme-only replies' },
        { id: 'texting_22', text: 'Long paragraph texts' },
        { id: 'texting_23', text: 'Answering only one part' },
        { id: 'texting_24', text: 'Reacting instead of replying' },
        { id: 'texting_25', text: '3am texts' },
    ],
    group_chats: [
        { id: 'group_chats_01', text: 'Silent lurkers' },
        { id: 'group_chats_02', text: '200 unread messages' },
        { id: 'group_chats_03', text: 'Adding people without asking' },
        { id: 'group_chats_04', text: 'Constant meme spam' },
        { id: 'group_chats_05', text: 'Political rants' },
        { id: 'group_chats_06', text: 'Ignoring plans being made' },
        { id: 'group_chats_07', text: 'Endless off-topic tangents' },
        { id: 'group_chats_08', text: 'Leaving the chat dramatically' },
        { id: 'group_chats_09', text: 'Renaming the chat constantly' },
        { id: 'group_chats_10', text: 'Ignoring a direct question' },
        { id: 'group_chats_11', text: 'Videos with no context' },
        { id: 'group_chats_12', text: 'Voting on plans forever' },
        { id: 'group_chats_13', text: '"Anyone up?" at 2am' },
        { id: 'group_chats_14', text: '80 messages while you sleep' },
        { id: 'group_chats_15', text: 'Bringing up old drama' },
        { id: 'group_chats_16', text: 'Sub-tweeting the group' },
        { id: 'group_chats_17', text: 'Long life updates only here' },
        { id: 'group_chats_18', text: 'Muting but never leaving' },
        { id: 'group_chats_19', text: 'Never responding' },
        { id: 'group_chats_20', text: 'Screenshots to other chats' },
        { id: 'group_chats_21', text: 'Passive-aggressive replies' },
        { id: 'group_chats_22', text: 'Bragging about vacations' },
        { id: 'group_chats_23', text: 'Only sending TikToks' },
        { id: 'group_chats_24', text: 'Chain messages' },
        { id: 'group_chats_25', text: 'Reviving a dead chat weekly' },
    ],
    roommates: [
        { id: 'roommates_01', text: 'Dishes left in the sink' },
        { id: 'roommates_02', text: 'Loud late-night calls' },
        { id: 'roommates_03', text: 'Never taking out trash' },
        { id: 'roommates_04', text: 'Eating your food' },
        { id: 'roommates_05', text: 'Long showers' },
        { id: 'roommates_06', text: 'Overnight guests every week' },
        { id: 'roommates_07', text: 'Blasting music' },
        { id: 'roommates_08', text: 'Passive-aggressive notes' },
        { id: 'roommates_09', text: 'Hair in the drain' },
        { id: 'roommates_10', text: 'Thermostat wars' },
        { id: 'roommates_11', text: 'A filthy bathroom' },
        { id: 'roommates_12', text: 'Leaving lights on' },
        { id: 'roommates_13', text: 'Never buying toilet paper' },
        { id: 'roommates_14', text: 'Wet towels on the floor' },
        { id: 'roommates_15', text: 'Alarms they never hear' },
        { id: 'roommates_16', text: 'Borrowing without asking' },
        { id: 'roommates_17', text: 'Cranking the AC' },
        { id: 'roommates_18', text: 'Smelly cooking at all hours' },
        { id: 'roommates_19', text: 'Slamming doors' },
        { id: 'roommates_20', text: 'Late rent every month' },
        { id: 'roommates_21', text: 'Snoozing for an hour' },
        { id: 'roommates_22', text: 'Hair on the soap' },
        { id: 'roommates_23', text: 'Loud TV through the wall' },
        { id: 'roommates_24', text: 'Never cleaning the fridge' },
        { id: 'roommates_25', text: 'Skipping their chores' },
    ],
    bad_habits: [
        { id: 'bad_habits_01', text: 'Caffeine' },
        { id: 'bad_habits_02', text: 'Doomscrolling' },
        { id: 'bad_habits_03', text: 'Nail biting' },
        { id: 'bad_habits_04', text: 'Late-night snacking' },
        { id: 'bad_habits_05', text: 'Hitting snooze' },
        { id: 'bad_habits_06', text: 'Junk food' },
        { id: 'bad_habits_07', text: 'Sugar' },
        { id: 'bad_habits_08', text: 'Oversleeping' },
        { id: 'bad_habits_09', text: 'Overspending' },
        { id: 'bad_habits_10', text: 'Procrastinating' },
        { id: 'bad_habits_11', text: 'Skipping breakfast' },
        { id: 'bad_habits_12', text: 'Sitting all day' },
        { id: 'bad_habits_13', text: 'Overthinking' },
        { id: 'bad_habits_14', text: 'Gossiping' },
        { id: 'bad_habits_15', text: 'Interrupting' },
        { id: 'bad_habits_16', text: 'Complaining' },
        { id: 'bad_habits_17', text: 'Phone in bed' },
        { id: 'bad_habits_18', text: 'Saying yes to everything' },
        { id: 'bad_habits_19', text: 'Skipping the gym' },
        { id: 'bad_habits_20', text: 'Cracking your knuckles' },
        { id: 'bad_habits_21', text: 'TV to fall asleep' },
        { id: 'bad_habits_22', text: 'Online shopping' },
        { id: 'bad_habits_23', text: 'Cursing' },
        { id: 'bad_habits_24', text: 'Skipping water' },
        { id: 'bad_habits_25', text: 'Multitasking' },
    ],
    procrastination: [
        { id: 'procrastination_01', text: 'Scrolling social media' },
        { id: 'procrastination_02', text: 'Making coffee' },
        { id: 'procrastination_03', text: 'Cleaning your desk' },
        { id: 'procrastination_04', text: 'Reorganizing folders' },
        { id: 'procrastination_05', text: 'Watching YouTube' },
        { id: 'procrastination_06', text: 'Snack breaks' },
        { id: 'procrastination_07', text: 'Long showers' },
        { id: 'procrastination_08', text: 'Rewatching a favorite show' },
        { id: 'procrastination_09', text: 'Napping' },
        { id: 'procrastination_10', text: 'Texting friends' },
        { id: 'procrastination_11', text: 'Endless to-do list making' },
        { id: 'procrastination_12', text: 'Doing laundry' },
        { id: 'procrastination_13', text: 'Deep-cleaning the kitchen' },
        { id: 'procrastination_14', text: 'Wikipedia rabbit holes' },
        { id: 'procrastination_15', text: 'Answering easy emails' },
        { id: 'procrastination_16', text: 'Online shopping' },
        { id: 'procrastination_17', text: 'Watching cooking videos' },
        { id: 'procrastination_18', text: 'Journaling about it' },
        { id: 'procrastination_19', text: 'Meal prepping' },
        { id: 'procrastination_20', text: 'Rearranging furniture' },
        { id: 'procrastination_21', text: 'Doomscrolling news' },
        { id: 'procrastination_22', text: 'Learning a new app' },
        { id: 'procrastination_23', text: 'Going for a walk' },
        { id: 'procrastination_24', text: 'Watering plants' },
        { id: 'procrastination_25', text: 'Planning the perfect start' },
    ],
    mornings: [
        { id: 'mornings_01', text: 'A strong coffee' },
        { id: 'mornings_02', text: 'A shower' },
        { id: 'mornings_03', text: 'A big breakfast' },
        { id: 'mornings_04', text: 'Checking your phone' },
        { id: 'mornings_05', text: 'Making the bed' },
        { id: 'mornings_06', text: 'Brushing your teeth' },
        { id: 'mornings_07', text: 'A workout' },
        { id: 'mornings_08', text: 'Silence' },
        { id: 'mornings_09', text: 'Music' },
        { id: 'mornings_10', text: 'Sunlight' },
        { id: 'mornings_11', text: 'Alone time' },
        { id: 'mornings_12', text: 'Morning pages' },
        { id: 'mornings_13', text: 'Skincare' },
        { id: 'mornings_14', text: 'The news' },
        { id: 'mornings_15', text: 'Stretching' },
        { id: 'mornings_16', text: 'A glass of water' },
        { id: 'mornings_17', text: 'Washing your face' },
        { id: 'mornings_18', text: 'A cold plunge' },
        { id: 'mornings_19', text: 'Pet cuddles' },
        { id: 'mornings_20', text: 'A slow start' },
        { id: 'mornings_21', text: 'Meditation' },
        { id: 'mornings_22', text: 'A podcast' },
        { id: 'mornings_23', text: 'Making kids breakfast' },
        { id: 'mornings_24', text: 'Getting outside' },
        { id: 'mornings_25', text: 'A quick tidy' },
    ],
    nights: [
        { id: 'nights_01', text: 'A shower before bed' },
        { id: 'nights_02', text: 'Reading in bed' },
        { id: 'nights_03', text: 'A cup of tea' },
        { id: 'nights_04', text: 'TV in bed' },
        { id: 'nights_05', text: 'Scrolling in bed' },
        { id: 'nights_06', text: 'A skincare routine' },
        { id: 'nights_07', text: 'Reflecting on the day' },
        { id: 'nights_08', text: 'Stretching' },
        { id: 'nights_09', text: 'Chill music' },
        { id: 'nights_10', text: 'A candle' },
        { id: 'nights_11', text: 'Cooking dinner' },
        { id: 'nights_12', text: 'A walk after dinner' },
        { id: 'nights_13', text: 'Talking to your partner' },
        { id: 'nights_14', text: 'Cuddling a pet' },
        { id: 'nights_15', text: 'Meditation' },
        { id: 'nights_16', text: 'Deep breathing' },
        { id: 'nights_17', text: 'A hobby project' },
        { id: 'nights_18', text: 'Playing a video game' },
        { id: 'nights_19', text: 'Turning off all screens' },
        { id: 'nights_20', text: 'A warm bath' },
        { id: 'nights_21', text: 'A podcast' },
        { id: 'nights_22', text: 'Tidying up the space' },
        { id: 'nights_23', text: 'A late snack' },
        { id: 'nights_24', text: 'Watching the stars' },
        { id: 'nights_25', text: 'Planning tomorrow' },
    ],
    guilty_pleasures: [
        { id: 'guilty_pleasures_01', text: 'Trashy reality TV' },
        { id: 'guilty_pleasures_02', text: 'Fast food' },
        { id: 'guilty_pleasures_03', text: 'Celebrity gossip' },
        { id: 'guilty_pleasures_04', text: 'Long naps' },
        { id: 'guilty_pleasures_05', text: 'Cheesy love songs' },
        { id: 'guilty_pleasures_06', text: 'Rom-coms' },
        { id: 'guilty_pleasures_07', text: 'Endless scrolling' },
        { id: 'guilty_pleasures_08', text: 'Dessert for breakfast' },
        { id: 'guilty_pleasures_09', text: 'Skipping the gym' },
        { id: 'guilty_pleasures_10', text: 'Impulse online buys' },
        { id: 'guilty_pleasures_11', text: 'A whole pint of ice cream' },
        { id: 'guilty_pleasures_12', text: 'Reading tabloids' },
        { id: 'guilty_pleasures_13', text: 'Rewatching old shows' },
        { id: 'guilty_pleasures_14', text: 'Petty group chat drama' },
        { id: 'guilty_pleasures_15', text: 'Karaoke solos' },
        { id: 'guilty_pleasures_16', text: 'Trashy novels' },
        { id: 'guilty_pleasures_17', text: 'Snooping on socials' },
        { id: 'guilty_pleasures_18', text: 'Cheap chocolate' },
        { id: 'guilty_pleasures_19', text: 'Sleeping in on weekdays' },
        { id: 'guilty_pleasures_20', text: 'Junky snacks' },
        { id: 'guilty_pleasures_21', text: 'Boy band deep cuts' },
        { id: 'guilty_pleasures_22', text: 'Talking through movies' },
        { id: 'guilty_pleasures_23', text: 'Reality dating shows' },
        { id: 'guilty_pleasures_24', text: 'Reading the comments' },
        { id: 'guilty_pleasures_25', text: 'Dance breaks alone' },
    ],
};
