export default {
  birthdays: [
    { id: 'birthdays_01', text: 'Dinner with close friends' },
    { id: 'birthdays_02', text: 'A surprise party' },
    { id: 'birthdays_03', text: 'A weekend getaway' },
    { id: 'birthdays_04', text: 'Karaoke night' },
    { id: 'birthdays_05', text: 'A bar crawl' },
    { id: 'birthdays_06', text: 'A quiet night alone' },
    { id: 'birthdays_07', text: 'A themed costume party' },
    { id: 'birthdays_08', text: 'Escape room with friends' },
    { id: 'birthdays_09', text: 'A big house party' },
    { id: 'birthdays_10', text: 'Fancy restaurant dinner' },
    { id: 'birthdays_11', text: 'Movie marathon at home' },
    { id: 'birthdays_12', text: 'A pottery class' },
    { id: 'birthdays_13', text: 'A wine tasting trip' },
    { id: 'birthdays_14', text: 'A skydiving jump' },
    { id: 'birthdays_15', text: 'Beach day with friends' },
    { id: 'birthdays_16', text: 'A camping trip' },
    { id: 'birthdays_17', text: 'Roller skating party' },
    { id: 'birthdays_18', text: 'Board game night' },
    { id: 'birthdays_19', text: 'A concert with friends' },
    { id: 'birthdays_20', text: 'A full spa day' },
    { id: 'birthdays_21', text: 'Amusement park trip' },
    { id: 'birthdays_22', text: 'Brunch with family' },
    { id: 'birthdays_23', text: 'A road trip weekend' },
    { id: 'birthdays_24', text: 'A paintball afternoon' },
    { id: 'birthdays_25', text: 'Pub trivia night' },
  ],
  style: [
    { id: 'style_01', text: 'A tailored suit' },
    { id: 'style_02', text: 'All black outfit' },
    { id: 'style_03', text: 'Bright bold colors' },
    { id: 'style_04', text: 'Vintage thrifted look' },
    { id: 'style_05', text: 'Athleisure fit' },
    { id: 'style_06', text: 'Streetwear drip' },
    { id: 'style_07', text: 'Classic jeans and tee' },
    { id: 'style_08', text: 'A flowy sundress' },
    { id: 'style_09', text: 'Cottagecore look' },
    { id: 'style_10', text: 'Cowboy boots and denim' },
    { id: 'style_11', text: 'Little black dress' },
    { id: 'style_12', text: 'Preppy polo look' },
    { id: 'style_13', text: 'Business casual' },
    { id: 'style_14', text: 'Loud print shirt' },
    { id: 'style_15', text: 'Leather jacket look' },
    { id: 'style_16', text: 'Minimalist neutrals' },
    { id: 'style_17', text: 'Gothic all-black' },
    { id: 'style_18', text: 'Beach cover-up' },
    { id: 'style_19', text: 'Y2K throwback fit' },
    { id: 'style_20', text: 'Head-to-toe designer' },
    { id: 'style_21', text: 'Bohemian maxi dress' },
    { id: 'style_22', text: 'Statement hat and coat' },
    { id: 'style_23', text: 'Crisp white sneakers fit' },
    { id: 'style_24', text: 'Oversized cozy sweater' },
    { id: 'style_25', text: 'Sparkly going-out top' },
  ],
  shoes: [
    { id: 'shoes_01', text: 'White sneakers' },
    { id: 'shoes_02', text: 'Black loafers' },
    { id: 'shoes_03', text: 'Hiking boots' },
    { id: 'shoes_04', text: 'Cowboy boots' },
    { id: 'shoes_05', text: 'Flip-flops' },
    { id: 'shoes_06', text: 'High heels' },
    { id: 'shoes_07', text: 'Running shoes' },
    { id: 'shoes_08', text: 'Combat boots' },
    { id: 'shoes_09', text: 'Ballet flats' },
    { id: 'shoes_10', text: 'Chunky platforms' },
    { id: 'shoes_11', text: 'Slide sandals' },
    { id: 'shoes_12', text: 'Dress shoes' },
    { id: 'shoes_13', text: 'Crocs' },
    { id: 'shoes_14', text: 'Rain boots' },
    { id: 'shoes_15', text: 'Snow boots' },
    { id: 'shoes_16', text: 'Ankle boots' },
    { id: 'shoes_17', text: 'Boat shoes' },
    { id: 'shoes_18', text: 'Espadrilles' },
    { id: 'shoes_19', text: 'Basketball sneakers' },
    { id: 'shoes_20', text: 'Slippers' },
    { id: 'shoes_21', text: 'Cleats' },
    { id: 'shoes_22', text: 'Doc Martens' },
    { id: 'shoes_23', text: 'Wedges' },
    { id: 'shoes_24', text: 'Skate shoes' },
    { id: 'shoes_25', text: 'Knee-high boots' },
  ],
  workouts: [
    { id: 'workouts_01', text: 'Long distance running' },
    { id: 'workouts_02', text: 'Weight lifting' },
    { id: 'workouts_03', text: 'A yoga class' },
    { id: 'workouts_04', text: 'A spin class' },
    { id: 'workouts_05', text: 'Swimming laps' },
    { id: 'workouts_06', text: 'Rock climbing' },
    { id: 'workouts_07', text: 'A boxing session' },
    { id: 'workouts_08', text: 'A pilates class' },
    { id: 'workouts_09', text: 'A HIIT workout' },
    { id: 'workouts_10', text: 'Dance cardio' },
    { id: 'workouts_11', text: 'A CrossFit class' },
    { id: 'workouts_12', text: 'Hiking uphill' },
    { id: 'workouts_13', text: 'Jump rope session' },
    { id: 'workouts_14', text: 'Rowing machine' },
    { id: 'workouts_15', text: 'Group aerobics' },
    { id: 'workouts_16', text: 'A solo gym session' },
    { id: 'workouts_17', text: 'Kickboxing' },
    { id: 'workouts_18', text: 'A Zumba class' },
    { id: 'workouts_19', text: 'A barre class' },
    { id: 'workouts_20', text: 'Mountain biking' },
    { id: 'workouts_21', text: 'Martial arts training' },
    { id: 'workouts_22', text: 'A long kayak paddle' },
    { id: 'workouts_23', text: 'Trail running' },
    { id: 'workouts_24', text: 'Bodyweight circuit' },
    { id: 'workouts_25', text: 'A stretching session' },
  ],
  sports: [
    { id: 'sports_01', text: 'Football' },
    { id: 'sports_02', text: 'Basketball' },
    { id: 'sports_03', text: 'Baseball' },
    { id: 'sports_04', text: 'Soccer' },
    { id: 'sports_05', text: 'Hockey' },
    { id: 'sports_06', text: 'Tennis' },
    { id: 'sports_07', text: 'Golf' },
    { id: 'sports_08', text: 'Boxing' },
    { id: 'sports_09', text: 'MMA' },
    { id: 'sports_10', text: 'Formula 1' },
    { id: 'sports_11', text: 'NASCAR' },
    { id: 'sports_12', text: 'Gymnastics' },
    { id: 'sports_13', text: 'Figure skating' },
    { id: 'sports_14', text: 'Olympic swimming' },
    { id: 'sports_15', text: 'Track and field' },
    { id: 'sports_16', text: 'Volleyball' },
    { id: 'sports_17', text: 'Rugby' },
    { id: 'sports_18', text: 'Cricket' },
    { id: 'sports_19', text: 'Skateboarding' },
    { id: 'sports_20', text: 'Surfing' },
    { id: 'sports_21', text: 'Snowboarding' },
    { id: 'sports_22', text: 'Bowling' },
    { id: 'sports_23', text: 'Curling' },
    { id: 'sports_24', text: 'Horse racing' },
    { id: 'sports_25', text: 'E-sports' },
  ],
  theme_parks: [
    { id: 'theme_parks_01', text: 'A giant roller coaster' },
    { id: 'theme_parks_02', text: 'Bumper cars' },
    { id: 'theme_parks_03', text: 'The teacups' },
    { id: 'theme_parks_04', text: 'A log flume' },
    { id: 'theme_parks_05', text: 'A ferris wheel' },
    { id: 'theme_parks_06', text: 'A drop tower' },
    { id: 'theme_parks_07', text: 'A haunted house ride' },
    { id: 'theme_parks_08', text: 'Spinning swings' },
    { id: 'theme_parks_09', text: 'A carousel' },
    { id: 'theme_parks_10', text: 'A big water slide' },
    { id: 'theme_parks_11', text: 'A dark indoor coaster' },
    { id: 'theme_parks_12', text: 'A wooden coaster' },
    { id: 'theme_parks_13', text: 'A lazy river float' },
    { id: 'theme_parks_14', text: 'A 4D theater ride' },
    { id: 'theme_parks_15', text: "A kids' train ride" },
    { id: 'theme_parks_16', text: 'A rapids raft ride' },
    { id: 'theme_parks_17', text: 'A sky ride gondola' },
    { id: 'theme_parks_18', text: 'A pirate ship swing' },
    { id: 'theme_parks_19', text: 'A motion simulator' },
    { id: 'theme_parks_20', text: 'A zero-gravity spinner' },
    { id: 'theme_parks_21', text: 'A steep-drop coaster' },
    { id: 'theme_parks_22', text: 'A boat dark ride' },
    { id: 'theme_parks_23', text: 'A bungee trampoline' },
    { id: 'theme_parks_24', text: 'Antique cars ride' },
    { id: 'theme_parks_25', text: 'Go-kart track' },
  ],
  outdoors: [
    { id: 'outdoors_01', text: 'A long hike' },
    { id: 'outdoors_02', text: 'Kayaking a lake' },
    { id: 'outdoors_03', text: 'Camping in tents' },
    { id: 'outdoors_04', text: 'Fishing at a lake' },
    { id: 'outdoors_05', text: 'Outdoor rock climbing' },
    { id: 'outdoors_06', text: 'Mountain biking a trail' },
    { id: 'outdoors_07', text: 'A beach day' },
    { id: 'outdoors_08', text: 'A picnic in a park' },
    { id: 'outdoors_09', text: 'A backyard bonfire' },
    { id: 'outdoors_10', text: 'Cross-country skiing' },
    { id: 'outdoors_11', text: 'Sledding down a hill' },
    { id: 'outdoors_12', text: 'Bird watching' },
    { id: 'outdoors_13', text: 'Stargazing at night' },
    { id: 'outdoors_14', text: 'Foraging mushrooms' },
    { id: 'outdoors_15', text: 'A backpacking trip' },
    { id: 'outdoors_16', text: 'Canoeing a river' },
    { id: 'outdoors_17', text: 'Taking surfing lessons' },
    { id: 'outdoors_18', text: 'Snowshoeing' },
    { id: 'outdoors_19', text: 'Horseback riding' },
    { id: 'outdoors_20', text: 'Outdoor yoga' },
    { id: 'outdoors_21', text: 'Gardening in the yard' },
    { id: 'outdoors_22', text: 'Whitewater rafting' },
    { id: 'outdoors_23', text: 'A round of golf' },
    { id: 'outdoors_24', text: 'Ice fishing' },
    { id: 'outdoors_25', text: 'Trail jogging' },
  ],
  cooking: [
    { id: 'cooking_01', text: 'Chopping vegetables' },
    { id: 'cooking_02', text: 'Doing the dishes' },
    { id: 'cooking_03', text: 'Kneading dough' },
    { id: 'cooking_04', text: 'Frosting a cake' },
    { id: 'cooking_05', text: 'Grilling meat' },
    { id: 'cooking_06', text: 'Flipping pancakes' },
    { id: 'cooking_07', text: 'Simmering a sauce' },
    { id: 'cooking_08', text: 'Peeling potatoes' },
    { id: 'cooking_09', text: 'Meal prepping' },
    { id: 'cooking_10', text: 'Baking cookies' },
    { id: 'cooking_11', text: 'Rolling sushi' },
    { id: 'cooking_12', text: 'Deep frying' },
    { id: 'cooking_13', text: 'Plating a dish' },
    { id: 'cooking_14', text: 'Reading a recipe' },
    { id: 'cooking_15', text: 'Grocery shopping' },
    { id: 'cooking_16', text: 'Chopping onions' },
    { id: 'cooking_17', text: 'Loading the dishwasher' },
    { id: 'cooking_18', text: 'Seasoning a steak' },
    { id: 'cooking_19', text: 'Rolling out pastry' },
    { id: 'cooking_20', text: 'Whisking a sauce' },
    { id: 'cooking_21', text: 'Setting the table' },
    { id: 'cooking_22', text: 'Stirring risotto' },
    { id: 'cooking_23', text: 'Cleaning as you go' },
    { id: 'cooking_24', text: 'Tasting as you cook' },
    { id: 'cooking_25', text: 'Mincing garlic' },
  ],
  dinner_guests: [
    { id: 'dinner_guests_01', text: 'A world-famous chef' },
    { id: 'dinner_guests_02', text: 'Your favorite author' },
    { id: 'dinner_guests_03', text: 'A retired astronaut' },
    { id: 'dinner_guests_04', text: 'A stand-up comedian' },
    { id: 'dinner_guests_05', text: 'A rockstar in their prime' },
    { id: 'dinner_guests_06', text: 'A wise grandparent' },
    { id: 'dinner_guests_07', text: 'A Nobel-winning scientist' },
    { id: 'dinner_guests_08', text: 'A Buddhist monk' },
    { id: 'dinner_guests_09', text: 'Your childhood best friend' },
    { id: 'dinner_guests_10', text: 'A war photographer' },
    { id: 'dinner_guests_11', text: 'A cookbook legend' },
    { id: 'dinner_guests_12', text: 'A retired diplomat' },
    { id: 'dinner_guests_13', text: 'A brilliant therapist' },
    { id: 'dinner_guests_14', text: 'A gossip columnist' },
    { id: 'dinner_guests_15', text: 'A close-up magician' },
    { id: 'dinner_guests_16', text: 'A billionaire founder' },
    { id: 'dinner_guests_17', text: 'A championship coach' },
    { id: 'dinner_guests_18', text: 'A famous painter' },
    { id: 'dinner_guests_19', text: 'A food travel writer' },
    { id: 'dinner_guests_20', text: 'A Michelin sommelier' },
    { id: 'dinner_guests_21', text: 'A romance novelist' },
    { id: 'dinner_guests_22', text: 'A documentary maker' },
    { id: 'dinner_guests_23', text: 'A Shakespeare scholar' },
    { id: 'dinner_guests_24', text: 'Your future self' },
    { id: 'dinner_guests_25', text: 'A pro athlete you love' },
  ],
  time_travel: [
    { id: 'time_travel_01', text: 'Ancient Egypt' },
    { id: 'time_travel_02', text: 'Ancient Rome' },
    { id: 'time_travel_03', text: 'Medieval Europe' },
    { id: 'time_travel_04', text: 'The Renaissance' },
    { id: 'time_travel_05', text: 'The Wild West' },
    { id: 'time_travel_06', text: 'The Roaring Twenties' },
    { id: 'time_travel_07', text: 'Victorian England' },
    { id: 'time_travel_08', text: 'Ancient Greece' },
    { id: 'time_travel_09', text: 'Feudal Japan' },
    { id: 'time_travel_10', text: 'The Aztec Empire' },
    { id: 'time_travel_11', text: '1960s America' },
    { id: 'time_travel_12', text: '1970s New York' },
    { id: 'time_travel_13', text: 'Prehistoric times' },
    { id: 'time_travel_14', text: 'The Age of Dinosaurs' },
    { id: 'time_travel_15', text: 'The Viking era' },
    { id: 'time_travel_16', text: 'Ancient China' },
    { id: 'time_travel_17', text: 'The Belle Epoque' },
    { id: 'time_travel_18', text: '1980s Los Angeles' },
    { id: 'time_travel_19', text: 'The Age of Exploration' },
    { id: 'time_travel_20', text: 'The 1893 World Fair' },
    { id: 'time_travel_21', text: 'Woodstock 1969' },
    { id: 'time_travel_22', text: 'The far future' },
    { id: 'time_travel_23', text: 'Golden age Hollywood' },
    { id: 'time_travel_24', text: '1990s internet boom' },
    { id: 'time_travel_25', text: 'The Silk Road era' },
  ],
  windfall: [
    { id: 'windfall_01', text: 'A dream vacation' },
    { id: 'windfall_02', text: 'Debt payoff' },
    { id: 'windfall_03', text: 'A luxury car' },
    { id: 'windfall_04', text: 'Home renovations' },
    { id: 'windfall_05', text: 'A designer wardrobe' },
    { id: 'windfall_06', text: 'An investment fund' },
    { id: 'windfall_07', text: 'A charity donation' },
    { id: 'windfall_08', text: 'A savings buffer' },
    { id: 'windfall_09', text: 'Fancy dinners out' },
    { id: 'windfall_10', text: 'A stack of concert tickets' },
    { id: 'windfall_11', text: 'A new gaming setup' },
    { id: 'windfall_12', text: 'A house down payment' },
    { id: 'windfall_13', text: 'A splurge on friends' },
    { id: 'windfall_14', text: 'A month off work' },
    { id: 'windfall_15', text: 'An art collection' },
    { id: 'windfall_16', text: 'Fine jewelry' },
    { id: 'windfall_17', text: 'Elite gym membership' },
    { id: 'windfall_18', text: 'A small boat' },
    { id: 'windfall_19', text: 'Cosmetic procedures' },
    { id: 'windfall_20', text: 'Startup seed money' },
    { id: 'windfall_21', text: 'A home theater setup' },
    { id: 'windfall_22', text: "A kids' college fund" },
    { id: 'windfall_23', text: 'High-end kitchen gear' },
    { id: 'windfall_24', text: 'One giant party' },
    { id: 'windfall_25', text: 'A rare wine collection' },
  ],
  talent_show: [
    { id: 'talent_show_01', text: 'A vocal solo' },
    { id: 'talent_show_02', text: 'Stand-up comedy' },
    { id: 'talent_show_03', text: 'A piano performance' },
    { id: 'talent_show_04', text: 'A dance routine' },
    { id: 'talent_show_05', text: 'An original poem' },
    { id: 'talent_show_06', text: 'Magic tricks' },
    { id: 'talent_show_07', text: 'A dramatic monologue' },
    { id: 'talent_show_08', text: 'An impressions act' },
    { id: 'talent_show_09', text: 'A karaoke number' },
    { id: 'talent_show_10', text: 'Juggling' },
    { id: 'talent_show_11', text: 'A ventriloquist act' },
    { id: 'talent_show_12', text: 'An original rap' },
    { id: 'talent_show_13', text: 'A ballet solo' },
    { id: 'talent_show_14', text: 'Beatboxing' },
    { id: 'talent_show_15', text: 'A tap dance routine' },
    { id: 'talent_show_16', text: 'A puppet show' },
    { id: 'talent_show_17', text: 'A gymnastics routine' },
    { id: 'talent_show_18', text: 'A lip sync battle' },
    { id: 'talent_show_19', text: 'A storytelling set' },
    { id: 'talent_show_20', text: 'A guitar solo' },
    { id: 'talent_show_21', text: 'An improv scene' },
    { id: 'talent_show_22', text: 'Baton twirling' },
    { id: 'talent_show_23', text: 'A duet with a friend' },
    { id: 'talent_show_24', text: 'Card sleight of hand' },
    { id: 'talent_show_25', text: 'An opera aria' },
  ],
  last_meal: [
    { id: 'last_meal_01', text: 'Cheeseburger and fries' },
    { id: 'last_meal_02', text: 'Wood-fired pizza' },
    { id: 'last_meal_03', text: 'Sushi omakase' },
    { id: 'last_meal_04', text: 'Chicken tikka masala' },
    { id: 'last_meal_05', text: 'Ramen with pork belly' },
    { id: 'last_meal_06', text: 'Chicken and waffles' },
    { id: 'last_meal_07', text: 'Steak and mashed potatoes' },
    { id: 'last_meal_08', text: 'Pad thai' },
    { id: 'last_meal_09', text: "Mom's spaghetti" },
    { id: 'last_meal_10', text: 'Lobster with butter' },
    { id: 'last_meal_11', text: 'Tacos al pastor' },
    { id: 'last_meal_12', text: 'BBQ ribs and cornbread' },
    { id: 'last_meal_13', text: 'Beef pho' },
    { id: 'last_meal_14', text: 'Chicken parmesan' },
    { id: 'last_meal_15', text: 'Roast turkey dinner' },
    { id: 'last_meal_16', text: 'Pepperoni pizza' },
    { id: 'last_meal_17', text: 'Peking duck' },
    { id: 'last_meal_18', text: 'Grilled cheese and soup' },
    { id: 'last_meal_19', text: 'Chicken biryani' },
    { id: 'last_meal_20', text: 'Croissant and coffee' },
    { id: 'last_meal_21', text: 'Eggs benedict' },
    { id: 'last_meal_22', text: 'Chicken shawarma' },
    { id: 'last_meal_23', text: 'Beef wellington' },
    { id: 'last_meal_24', text: 'Mac and cheese' },
    { id: 'last_meal_25', text: 'Chocolate lava cake' },
  ],
  dream_home: [
    { id: 'dream_home_01', text: 'A big backyard' },
    { id: 'dream_home_02', text: 'A home theater room' },
    { id: 'dream_home_03', text: "A chef's kitchen" },
    { id: 'dream_home_04', text: 'An in-ground pool' },
    { id: 'dream_home_05', text: 'A huge walk-in closet' },
    { id: 'dream_home_06', text: 'A home office' },
    { id: 'dream_home_07', text: 'A library with fireplace' },
    { id: 'dream_home_08', text: 'A wine cellar' },
    { id: 'dream_home_09', text: 'A hot tub on the deck' },
    { id: 'dream_home_10', text: 'A sun-drenched sunroom' },
    { id: 'dream_home_11', text: 'A rooftop deck' },
    { id: 'dream_home_12', text: 'A home gym' },
    { id: 'dream_home_13', text: 'A recording studio' },
    { id: 'dream_home_14', text: 'A guest suite' },
    { id: 'dream_home_15', text: 'A massive garage' },
    { id: 'dream_home_16', text: 'An ocean view' },
    { id: 'dream_home_17', text: 'A mountain view' },
    { id: 'dream_home_18', text: 'A cozy reading nook' },
    { id: 'dream_home_19', text: 'A vegetable garden' },
    { id: 'dream_home_20', text: 'A big walk-in pantry' },
    { id: 'dream_home_21', text: 'A basement game room' },
    { id: 'dream_home_22', text: 'A meditation room' },
    { id: 'dream_home_23', text: 'A private art studio' },
    { id: 'dream_home_24', text: 'Smart home tech' },
    { id: 'dream_home_25', text: 'A backyard sauna' },
  ],
  long_flight: [
    { id: 'long_flight_01', text: 'A window seat' },
    { id: 'long_flight_02', text: 'Noise-canceling headphones' },
    { id: 'long_flight_03', text: 'A great book' },
    { id: 'long_flight_04', text: 'A great in-flight meal' },
    { id: 'long_flight_05', text: 'A neck pillow' },
    { id: 'long_flight_06', text: 'Cozy blanket and socks' },
    { id: 'long_flight_07', text: 'Downloaded movies' },
    { id: 'long_flight_08', text: 'A chatty seatmate' },
    { id: 'long_flight_09', text: 'A business class upgrade' },
    { id: 'long_flight_10', text: 'An empty middle seat' },
    { id: 'long_flight_11', text: 'A crossword puzzle' },
    { id: 'long_flight_12', text: 'Extra legroom' },
    { id: 'long_flight_13', text: 'Snacks from home' },
    { id: 'long_flight_14', text: 'A power outlet' },
    { id: 'long_flight_15', text: 'Wi-Fi onboard' },
    { id: 'long_flight_16', text: 'An eye mask and earplugs' },
    { id: 'long_flight_17', text: 'Free-flowing wine' },
    { id: 'long_flight_18', text: 'A gripping podcast' },
    { id: 'long_flight_19', text: 'Stretching in the aisle' },
    { id: 'long_flight_20', text: 'A fresh change of clothes' },
    { id: 'long_flight_21', text: 'A meditation app' },
    { id: 'long_flight_22', text: 'A handheld game console' },
    { id: 'long_flight_23', text: 'A journal and pen' },
    { id: 'long_flight_24', text: 'A friend beside you' },
    { id: 'long_flight_25', text: 'Bottomless coffee' },
  ],
};
