export default {
  breakfast: [
    { id: "breakfast_01", text: "Pancakes" },
    { id: "breakfast_02", text: "Waffles" },
    { id: "breakfast_03", text: "Scrambled eggs" },
    { id: "breakfast_04", text: "Bacon and eggs" },
    { id: "breakfast_05", text: "French toast" },
    { id: "breakfast_06", text: "Bagel with cream cheese" },
    { id: "breakfast_07", text: "Avocado toast" },
    { id: "breakfast_08", text: "Cereal with milk" },
    { id: "breakfast_09", text: "Oatmeal" },
    { id: "breakfast_10", text: "Yogurt and granola" },
    { id: "breakfast_11", text: "Breakfast burrito" },
    { id: "breakfast_12", text: "Eggs Benedict" },
    { id: "breakfast_13", text: "Fruit salad" },
    { id: "breakfast_14", text: "Croissant" },
    { id: "breakfast_15", text: "Sausage biscuit" },
    { id: "breakfast_16", text: "Hash browns" },
    { id: "breakfast_17", text: "Blueberry muffin" },
    { id: "breakfast_18", text: "Smoothie bowl" },
    { id: "breakfast_19", text: "Toast and jam" },
    { id: "breakfast_20", text: "Cinnamon roll" },
    { id: "breakfast_21", text: "Omelet" },
    { id: "breakfast_22", text: "Grits" },
    { id: "breakfast_23", text: "Congee" },
    { id: "breakfast_24", text: "Shakshuka" },
    { id: "breakfast_25", text: "Cold pizza" },
  ],
  pizza: [
    { id: "pizza_01", text: "Pepperoni" },
    { id: "pizza_02", text: "Mushrooms" },
    { id: "pizza_03", text: "Sausage" },
    { id: "pizza_04", text: "Bell peppers" },
    { id: "pizza_05", text: "Onions" },
    { id: "pizza_06", text: "Black olives" },
    { id: "pizza_07", text: "Pineapple" },
    { id: "pizza_08", text: "Anchovies" },
    { id: "pizza_09", text: "Bacon" },
    { id: "pizza_10", text: "Ham" },
    { id: "pizza_11", text: "Jalapeños" },
    { id: "pizza_12", text: "Extra cheese" },
    { id: "pizza_13", text: "Spinach" },
    { id: "pizza_14", text: "Artichoke hearts" },
    { id: "pizza_15", text: "Sun-dried tomatoes" },
    { id: "pizza_16", text: "Fresh basil" },
    { id: "pizza_17", text: "Roasted garlic" },
    { id: "pizza_18", text: "Ricotta" },
    { id: "pizza_19", text: "Feta" },
    { id: "pizza_20", text: "Chicken" },
    { id: "pizza_21", text: "Ground beef" },
    { id: "pizza_22", text: "Meatballs" },
    { id: "pizza_23", text: "Banana peppers" },
    { id: "pizza_24", text: "Broccoli" },
    { id: "pizza_25", text: "Arugula" },
  ],
  drinks: [
    { id: "drinks_01", text: "Ice water" },
    { id: "drinks_02", text: "Lemonade" },
    { id: "drinks_03", text: "Iced tea" },
    { id: "drinks_04", text: "Hot chocolate" },
    { id: "drinks_05", text: "Chocolate milk" },
    { id: "drinks_06", text: "Orange juice" },
    { id: "drinks_07", text: "Apple juice" },
    { id: "drinks_08", text: "Cola" },
    { id: "drinks_09", text: "Root beer" },
    { id: "drinks_10", text: "Ginger ale" },
    { id: "drinks_11", text: "Sparkling water" },
    { id: "drinks_12", text: "Milkshake" },
    { id: "drinks_13", text: "Fruit smoothie" },
    { id: "drinks_14", text: "Fruit punch" },
    { id: "drinks_15", text: "Sweet tea" },
    { id: "drinks_16", text: "Cranberry juice" },
    { id: "drinks_17", text: "Coconut water" },
    { id: "drinks_18", text: "Kombucha" },
    { id: "drinks_19", text: "Energy drink" },
    { id: "drinks_20", text: "Grape soda" },
    { id: "drinks_21", text: "Diet cola" },
    { id: "drinks_22", text: "A glass of milk" },
    { id: "drinks_23", text: "Horchata" },
    { id: "drinks_24", text: "Bubble tea" },
    { id: "drinks_25", text: "Slushie" },
  ],
  condiments: [
    { id: "condiments_01", text: "Ketchup" },
    { id: "condiments_02", text: "Yellow mustard" },
    { id: "condiments_03", text: "Mayonnaise" },
    { id: "condiments_04", text: "Ranch" },
    { id: "condiments_05", text: "BBQ sauce" },
    { id: "condiments_06", text: "Hot sauce" },
    { id: "condiments_07", text: "Sriracha" },
    { id: "condiments_08", text: "Soy sauce" },
    { id: "condiments_09", text: "Sweet chili sauce" },
    { id: "condiments_10", text: "Honey mustard" },
    { id: "condiments_11", text: "Tartar sauce" },
    { id: "condiments_12", text: "Salsa" },
    { id: "condiments_13", text: "Guacamole" },
    { id: "condiments_14", text: "Pesto" },
    { id: "condiments_15", text: "Garlic aioli" },
    { id: "condiments_16", text: "Pickle relish" },
    { id: "condiments_17", text: "Horseradish" },
    { id: "condiments_18", text: "Wasabi" },
    { id: "condiments_19", text: "Chimichurri" },
    { id: "condiments_20", text: "Tzatziki" },
    { id: "condiments_21", text: "Steak sauce" },
    { id: "condiments_22", text: "Cocktail sauce" },
    { id: "condiments_23", text: "Dijon mustard" },
    { id: "condiments_24", text: "Buffalo sauce" },
    { id: "condiments_25", text: "Malt vinegar" },
  ],
  fast_food: [
    { id: "fast_food_01", text: "Cheeseburger" },
    { id: "fast_food_02", text: "Chicken nuggets" },
    { id: "fast_food_03", text: "French fries" },
    { id: "fast_food_04", text: "Fish sandwich" },
    { id: "fast_food_05", text: "Chicken sandwich" },
    { id: "fast_food_06", text: "Bacon cheeseburger" },
    { id: "fast_food_07", text: "Double cheeseburger" },
    { id: "fast_food_08", text: "Onion rings" },
    { id: "fast_food_09", text: "Chicken tenders" },
    { id: "fast_food_10", text: "A hard shell taco" },
    { id: "fast_food_11", text: "Burrito" },
    { id: "fast_food_12", text: "Quesadilla" },
    { id: "fast_food_13", text: "Hot dog" },
    { id: "fast_food_14", text: "Corn dog" },
    { id: "fast_food_15", text: "Chili cheese fries" },
    { id: "fast_food_16", text: "Loaded nachos" },
    { id: "fast_food_17", text: "Chicken wrap" },
    { id: "fast_food_18", text: "Veggie burger" },
    { id: "fast_food_19", text: "Grilled chicken salad" },
    { id: "fast_food_20", text: "Mozzarella sticks" },
    { id: "fast_food_21", text: "Vanilla shake" },
    { id: "fast_food_22", text: "Kids meal" },
    { id: "fast_food_23", text: "Spicy chicken sandwich" },
    { id: "fast_food_24", text: "Breakfast sandwich" },
    { id: "fast_food_25", text: "Soft-serve cone" },
  ],
  coffee: [
    { id: "coffee_01", text: "Black coffee" },
    { id: "coffee_02", text: "Latte" },
    { id: "coffee_03", text: "Cappuccino" },
    { id: "coffee_04", text: "Americano" },
    { id: "coffee_05", text: "Espresso shot" },
    { id: "coffee_06", text: "Iced latte" },
    { id: "coffee_07", text: "Iced coffee" },
    { id: "coffee_08", text: "Cold brew" },
    { id: "coffee_09", text: "Mocha" },
    { id: "coffee_10", text: "Vanilla latte" },
    { id: "coffee_11", text: "Caramel macchiato" },
    { id: "coffee_12", text: "Flat white" },
    { id: "coffee_13", text: "Pumpkin spice latte" },
    { id: "coffee_14", text: "Cortado" },
    { id: "coffee_15", text: "Nitro cold brew" },
    { id: "coffee_16", text: "Frappuccino" },
    { id: "coffee_17", text: "Double espresso" },
    { id: "coffee_18", text: "Macchiato" },
    { id: "coffee_19", text: "Affogato" },
    { id: "coffee_20", text: "Café au lait" },
    { id: "coffee_21", text: "Turkish coffee" },
    { id: "coffee_22", text: "Iced mocha" },
    { id: "coffee_23", text: "Hazelnut latte" },
    { id: "coffee_24", text: "Honey oat latte" },
    { id: "coffee_25", text: "Decaf coffee" },
  ],
  candy: [
    { id: "candy_01", text: "A chocolate bar" },
    { id: "candy_02", text: "Gummy bears" },
    { id: "candy_03", text: "Sour gummies" },
    { id: "candy_04", text: "Licorice" },
    { id: "candy_05", text: "Peanut butter cups" },
    { id: "candy_06", text: "Caramels" },
    { id: "candy_07", text: "Jelly beans" },
    { id: "candy_08", text: "Candy corn" },
    { id: "candy_09", text: "Marshmallows" },
    { id: "candy_10", text: "Lollipops" },
    { id: "candy_11", text: "Chocolate truffles" },
    { id: "candy_12", text: "Toffee" },
    { id: "candy_13", text: "Peppermints" },
    { id: "candy_14", text: "Chewing gum" },
    { id: "candy_15", text: "Fruit chews" },
    { id: "candy_16", text: "Chocolate almonds" },
    { id: "candy_17", text: "Sour belts" },
    { id: "candy_18", text: "A nougat bar" },
    { id: "candy_19", text: "Bubblegum" },
    { id: "candy_20", text: "Rock candy" },
    { id: "candy_21", text: "Cotton candy" },
    { id: "candy_22", text: "Milk chocolate" },
    { id: "candy_23", text: "Dark chocolate" },
    { id: "candy_24", text: "White chocolate" },
    { id: "candy_25", text: "Gummy worms" },
  ],
  comforts: [
    { id: "comforts_01", text: "Your bed" },
    { id: "comforts_02", text: "Hot showers" },
    { id: "comforts_03", text: "Your morning coffee" },
    { id: "comforts_04", text: "Air conditioning" },
    { id: "comforts_05", text: "Your phone" },
    { id: "comforts_06", text: "Wi-Fi at home" },
    { id: "comforts_07", text: "Home cooking" },
    { id: "comforts_08", text: "A favorite chair" },
    { id: "comforts_09", text: "Soft blankets" },
    { id: "comforts_10", text: "Slippers" },
    { id: "comforts_11", text: "Sunlight in the house" },
    { id: "comforts_12", text: "A morning routine" },
    { id: "comforts_13", text: "Quiet time alone" },
    { id: "comforts_14", text: "A hug" },
    { id: "comforts_15", text: "Your favorite playlist" },
    { id: "comforts_16", text: "A stack of books" },
    { id: "comforts_17", text: "Naps" },
    { id: "comforts_18", text: "A pet at home" },
    { id: "comforts_19", text: "Fresh sheets" },
    { id: "comforts_20", text: "Comfortable shoes" },
    { id: "comforts_21", text: "Your favorite mug" },
    { id: "comforts_22", text: "A good pillow" },
    { id: "comforts_23", text: "Long baths" },
    { id: "comforts_24", text: "Streaming shows" },
    { id: "comforts_25", text: "A stocked pantry" },
  ],
  smells: [
    { id: "smells_01", text: "Fresh bread" },
    { id: "smells_02", text: "Coffee brewing" },
    { id: "smells_03", text: "Rain on pavement" },
    { id: "smells_04", text: "Cut grass" },
    { id: "smells_05", text: "Bacon frying" },
    { id: "smells_06", text: "Pine trees" },
    { id: "smells_07", text: "Lavender" },
    { id: "smells_08", text: "Vanilla" },
    { id: "smells_09", text: "Cinnamon" },
    { id: "smells_10", text: "Old books" },
    { id: "smells_11", text: "Campfire smoke" },
    { id: "smells_12", text: "Ocean breeze" },
    { id: "smells_13", text: "A new car" },
    { id: "smells_14", text: "Gasoline" },
    { id: "smells_15", text: "Chlorine" },
    { id: "smells_16", text: "Sunscreen" },
    { id: "smells_17", text: "Baby powder" },
    { id: "smells_18", text: "Fresh laundry" },
    { id: "smells_19", text: "Peppermint" },
    { id: "smells_20", text: "Wet dog" },
    { id: "smells_21", text: "Popcorn" },
    { id: "smells_22", text: "Leather" },
    { id: "smells_23", text: "Nail polish" },
    { id: "smells_24", text: "Bakery frosting" },
    { id: "smells_25", text: "Damp earth" },
  ],
  sounds: [
    { id: "sounds_01", text: "Rain on a roof" },
    { id: "sounds_02", text: "Ocean waves" },
    { id: "sounds_03", text: "A crackling fire" },
    { id: "sounds_04", text: "A purring cat" },
    { id: "sounds_05", text: "Birds chirping" },
    { id: "sounds_06", text: "Wind in the trees" },
    { id: "sounds_07", text: "Bubble wrap popping" },
    { id: "sounds_08", text: "Snow crunching" },
    { id: "sounds_09", text: "A page turning" },
    { id: "sounds_10", text: "Distant thunder" },
    { id: "sounds_11", text: "Keyboard typing" },
    { id: "sounds_12", text: "Church bells" },
    { id: "sounds_13", text: "A crowd cheering" },
    { id: "sounds_14", text: "A humming fridge" },
    { id: "sounds_15", text: "A ceiling fan" },
    { id: "sounds_16", text: "Ice in a glass" },
    { id: "sounds_17", text: "A whistling kettle" },
    { id: "sounds_18", text: "Whispered talking" },
    { id: "sounds_19", text: "Someone humming" },
    { id: "sounds_20", text: "A ticking clock" },
    { id: "sounds_21", text: "A dog barking" },
    { id: "sounds_22", text: "Wind chimes" },
    { id: "sounds_23", text: "Popcorn popping" },
    { id: "sounds_24", text: "A creaky door" },
    { id: "sounds_25", text: "Cracking knuckles" },
  ],
  weather: [
    { id: "weather_01", text: "Sunny and warm" },
    { id: "weather_02", text: "Sunny and hot" },
    { id: "weather_03", text: "Light rain" },
    { id: "weather_04", text: "A thunderstorm" },
    { id: "weather_05", text: "Snow falling" },
    { id: "weather_06", text: "A blizzard" },
    { id: "weather_07", text: "Foggy morning" },
    { id: "weather_08", text: "Overcast and cool" },
    { id: "weather_09", text: "Windy day" },
    { id: "weather_10", text: "Humid heat" },
    { id: "weather_11", text: "Crisp autumn day" },
    { id: "weather_12", text: "Spring breeze" },
    { id: "weather_13", text: "Cold and dry" },
    { id: "weather_14", text: "Freezing rain" },
    { id: "weather_15", text: "A hailstorm" },
    { id: "weather_16", text: "A heat wave" },
    { id: "weather_17", text: "A cold snap" },
    { id: "weather_18", text: "Drizzle" },
    { id: "weather_19", text: "Muggy night" },
    { id: "weather_20", text: "Clear cold night" },
    { id: "weather_21", text: "Sunset skies" },
    { id: "weather_22", text: "Fresh snow" },
    { id: "weather_23", text: "Warm summer rain" },
    { id: "weather_24", text: "Sleet" },
    { id: "weather_25", text: "Cloudy and mild" },
  ],
  seasons: [
    { id: "seasons_01", text: "First snowfall" },
    { id: "seasons_02", text: "Christmas morning" },
    { id: "seasons_03", text: "Halloween costumes" },
    { id: "seasons_04", text: "Thanksgiving dinner" },
    { id: "seasons_05", text: "Summer vacation" },
    { id: "seasons_06", text: "Beach days" },
    { id: "seasons_07", text: "Fall leaves changing" },
    { id: "seasons_08", text: "Spring flowers blooming" },
    { id: "seasons_09", text: "New Year fireworks" },
    { id: "seasons_10", text: "Fourth of July cookouts" },
    { id: "seasons_11", text: "Back to school season" },
    { id: "seasons_12", text: "A pumpkin patch trip" },
    { id: "seasons_13", text: "Valentine chocolates" },
    { id: "seasons_14", text: "Easter egg hunts" },
    { id: "seasons_15", text: "Long summer evenings" },
    { id: "seasons_16", text: "Cozy winter nights" },
    { id: "seasons_17", text: "Iced drinks in summer" },
    { id: "seasons_18", text: "Hot cocoa in winter" },
    { id: "seasons_19", text: "The first warm day" },
    { id: "seasons_20", text: "Sweater weather" },
    { id: "seasons_21", text: "Fireflies at dusk" },
    { id: "seasons_22", text: "Ski trips" },
    { id: "seasons_23", text: "Bonfires with friends" },
    { id: "seasons_24", text: "Farmers market season" },
    { id: "seasons_25", text: "Holiday shopping" },
  ],
  destinations: [
    { id: "destinations_01", text: "Japan" },
    { id: "destinations_02", text: "Italy" },
    { id: "destinations_03", text: "France" },
    { id: "destinations_04", text: "Iceland" },
    { id: "destinations_05", text: "New Zealand" },
    { id: "destinations_06", text: "Egypt" },
    { id: "destinations_07", text: "Greece" },
    { id: "destinations_08", text: "Morocco" },
    { id: "destinations_09", text: "A Kenya safari" },
    { id: "destinations_10", text: "The Norwegian fjords" },
    { id: "destinations_11", text: "The Great Wall of China" },
    { id: "destinations_12", text: "Machu Picchu" },
    { id: "destinations_13", text: "The Northern Lights" },
    { id: "destinations_14", text: "The Grand Canyon" },
    { id: "destinations_15", text: "Australia" },
    { id: "destinations_16", text: "Thailand" },
    { id: "destinations_17", text: "Ireland" },
    { id: "destinations_18", text: "Switzerland" },
    { id: "destinations_19", text: "Brazil" },
    { id: "destinations_20", text: "India" },
    { id: "destinations_21", text: "South Korea" },
    { id: "destinations_22", text: "Antarctica" },
    { id: "destinations_23", text: "The Amazon rainforest" },
    { id: "destinations_24", text: "Petra" },
    { id: "destinations_25", text: "Angkor Wat" },
  ],
  vacations: [
    { id: "vacations_01", text: "Beach resort" },
    { id: "vacations_02", text: "Backpacking abroad" },
    { id: "vacations_03", text: "Cross-country road trip" },
    { id: "vacations_04", text: "Ocean cruise" },
    { id: "vacations_05", text: "All-inclusive resort" },
    { id: "vacations_06", text: "Ski trip" },
    { id: "vacations_07", text: "Camping in the woods" },
    { id: "vacations_08", text: "Mountain cabin stay" },
    { id: "vacations_09", text: "Big city weekend" },
    { id: "vacations_10", text: "Small town getaway" },
    { id: "vacations_11", text: "Family reunion trip" },
    { id: "vacations_12", text: "Solo travel abroad" },
    { id: "vacations_13", text: "Group bus tour" },
    { id: "vacations_14", text: "Music festival trip" },
    { id: "vacations_15", text: "Theme park vacation" },
    { id: "vacations_16", text: "National park trip" },
    { id: "vacations_17", text: "Wine country tour" },
    { id: "vacations_18", text: "Food tour trip" },
    { id: "vacations_19", text: "Wellness retreat" },
    { id: "vacations_20", text: "Volunteer trip abroad" },
    { id: "vacations_21", text: "Staycation at home" },
    { id: "vacations_22", text: "Safari trip" },
    { id: "vacations_23", text: "River cruise" },
    { id: "vacations_24", text: "Historical sites tour" },
    { id: "vacations_25", text: "Island hopping" },
  ],
  cities: [
    { id: "cities_01", text: "New York City" },
    { id: "cities_02", text: "Los Angeles" },
    { id: "cities_03", text: "Chicago" },
    { id: "cities_04", text: "San Francisco" },
    { id: "cities_05", text: "Seattle" },
    { id: "cities_06", text: "Austin" },
    { id: "cities_07", text: "Miami" },
    { id: "cities_08", text: "Denver" },
    { id: "cities_09", text: "Nashville" },
    { id: "cities_10", text: "Boston" },
    { id: "cities_11", text: "Portland" },
    { id: "cities_12", text: "New Orleans" },
    { id: "cities_13", text: "Honolulu" },
    { id: "cities_14", text: "London" },
    { id: "cities_15", text: "Paris" },
    { id: "cities_16", text: "Tokyo" },
    { id: "cities_17", text: "Berlin" },
    { id: "cities_18", text: "Barcelona" },
    { id: "cities_19", text: "Amsterdam" },
    { id: "cities_20", text: "Sydney" },
    { id: "cities_21", text: "Vancouver" },
    { id: "cities_22", text: "Montreal" },
    { id: "cities_23", text: "Dubai" },
    { id: "cities_24", text: "Singapore" },
    { id: "cities_25", text: "Mexico City" },
  ],
};
