export default {
  small_wins: [
    { id: 'small_wins_01', text: 'Finding cash in an old coat' },
    { id: 'small_wins_02', text: 'A perfect parking spot' },
    { id: 'small_wins_03', text: "A stranger's compliment" },
    { id: 'small_wins_04', text: 'Free samples at the store' },
    { id: 'small_wins_05', text: 'No line at the coffee shop' },
    { id: 'small_wins_06', text: 'Green lights the whole way' },
    { id: 'small_wins_07', text: 'A text from an old friend' },
    { id: 'small_wins_08', text: 'Nailing a recipe first try' },
    { id: 'small_wins_09', text: 'Clean sheets on the bed' },
    { id: 'small_wins_10', text: 'A song you forgot you loved' },
    { id: 'small_wins_11', text: 'Beating a personal best' },
    { id: 'small_wins_12', text: 'A dog wanting to say hi' },
    { id: 'small_wins_13', text: 'A package arriving early' },
    { id: 'small_wins_14', text: 'Getting the window seat' },
    { id: 'small_wins_15', text: 'A good hair day' },
    { id: 'small_wins_16', text: 'Zero unread emails' },
    { id: 'small_wins_17', text: 'Someone laughing at your joke' },
    { id: 'small_wins_18', text: 'Sunshine after a rainy week' },
    { id: 'small_wins_19', text: 'A really good nap' },
    { id: 'small_wins_20', text: 'A refund you forgot about' },
    { id: 'small_wins_21', text: 'Cracking a hard crossword' },
    { id: 'small_wins_22', text: 'A grocery run under budget' },
    { id: 'small_wins_23', text: 'A kind note from a stranger' },
    { id: 'small_wins_24', text: 'A weekend starting Friday' },
    { id: 'small_wins_25', text: 'Your team winning' },
  ],
  first_dates: [
    { id: 'first_dates_01', text: 'A fancy dinner reservation' },
    { id: 'first_dates_02', text: 'Meeting for coffee' },
    { id: 'first_dates_03', text: 'A long walk in the park' },
    { id: 'first_dates_04', text: 'A crowded bar' },
    { id: 'first_dates_05', text: 'Bowling' },
    { id: 'first_dates_06', text: 'Cooking a meal together' },
    { id: 'first_dates_07', text: 'A hike' },
    { id: 'first_dates_08', text: 'A concert' },
    { id: 'first_dates_09', text: 'Meeting at their place' },
    { id: 'first_dates_10', text: 'A double date' },
    { id: 'first_dates_11', text: 'Rock climbing' },
    { id: 'first_dates_12', text: 'Karaoke' },
    { id: 'first_dates_13', text: 'A movie' },
    { id: 'first_dates_14', text: 'Mini golf' },
    { id: 'first_dates_15', text: 'A cocktail-making class' },
    { id: 'first_dates_16', text: 'A game at a sports bar' },
    { id: 'first_dates_17', text: 'A picnic' },
    { id: 'first_dates_18', text: 'A museum visit' },
    { id: 'first_dates_19', text: 'A comedy show' },
    { id: 'first_dates_20', text: 'Meeting their friends' },
    { id: 'first_dates_21', text: 'A weekend trip' },
    { id: 'first_dates_22', text: 'Going dancing' },
    { id: 'first_dates_23', text: 'A pottery class' },
    { id: 'first_dates_24', text: 'Going for ice cream' },
    { id: 'first_dates_25', text: 'Meeting after work' },
  ],
  date_ideas: [
    { id: 'date_ideas_01', text: 'A nice dinner out' },
    { id: 'date_ideas_02', text: 'A sunset drive' },
    { id: 'date_ideas_03', text: 'The farmers market together' },
    { id: 'date_ideas_04', text: 'A board game night' },
    { id: 'date_ideas_05', text: 'A dive bar' },
    { id: 'date_ideas_06', text: 'A cooking class' },
    { id: 'date_ideas_07', text: 'An amusement park' },
    { id: 'date_ideas_08', text: 'Trivia night' },
    { id: 'date_ideas_09', text: 'A live music show' },
    { id: 'date_ideas_10', text: 'A day at the beach' },
    { id: 'date_ideas_11', text: 'Wine tasting' },
    { id: 'date_ideas_12', text: 'A late-night diner' },
    { id: 'date_ideas_13', text: 'Browsing a bookstore' },
    { id: 'date_ideas_14', text: 'A road trip' },
    { id: 'date_ideas_15', text: 'An escape room' },
    { id: 'date_ideas_16', text: 'Ice skating' },
    { id: 'date_ideas_17', text: 'A movie marathon at home' },
    { id: 'date_ideas_18', text: 'A long brunch' },
    { id: 'date_ideas_19', text: 'A karaoke night' },
    { id: 'date_ideas_20', text: 'Stargazing' },
    { id: 'date_ideas_21', text: 'A day at the zoo' },
    { id: 'date_ideas_22', text: 'A costume party' },
    { id: 'date_ideas_23', text: 'A cocktail bar' },
    { id: 'date_ideas_24', text: 'A backyard barbecue' },
    { id: 'date_ideas_25', text: 'Dance lessons' },
  ],
  at_a_party: [
    { id: 'at_a_party_01', text: 'First on the dance floor' },
    { id: 'at_a_party_02', text: 'Deep in a corner conversation' },
    { id: 'at_a_party_03', text: 'Running the music' },
    { id: 'at_a_party_04', text: 'Caring for the drunk friend' },
    { id: 'at_a_party_05', text: 'Hosting in the kitchen' },
    { id: 'at_a_party_06', text: 'Petting the dog all night' },
    { id: 'at_a_party_07', text: 'Hiding on the porch' },
    { id: 'at_a_party_08', text: 'Pouring everyone shots' },
    { id: 'at_a_party_09', text: 'Leaving after an hour' },
    { id: 'at_a_party_10', text: 'Meeting five new people' },
    { id: 'at_a_party_11', text: 'Telling long stories' },
    { id: 'at_a_party_12', text: 'Guarding the snack table' },
    { id: 'at_a_party_13', text: 'Judging the playlist quietly' },
    { id: 'at_a_party_14', text: 'Starting the dance floor' },
    { id: 'at_a_party_15', text: 'Doing dishes way too early' },
    { id: 'at_a_party_16', text: 'Trapped by one talker' },
    { id: 'at_a_party_17', text: 'Glued to your phone' },
    { id: 'at_a_party_18', text: 'Ordering everyone a ride home' },
    { id: 'at_a_party_19', text: 'Leading a group singalong' },
    { id: 'at_a_party_20', text: 'Filming everything' },
    { id: 'at_a_party_21', text: 'Cleaning up with the host' },
    { id: 'at_a_party_22', text: 'Starting a game' },
    { id: 'at_a_party_23', text: 'Losing your shoes' },
    { id: 'at_a_party_24', text: 'Watching from the couch' },
    { id: 'at_a_party_25', text: 'Making a new best friend' },
  ],
  travel_style: [
    { id: 'travel_style_01', text: 'Every hour planned' },
    { id: 'travel_style_02', text: 'No plan, no problem' },
    { id: 'travel_style_03', text: 'All-inclusive resort' },
    { id: 'travel_style_04', text: 'Off the beaten path' },
    { id: 'travel_style_05', text: 'Museums and history' },
    { id: 'travel_style_06', text: 'Beach and nothing else' },
    { id: 'travel_style_07', text: 'Chasing the local food' },
    { id: 'travel_style_08', text: 'Backpacking on a budget' },
    { id: 'travel_style_09', text: 'Splurging on a nice hotel' },
    { id: 'travel_style_10', text: 'Guided tours all the way' },
    { id: 'travel_style_11', text: 'Rental car and a map' },
    { id: 'travel_style_12', text: 'City nightlife' },
    { id: 'travel_style_13', text: 'Nature and long hikes' },
    { id: 'travel_style_14', text: 'The same trip every year' },
    { id: 'travel_style_15', text: 'Somewhere new each time' },
    { id: 'travel_style_16', text: 'Solo travel' },
    { id: 'travel_style_17', text: 'Big group trips' },
    { id: 'travel_style_18', text: 'A classic family road trip' },
    { id: 'travel_style_19', text: 'Chasing sunsets and photos' },
    { id: 'travel_style_20', text: 'Working from a new city' },
    { id: 'travel_style_21', text: 'Learning the language' },
    { id: 'travel_style_22', text: 'Overpacking every time' },
    { id: 'travel_style_23', text: 'Carry-on only' },
    { id: 'travel_style_24', text: 'Long layovers on purpose' },
    { id: 'travel_style_25', text: 'A cruise ship vacation' },
  ],
  airports: [
    { id: 'airports_01', text: 'Arriving three hours early' },
    { id: 'airports_02', text: 'Sprinting to the gate' },
    { id: 'airports_03', text: 'A drink at the airport bar' },
    { id: 'airports_04', text: 'Airport shopping' },
    { id: 'airports_05', text: 'Reading a whole book' },
    { id: 'airports_06', text: 'Working on your laptop' },
    { id: 'airports_07', text: 'People-watching' },
    { id: 'airports_08', text: 'Napping at the gate' },
    { id: 'airports_09', text: 'Calling everyone you know' },
    { id: 'airports_10', text: 'Grabbing fast food' },
    { id: 'airports_11', text: 'Sitting in silence' },
    { id: 'airports_12', text: 'Charging every device' },
    { id: 'airports_13', text: 'Wandering the terminal' },
    { id: 'airports_14', text: 'Chatting up strangers' },
    { id: 'airports_15', text: 'Splurging on the lounge' },
    { id: 'airports_16', text: 'A podcast and a long walk' },
    { id: 'airports_17', text: 'Watching planes take off' },
    { id: 'airports_18', text: 'Doomscrolling' },
    { id: 'airports_19', text: 'A second breakfast' },
    { id: 'airports_20', text: 'Journaling at the gate' },
    { id: 'airports_21', text: 'Boarding at the last call' },
    { id: 'airports_22', text: 'Checking the flight board' },
    { id: 'airports_23', text: 'Buying a magazine' },
    { id: 'airports_24', text: 'Browsing duty free' },
    { id: 'airports_25', text: 'Pacing for step count' },
  ],
  money: [
    { id: 'money_01', text: 'Great food' },
    { id: 'money_02', text: 'Concert tickets' },
    { id: 'money_03', text: 'Travel' },
    { id: 'money_04', text: 'Clothes' },
    { id: 'money_05', text: 'Books' },
    { id: 'money_06', text: 'Nice coffee' },
    { id: 'money_07', text: 'Skincare' },
    { id: 'money_08', text: 'Gifts for friends' },
    { id: 'money_09', text: 'A big night out' },
    { id: 'money_10', text: 'Home decor' },
    { id: 'money_11', text: 'Gym or fitness classes' },
    { id: 'money_12', text: 'Tech gadgets' },
    { id: 'money_13', text: 'Sports gear' },
    { id: 'money_14', text: 'A great haircut' },
    { id: 'money_15', text: 'Streaming subscriptions' },
    { id: 'money_16', text: 'Art and prints' },
    { id: 'money_17', text: 'Plants' },
    { id: 'money_18', text: 'Board games' },
    { id: 'money_19', text: 'Kitchen gear' },
    { id: 'money_20', text: 'Video games' },
    { id: 'money_21', text: 'Cocktails out' },
    { id: 'money_22', text: 'A good bottle of wine' },
    { id: 'money_23', text: 'Sports tickets' },
    { id: 'money_24', text: 'A spa day' },
    { id: 'money_25', text: 'Giving to charity' },
  ],
  splurging: [
    { id: 'splurging_01', text: 'A first class flight' },
    { id: 'splurging_02', text: 'A nicer hotel room' },
    { id: 'splurging_03', text: 'Front row seats' },
    { id: 'splurging_04', text: 'Really nice sheets' },
    { id: 'splurging_05', text: 'A better mattress' },
    { id: 'splurging_06', text: 'Fancy headphones' },
    { id: 'splurging_07', text: 'High-end skincare' },
    { id: 'splurging_08', text: "A great chef's knife" },
    { id: 'splurging_09', text: 'Nicer running shoes' },
    { id: 'splurging_10', text: 'A bigger TV' },
    { id: 'splurging_11', text: 'Faster home internet' },
    { id: 'splurging_12', text: 'Premium coffee beans' },
    { id: 'splurging_13', text: 'A quality winter coat' },
    { id: 'splurging_14', text: 'Better tires' },
    { id: 'splurging_15', text: 'A tasting menu dinner' },
    { id: 'splurging_16', text: 'A designer bag' },
    { id: 'splurging_17', text: 'Fresh flowers weekly' },
    { id: 'splurging_18', text: 'A memory foam pillow' },
    { id: 'splurging_19', text: 'Top-shelf liquor' },
    { id: 'splurging_20', text: 'A car service over rideshare' },
    { id: 'splurging_21', text: 'Nicer luggage' },
    { id: 'splurging_22', text: 'A better desk chair' },
    { id: 'splurging_23', text: 'Tailored clothes' },
    { id: 'splurging_24', text: 'Private lessons' },
    { id: 'splurging_25', text: 'A newer phone' },
  ],
  weekends: [
    { id: 'weekends_01', text: 'Sleeping in both days' },
    { id: 'weekends_02', text: 'A long hike' },
    { id: 'weekends_03', text: 'A house party' },
    { id: 'weekends_04', text: 'A Saturday night concert' },
    { id: 'weekends_05', text: 'A farmers market run' },
    { id: 'weekends_06', text: 'A short road trip' },
    { id: 'weekends_07', text: 'Deep cleaning the house' },
    { id: 'weekends_08', text: 'A big brunch out' },
    { id: 'weekends_09', text: 'A movie marathon' },
    { id: 'weekends_10', text: 'Yard work in the sun' },
    { id: 'weekends_11', text: 'A board game afternoon' },
    { id: 'weekends_12', text: 'A backyard barbecue' },
    { id: 'weekends_13', text: 'A day at the beach' },
    { id: 'weekends_14', text: 'A solo bookstore trip' },
    { id: 'weekends_15', text: 'Cooking something ambitious' },
    { id: 'weekends_16', text: 'Nothing on the calendar' },
    { id: 'weekends_17', text: 'A wedding out of town' },
    { id: 'weekends_18', text: 'A big family gathering' },
    { id: 'weekends_19', text: 'A pickup game with friends' },
    { id: 'weekends_20', text: 'A long bike ride' },
    { id: 'weekends_21', text: 'Fixing things around home' },
    { id: 'weekends_22', text: 'A day at a museum' },
    { id: 'weekends_23', text: 'Trying a new restaurant' },
    { id: 'weekends_24', text: 'Volunteering somewhere' },
    { id: 'weekends_25', text: 'Catching up with a friend' },
  ],
  free_hour: [
    { id: 'free_hour_01', text: 'A power nap' },
    { id: 'free_hour_02', text: 'A quick workout' },
    { id: 'free_hour_03', text: 'Reading a book' },
    { id: 'free_hour_04', text: 'Scrolling your phone' },
    { id: 'free_hour_05', text: 'A walk outside' },
    { id: 'free_hour_06', text: 'Playing a video game' },
    { id: 'free_hour_07', text: 'Calling a friend' },
    { id: 'free_hour_08', text: 'A long hot shower' },
    { id: 'free_hour_09', text: 'Cleaning your space' },
    { id: 'free_hour_10', text: 'Trying a new recipe' },
    { id: 'free_hour_11', text: 'Working on a hobby' },
    { id: 'free_hour_12', text: 'A crossword or puzzle' },
    { id: 'free_hour_13', text: 'Stretching on the floor' },
    { id: 'free_hour_14', text: 'Learning something new online' },
    { id: 'free_hour_15', text: 'Baking something' },
    { id: 'free_hour_16', text: 'Playing an instrument' },
    { id: 'free_hour_17', text: 'A quick errand' },
    { id: 'free_hour_18', text: 'Puttering in the garden' },
    { id: 'free_hour_19', text: 'Watching an episode' },
    { id: 'free_hour_20', text: 'A long bath' },
    { id: 'free_hour_21', text: 'Organizing a drawer' },
    { id: 'free_hour_22', text: 'Sitting outside doing nothing' },
    { id: 'free_hour_23', text: 'Doodling or sketching' },
    { id: 'free_hour_24', text: 'Prepping tomorrow morning' },
    { id: 'free_hour_25', text: 'Meal prepping for the week' },
  ],
  stress: [
    { id: 'stress_01', text: 'Deep breathing' },
    { id: 'stress_02', text: 'A long walk alone' },
    { id: 'stress_03', text: 'A hot shower' },
    { id: 'stress_04', text: 'Venting to a friend' },
    { id: 'stress_05', text: 'Cleaning something' },
    { id: 'stress_06', text: 'Loud music alone' },
    { id: 'stress_07', text: 'A hard workout' },
    { id: 'stress_08', text: 'Baking a treat' },
    { id: 'stress_09', text: 'Journaling it out' },
    { id: 'stress_10', text: 'Petting an animal' },
    { id: 'stress_11', text: 'A good cry' },
    { id: 'stress_12', text: 'A yoga class' },
    { id: 'stress_13', text: 'A comfort movie' },
    { id: 'stress_14', text: 'Making a to-do list' },
    { id: 'stress_15', text: 'A hot cup of tea' },
    { id: 'stress_16', text: 'Weeding the garden' },
    { id: 'stress_17', text: 'A drive with no destination' },
    { id: 'stress_18', text: 'Screaming into a pillow' },
    { id: 'stress_19', text: 'A weighted blanket' },
    { id: 'stress_20', text: 'Rewatching a comfort show' },
    { id: 'stress_21', text: 'Sitting in the sun' },
    { id: 'stress_22', text: 'Cooking a big meal' },
    { id: 'stress_23', text: 'A meditation app' },
    { id: 'stress_24', text: 'A really long nap' },
    { id: 'stress_25', text: 'Going for a swim' },
  ],
  rest: [
    { id: 'rest_01', text: 'A full night of sleep' },
    { id: 'rest_02', text: 'A long weekend off' },
    { id: 'rest_03', text: 'Time completely alone' },
    { id: 'rest_04', text: 'A break from your phone' },
    { id: 'rest_05', text: 'A day of no decisions' },
    { id: 'rest_06', text: 'An actual vacation' },
    { id: 'rest_07', text: 'A nap on the couch' },
    { id: 'rest_08', text: 'A quiet slow morning' },
    { id: 'rest_09', text: 'A break from social plans' },
    { id: 'rest_10', text: 'Not thinking about work' },
    { id: 'rest_11', text: 'Time in nature' },
    { id: 'rest_12', text: 'A break from the news' },
    { id: 'rest_13', text: 'Sleeping in one morning' },
    { id: 'rest_14', text: 'A day of doing nothing' },
    { id: 'rest_15', text: 'A break from cooking' },
    { id: 'rest_16', text: 'A break from driving' },
    { id: 'rest_17', text: 'A quiet dinner alone' },
    { id: 'rest_18', text: 'A break from your inbox' },
    { id: 'rest_19', text: 'Time away from family' },
    { id: 'rest_20', text: 'A screen-free evening' },
    { id: 'rest_21', text: 'Not being needed for a day' },
    { id: 'rest_22', text: 'A very slow Sunday' },
    { id: 'rest_23', text: 'A day off with no plans' },
    { id: 'rest_24', text: 'Real silence' },
    { id: 'rest_25', text: 'Being totally unreachable' },
  ],
  how_you_work: [
    { id: 'how_you_work_01', text: 'Early mornings, no talking' },
    { id: 'how_you_work_02', text: 'Long blocks of deep focus' },
    { id: 'how_you_work_03', text: 'Short bursts with breaks' },
    { id: 'how_you_work_04', text: 'Music blasting' },
    { id: 'how_you_work_05', text: 'Total silence' },
    { id: 'how_you_work_06', text: 'A busy coffee shop' },
    { id: 'how_you_work_07', text: 'Working with a team' },
    { id: 'how_you_work_08', text: 'Alone with a clear task' },
    { id: 'how_you_work_09', text: 'Tight deadlines' },
    { id: 'how_you_work_10', text: 'Loose deadlines' },
    { id: 'how_you_work_11', text: 'A perfectly tidy desk' },
    { id: 'how_you_work_12', text: 'Controlled chaos' },
    { id: 'how_you_work_13', text: 'Talking things through' },
    { id: 'how_you_work_14', text: 'Making lists first' },
    { id: 'how_you_work_15', text: 'Diving straight in' },
    { id: 'how_you_work_16', text: 'Late-night sessions' },
    { id: 'how_you_work_17', text: 'Pacing at a standing desk' },
    { id: 'how_you_work_18', text: 'Snacks within reach' },
    { id: 'how_you_work_19', text: 'Notifications off' },
    { id: 'how_you_work_20', text: 'One tab at a time' },
    { id: 'how_you_work_21', text: 'Ten tabs at once' },
    { id: 'how_you_work_22', text: 'A big whiteboard' },
    { id: 'how_you_work_23', text: 'Detailed plans upfront' },
    { id: 'how_you_work_24', text: 'Making it up as you go' },
    { id: 'how_you_work_25', text: 'Frequent check-ins' },
  ],
  working_from_home: [
    { id: 'working_from_home_01', text: 'Sleeping in' },
    { id: 'working_from_home_02', text: 'No commute' },
    { id: 'working_from_home_03', text: 'Pajamas all day' },
    { id: 'working_from_home_04', text: 'Cooking your own lunch' },
    { id: 'working_from_home_05', text: 'Laundry between calls' },
    { id: 'working_from_home_06', text: 'Your own bathroom' },
    { id: 'working_from_home_07', text: 'Your own coffee' },
    { id: 'working_from_home_08', text: 'A midday walk' },
    { id: 'working_from_home_09', text: 'A cat on your lap' },
    { id: 'working_from_home_10', text: 'Blasting your own music' },
    { id: 'working_from_home_11', text: 'Working from bed' },
    { id: 'working_from_home_12', text: 'No coworker noise' },
    { id: 'working_from_home_13', text: 'A midday nap' },
    { id: 'working_from_home_14', text: 'Camera off all day' },
    { id: 'working_from_home_15', text: 'Running quick errands' },
    { id: 'working_from_home_16', text: 'Snacks from your kitchen' },
    { id: 'working_from_home_17', text: 'Family or partner nearby' },
    { id: 'working_from_home_18', text: 'Working outside' },
    { id: 'working_from_home_19', text: 'No pants' },
    { id: 'working_from_home_20', text: 'Skipping small talk' },
    { id: 'working_from_home_21', text: 'Setting the temperature' },
    { id: 'working_from_home_22', text: 'TV on in the background' },
    { id: 'working_from_home_23', text: 'Your own comfy chair' },
    { id: 'working_from_home_24', text: 'Working from the couch' },
    { id: 'working_from_home_25', text: 'A tidy, quiet space' },
  ],
  dream_jobs: [
    { id: 'dream_jobs_01', text: 'Novelist' },
    { id: 'dream_jobs_02', text: 'Chef at a nice restaurant' },
    { id: 'dream_jobs_03', text: 'Wildlife photographer' },
    { id: 'dream_jobs_04', text: 'Museum curator' },
    { id: 'dream_jobs_05', text: 'Talk show host' },
    { id: 'dream_jobs_06', text: 'Standup comedian' },
    { id: 'dream_jobs_07', text: 'Movie director' },
    { id: 'dream_jobs_08', text: 'Long-haul truck driver' },
    { id: 'dream_jobs_09', text: 'Park ranger' },
    { id: 'dream_jobs_10', text: 'Marine biologist' },
    { id: 'dream_jobs_11', text: 'Investigative journalist' },
    { id: 'dream_jobs_12', text: 'Interior designer' },
    { id: 'dream_jobs_13', text: 'Video game designer' },
    { id: 'dream_jobs_14', text: 'Bookshop owner' },
    { id: 'dream_jobs_15', text: 'Winery owner' },
    { id: 'dream_jobs_16', text: 'Music producer' },
    { id: 'dream_jobs_17', text: 'Airline pilot' },
    { id: 'dream_jobs_18', text: 'Small farmer' },
    { id: 'dream_jobs_19', text: 'Therapist' },
    { id: 'dream_jobs_20', text: 'Detective' },
    { id: 'dream_jobs_21', text: 'Voice actor' },
    { id: 'dream_jobs_22', text: 'Diplomat' },
    { id: 'dream_jobs_23', text: 'Architect' },
    { id: 'dream_jobs_24', text: 'Astronaut' },
    { id: 'dream_jobs_25', text: 'Bartender at a great bar' },
  ],
};
