// All 30 situations — 26 cleaned from originals + 4 new replacements
// Removed: sit_off_grid, sit_survival_skills, sit_zombie, sit_desert_island
// Added: sit_road_trip, sit_stranded_airport, sit_potluck, sit_time_capsule
export default [
  {
    id: "sit_tiny_apartment",
    name: "Tiny Apartment",
    prompt: "Rank what you'd give up last",
    cards: [
      { id: "sit_tiny_001", text: "A full-size bed" },
      { id: "sit_tiny_002", text: "A proper kitchen with a stove" },
      { id: "sit_tiny_003", text: "A desk or workspace" },
      { id: "sit_tiny_004", text: "A couch" },
      { id: "sit_tiny_005", text: "A closet that fits all your clothes" },
      { id: "sit_tiny_006", text: "A bathtub" },
      { id: "sit_tiny_007", text: "Natural light from a window" },
      { id: "sit_tiny_008", text: "A TV setup" },
      { id: "sit_tiny_009", text: "A dining table" },
      { id: "sit_tiny_010", text: "General storage space" },
      { id: "sit_tiny_011", text: "A dishwasher" },
      { id: "sit_tiny_012", text: "An air purifier" },
      { id: "sit_tiny_013", text: "A bathroom with counter space" },
      { id: "sit_tiny_014", text: "A full-length mirror" },
      { id: "sit_tiny_015", text: "A nightstand next to your bed" },
      { id: "sit_tiny_016", text: "Under-bed storage" },
      { id: "sit_tiny_017", text: "A ceiling fan" },
      { id: "sit_tiny_018", text: "Thick walls between neighbors" },
      { id: "sit_tiny_019", text: "Hooks on every door" },
      { id: "sit_tiny_020", text: "A convertible guest bed" },
      { id: "sit_tiny_021", text: "A shoe rack" },
      { id: "sit_tiny_022", text: "A closet door that opens all the way" },
      { id: "sit_tiny_023", text: "A kitchen with more than two burners" },
      { id: "sit_tiny_024", text: "A balcony or fire escape to sit on" },
      { id: "sit_tiny_025", text: "In-unit laundry" },
    ]
  },
  {
    id: "sit_apocalypse",
    name: "Last Night on Earth",
    prompt: "The apocalypse is tomorrow — rank what you'd do tonight",
    cards: [
      { id: "sit_apoc_001", text: "Call everyone you love" },
      { id: "sit_apoc_002", text: "Have the best meal of your life" },
      { id: "sit_apoc_003", text: "Watch the sunset somewhere beautiful" },
      { id: "sit_apoc_004", text: "Throw a massive party" },
      { id: "sit_apoc_005", text: "Tell someone how you really feel" },
      { id: "sit_apoc_006", text: "Go skinny dipping" },
      { id: "sit_apoc_007", text: "Drive fast with the windows down" },
      { id: "sit_apoc_008", text: "Write a letter to someone" },
      { id: "sit_apoc_009", text: "Do the thing you've always been scared of" },
      { id: "sit_apoc_010", text: "Sit quietly with the person who matters most" },
      { id: "sit_apoc_011", text: "Apologize to someone you owe it to" },
      { id: "sit_apoc_012", text: "Road trip to your favorite place" },
      { id: "sit_apoc_013", text: "Delete your search history" },
      { id: "sit_apoc_014", text: "Play your all-time favorites playlist" },
      { id: "sit_apoc_015", text: "Have an honest talk with your parents" },
      { id: "sit_apoc_016", text: "Forgive someone who hurt you" },
      { id: "sit_apoc_017", text: "Stay up all night with the people who matter" },
      { id: "sit_apoc_018", text: "Dance, even if you can't" },
      { id: "sit_apoc_019", text: "Climb to the highest point you can find" },
      { id: "sit_apoc_020", text: "Hug your pet for an unreasonable amount of time" },
      { id: "sit_apoc_021", text: "Laugh until your stomach hurts" },
      { id: "sit_apoc_022", text: "Sing your heart out" },
      { id: "sit_apoc_023", text: "Lie in the grass and look at the stars" },
      { id: "sit_apoc_024", text: "Take a photo of everyone together" },
      { id: "sit_apoc_025", text: "Fall asleep holding someone's hand" },
    ]
  },
  {
    id: "sit_meditation_retreat",
    name: "Silent Retreat",
    prompt: "Two weeks of silence — rank what you'd miss most",
    cards: [
      { id: "sit_med_001", text: "Your phone" },
      { id: "sit_med_002", text: "Music" },
      { id: "sit_med_003", text: "Talking to friends" },
      { id: "sit_med_004", text: "Coffee or caffeine" },
      { id: "sit_med_005", text: "TV and streaming" },
      { id: "sit_med_006", text: "Your own schedule" },
      { id: "sit_med_007", text: "Cooking what you want" },
      { id: "sit_med_008", text: "Reading the news" },
      { id: "sit_med_009", text: "Sleeping in" },
      { id: "sit_med_010", text: "Privacy" },
      { id: "sit_med_011", text: "Social media" },
      { id: "sit_med_012", text: "Podcasts" },
      { id: "sit_med_013", text: "Snacking whenever you want" },
      { id: "sit_med_014", text: "Your own bed" },
      { id: "sit_med_015", text: "Background noise" },
      { id: "sit_med_016", text: "Complaining out loud" },
      { id: "sit_med_017", text: "Sarcasm" },
      { id: "sit_med_018", text: "A glass of wine at night" },
      { id: "sit_med_019", text: "Your pet" },
      { id: "sit_med_020", text: "Group chats" },
      { id: "sit_med_021", text: "Choosing what to eat" },
      { id: "sit_med_022", text: "Hot showers on demand" },
      { id: "sit_med_023", text: "Checking the time constantly" },
      { id: "sit_med_024", text: "Venting when things go wrong" },
      { id: "sit_med_025", text: "Wearing whatever you want" },
    ]
  },
  {
    id: "sit_10k_windfall",
    name: "$10K Windfall",
    prompt: "All on yourself — rank what you'd spend it on first",
    cards: [
      { id: "sit_10k_001", text: "A dream vacation" },
      { id: "sit_10k_002", text: "A wardrobe refresh" },
      { id: "sit_10k_003", text: "The best home office setup" },
      { id: "sit_10k_004", text: "A spa weekend" },
      { id: "sit_10k_005", text: "A month of someone doing your chores" },
      { id: "sit_10k_006", text: "Concert tickets for the whole year" },
      { id: "sit_10k_007", text: "Kitchen gadgets and cooking classes" },
      { id: "sit_10k_008", text: "A really nice mattress" },
      { id: "sit_10k_009", text: "A hobby you've always wanted to try" },
      { id: "sit_10k_010", text: "An incredible party for your friends" },
      { id: "sit_10k_011", text: "Paying off your credit card" },
      { id: "sit_10k_012", text: "Surprising someone you love" },
      { id: "sit_10k_013", text: "A spontaneous weekend getaway" },
      { id: "sit_10k_014", text: "That thing you've been eyeing for months" },
      { id: "sit_10k_015", text: "Investing it all" },
      { id: "sit_10k_016", text: "Donating to a cause you believe in" },
      { id: "sit_10k_017", text: "A series of professional massages" },
      { id: "sit_10k_018", text: "Front-row concert tickets" },
      { id: "sit_10k_019", text: "Straight into savings" },
      { id: "sit_10k_020", text: "A piece of art from a local artist" },
      { id: "sit_10k_021", text: "A home improvement project" },
      { id: "sit_10k_022", text: "A personal trainer for six months" },
      { id: "sit_10k_023", text: "New tech and gadgets" },
      { id: "sit_10k_024", text: "A custom piece of furniture" },
      { id: "sit_10k_025", text: "An experience you'll never forget" },
    ]
  },
  {
    id: "sit_new_city",
    name: "New City, No Friends",
    prompt: "Rank what would help you feel at home fastest",
    cards: [
      { id: "sit_city_001", text: "A coffee shop where they know your name" },
      { id: "sit_city_002", text: "A local friend" },
      { id: "sit_city_003", text: "A gym or fitness studio you love" },
      { id: "sit_city_004", text: "A favorite restaurant nearby" },
      { id: "sit_city_005", text: "A pet" },
      { id: "sit_city_006", text: "A neighborhood you want to walk around" },
      { id: "sit_city_007", text: "An apartment that feels like yours" },
      { id: "sit_city_008", text: "A hobby group or class" },
      { id: "sit_city_009", text: "Knowing the best local spots" },
      { id: "sit_city_010", text: "A reliable daily routine" },
      { id: "sit_city_011", text: "A recreational sports league" },
      { id: "sit_city_012", text: "Volunteering somewhere" },
      { id: "sit_city_013", text: "Saying yes to every invite" },
      { id: "sit_city_014", text: "A coworker to grab lunch with" },
      { id: "sit_city_015", text: "A book club or trivia night" },
      { id: "sit_city_016", text: "A concert to go to alone" },
      { id: "sit_city_017", text: "A community garden" },
      { id: "sit_city_018", text: "A class — cooking, pottery, improv" },
      { id: "sit_city_019", text: "A walking buddy or dog park crew" },
      { id: "sit_city_020", text: "Hosting dinner for people you've met" },
      { id: "sit_city_021", text: "A barber or stylist you trust" },
      { id: "sit_city_022", text: "A farmers market to browse on Saturdays" },
      { id: "sit_city_023", text: "A bar where the bartender knows you" },
      { id: "sit_city_024", text: "A running route you love" },
      { id: "sit_city_025", text: "Finding your go-to takeout spot" },
    ]
  },
  {
    id: "sit_perfect_saturday",
    name: "Perfect Saturday",
    prompt: "Zero obligations — rank how you'd spend it",
    cards: [
      { id: "sit_sat_001", text: "Sleep in until you naturally wake up" },
      { id: "sit_sat_002", text: "A long, lazy brunch" },
      { id: "sit_sat_003", text: "A hike or outdoor adventure" },
      { id: "sit_sat_004", text: "Binge a show you've been saving" },
      { id: "sit_sat_005", text: "Cook an ambitious recipe" },
      { id: "sit_sat_006", text: "Meet up with friends for no reason" },
      { id: "sit_sat_007", text: "Read a book cover to cover" },
      { id: "sit_sat_008", text: "Go shopping with no budget" },
      { id: "sit_sat_009", text: "An afternoon nap in the sun" },
      { id: "sit_sat_010", text: "Work on a creative project" },
      { id: "sit_sat_011", text: "A farmers market trip" },
      { id: "sit_sat_012", text: "A spontaneous day trip" },
      { id: "sit_sat_013", text: "Reading in a hammock" },
      { id: "sit_sat_014", text: "Your favorite movie for the hundredth time" },
      { id: "sit_sat_015", text: "A walk through a botanical garden" },
      { id: "sit_sat_016", text: "Trying a new restaurant" },
      { id: "sit_sat_017", text: "Playing video games all afternoon" },
      { id: "sit_sat_018", text: "A sunset picnic" },
      { id: "sit_sat_019", text: "A long drive with the windows down" },
      { id: "sit_sat_020", text: "Baking something new" },
      { id: "sit_sat_021", text: "Calling a friend you haven't talked to" },
      { id: "sit_sat_022", text: "A matinee in an empty theater" },
      { id: "sit_sat_023", text: "Sitting on a patio with a drink" },
      { id: "sit_sat_024", text: "Ending the night with a bonfire" },
      { id: "sit_sat_025", text: "Doing absolutely nothing" },
    ]
  },
  {
    id: "sit_eliminate_forever",
    name: "Eliminate Forever",
    prompt: "Rank what you'd be most willing to live without",
    cards: [
      { id: "sit_elim_001", text: "Doing dishes" },
      { id: "sit_elim_002", text: "Commuting" },
      { id: "sit_elim_003", text: "Making your bed" },
      { id: "sit_elim_004", text: "Small talk with strangers" },
      { id: "sit_elim_005", text: "Waiting in lines" },
      { id: "sit_elim_006", text: "Folding laundry" },
      { id: "sit_elim_007", text: "Going to the dentist" },
      { id: "sit_elim_008", text: "Hangovers" },
      { id: "sit_elim_009", text: "Grocery shopping" },
      { id: "sit_elim_010", text: "Alarm clocks" },
      { id: "sit_elim_011", text: "Mosquitoes" },
      { id: "sit_elim_012", text: "Traffic jams" },
      { id: "sit_elim_013", text: "Doing taxes" },
      { id: "sit_elim_014", text: "Slow WiFi" },
      { id: "sit_elim_015", text: "Bad breath" },
      { id: "sit_elim_016", text: "Student loans" },
      { id: "sit_elim_017", text: "Meetings that should've been emails" },
      { id: "sit_elim_018", text: "Getting a cold" },
      { id: "sit_elim_019", text: "Losing socks in the laundry" },
      { id: "sit_elim_020", text: "Spam calls" },
      { id: "sit_elim_021", text: "Potholes" },
      { id: "sit_elim_022", text: "Jet lag" },
      { id: "sit_elim_023", text: "Parallel parking" },
      { id: "sit_elim_024", text: "Tangled headphone cords" },
      { id: "sit_elim_025", text: "Hiccups" },
    ]
  },
  {
    id: "sit_dinner_party",
    name: "Perfect Dinner Party",
    prompt: "Rank what matters most for the perfect dinner",
    cards: [
      { id: "sit_dinner_001", text: "Incredible food" },
      { id: "sit_dinner_002", text: "The right mix of people" },
      { id: "sit_dinner_003", text: "Great music in the background" },
      { id: "sit_dinner_004", text: "The place looking immaculate" },
      { id: "sit_dinner_005", text: "Good drinks flowing" },
      { id: "sit_dinner_006", text: "Comfortable seating" },
      { id: "sit_dinner_007", text: "A conversation topic that gets everyone going" },
      { id: "sit_dinner_008", text: "No one on their phone" },
      { id: "sit_dinner_009", text: "Good lighting and ambiance" },
      { id: "sit_dinner_010", text: "People staying later than planned" },
      { id: "sit_dinner_011", text: "A welcome cocktail" },
      { id: "sit_dinner_012", text: "Everyone arriving on time" },
      { id: "sit_dinner_013", text: "A dessert people talk about the next day" },
      { id: "sit_dinner_014", text: "A theme for the evening" },
      { id: "sit_dinner_015", text: "Someone helping clean up" },
      { id: "sit_dinner_016", text: "The host sitting down to enjoy it" },
      { id: "sit_dinner_017", text: "Enough food that no one leaves hungry" },
      { id: "sit_dinner_018", text: "A surprise dish" },
      { id: "sit_dinner_019", text: "A toast that makes everyone laugh" },
      { id: "sit_dinner_020", text: "Games after the meal" },
      { id: "sit_dinner_021", text: "Candles on the table" },
      { id: "sit_dinner_022", text: "A friend who brings something unasked" },
      { id: "sit_dinner_023", text: "Not talking about work" },
      { id: "sit_dinner_024", text: "The night ending naturally" },
      { id: "sit_dinner_025", text: "A playlist everyone vibes with" },
    ]
  },
  {
    id: "sit_last_meal",
    name: "Last Meal",
    prompt: "Your last meal ever — rank what's on the table",
    cards: [
      { id: "sit_meal_001", text: "A perfectly cooked steak" },
      { id: "sit_meal_002", text: "Fresh pasta with a rich sauce" },
      { id: "sit_meal_003", text: "A dish your mom or grandma makes" },
      { id: "sit_meal_004", text: "Freshly baked bread with butter" },
      { id: "sit_meal_005", text: "Your favorite childhood meal" },
      { id: "sit_meal_006", text: "A decadent chocolate dessert" },
      { id: "sit_meal_007", text: "The best sushi you've ever had" },
      { id: "sit_meal_008", text: "A glass of really good wine" },
      { id: "sit_meal_009", text: "An endless cheese course" },
      { id: "sit_meal_010", text: "Something spicy" },
      { id: "sit_meal_011", text: "Lobster tail with butter" },
      { id: "sit_meal_012", text: "A perfect slice of pizza" },
      { id: "sit_meal_013", text: "Crispy fried chicken" },
      { id: "sit_meal_014", text: "Ramen with a soft-boiled egg" },
      { id: "sit_meal_015", text: "Fish and chips on the beach" },
      { id: "sit_meal_016", text: "A burrito the size of your forearm" },
      { id: "sit_meal_017", text: "Unlimited dim sum" },
      { id: "sit_meal_018", text: "A Thanksgiving plate piled high" },
      { id: "sit_meal_019", text: "A bánh mì" },
      { id: "sit_meal_020", text: "Mac and cheese from scratch" },
      { id: "sit_meal_021", text: "Tacos al pastor" },
      { id: "sit_meal_022", text: "A croissant from Paris" },
      { id: "sit_meal_023", text: "Fresh oysters" },
      { id: "sit_meal_024", text: "Your favorite ice cream flavor" },
      { id: "sit_meal_025", text: "A bowl of pho" },
    ]
  },
  {
    id: "sit_dream_home",
    name: "Dream Home",
    prompt: "Rank what you'd prioritize first",
    cards: [
      { id: "sit_home_001", text: "A massive kitchen" },
      { id: "sit_home_002", text: "A big backyard" },
      { id: "sit_home_003", text: "Floor-to-ceiling windows with a view" },
      { id: "sit_home_004", text: "A home theater room" },
      { id: "sit_home_005", text: "A walk-in closet" },
      { id: "sit_home_006", text: "A rooftop terrace" },
      { id: "sit_home_007", text: "A dedicated home office" },
      { id: "sit_home_008", text: "A rainfall shower" },
      { id: "sit_home_009", text: "A library or reading nook" },
      { id: "sit_home_010", text: "A garage or workshop" },
      { id: "sit_home_011", text: "A wrap-around porch" },
      { id: "sit_home_012", text: "A secret room behind a bookshelf" },
      { id: "sit_home_013", text: "A fire pit in the backyard" },
      { id: "sit_home_014", text: "A wine cellar" },
      { id: "sit_home_015", text: "Smart home automation" },
      { id: "sit_home_016", text: "A breakfast nook with a window seat" },
      { id: "sit_home_017", text: "A sauna" },
      { id: "sit_home_018", text: "A music room or studio" },
      { id: "sit_home_019", text: "An outdoor shower" },
      { id: "sit_home_020", text: "A treehouse" },
      { id: "sit_home_021", text: "A sunroom full of plants" },
      { id: "sit_home_022", text: "Heated floors" },
      { id: "sit_home_023", text: "A pool" },
      { id: "sit_home_024", text: "A mudroom with built-in storage" },
      { id: "sit_home_025", text: "A guest house" },
    ]
  },
  {
    id: "sit_month_off",
    name: "Month Off",
    prompt: "Full pay, no plans — rank how you'd spend it",
    cards: [
      { id: "sit_month_001", text: "Travel somewhere you've always wanted" },
      { id: "sit_month_002", text: "Learn a new skill" },
      { id: "sit_month_003", text: "Do absolutely nothing the first week" },
      { id: "sit_month_004", text: "Renovate or redecorate your space" },
      { id: "sit_month_005", text: "Visit everyone you haven't seen" },
      { id: "sit_month_006", text: "Start a creative project" },
      { id: "sit_month_007", text: "Get into the best shape of your life" },
      { id: "sit_month_008", text: "Read every book on your list" },
      { id: "sit_month_009", text: "Volunteer in your community" },
      { id: "sit_month_010", text: "Cook your way through a cookbook" },
      { id: "sit_month_011", text: "A solo camping trip" },
      { id: "sit_month_012", text: "Write that book you keep talking about" },
      { id: "sit_month_013", text: "Learn to surf" },
      { id: "sit_month_014", text: "A road trip with no itinerary" },
      { id: "sit_month_015", text: "A deep dive into a new hobby" },
      { id: "sit_month_016", text: "A silent retreat in the mountains" },
      { id: "sit_month_017", text: "Declutter every room top to bottom" },
      { id: "sit_month_018", text: "Take a language course" },
      { id: "sit_month_019", text: "Train for a race" },
      { id: "sit_month_020", text: "Explore a country by train" },
      { id: "sit_month_021", text: "Sleep until you're not tired anymore" },
      { id: "sit_month_022", text: "Build something with your hands" },
      { id: "sit_month_023", text: "Journal every day" },
      { id: "sit_month_024", text: "Pick up a childhood hobby again" },
      { id: "sit_month_025", text: "See how long you can go without a plan" },
    ]
  },
  {
    id: "sit_looking_back",
    name: "Looking Back at 80",
    prompt: "Rank what you'd be most glad you did",
    cards: [
      { id: "sit_80_001", text: "Traveled as much as possible" },
      { id: "sit_80_002", text: "Stayed close with your family" },
      { id: "sit_80_003", text: "Took more risks" },
      { id: "sit_80_004", text: "Built something you're proud of" },
      { id: "sit_80_005", text: "Spent more time outdoors" },
      { id: "sit_80_006", text: "Let go of grudges" },
      { id: "sit_80_007", text: "Had a job you loved" },
      { id: "sit_80_008", text: "Made time for friendships" },
      { id: "sit_80_009", text: "Said yes to spontaneous things" },
      { id: "sit_80_010", text: "Worried less about others' opinions" },
      { id: "sit_80_011", text: "The place you called home the longest" },
      { id: "sit_80_012", text: "A risk that changed everything" },
      { id: "sit_80_013", text: "A friendship that lasted decades" },
      { id: "sit_80_014", text: "A trip that changed your perspective" },
      { id: "sit_80_015", text: "Choosing rest over hustle" },
      { id: "sit_80_016", text: "A hobby that became part of you" },
      { id: "sit_80_017", text: "A conversation that changed your life" },
      { id: "sit_80_018", text: "Forgiving something you thought you couldn't" },
      { id: "sit_80_019", text: "A tradition you started" },
      { id: "sit_80_020", text: "A lesson learned the hard way" },
      { id: "sit_80_021", text: "A meal you can still taste in memory" },
      { id: "sit_80_022", text: "Standing up for what was right" },
      { id: "sit_80_023", text: "The person who believed in you" },
      { id: "sit_80_024", text: "Being kind when it was easier not to" },
      { id: "sit_80_025", text: "Loving deeply" },
    ]
  },
  {
    id: "sit_two_suitcases",
    name: "Two Suitcases",
    prompt: "Moving abroad — rank what makes the cut",
    cards: [
      { id: "sit_suit_001", text: "Your favorite pillow" },
      { id: "sit_suit_002", text: "A family photo album" },
      { id: "sit_suit_003", text: "Your most comfortable outfit" },
      { id: "sit_suit_004", text: "A laptop" },
      { id: "sit_suit_005", text: "A sentimental piece of jewelry" },
      { id: "sit_suit_006", text: "Your go-to pair of shoes" },
      { id: "sit_suit_007", text: "A favorite book or journal" },
      { id: "sit_suit_008", text: "A small kitchen item you can't skip" },
      { id: "sit_suit_009", text: "Your skincare essentials" },
      { id: "sit_suit_010", text: "Something that smells like home" },
      { id: "sit_suit_011", text: "Running shoes" },
      { id: "sit_suit_012", text: "A journal for documenting everything" },
      { id: "sit_suit_013", text: "Your most sentimental possession" },
      { id: "sit_suit_014", text: "A camera" },
      { id: "sit_suit_015", text: "A versatile jacket" },
      { id: "sit_suit_016", text: "A power bank and all your cables" },
      { id: "sit_suit_017", text: "A small Bluetooth speaker" },
      { id: "sit_suit_018", text: "A scarf that doubles as a blanket" },
      { id: "sit_suit_019", text: "Hot sauce" },
      { id: "sit_suit_020", text: "A Swiss Army knife" },
      { id: "sit_suit_021", text: "Your lucky charm" },
      { id: "sit_suit_022", text: "Comfortable walking shoes" },
      { id: "sit_suit_023", text: "A stuffed animal from childhood" },
      { id: "sit_suit_024", text: "A real book, not a Kindle" },
      { id: "sit_suit_025", text: "Letters from people you love" },
    ]
  },
  {
    id: "sit_one_hour",
    name: "One Hour to Yourself",
    prompt: "Rank how you'd spend it",
    cards: [
      { id: "sit_hour_001", text: "A long shower or bath" },
      { id: "sit_hour_002", text: "Scrolling your phone guilt-free" },
      { id: "sit_hour_003", text: "A power nap" },
      { id: "sit_hour_004", text: "A walk with no destination" },
      { id: "sit_hour_005", text: "Calling someone you miss" },
      { id: "sit_hour_006", text: "Reading or a podcast" },
      { id: "sit_hour_007", text: "Working out" },
      { id: "sit_hour_008", text: "Cooking or baking something fun" },
      { id: "sit_hour_009", text: "Meditating or journaling" },
      { id: "sit_hour_010", text: "Playing a game" },
      { id: "sit_hour_011", text: "Playing an instrument" },
      { id: "sit_hour_012", text: "Sitting in the sun with a cold drink" },
      { id: "sit_hour_013", text: "Doing a puzzle" },
      { id: "sit_hour_014", text: "Stretching and yoga" },
      { id: "sit_hour_015", text: "Writing something — anything" },
      { id: "sit_hour_016", text: "Your favorite video game" },
      { id: "sit_hour_017", text: "Drawing or doodling" },
      { id: "sit_hour_018", text: "Lying on the floor listening to an album" },
      { id: "sit_hour_019", text: "Organizing one drawer" },
      { id: "sit_hour_020", text: "Watching the world go by" },
      { id: "sit_hour_021", text: "Online shopping" },
      { id: "sit_hour_022", text: "Making yourself a fancy coffee" },
      { id: "sit_hour_023", text: "Taking a bath with candles" },
      { id: "sit_hour_024", text: "Staring at the ceiling thinking" },
      { id: "sit_hour_025", text: "Eating something slowly for once" },
    ]
  },
  {
    id: "sit_terrible_week",
    name: "Terrible Week Recovery",
    prompt: "Rank what would help you recover most",
    cards: [
      { id: "sit_recov_001", text: "A hug from someone who gets it" },
      { id: "sit_recov_002", text: "Your favorite comfort food" },
      { id: "sit_recov_003", text: "A full 12 hours of sleep" },
      { id: "sit_recov_004", text: "Venting to your best friend" },
      { id: "sit_recov_005", text: "A long walk outside" },
      { id: "sit_recov_006", text: "A funny show or movie" },
      { id: "sit_recov_007", text: "A hot bath" },
      { id: "sit_recov_008", text: "Doing something creative" },
      { id: "sit_recov_009", text: "Canceling all your plans" },
      { id: "sit_recov_010", text: "A workout to burn it off" },
      { id: "sit_recov_011", text: "A friend who always makes you laugh" },
      { id: "sit_recov_012", text: "Ordering your favorite takeout" },
      { id: "sit_recov_013", text: "Your comfort show from episode one" },
      { id: "sit_recov_014", text: "A drive with no destination" },
      { id: "sit_recov_015", text: "Crying it out" },
      { id: "sit_recov_016", text: "Buying yourself flowers" },
      { id: "sit_recov_017", text: "A walk in nature" },
      { id: "sit_recov_018", text: "Sleeping in with zero guilt" },
      { id: "sit_recov_019", text: "A playlist that matches your mood" },
      { id: "sit_recov_020", text: "An unplanned day off" },
      { id: "sit_recov_021", text: "A sunset" },
      { id: "sit_recov_022", text: "A home-cooked meal by someone else" },
      { id: "sit_recov_023", text: "Cuddling with a pet" },
      { id: "sit_recov_024", text: "A really good cup of tea" },
      { id: "sit_recov_025", text: "Just being left alone for a bit" },
    ]
  },
  {
    id: "sit_long_flight",
    name: "12-Hour Flight",
    prompt: "Rank what would make it bearable",
    cards: [
      { id: "sit_fly_001", text: "A window seat with no one beside you" },
      { id: "sit_fly_002", text: "Noise-canceling headphones" },
      { id: "sit_fly_003", text: "An amazing movie lineup" },
      { id: "sit_fly_004", text: "A neck pillow that works" },
      { id: "sit_fly_005", text: "A really good book" },
      { id: "sit_fly_006", text: "WiFi on the plane" },
      { id: "sit_fly_007", text: "Snacks you brought yourself" },
      { id: "sit_fly_008", text: "A sleeping pill" },
      { id: "sit_fly_009", text: "Extra legroom" },
      { id: "sit_fly_010", text: "A seatmate who knows when to stop talking" },
      { id: "sit_fly_011", text: "Multiple seasons of your show downloaded" },
      { id: "sit_fly_012", text: "A crossword or Sudoku book" },
      { id: "sit_fly_013", text: "Compression socks" },
      { id: "sit_fly_014", text: "A travel blanket and cozy socks" },
      { id: "sit_fly_015", text: "A 12-hour playlist" },
      { id: "sit_fly_016", text: "An aisle seat for easy access" },
      { id: "sit_fly_017", text: "The perfect recline angle" },
      { id: "sit_fly_018", text: "An eye mask" },
      { id: "sit_fly_019", text: "Your own headphones, not the airline ones" },
      { id: "sit_fly_020", text: "A pen for journaling" },
      { id: "sit_fly_021", text: "A window to lean against" },
      { id: "sit_fly_022", text: "Melatonin" },
      { id: "sit_fly_023", text: "An empty middle seat" },
      { id: "sit_fly_024", text: "A warm meal on a cold flight" },
      { id: "sit_fly_025", text: "Knowing the turbulence will stop" },
    ]
  },
  {
    id: "sit_fame",
    name: "Famous For...",
    prompt: "Rank which kind of fame sounds best",
    cards: [
      { id: "sit_fame_001", text: "Famous musician" },
      { id: "sit_fame_002", text: "Bestselling author" },
      { id: "sit_fame_003", text: "Award-winning actor" },
      { id: "sit_fame_004", text: "Celebrity chef" },
      { id: "sit_fame_005", text: "Pro athlete" },
      { id: "sit_fame_006", text: "Viral internet personality" },
      { id: "sit_fame_007", text: "Inventor of something everyone uses" },
      { id: "sit_fame_008", text: "Fashion icon" },
      { id: "sit_fame_009", text: "Beloved TV show host" },
      { id: "sit_fame_010", text: "Space explorer" },
      { id: "sit_fame_011", text: "A viral moment that became a meme" },
      { id: "sit_fame_012", text: "An invention that changed millions of lives" },
      { id: "sit_fame_013", text: "A speech that moved a room to tears" },
      { id: "sit_fame_014", text: "The funniest person in any room" },
      { id: "sit_fame_015", text: "A philanthropist who changed lives" },
      { id: "sit_fame_016", text: "A scientific discovery" },
      { id: "sit_fame_017", text: "Unforgettable dance moves" },
      { id: "sit_fame_018", text: "A business built from nothing" },
      { id: "sit_fame_019", text: "A podcast everyone listens to" },
      { id: "sit_fame_020", text: "Your kids turned out amazing" },
      { id: "sit_fame_021", text: "A random act of kindness that went viral" },
      { id: "sit_fame_022", text: "Your art hanging in galleries" },
      { id: "sit_fame_023", text: "A garden people travel to see" },
      { id: "sit_fame_024", text: "A documentary made about your life" },
      { id: "sit_fame_025", text: "Cooking so good people beg for recipes" },
    ]
  },
  {
    id: "sit_retirement",
    name: "Ideal Retirement",
    prompt: "Rank what you'd want most",
    cards: [
      { id: "sit_ret_001", text: "Living somewhere warm year-round" },
      { id: "sit_ret_002", text: "Being close to family" },
      { id: "sit_ret_003", text: "A daily hobby you love" },
      { id: "sit_ret_004", text: "Traveling regularly" },
      { id: "sit_ret_005", text: "A house fully paid off" },
      { id: "sit_ret_006", text: "A tight-knit group of friends" },
      { id: "sit_ret_007", text: "Good health to enjoy it all" },
      { id: "sit_ret_008", text: "A garden to tend" },
      { id: "sit_ret_009", text: "Still learning new things" },
      { id: "sit_ret_010", text: "No alarm clocks ever again" },
      { id: "sit_ret_011", text: "A cottage near the water" },
      { id: "sit_ret_012", text: "A workshop to build things" },
      { id: "sit_ret_013", text: "Daily walks and coffee shop visits" },
      { id: "sit_ret_014", text: "Volunteering at a cause you care about" },
      { id: "sit_ret_015", text: "A garden that feeds the neighbors too" },
      { id: "sit_ret_016", text: "Learning an instrument" },
      { id: "sit_ret_017", text: "Writing your memoirs" },
      { id: "sit_ret_018", text: "A weekly card game with friends" },
      { id: "sit_ret_019", text: "Taking college classes for fun" },
      { id: "sit_ret_020", text: "Traveling to every continent" },
      { id: "sit_ret_021", text: "A reading chair with perfect light" },
      { id: "sit_ret_022", text: "Hosting dinner parties" },
      { id: "sit_ret_023", text: "A rescue pet as your best friend" },
      { id: "sit_ret_024", text: "A painting hobby that fills the walls" },
      { id: "sit_ret_025", text: "A porch with a view" },
    ]
  },
  {
    id: "sit_time_travel",
    name: "Time Traveler",
    prompt: "You can time travel once — rank which era you'd visit",
    cards: [
      { id: "sit_time_001", text: "Ancient Rome at its peak" },
      { id: "sit_time_002", text: "The roaring 1920s" },
      { id: "sit_time_003", text: "The Renaissance in Florence" },
      { id: "sit_time_004", text: "The 1960s space race" },
      { id: "sit_time_005", text: "The Wild West" },
      { id: "sit_time_006", text: "100 years in the future" },
      { id: "sit_time_007", text: "When dinosaurs roamed" },
      { id: "sit_time_008", text: "The 1980s pop culture era" },
      { id: "sit_time_009", text: "Ancient Egypt during the pyramids" },
      { id: "sit_time_010", text: "The day you were born" },
      { id: "sit_time_011", text: "Your parents' wedding day" },
      { id: "sit_time_012", text: "The first moon landing" },
      { id: "sit_time_013", text: "Shakespeare's opening night" },
      { id: "sit_time_014", text: "Woodstock" },
      { id: "sit_time_015", text: "When your favorite song was first played" },
      { id: "sit_time_016", text: "Your grandparents as teenagers" },
      { id: "sit_time_017", text: "A medieval feast in a real castle" },
      { id: "sit_time_018", text: "The signing of a world-changing document" },
      { id: "sit_time_019", text: "A family reunion with ancestors" },
      { id: "sit_time_020", text: "The day the internet went live" },
      { id: "sit_time_021", text: "The golden age of pirates" },
      { id: "sit_time_022", text: "Ancient Greece during the Olympics" },
      { id: "sit_time_023", text: "The night your favorite movie premiered" },
      { id: "sit_time_024", text: "The first human campfire" },
      { id: "sit_time_025", text: "Your own childhood, just to watch" },
    ]
  },
  {
    id: "sit_superpower_catch",
    name: "Superpower With a Catch",
    prompt: "Each power has a catch — rank which you'd still take",
    cards: [
      { id: "sit_spow_001", text: "Fly, but only at walking speed" },
      { id: "sit_spow_002", text: "Read minds, but can't turn it off" },
      { id: "sit_spow_003", text: "Invisible, but you're naked" },
      { id: "sit_spow_004", text: "Super strength, but break everything" },
      { id: "sit_spow_005", text: "Teleport, but arrive 5 minutes late" },
      { id: "sit_spow_006", text: "Speak every language, forget one yearly" },
      { id: "sit_spow_007", text: "See the future, but only 10 seconds" },
      { id: "sit_spow_008", text: "Immortal, but you still age" },
      { id: "sit_spow_009", text: "Talk to animals, but they're rude" },
      { id: "sit_spow_010", text: "Perfect memory, including every cringe" },
      { id: "sit_spow_011", text: "Breathe underwater, but scared of fish" },
      { id: "sit_spow_012", text: "Stop time, but everything smells bad" },
      { id: "sit_spow_013", text: "Invisible, but only while holding breath" },
      { id: "sit_spow_014", text: "Control weather, but it matches your mood" },
      { id: "sit_spow_015", text: "Fireproof, but always feel cold" },
      { id: "sit_spow_016", text: "Teleport, but arrive 3 feet in the air" },
      { id: "sit_spow_017", text: "X-ray vision, but only through wood" },
      { id: "sit_spow_018", text: "Shrink to ant-size, takes 10 minutes" },
      { id: "sit_spow_019", text: "Never age, but move cities every 5 years" },
      { id: "sit_spow_020", text: "Clone yourself, but they argue with you" },
      { id: "sit_spow_021", text: "Genius, but only between 2 and 4 AM" },
      { id: "sit_spow_022", text: "Super speed, but can't stop gracefully" },
      { id: "sit_spow_023", text: "Heal others, but feel their pain" },
      { id: "sit_spow_024", text: "Shape-shift, but forget your own face" },
      { id: "sit_spow_025", text: "Time travel, but lose one memory each trip" },
    ]
  },
  {
    id: "sit_bank_heist",
    name: "Heist Crew",
    prompt: "Rank who you'd recruit first",
    cards: [
      { id: "sit_heist_001", text: "The tech genius" },
      { id: "sit_heist_002", text: "The smooth talker" },
      { id: "sit_heist_003", text: "The getaway driver" },
      { id: "sit_heist_004", text: "The inside person" },
      { id: "sit_heist_005", text: "The muscle" },
      { id: "sit_heist_006", text: "The disguise expert" },
      { id: "sit_heist_007", text: "The mastermind with the plan" },
      { id: "sit_heist_008", text: "The lockpick" },
      { id: "sit_heist_009", text: "The calm one who never panics" },
      { id: "sit_heist_010", text: "The unpredictable wildcard" },
      { id: "sit_heist_011", text: "The forger" },
      { id: "sit_heist_012", text: "The safe cracker" },
      { id: "sit_heist_013", text: "The ex-cop who knows how they think" },
      { id: "sit_heist_014", text: "The voice actor who mimics anyone" },
      { id: "sit_heist_015", text: "The clean-up crew" },
      { id: "sit_heist_016", text: "The planner who thinks of everything" },
      { id: "sit_heist_017", text: "The contortionist for the vents" },
      { id: "sit_heist_018", text: "The lookout" },
      { id: "sit_heist_019", text: "The demolitions expert" },
      { id: "sit_heist_020", text: "The rookie who's surprisingly useful" },
      { id: "sit_heist_021", text: "The getaway pilot" },
      { id: "sit_heist_022", text: "The tunnel digger" },
      { id: "sit_heist_023", text: "The distraction artist" },
      { id: "sit_heist_024", text: "The hacker who loops the cameras" },
      { id: "sit_heist_025", text: "The one everyone trusts" },
    ]
  },
  {
    id: "sit_dating_profile",
    name: "Dating Profile",
    prompt: "Rank what you'd highlight about yourself",
    cards: [
      { id: "sit_date_001", text: "Your sense of humor" },
      { id: "sit_date_002", text: "Your taste in music or movies" },
      { id: "sit_date_003", text: "Your cooking skills" },
      { id: "sit_date_004", text: "Your love of travel" },
      { id: "sit_date_005", text: "Your ambition and drive" },
      { id: "sit_date_006", text: "How close you are with family" },
      { id: "sit_date_007", text: "Your hobbies or creative side" },
      { id: "sit_date_008", text: "Your fitness routine" },
      { id: "sit_date_009", text: "Your taste in food" },
      { id: "sit_date_010", text: "Your ability to have deep conversations" },
      { id: "sit_date_011", text: "A funny bio" },
      { id: "sit_date_012", text: "A travel photo" },
      { id: "sit_date_013", text: "Mentioning your dog" },
      { id: "sit_date_014", text: "A group photo that proves you have friends" },
      { id: "sit_date_015", text: "A candid laugh photo" },
      { id: "sit_date_016", text: "Your comfort show" },
      { id: "sit_date_017", text: "Emotional intelligence" },
      { id: "sit_date_018", text: "A hobby that sounds fun to join" },
      { id: "sit_date_019", text: "A photo with family" },
      { id: "sit_date_020", text: "Saying what you're looking for upfront" },
      { id: "sit_date_021", text: "Activity photos over selfies" },
      { id: "sit_date_022", text: "A niche interest" },
      { id: "sit_date_023", text: "A photo doing something you love" },
      { id: "sit_date_024", text: "Your Spotify top artists" },
      { id: "sit_date_025", text: "Your height" },
    ]
  },
  {
    id: "sit_talent_show",
    name: "Talent Show",
    prompt: "Rank what you'd be most willing to perform",
    cards: [
      { id: "sit_talent_001", text: "Sing a karaoke song" },
      { id: "sit_talent_002", text: "Do a stand-up comedy bit" },
      { id: "sit_talent_003", text: "A choreographed dance" },
      { id: "sit_talent_004", text: "Play an instrument" },
      { id: "sit_talent_005", text: "Do impressions of famous people" },
      { id: "sit_talent_006", text: "A dramatic spoken-word piece" },
      { id: "sit_talent_007", text: "A magic trick" },
      { id: "sit_talent_008", text: "A lip sync battle" },
      { id: "sit_talent_009", text: "A weird hidden talent" },
      { id: "sit_talent_010", text: "Walk out and bow confidently" },
      { id: "sit_talent_011", text: "Speed painting a portrait" },
      { id: "sit_talent_012", text: "A hula hoop act" },
      { id: "sit_talent_013", text: "A ventriloquist act" },
      { id: "sit_talent_014", text: "A dramatic monologue" },
      { id: "sit_talent_015", text: "Beatboxing" },
      { id: "sit_talent_016", text: "A gymnastics routine" },
      { id: "sit_talent_017", text: "Guitar and singing" },
      { id: "sit_talent_018", text: "A puppet show" },
      { id: "sit_talent_019", text: "A cooking demo" },
      { id: "sit_talent_020", text: "A poetry recital" },
      { id: "sit_talent_021", text: "A freestyle rap" },
      { id: "sit_talent_022", text: "Juggling unusual objects" },
      { id: "sit_talent_023", text: "A synchronized routine with a partner" },
      { id: "sit_talent_024", text: "A comedy skit with props" },
      { id: "sit_talent_025", text: "An interpretive dance" },
    ]
  },
  {
    id: "sit_roommate",
    name: "Ideal Roommate",
    prompt: "Rank what matters most in a roommate",
    cards: [
      { id: "sit_room_001", text: "Cleans up after themselves" },
      { id: "sit_room_002", text: "Respects quiet hours" },
      { id: "sit_room_003", text: "Pays rent on time, every time" },
      { id: "sit_room_004", text: "Doesn't eat your food" },
      { id: "sit_room_005", text: "Fun to hang out with" },
      { id: "sit_room_006", text: "Gives you space when you need it" },
      { id: "sit_room_007", text: "Warns you before having people over" },
      { id: "sit_room_008", text: "Has a similar sleep schedule" },
      { id: "sit_room_009", text: "Handles conflict like an adult" },
      { id: "sit_room_010", text: "No passive-aggressive notes" },
      { id: "sit_room_011", text: "Does dishes the same day" },
      { id: "sit_room_012", text: "Brings home leftovers sometimes" },
      { id: "sit_room_013", text: "Has a similar cleanliness standard" },
      { id: "sit_room_014", text: "Is your friend, not just your roommate" },
      { id: "sit_room_015", text: "Splits supplies fairly" },
      { id: "sit_room_016", text: "Doesn't hog the bathroom" },
      { id: "sit_room_017", text: "Remembers to lock the door" },
      { id: "sit_room_018", text: "Takes out the trash unprompted" },
      { id: "sit_room_019", text: "Can fix things around the place" },
      { id: "sit_room_020", text: "Communicates when bothered" },
      { id: "sit_room_021", text: "Watches the same shows" },
      { id: "sit_room_022", text: "Keeps common areas clean" },
      { id: "sit_room_023", text: "Someone you'd choose to live with again" },
      { id: "sit_room_024", text: "Respects your stuff" },
      { id: "sit_room_025", text: "Doesn't blast music at 7 AM" },
    ]
  },
  {
    id: "sit_billionaire_day",
    name: "Billionaire for a Day",
    prompt: "One day only — rank what you'd do first",
    cards: [
      { id: "sit_bill_001", text: "Pay off your debt and your family's" },
      { id: "sit_bill_002", text: "Buy a house outright" },
      { id: "sit_bill_003", text: "Donate to a cause you believe in" },
      { id: "sit_bill_004", text: "Charter a private jet somewhere" },
      { id: "sit_bill_005", text: "Throw the party of the century" },
      { id: "sit_bill_006", text: "An insane shopping spree" },
      { id: "sit_bill_007", text: "Set up a trust fund" },
      { id: "sit_bill_008", text: "Courtside seats to every game" },
      { id: "sit_bill_009", text: "Rent out a restaurant for your friends" },
      { id: "sit_bill_010", text: "Buy something ridiculous like a castle" },
      { id: "sit_bill_011", text: "Rent out an entire theme park" },
      { id: "sit_bill_012", text: "Buy your parents their dream house" },
      { id: "sit_bill_013", text: "Tip every service worker $1,000" },
      { id: "sit_bill_014", text: "A private concert by your favorite artist" },
      { id: "sit_bill_015", text: "Set up a full scholarship fund" },
      { id: "sit_bill_016", text: "A helicopter tour at sunset" },
      { id: "sit_bill_017", text: "Commission a famous artist to paint you" },
      { id: "sit_bill_018", text: "Rent a yacht and do nothing" },
      { id: "sit_bill_019", text: "Name a building something ridiculous" },
      { id: "sit_bill_020", text: "A fireworks show in your backyard" },
      { id: "sit_bill_021", text: "Pay off every friend's debt" },
      { id: "sit_bill_022", text: "A custom car you'd never actually buy" },
      { id: "sit_bill_023", text: "Fly everyone you love to one place" },
      { id: "sit_bill_024", text: "Buy a tropical island" },
      { id: "sit_bill_025", text: "Leave a $10K tip at a diner" },
    ]
  },
  {
    id: "sit_school_subjects",
    name: "School Subjects",
    prompt: "Rank which subject you'd enjoy again as an adult",
    cards: [
      { id: "sit_school_001", text: "Art" },
      { id: "sit_school_002", text: "History" },
      { id: "sit_school_003", text: "Music" },
      { id: "sit_school_004", text: "Science" },
      { id: "sit_school_005", text: "Creative writing" },
      { id: "sit_school_006", text: "Gym" },
      { id: "sit_school_007", text: "Math" },
      { id: "sit_school_008", text: "A foreign language" },
      { id: "sit_school_009", text: "Psychology" },
      { id: "sit_school_010", text: "Home economics" },
      { id: "sit_school_011", text: "Chemistry" },
      { id: "sit_school_012", text: "Computer science" },
      { id: "sit_school_013", text: "Drama" },
      { id: "sit_school_014", text: "Art history" },
      { id: "sit_school_015", text: "Economics" },
      { id: "sit_school_016", text: "Philosophy" },
      { id: "sit_school_017", text: "Biology" },
      { id: "sit_school_018", text: "Geography" },
      { id: "sit_school_019", text: "Woodshop" },
      { id: "sit_school_020", text: "Debate" },
      { id: "sit_school_021", text: "Film studies" },
      { id: "sit_school_022", text: "Environmental science" },
      { id: "sit_school_023", text: "Sociology" },
      { id: "sit_school_024", text: "Astronomy" },
      { id: "sit_school_025", text: "Recess" },
    ]
  },
  // === 4 NEW SITUATIONS replacing removed ones ===
  {
    id: "sit_road_trip",
    name: "Road Trip",
    prompt: "Rank what matters most on a road trip",
    cards: [
      { id: "sit_road_001", text: "The playlist" },
      { id: "sit_road_002", text: "The snack selection" },
      { id: "sit_road_003", text: "Who's driving" },
      { id: "sit_road_004", text: "The destination" },
      { id: "sit_road_005", text: "Good weather" },
      { id: "sit_road_006", text: "Gas station stops" },
      { id: "sit_road_007", text: "A comfortable passenger seat" },
      { id: "sit_road_008", text: "Scenic routes over highways" },
      { id: "sit_road_009", text: "A cooler full of drinks" },
      { id: "sit_road_010", text: "The people in the car" },
      { id: "sit_road_011", text: "A phone charger that reaches every seat" },
      { id: "sit_road_012", text: "Stopping at weird roadside attractions" },
      { id: "sit_road_013", text: "A clean car" },
      { id: "sit_road_014", text: "Aux cord control" },
      { id: "sit_road_015", text: "Fast food drive-throughs" },
      { id: "sit_road_016", text: "A good GPS" },
      { id: "sit_road_017", text: "Windows down on a warm night" },
      { id: "sit_road_018", text: "A blanket and pillow for napping" },
      { id: "sit_road_019", text: "A no-phone-policy for the driver" },
      { id: "sit_road_020", text: "Splitting the driving evenly" },
      { id: "sit_road_021", text: "An unplanned detour" },
      { id: "sit_road_022", text: "Arriving before dark" },
      { id: "sit_road_023", text: "Deep conversations in hour three" },
      { id: "sit_road_024", text: "Everyone agreeing on where to eat" },
      { id: "sit_road_025", text: "The feeling of finally getting there" },
    ]
  },
  {
    id: "sit_stranded_airport",
    name: "Stranded at the Airport",
    prompt: "12-hour layover — rank how you'd survive",
    cards: [
      { id: "sit_strand_001", text: "Find a lounge to sleep in" },
      { id: "sit_strand_002", text: "People-watch for hours" },
      { id: "sit_strand_003", text: "Try every restaurant in the terminal" },
      { id: "sit_strand_004", text: "Read an entire book" },
      { id: "sit_strand_005", text: "Binge a show on your phone" },
      { id: "sit_strand_006", text: "Walk laps around the terminal" },
      { id: "sit_strand_007", text: "Make friends with a stranger" },
      { id: "sit_strand_008", text: "Buy overpriced snacks guilt-free" },
      { id: "sit_strand_009", text: "Explore duty free like it's a museum" },
      { id: "sit_strand_010", text: "Find a power outlet and camp there" },
      { id: "sit_strand_011", text: "Nap on the floor with no shame" },
      { id: "sit_strand_012", text: "Write in a journal" },
      { id: "sit_strand_013", text: "Call everyone you've been meaning to" },
      { id: "sit_strand_014", text: "Start a podcast you've been putting off" },
      { id: "sit_strand_015", text: "Download a game and get addicted" },
      { id: "sit_strand_016", text: "Sit at the bar alone" },
      { id: "sit_strand_017", text: "Watch planes take off and land" },
      { id: "sit_strand_018", text: "Plan your entire next vacation" },
      { id: "sit_strand_019", text: "Do a full skincare routine in the bathroom" },
      { id: "sit_strand_020", text: "Stretch and do yoga by the gate" },
      { id: "sit_strand_021", text: "Spend an hour at a bookstore" },
      { id: "sit_strand_022", text: "Reorganize everything in your bag" },
      { id: "sit_strand_023", text: "Make a playlist for the next flight" },
      { id: "sit_strand_024", text: "Have a long video call with friends" },
      { id: "sit_strand_025", text: "Stare out the window and zone out" },
    ]
  },
  {
    id: "sit_potluck",
    name: "Potluck",
    prompt: "Rank what you'd bring to impress everyone",
    cards: [
      { id: "sit_pot_001", text: "A homemade mac and cheese" },
      { id: "sit_pot_002", text: "A charcuterie board" },
      { id: "sit_pot_003", text: "Brownies from scratch" },
      { id: "sit_pot_004", text: "Your best guacamole" },
      { id: "sit_pot_005", text: "A crockpot of chili" },
      { id: "sit_pot_006", text: "A tray of sushi rolls" },
      { id: "sit_pot_007", text: "A signature cocktail pitcher" },
      { id: "sit_pot_008", text: "Deviled eggs" },
      { id: "sit_pot_009", text: "A pasta bake" },
      { id: "sit_pot_010", text: "A fruit salad" },
      { id: "sit_pot_011", text: "Store-bought cookies you repackaged" },
      { id: "sit_pot_012", text: "Your grandma's recipe" },
      { id: "sit_pot_013", text: "A seven-layer dip" },
      { id: "sit_pot_014", text: "A big salad" },
      { id: "sit_pot_015", text: "Pulled pork sliders" },
      { id: "sit_pot_016", text: "A pie from scratch" },
      { id: "sit_pot_017", text: "Spring rolls" },
      { id: "sit_pot_018", text: "A cheese dip that never stops" },
      { id: "sit_pot_019", text: "Fried chicken" },
      { id: "sit_pot_020", text: "A layered dessert in a glass" },
      { id: "sit_pot_021", text: "A bread you baked that morning" },
      { id: "sit_pot_022", text: "Buffalo chicken dip" },
      { id: "sit_pot_023", text: "Garlic bread" },
      { id: "sit_pot_024", text: "A bag of chips and no shame" },
      { id: "sit_pot_025", text: "Whatever looked good at the deli" },
    ]
  },
  {
    id: "sit_time_capsule",
    name: "Time Capsule",
    prompt: "Rank what you'd put in a capsule opened in 50 years",
    cards: [
      { id: "sit_cap_001", text: "A photo of your friend group" },
      { id: "sit_cap_002", text: "A letter to your future self" },
      { id: "sit_cap_003", text: "Your favorite song on a USB" },
      { id: "sit_cap_004", text: "A newspaper from today" },
      { id: "sit_cap_005", text: "A list of your current predictions" },
      { id: "sit_cap_006", text: "Your phone case" },
      { id: "sit_cap_007", text: "A menu from your favorite restaurant" },
      { id: "sit_cap_008", text: "A screenshot of your group chat" },
      { id: "sit_cap_009", text: "Your most-worn shirt" },
      { id: "sit_cap_010", text: "A handwritten recipe" },
      { id: "sit_cap_011", text: "Your current playlist" },
      { id: "sit_cap_012", text: "A map of your neighborhood" },
      { id: "sit_cap_013", text: "A list of things you're worried about" },
      { id: "sit_cap_014", text: "Your coffee order" },
      { id: "sit_cap_015", text: "A childhood toy" },
      { id: "sit_cap_016", text: "A polaroid of your room" },
      { id: "sit_cap_017", text: "Your current goals" },
      { id: "sit_cap_018", text: "A bar of your favorite chocolate" },
      { id: "sit_cap_019", text: "A ticket stub from something recent" },
      { id: "sit_cap_020", text: "Your house key" },
      { id: "sit_cap_021", text: "A voicemail you saved" },
      { id: "sit_cap_022", text: "The book you're currently reading" },
      { id: "sit_cap_023", text: "A list of people you love" },
      { id: "sit_cap_024", text: "Your passwords — for the chaos" },
      { id: "sit_cap_025", text: "A note that says 'I hope you're happy'" },
    ]
  },
];
